export const chapter9 = {
  chapterTitle: "Ĉaptiro 9",
  summary: "",
  verses: [
    "AbimeleĤ, filo de Jerubaal, iris en ŜeĤemon, al la fratoj de sia patrino, kaj ekparolis al ili kaj al la tuta familio de la domo de sia patrinpatro jene:",
    "Diru al la oreloj de ĉiuj loĝantoj de ŜeĤem:Kio estas pli bona al vi, ĉu ke regu vin sepdek homoj, ĉiuj filoj de Jerubaal, aŭ ke regu vin unu homo? memoru ankaŭ, ke mi estas via osto kaj via karno.",
    "Kaj la fratoj de lia patrino diris pri li al la oreloj de ĉiuj loĝantoj de ŜeĤem ĉiujn tiujn vortojn, kaj ilia koro inkliniĝis al AbimeleĤ; ĉar ili diris:Li estas nia frato.",
    "Kaj ili donis al li sepdek arĝentajn monerojn el la domo de Baal-Berit, kaj AbimeleĤ dungis per ili homojn mallaboremajn kaj facilanimajn, kaj ili sekvis lin.",
    "Kaj li venis en la domon de sia patro en Ofra, kaj mortigis siajn fratojn, la filojn de Jerubaal, sepdek homojn, sur unu ŝtono; restis Jotam, la plej juna filo de Jerubaal, ĉar li kaŝiĝis.",
    "Kaj kolektiĝis ĉiuj loĝantoj de ŜeĤem kaj la tuta domo de Milo, kaj ili iris kaj faris AbimeleĤon reĝo, ĉe la kverko, kiu staras en ŜeĤem.",
    "Kaj oni diris pri tio al Jotam, kaj li iris kaj stariĝis sur la supro de la monto Gerizim, kaj laŭte ekkriis, kaj diris al ili:Aŭskultu min, loĝantoj de ŜeĤem, kaj aŭskultos vin Dio.",
    "Iris la arboj, por sanktolei reĝon super si; kaj ili diris al la olivarbo:Reĝu super ni.",
    "Sed la olivarbo diris al ili:Ĉu mi perdis mian grason, per kiu estas honorataj Dio kaj homoj, ke mi iru vagi super la arboj?",
    "Kaj la arboj diris al la figarbo:Iru vi, reĝu super ni.",
    "Sed la figarbo diris al ili:Ĉu mi perdis mian dolĉecon kaj miajn bonajn fruktojn, ke mi iru vagi super la arboj?",
    "Kaj la arboj diris al la vinberujo:Iru vi, reĝu super ni.",
    "Sed la vinberujo diris al ili:Ĉu mi perdis mian moston, kiu gajigas Dion kaj homojn, ke mi iru vagi super la arboj?",
    "Tiam ĉiuj arboj diris al la dornarbusto:Iru vi, reĝu super ni.",
    "Kaj la dornarbusto diris al la arboj:Se vere vi sanktoleas min kiel reĝon super vi, tiam venu, ŝirmu vin sub mia ombro; se ne, tiam eliros fajro el la dornarbusto kaj forbruligos la cedrojn de Lebanon.",
    "Nun ĉu vi agis ĝuste kaj juste, reĝigante AbimeleĤon? kaj ĉu vi agis bone rilate Jerubaalon kaj lian domon, kaj ĉu vi agis kun li konforme al lia merito?",
    "Mia patro batalis pro vi kaj ne ŝatis sian vivon kaj savis vin el la manoj de Midjan;",
    "kaj vi leviĝis nun kontraŭ la domon de mia patro, kaj mortigis liajn filojn, sepdek homojn, sur unu ŝtono, kaj AbimeleĤon, filon de lia sklavino, vi reĝigis super la loĝantoj de ŜeĤem, pro tio, ke li estas via frato.",
    "Se ĝuste kaj juste vi agis nun rilate Jerubaalon kaj lian domon, tiam ĝoju pri AbimeleĤ, kaj li ankaŭ ĝoju pri vi.",
    "Sed se ne, tiam eliru fajro el AbimeleĤ kaj forbruligu la loĝantojn de ŜeĤem kaj la domon de Milo; kaj fajro eliru el la loĝantoj de ŜeĤem kaj el la domo de Milo kaj forbruligu AbimeleĤon.",
    "Kaj Jotam forkuris kaj forsavis sin kaj iris en Beeron kaj ekloĝis tie pro timo antaŭ sia frato AbimeleĤ.",
    "Kaj AbimeleĤ regis super Izrael tri jarojn.",
    "Kaj Dio venigis malbonan spiriton inter AbimeleĤ kaj la loĝantoj de ŜeĤem; kaj la loĝantoj de ŜeĤem perfidis AbimeleĤon,",
    "por ke la krimo pri la sepdek filoj de Jerubaal kaj ilia sango venu sur AbimeleĤon, ilian fraton, kiu mortigis ilin, kaj sur la loĝantojn de ŜeĤem, kiuj subtenis liajn manojn, por ke li mortigu siajn fratojn.",
    "Kaj la loĝantoj de ŜeĤem starigis kontraŭ li insidantojn sur la suproj de la montoj, kaj ili prirabadis ĉiun, kiu pasis preter ili sur la vojo. Kaj oni diris tion al AbimeleĤ.",
    "Kaj venis Gaal, filo de Ebed, kun siaj fratoj, kaj ili iris tra ŜeĤem; kaj fidis lin la loĝantoj de ŜeĤem.",
    "Kaj ili eliris sur la kampon kaj ŝirkolektis siajn vinberojn kaj elpremis ilin kaj faris feston kaj iris en la domon de sia dio kaj manĝis kaj drinkis kaj malbenis AbimeleĤon.",
    "Kaj Gaal, filo de Ebed, diris:Kiu estas AbimeleĤ, kaj kio estas ŜeĤem, ke ni servu al li? li estas ja filo de Jerubaal, kaj Zebul estas lia oficisto. Servu al la homoj de ĥamor, patro de ŜeĤem, sed al tiu kial ni servu?",
    "Se iu donus ĉi tiun popolon en miajn manojn, mi forpelus AbimeleĤon. Kaj oni diris al AbimeleĤ:Plimultigu vian militistaron, kaj eliru.",
    "Kiam Zebul, la estro de la urbo, aŭdis la vortojn de Gaal, filo de Ebed, lia kolero ekflamis.",
    "Kaj li sendis ruze senditojn al AbimeleĤ, por diri:Jen Gaal, filo de Ebed, kun siaj fratoj venis en ŜeĤemon kaj ribeligas la urbon kontraŭ vi;",
    "tial leviĝu en la nokto, vi kaj la popolo, kiu estas kun vi, kaj faru embuskon sur la kampo;",
    "kaj matene, kiam leviĝos la suno, leviĝu frue, kaj ataku la urbon; kaj kiam li kaj la popolo, kiu estas kun li, eliros al vi, tiam faru al li, kion via mano povos.",
    "Kaj AbimeleĤ, kaj la tuta popolo, kiu estis kun li, leviĝis en la nokto, kaj faris apud ŜeĤem embuskon el kvar taĉmentoj.",
    "Kaj Gaal, filo de Ebed, eliris kaj stariĝis ĉe la pordego de la urbo; kaj AbimeleĤ, kaj la popolo, kiu estis kun li, leviĝis el la embusko.",
    "Kiam Gaal ekvidis la popolon, li diris al Zebul:Jen popolo malsupreniras de la suproj de la montoj. Sed Zebul diris al li:La ombro de la montoj ŝajnas al vi homoj.",
    "Kaj Gaal parolis plue, kaj diris:Jen popolo malsupreniras de la altaĵo, kaj unu taĉmento venas laŭ la vojo de la kverko de sorĉistoj.",
    "Tiam Zebul diris al li:Kie nun estas via buŝo, kiu diris:Kiu estas AbimeleĤ, ke ni servu al li? Tio estas ja tiu popolo, kiun vi malŝatis; nun eliru, kaj batalu kontraŭ ĝi.",
    "Kaj Gaal eliris, havante post si la loĝantojn de ŜeĤem, kaj ekbatalis kontraŭ AbimeleĤ.",
    "Kaj AbimeleĤ ekpelis lin, kaj li forkuris, kaj falis multe da mortigitoj ĝis la pordego mem.",
    "Kaj AbimeleĤ restis en Aruma; kaj Zebul elpelis Gaalon kaj liajn fratojn, ke ili ne loĝu en ŜeĤem.",
    "En la sekvanta tago la popolo eliris sur la kampon. Kaj oni diris tion al AbimeleĤ.",
    "Kaj li prenis sian militistaron kaj dividis ĝin en tri taĉmentojn kaj faris embuskon sur la kampo. Kiam li vidis, ke la popolo eliras el la urbo, li leviĝis kontraŭ ili kaj batis ilin.",
    "Kaj AbimeleĤ, kaj la taĉmentoj, kiuj estis kun li, atakis kaj stariĝis antaŭ la pordego de la urbo; kaj du taĉmentoj atakis ĉiujn, kiuj estis sur la kampo, kaj mortigis ilin.",
    "Kaj AbimeleĤ batalis kontraŭ la urbo la tutan tiun tagon; kaj li prenis la urbon, kaj mortigis la popolon, kiu estis en ĝi; kaj li detruis la urbon kaj semis sur ĝia loko salon.",
    "Kiam tion aŭdis ĉiuj loĝantoj de la turo de ŜeĤem, ili foriris en la fortikaĵon de la dio Berit.",
    "Kaj oni diris al AbimeleĤ, ke kolektiĝis ĉiuj loĝantoj de la turo de ŜeĤem.",
    "Tiam AbimeleĤ iris sur la monton Calmon, li kaj la tuta popolo, kiu estis kun li, kaj AbimeleĤ prenis hakilon en sian manon kaj dehakis branĉon de arbo kaj prenis ĝin kaj metis ĝin sur sian ŝultron, kaj diris al la homoj, kiuj estis kun li:Kion vi vidis, ke mi faris, tion rapide faru kiel mi.",
    "Kaj ankaŭ ĉiuj el la tuta popolo dehakis branĉojn kaj iris post AbimeleĤ kaj almetis al la fortikaĵo kaj ekbruligis per ili la fortikaĵon per fajro; kaj mortis ankaŭ ĉiuj homoj de la turo de ŜeĤem, ĉirkaŭ mil viroj kaj virinoj.",
    "Kaj AbimeleĤ iris al Tebec kaj sieĝis Tebecon kaj prenis ĝin.",
    "Fortika turo estis meze de la urbo, kaj tien forkuris ĉiuj viroj kaj virinoj kaj ĉiuj loĝantoj de la urbo, kaj enŝlosis sin tie kaj supreniris sur la tegmenton de la turo.",
    "Kaj AbimeleĤ venis al la turo kaj sieĝis ĝin, kaj aliris al la pordo de la turo, por forbruligi ĝin per fajro.",
    "Tiam iu virino ĵetis muelŝtonon sur la kapon de AbimeleĤ kaj rompis al li la kranion.",
    "Tiam li rapide alvokis la junulon, kiu portis liajn batalilojn, kaj diris al li:Eltiru vian glavon kaj mortigu min, por ke oni ne diru pri mi:Virino lin mortigis. Kaj lia junulo lin trapikis, kaj li mortis.",
    "Kaj la Izraelidoj vidis, ke AbimeleĤ mortis, kaj ili iris ĉiu al sia loko.",
    "Tiel Dio repagis la malbonagon de AbimeleĤ, kiun ĉi tiu faris rilate sian patron, mortigante siajn sepdek fratojn.",
    "Kaj la tutan malbonagon de la loĝantoj de ŜeĤem Dio revenigis sur ilian kapon; kaj venis sur ilin la malbeno de Jotam, filo de Jerubaal.",
  ],
} as const satisfies Chapter;
