export const chapter21 = {
  chapterTitle: "Ĉapitro 21",
  summary: "",
  verses: [
    "Post tiu historio okazis jeno:Nabot, Jizreelano, havis vinberĝardenon en Jizreel, apud la palaco de AĤab, reĝo de Samario.",
    "Kaj AĤab ekparolis al Nabot, dirante:Donu al mi vian vinberĝardenon, por ke ĝi fariĝu por mi legomĝardeno, ĉar ĝi estas proksime de mia domo;  kaj mi donos al vi anstataŭ ĝi vinberĝardenon pli bonan ol ĝi; se vi volas, mi donos al vi per arĝento ĝian prezon.",
    "Sed Nabot diris al AĤab:La Eternulo gardu min, ke mi ne fordonu al vi la heredaĵon de miaj patroj.",
    "Tiam AĤab revenis hejmen malĝoja kaj afliktita pro la vortoj, kiujn diris al li Nabot, la Jizreelano, dirante:Mi ne donos al vi la heredaĵon de miaj patroj. Kaj li kuŝiĝis sur sia lito kaj forturnis sian vizaĝon kaj ne manĝis panon.",
    "Kaj venis al li lia edzino Izebel, kaj diris al li:Kial via spirito estas tiel malĝoja, ke vi ne manĝas panon?",
    "Li respondis al ŝi:Kiam mi parolis al Nabot, la Jizreelano, kaj diris al li:Donu al mi vian vinberĝardenon pro mono, aŭ, se vi volas, mi donos al vi alian vinberĝardenon anstataŭ ĝi, li diris:Mi ne donos al vi mian vinberĝardenon.",
    "Tiam diris al li lia edzino Izebel:Nun vi montru vian reĝecon super Izrael; leviĝu, manĝu panon, kaj estu bonhumora:mi donos al vi la vinberĝardenon de Nabot, la Jizreelano.",
    "Kaj ŝi skribis leterojn en la nomo de AĤab kaj sigelis per lia sigelilo, kaj ŝi sendis la leterojn al la plejaĝuloj kaj al la eminentuloj, kiuj loĝis kun Nabot en lia urbo.",
    "Kaj ŝi skribis en la leteroj jenon:Proklamu faston kaj sidigu Naboton sur la ĉefa loko inter la popolo;",
    "kaj sidigu apud li du homojn malvirtajn, kaj ili atestu kontraŭ li kaj diru:Vi blasfemis kontraŭ Dio kaj la reĝo; kaj oni elkonduku lin, kaj priĵetu lin per ŝtonoj, ke li mortu.",
    "Kaj la viroj de lia urbo, la plejaĝuloj kaj la eminentuloj, kiuj loĝis en lia urbo, faris kiel ordonis al ili Izebel, kiel estis skribite en la leteroj, kiujn ŝi sendis al ili.",
    "Ili proklamis faston kaj sidigis Naboton sur la ĉefa loko inter la popolo.",
    "Kaj venis du homoj malvirtaj kaj sidiĝis apud li, kaj la malvirtaj homoj atestis kontraŭ Nabot antaŭ la popolo, dirante:Nabot blasfemis kontraŭ Dio kaj la reĝo. Kaj oni elkondukis lin ekster la urbon kaj priĵetis lin per ŝtonoj, kaj li mortis.",
    "Kaj oni sendis al Izebel, por diri:Nabot estas priĵetita per ŝtonoj kaj mortis.",
    "Kiam Izebel aŭdis, ke Nabot estas priĵetita per ŝtonoj kaj mortis, Izebel diris al AĤab:Leviĝu, ekposedu la vinberĝardenon de Nabot, la Jizreelano, kiun li ne volis doni al vi pro mono; ĉar Nabot jam ne vivas; li mortis.",
    "Kiam AĤab aŭdis, ke Nabot mortis, AĤab leviĝis, por iri en la vinberĝardenon de Nabot, la Jizreelano, por ekposedi ĝin.",
    "Tiam aperis la vorto de la Eternulo al Elija, la Teŝebano, dirante:",
    "Leviĝu, iru renkonte al AĤab, reĝo de Izrael, kiu estas en Samario; jen li nun estas en la vinberĝardeno de Nabot, kien li iris, por ekposedi ĝin;",
    "kaj diru al li jene:Tiele diras la Eternulo:Vi mortigis, kaj vi ankoraŭ prenas en posedon! Kaj diru al li:Tiele diras la Eternulo:Sur la loko, kie la hundoj lekis la sangon de Nabot, la hundoj lekos ankaŭ vian sangon.",
    "Kaj AĤab diris al Elija:Vi trovis min, ho mia malamiko! Kaj tiu diris:Mi trovis, ĉar vi vin vendis, por fari malbonon antaŭ la okuloj de la Eternulo.",
    "Jen Mi venigos sur vin malbonon, kaj forbalaos la postesignojn post vi, kaj Mi ekstermos ĉe AĤab ĉiun virseksulon, malliberulon kaj liberulon en Izrael.",
    "Kaj Mi agos kun via domo, kiel kun la domo de Jerobeam, filo de Nebat, kaj kiel kun la domo de Baaŝa, filo de AĤija, pro la incito, per kiu vi Min incitis kaj pekigis Izraelon.",
    "Kaj ankaŭ pri Izebel parolis la Eternulo, dirante:La hundoj formanĝos Izebelon apud la murego de Jizreel.",
    "Kiu mortos ĉe AĤab en la urbo, tiun manĝos la hundoj; kaj kiu mortos sur la kampo, tiun manĝos la birdoj de la ĉielo.",
    "(Estis neniu tia, kiel AĤab, kiu fordonis sin al farado de malbono antaŭ la okuloj de la Eternulo, al kio instigadis lin lia edzino Izebel.",
    "Li fariĝis tre abomeninda, sekvante la idolojn, konforme al ĉio, kion faradis la Amoridoj, kiujn la Eternulo forpelis de antaŭ la Izraelidoj.)",
    "Kiam AĤab aŭdis tiujn vortojn, li disŝiris siajn vestojn kaj metis sakaĵon sur sian korpon kaj fastis kaj dormis en la sakaĵo kaj iradis malĝoje.",
    "Tiam aperis vorto de la Eternulo al Elija, la Teŝebano, dirante:",
    "Ĉu vi vidas, kiel AĤab humiliĝis antaŭ Mi? Pro tio, ke li humiliĝis antaŭ Mi, Mi ne venigos la malbonon dum lia vivo; dum la vivo de lia filo Mi venigos la malbonon sur lian domon.",
  ],
} as const satisfies Chapter;
