export const chapter24 = {
  chapterTitle: "Ĉapitro 24",
  summary: "",
  verses: [
    "La ordo de la Aaronidoj:la filoj de Aaron:Nadab, Abihu, Eleazar, kaj Itamar.",
    "Nadab kaj Abihu mortis pli frue ol ilia patro, kaj filojn ili ne havis; kaj Eleazar kaj Itamar fariĝis pastroj.",
    "La ordon aranĝis David, kaj Cadok el la idoj de Eleazar, kaj AĤimeleĤ el la idoj de Itamar, laŭ iliaj oficoj ĉe ilia servado.",
    "Montriĝis, ke inter la idoj de Eleazar estis pli granda nombro da viroj, ol inter la idoj de Itamar. Oni dividis ilin:por la idoj de Eleazar estis dek ses ĉefoj de patrodomoj, kaj por la idoj de Itamar ok patrodomoj.",
    "Oni dividis ilin per lotado, ambaŭ partojn paralele, ĉar la estroj de la sanktejo kaj la estroj en la aferoj de Dio estis el la idoj de Eleazar kaj el la idoj de Itamar.",
    "Kaj enskribis ilin Ŝemaja, filo de Netanel, skribisto el la Levidoj, antaŭ la reĝo kaj la estroj, antaŭ la pastro Cadok, antaŭ AĤimeleĤ,  filo de Ebjatar, kaj antaŭ la ĉefoj de patrodomoj de la pastroj kaj de la Levidoj; unu loto estis por patrodomo de Eleazaridoj, kaj unu loto estis por patrodomo de Itamaridoj.",
    "La unua loto eliris por Jehojarib, la dua por Jedaja,",
    "la tria por ĥarim, la kvara por Seorim,",
    "la kvina por Malkija, la sesa por Mijamin,",
    "la sepa por Hakoc, la oka por Abija,",
    "la naŭa por Jeŝua, la deka por ŜeĤanja,",
    "la dek-unua por Eljaŝib, la dek-dua por Jakim,",
    "la dek-tria por ĥupa, la dek-kvara por Jeŝebab,",
    "la dek-kvina por Bilga, la dek-sesa por Imer,",
    "la dek-sepa por ĥezir, la dek-oka por Hapicec,",
    "la dek-naŭa por PetaĤja, la dudeka por JeĤezkel,",
    "la dudek-unua por JaĤin, la dudek-dua por Gamul,",
    "la dudek-tria por Delaja, la dudek-kvara por Maazja.",
    "Tio estis ilia ordo ĉe ilia servado, por iri en la domon de la Eternulo laŭ la preskribo donita per ilia patro Aaron, kiel ordonis al li la Eternulo, Dio de Izrael.",
    "La ordo por la ceteraj idoj de Levi:el la idoj de Amram:Ŝubael; el la idoj de Ŝubael:JeĤdeja;",
    "ĉe ReĤabja:el la idoj de ReĤabja la unua estis Jiŝija;",
    "ĉe la Jicharidoj:Ŝelomot; el la filoj de Ŝelomot:JaĤat;",
    "la filoj de ĥebron:Jerija, Amarja estis la dua, JaĤaziel la tria, Jekameam la kvara;",
    "el la filoj de Uziel:MiĤa; el la filoj de MiĤa:Ŝamir;",
    "la frato de MiĤa estis Jiŝija; el la filoj de Jiŝija:ZeĤarja;",
    "el la filoj de Merari:MaĤli kaj Muŝi; el la filoj de Jaazija:Beno;",
    "el la idoj de Merari:ĉe Jaazija:Beno, Ŝoham, Zakur, kaj Ibri;",
    "ĉe MaĤli:Eleazar; li ne havis filojn;",
    "ĉe Kiŝ:el la filoj de Kiŝ:JeraĤmeel;",
    "la filoj de Muŝi:MaĤli, Eder, kaj Jerimot. Tio estas la Levidoj laŭ iliaj patrodomoj.",
    "Ili ankaŭ lotis samtempe kun siaj fratoj la Aaronidoj, antaŭ la reĝo David, Cadok, AĤimeleĤ, kaj la ĉefoj de patrodomoj de la pastroj kaj de la Levidoj:ĉefo de patrodomo egale kun sia pli malgranda frato.",
  ],
} as const satisfies Chapter;
