export const chapter15 = {
  chapterTitle: "Ĉapitro 15",
  summary: "",
  verses: [
    "La lotaĵo de la tribo de la Jehudaidoj laŭ iliaj familioj estis:ĉe la limo de Edom la dezerto Cin, sude, en la suda fino de la lando.",
    "Ilia suda limo estis de la fino de la Sala Maro, de la golfo, kiu direktiĝas suden.",
    "Kaj ĝi iras de sude al la altaĵo Akrabim kaj pasas tra Cin kaj leviĝas de sude ĝis Kadeŝ-Barnea kaj pasas tra ĥecron kaj leviĝas ĝis Adar kaj turniĝas al Karka",
    "kaj pasas tra Acmon kaj iras al la torento Egipta; kaj la fino de la limo estas la maro. Tio estu por vi la limo suda.",
    "Kaj la limo oriente estas la Sala Maro ĝis la fino de Jordan; kaj la limo de la flanko norda estas de la golfo de la maro ĉe la fino de Jordan;",
    "kaj la limo leviĝas al Bet-ĥogla kaj pasas norde al Bet-Araba, kaj la limo leviĝas al la ŝtono de Bohan, filo de Ruben.",
    "Kaj la limo leviĝas al Debir de la valo AĤor, kaj norde ĝi turniĝas al Gilgal, kiu estas kontraŭ la altaĵo Adumim, kiu estas sude de la torento; kaj la limo pasas al la akvo En-Ŝemeŝ kaj finiĝas ĉe En-Rogel.",
    "Kaj la limo leviĝas al la valo de la filo de Hinom, ĉe la suda flanko de la Jebusidoj, kio estas Jerusalem, kaj la limo leviĝas al la supro de la monto, kiu estas okcidente kontraŭ la valo de Hinom, kiu estas ĉe la fino de la valo Refaim norde.",
    "Kaj de la supro de la monto la limo turniĝas al la fonto de la akvo NeftoaĤ kaj iras al la urboj de la monto Efron; kaj la limo turniĝas al Baala, kiu estas Kirjat-Jearim.",
    "Kaj la limo turniĝas de Baala okcidenten al la monto Ŝeir, kaj iras preter la norda flanko de la monto Jearim, kiu estas Kesalon, kaj malleviĝas al Bet-Ŝemeŝ kaj iras al Timna;",
    "kaj la limo iras preter la norda flanko de Ekron; kaj la limo turniĝas al Ŝikron kaj pasas tra la monto Baala kaj iras al Jabneel; kaj la fino de la limo estas ĉe la maro.",
    "La okcidenta limo estas la Granda Maro. Ĉi tiu limo estas la limo de la Jehudaidoj ĉirkaŭe, laŭ iliaj familioj.",
    "Kaj al Kaleb, filo de Jefune, estis donita parto meze de la Jehudaidoj, laŭ la diro de la Eternulo al Josuo, la urbo de Arba, patro de Anak (tio estas ĥebron).",
    "Kaj Kaleb elpelis el tie la tri filojn de Anak:Ŝeŝaj kaj AĤiman kaj Talmaj, la naskitojn de Anak.",
    "Kaj de tie li iris al la loĝantoj de Debir; la nomo de Debir antaŭe estis Kirjat-Sefer.",
    "Kaj Kaleb diris:Kiu venkobatos Kirjat-Seferon kaj prenos ĝin, al tiu mi donos mian filinon AĤsa kiel edzinon.",
    "Kaj prenis ĝin Otniel, filo de Kenaz, frato de Kaleb; kaj li donis al li sian filinon AĤsa kiel edzinon.",
    "Kaj kiam ŝi venis, ŝi instigis lin peti de ŝia patro kampon. Kaj ŝi malsupreniĝis de la azeno, kaj Kaleb diris al ŝi:Kio estas al vi?",
    "Kaj ŝi diris:Donu al mi benon; ĉar vi donis al mi teron sudflankan, tial donu al mi ankaŭ akvofontojn. Kaj li donis al ŝi fontojn suprajn kaj fontojn malsuprajn.",
    "Jen estas la posedaĵo de la tribo de la Jehudaidoj laŭ iliaj familioj.",
    "Kaj la urboj ĉe la rando de la tribo de la Jehudaidoj, apud la limo de Edom sude, estis:Kabceel kaj Eder kaj Jagur",
    "kaj Kina kaj Dimona kaj Adada",
    "kaj Kedeŝ kaj ĥacor kaj Jitnan,",
    "Zif kaj Telem kaj Bealot",
    "kaj ĥacor-ĥadata kaj Keriot-ĥecron (tio estas ĥacor),",
    "Amam kaj Ŝema kaj Molada",
    "kaj ĥacar-Gada kaj ĥeŝmon kaj Bet-Pelet",
    "kaj ĥacar-Ŝual kaj Beer-Ŝeba kaj Bizjotja,",
    "Baala kaj Ijim kaj Ecem",
    "kaj Eltolad kaj Kesil kaj ĥorma",
    "kaj Ciklag kaj Madmana kaj Sansana",
    "kaj Lebaot kaj ŜilĤim kaj Ain kaj Rimon. La nombro de ĉiuj urboj estis dudek naŭ kaj iliaj vilaĝoj.",
    "Sur la malaltaĵo:Eŝtaol kaj Corea kaj Aŝna",
    "kaj ZanoaĤ kaj En-Ganim, TapuaĤ kaj Enam,",
    "Jarmut kaj Adulam, SoĤo kaj Azeka",
    "kaj Ŝaaraim kaj Aditaim kaj Gedera kaj Gederotaim:dek kvar urboj kaj iliaj vilaĝoj.",
    "Cenan kaj ĥadaŝa kaj Migdal-Gad",
    "kaj Dilan kaj Micpe kaj Jokteel,",
    "LaĤiŝ kaj Bockat kaj Eglon",
    "kaj Kabon kaj LaĤmas kaj Kitliŝ",
    "kaj Gederot, Bet-Dagon kaj Naama kaj Makeda:dek ses urboj kaj iliaj vilaĝoj.",
    "Libna kaj Eter kaj Aŝan",
    "kaj JiftaĤ kaj Aŝna kaj Necib",
    "kaj Keila kaj AĤzib kaj Mareŝa:naŭ urboj kaj iliaj vilaĝoj.",
    "Ekron kaj ĝiaj urbetoj kaj ĝiaj vilaĝoj.",
    "De Ekron ĝis la maro ĉio, kio estas ĉirkaŭ Aŝdod kaj ĝiaj vilaĝoj.",
    "Aŝdod, ĝiaj urbetoj kaj ĝiaj vilaĝoj; Gaza, ĝiaj urbetoj kaj ĝiaj vilaĝoj, ĝis la torento Egipta; kaj la Granda Maro estas la limo.",
    "Kaj sur la monto:Ŝamir kaj Jatir kaj SoĤo",
    "kaj Dana kaj Kirjat-Sana (tio estas Debir)",
    "kaj Anab kaj Eŝtemo kaj Anim",
    "kaj Goŝen kaj ĥolon kaj Gilo:dek unu urboj kaj iliaj vilaĝoj.",
    "Arab kaj Duma kaj Eŝan",
    "kaj Janum kaj Bet-TapuaĤ kaj Afeka",
    "kaj ĥumta kaj Kirjat-Arba (tio estas ĥebron) kaj Cior; naŭ urboj kaj iliaj vilaĝoj.",
    "Maon, Karmel kaj Zif kaj Juta",
    "kaj Jizreel kaj Jokdeam kaj ZanoaĤ,",
    "Kain, Gibea kaj Timna:dek urboj kaj iliaj vilaĝoj.",
    "ĥalĤul, Bet-Cur kaj Gedor",
    "kaj Maarat kaj Bet-Anot kaj Eltekon:ses urboj kaj iliaj vilaĝoj.",
    "Kirjat-Baal (tio estas Kirjat-Jearim) kaj Raba:du urboj kaj iliaj vilaĝoj.",
    "En la dezerto:Bet-Araba kaj Midin kaj SeĤaĤa",
    "kaj Nibŝan kaj la Urbo de Salo kaj En-Gedi:ses urboj kaj iliaj vilaĝoj.",
    "Sed la Jebusidojn, loĝantojn de Jerusalem, la Jehudaidoj ne povis forpeli; kaj la Jebusidoj restis kun la Jehudaidoj en Jerusalem ĝis la nuna tago.",
  ],
} as const satisfies Chapter;
