export const chapter5 = {
  chapterTitle: "Ĉapitro 5",
  verses: [
    "Okazis, ke mi, Nifai, multfoje kriis al la Sinjoro, mia Dio, pro la kolero de miaj fratoj.",
    "Sed ilia kolero kontraŭ mi pligrandiĝis, tiom ke ili celis forpreni mian vivon.",
    "Jes, ili ja murmuris kontraŭ mi, dirante: Nia pli juna frato pensas, ke li regos super ni; kaj ni estas multe provitaj pro li; pro tio, ni nun mortigu lin, por ke ni ne estu plu afliktataj pro liaj vortoj. Ĉar ni ja ne volas havi lin kiel nian reganton; ĉar la rajto regi ĉi tiun popolon apartenas al ni, kiuj estas la pli aĝaj fratoj.",
    "Sed mi ne skribas sur ĉi tiujn platojn ĉiujn el la vortoj, kiujn ili murmuris kontraŭ mi. Sed por mi sufiĉas diri, ke ili ja celis forpreni mian vivon.",
    "Kaj okazis, ke la Sinjoro avertis min, ke mi, Nifai, foriru de ili kaj fuĝu en la dezerton, kun ĉiuj tiuj, kiuj volis iri kun mi.",
    "Pro tio okazis, ke mi, Nifai, prenis mian familion, kaj ankaŭ Zoram kaj lian familion, kaj Sam, mian pli aĝan fraton kaj lian familion, kaj Jakobon kaj Jozefon, miajn pli junajn fratojn, kaj ankaŭ miajn fratinojn, kaj ĉiujn el tiuj, kiuj volis iri kun mi. Kaj ĉiujn el tiuj, kiuj volis iri kun mi, estis tiuj, kiuj kredis pri la avertoj kaj la revelacioj de Dio; pro kio, ili aŭskultis miajn vortojn.",
    "Kaj ni prenis niajn tendojn kaj ĉion, kion ni povis porti, kaj iris en la dezerto dum multaj tagoj. Kaj, irinte multajn tagojn, ni starigis niajn tendojn.",
    "Kaj mia popolo deziris, ke ni nomu la lokon Nifai; pro kio, ni nomis ĝin Nifai.",
    "Kaj ĉiuj tiuj, kiuj estis kun mi, prenis sur sin nomi sin la popolo de Nifai.",
    "Kaj ni zorgis observi la juĝojn kaj la statutojn kaj la ordonojn de la Sinjoro pri ĉio laŭ la leĝo de Moseo.",
    "Kaj la Sinjoro estis kun ni; kaj ni treege prosperis; ĉar ni semis semon, kaj ni denove abunde rikoltis. Kaj ni komencis bredi gregojn kaj brutarojn kaj ĉiajn bestojn.",
    "Kaj mi, Nifai, alportis kun mi ankaŭ la analojn, kiuj estis gravuritaj sur la platoj el latuno; kaj ankaŭ la globon, aŭ kompason, kiu estis preparita por mia patro per la mano de la Sinjoro, laŭ tio, kio estas skribita.",
    "Kaj okazis, ke ni komencis treege prosperi, kaj multiĝi en la lando.",
    "Kaj mi, Nifai, prenis la glavon de Laban, kaj laŭ ĝia modelo mi faris multajn glavojn pro timo, ke la popolo, kiu estis eknomita lamanidoj, atakos nin kaj detruos nin; ĉar mi konis ilian malamon kontraŭ mi kaj miaj infanoj kaj tiuj, kiuj estis nomitaj mia popolo.",
    "Kaj mi instruis mian popolon konstrui domojn, kaj prilabori ĉian lignon, kaj feron, kaj kupron, kaj latunon, kaj ŝtalon, kaj oron, kaj arĝenton, kaj multvalorajn ercojn, kiuj tre abundis.",
    "Kaj mi, Nifai, konstruis templon; kaj mi konstruis ĝin laŭ la modelo de la templo de Salomono escepte de tio, ke ĝi ne estis konstruita el tiom multe da altvaloraj aĵoj; ĉar ili ne estis troveblaj sur la lando kaj pro tio ĝi ne povis esti konstruata kiel la templo de Salomono. Sed la konstrumaniero similis al tiu de la templo de Salomono; kaj ĝia elfaro estis treege bela.",
    "Kaj okazis, ke mi Nifai, igis mian popolon laborema kaj ke ili laboru per siaj manoj.",
    "Kaj okazis, ke ili volis, ke mi estu ilia reĝo. Sed mi, Nifai, deziris, ke ili ne havu reĝon; tamen, mi faris por ili laŭ tio, kio estis en mia povo.",
    "Kaj do plenumiĝis la vortoj de la Sinjoro al miaj fratoj, kiujn li parolis pri ili, ke mi estos ilia reganto kaj ilia instruisto. Pro tio, mi jam estis ilia reganto kaj ilia instruisto, laŭ la ordonoj de la Sinjoro, ĝis tiam, kiam ili celis forpreni mian vivon.",
    "Do plenumiĝis la parolo de la Sinjoro, kiun li parolis al mi, dirante, ke: Se ili ne aŭskultos viajn vortojn, ili estos detranĉitaj de antaŭ la Sinjoro. Kaj efektive ili estis detranĉita de antaŭ li.",
    "Kaj li venigis la malbenon sur ilin, jes, eĉ severan malbenon, pro iliaj malbonaj faroj. Ĉar ili ja malmoligis siajn korojn kontraŭ li, tiel ke ili fariĝis kiel siliko; pro tio, ĉar ili estis blankhaŭtaj, kaj treege belaj kaj ĉarmaj, la Sinjoro venigis sur ilin haŭton nigran, por ke ili ne allogu mian popolon.",
    "Kaj la Sinjoro diris jene: Mi kaŭzos, ke ili fariĝos abomenaĵo al via popolo, se ili ne pentos pri siaj malbonaj faroj.",
    "Kaj malbenita estos la idaro de tiu, kiu aliĝas al ilia idaro; ĉar ili estos malbenitaj eĉ per la sama malbeno. Kaj la Sinjoro diris tio, kaj tio fariĝis.",
    "Kaj pro la malbeno, kiu estis sur ili, ili fariĝis mallaborema popolo, plena de trompo kaj ruzemeco, kaj serĉis rabobestojn en la sovaĝejo.",
    "Kaj Dio la Sinjoro diris al mi: Ili estos skurĝo al via idaro, por vigligi ilin per memorigo pri mi; kaj, se ili ne memoros min kaj aŭskultos miajn vortojn, ili skurĝos ilin eĉ ĝis detruo",
    "Kaj okazis, ke mi, Nifai, konsekris Jakobon kaj Jozefon, por ke ili estu pastroj kaj instruistoj sur la lando de mia popolo.",
    "Kaj okazis, ke ni vivis laŭ feliĉa maniero.",
    "Kaj tridek jaroj pasis de la tempo, kiam ni foriris de Jerusalemo.",
    "Kaj mi, Nifai, konservis la analojn pri mia popolo ĝis tiam sur miaj platoj, kiujn mi faris.",
    "Kaj okazis, ke Dio la Sinjoro diris al mi: Faru aliajn platojn; kaj vi surgravuru sur ilin multon, kio estas bona antaŭ miaj okuloj, por la profito de via popolo.",
    "Pro tio, mi, Nifai, obeante la ordonojn de la Sinjoro, iris por fari ĉi tiujn platojn, sur kiujn mi gravuris ĉi tion.",
    "Kaj mi gravuris tion, kio plaĉas al Dio. Kaj, se la aferoj de Dio plaĉas al mia popolo, miajkiuj estas sur ĉi tiuj platoj, plaĉos al ili.",
    "Kaj, se mia popolo deziras koni la pli detalan parton de la historio de mia popolo, ili devos serĉi miajn aliajn platojn.",
    "Kaj por mi sufiĉas diri, ke kvardek jaroj forpasis, kaj ni jam spertis militojn kaj disputojn kun niaj fratoj.",
  ],
} as const satisfies Chapter;
