export const chapter29 = {
  chapterTitle: "Ĉapitro 29",
  summary: "",
  verses: [
    "Sed sciu, estos multaj en tiu tago, kiam mi faros mirindan verkon inter ili, por ke mi memoru miajn interligojn, kiujn mi faris kun la homidoj, por ke mi denove la duan fojon etendu mian manon por reakiri mian popolon, kiu estas el la domo de Izrael;",
    "Kaj ankaŭ, por ke mi memoru la promesojn, kiujn mi faris al vi, Nifai, kaj ankaŭ al via patro, ke mi memoros vian idaron; kaj ke la vortoj de via idaro disvastiĝos el mia buŝo al via idaro; kaj miaj vortoj dissiblos ĝis la ekstremaĵoj de la tero, kiel standardo al mia popolo, kiu estas el la domo de Izrael;",
    "Kaj, ĉar miaj vortoj disen siblos, multaj el la nejudoj diros: Biblion! Biblion! Ni jam havas Biblion, kaj ne povas esti plia Biblio.",
    "Sed tiele diras la Sinjoro: Malsaĝuloj, ili ja havos Biblion; kaj ĝi alvenos de la judoj, mia antikve interligita popolo. Kaj kian dankon ili donas al la judoj pro la Biblio, kiun ili ricevas de ili? Jes, kion la nejudoj pretendas? Ĉu ili memoras la vojaĝadon, kaj la laboradon, kaj la dolorojn de la judoj, kaj ilian fervoron al mi portante savon al la nejudoj?",
    "Ho, vi nejudoj, ĉu vi memoras la judojn, mian antikve interligitan popolon? Ne; sed vi malbenas ilin, kaj malamas ilin, kaj ne provas revenigi ilin. Sed sciu, ĉion mi revenigos sur vian kapon: ĉar mi la Sinjoro ne forgesas mian popolon.",
    "Vi malsaĝulo, kiu diros: Biblion, ni jam havas Biblion, kaj ni bezonas neniun plian Biblion. Ĉu vi akiris Biblion alie ol per la judoj?",
    "Ĉu vi ne scias, ke ekzistas pli da nacioj ol unu? Ĉu vi ne scias, ke mi, la Sinjoro, via Dio, kreis ĉiujn homojn, kaj ke mi memoras tiujn, kiuj estas sur la insuloj de la maro; kaj ke mi regas en la ĉielo supre kaj sur la tero malsupre; kaj mi disvastigas miajn vortojn al la homidoj, jes, al ĉiuj nacioj de la tero?",
    "Kial vi murmuras, ĉar vi ricevos pli de miaj vortoj? Ĉu vi ne scias, ke la atesto de du nacioj estas atesto al vi, ke mi estas Dio, ke mi memoras unu nacion same kiel alian. Pro tio, mi parolas la samajn vortojn al unu nacio kiel al alia. Kaj, kiam la du nacioj kune iros, la atesto de la du nacioj ankaŭ kune iros.",
    "Kaj mi faras tion, por ke mi pruvu al multaj, ke mi estas la sama hieraŭ, hodiaŭ, kaj por eterne; kaj ke mi elparolas miajn vortojn laŭ mia plaĉo. Kaj, ĉar mi parolis unu vorton, vi ne devas supozi, ke mi ne povos paroli alian; ĉar mia laboro ankoraŭ ne estas finita; kaj ĝi ne finiĝos ĝis la homo finiĝos, kaj ankaŭ nek post tiu tempo nek por eterne.",
    "Sekve, ĉar vi havas Biblion, vi devas ne supozi, ke ĝi enhavas ĉiujn el miaj vortoj; kaj vi devas ankaŭ ne supozi, ke mi ne skribigis pli da vortoj.",
    "Ĉar mi ordonas al ĉiuj homoj, kaj en la oriento kaj en la okcidento, kaj en la nordo, kaj en la sudo, kaj sur la insuloj de la maro, ke ili skribu la vortojn, kiujn mi parolas al ili; ĉar el la skribotaj libroj mi juĝos la mondon, kaj ĉiujn homojn laŭ iliaj faroj, laŭ tio, kio estas skribita.",
    "Ĉar, sciu, mi parolos al la judoj kaj ili tion skribos; kaj mi parolos ankaŭ al la nifaidoj kaj ili tion skribos; kaj mi parolos ankaŭ al la aliaj triboj de la domo de Izrael, kiujn mi forkondukis, kaj ili tion skribos; kaj mi parolos ankaŭ al ĉiuj nacioj de la tero kaj ili tion skribos.",
    "Kaj okazos, ke la judoj havos la vortojn de la nifaidoj, kaj la nifaidoj havos la vortojn de la judoj; kaj la nifaidoj kaj la judoj havos la vortojn de la perditaj triboj de Izrael; kaj la perditaj triboj de Izrael havos la vortojn de la nifaidoj kaj la judoj.",
    "Kaj okazos, ke mia popolo, kiu estas el la domo de Izrael, estos kune revenigita hejmen al la teroj de sia posedaĵo; kaj ankaŭ miaj vortoj estos kune kolektitaj en unuaĵon. Kaj mi montros al tiuj, kiuj batalas kontraŭ miaj vortoj kaj kontraŭ mia popolo, kiu estas el la domo de Izrael, ke mi estas Dio, kaj ke mi interligis kun Abraham, ke mi memoros lian idaron por ĉiam.",
  ],
} as const satisfies Chapter;
