export const chapter6 = {
  chapterTitle: "Ĉapitro 6",
  verses: [
    "Kaj nun mi finas mian kronikon pri la detruo de mia popolo, la nifaidoj. Kaj okazis, ke ni elmarŝis antaŭ la lamanidoj.",
    "Kaj mi, Mormon, skribis leteron al la reĝo de la lamanidoj, kaj alvokis al li, ke li permesu al ni, ke ni kunirigu nian popolon al la lando Kumora, apud monteto, kiu etis nomita Kumora, kaj tie ni povos interbatali kun ili.",
    "Kaj okazis, ke la reĝo de la lamanidoj konsentis al mi tio, kion mi deziris.",
    "Kaj okazis, ke ni elmarŝis al la lando Kumora, kaj ni starigis niajn tendojn ĉirkaŭ la monteto Kumora; kaj ĝi estis en regiono de multaj akvoj, riveroj, kaj fontoj; kaj ni esperis tie akiri avantaĝon super la lamanidoj.",
    "Kaj, kiam forpasis tricent okdek kvar jaroj, ni kolektis la tutan restaĵon de nia popolo en la lando Kumora.",
    "Kaj okazis, kiam ni kolektis ĉiujn el nia popolo en unu aron en la lando Kumora, jen mi, Mormon, ekmaljuniĝis; kaj sciante ke tio estos la lasta luktado de mia popolo, kaj ordonite de la Sinjoro, ke mi ne lasu la analojn, kiuj estis transdonitaj de niaj patroj, kaj kiuj estis sanktaj, fali en la manojn de la lamanidoj (ĉar la lamanidoj detruus ilin), mi tial skribis ĉi tiun kronikon laŭ la platoj de Nifai, kaj kaŝis supre en la monteto Kumora ĉiujn analojn, kiujn la mano de la Sinjoro konfidis al mi, krom ĉi tiuj malmultaj platoj, kiujn mi donis al mia filo Moroni.",
    "Kaj okazis, ke mia popolo, kun siaj edzinoj kaj siaj infanoj, vidis la armeojn de la lamanidoj marŝantaj al ili; kaj kun tiu terura timo pri morto, kiu plenigas la brustojn de ĉiuj malvirtuloj, ili atendis ricevi ilin.",
    "Kaj okazis, ke ili venis por batali kontraŭ ni, kaj ĉiu animo estis plenigita de teruro pro la grandeco de ilia nombro.",
    "Kaj okazis, ke ili atakis mian popolon per la glavo, kaj per la pafarko, kaj per la sago, kaj per la hakilo, kaj per ĉiaj militiloj.",
    "Kaj okazis, ke miaj viroj estis dishakitaj, jes, ja, mia dekmilo, kiu estis kun mi, kaj mi vundite falis meze de ili; kaj oni preterpasis min, ne finante mian vivon.",
    "Kaj post kiam ili trairis kaj falĉis ĉiujn el mia popolo krom dudek kvar el ni (inter kiuj estis mia filo Moroni), ni, kiuj postvivis la mortintojn de nia popolo, la morgaŭon, kiam la lamanidoj jam reiris al siaj bivakoj, vidis de la supro de la monteto Kumora, la dekmilon de mia popolo, kiu kondukata de mi estis dehakita.",
    "Kaj ni vidis ankaŭ la dekmilon de mia popolo, kiun mia filo Moroni kondukis.",
    "Kaj jen, la dekmilo de Gidgiddona falis, kaj ankaŭ li inter ili.",
    "Kaj Lama falis kun sia dekmilo; kaj Gilgal falis kun sia dekmilo; kaj Limha falis kun sia dekmilo; kaj Joneam falis kun sia dekmilo; kaj Kameniha, kaj Moroniha, kaj Antionum, kaj Ŝiblom, kaj Ŝem, kaj Joŝ falis ĉiu kun sia dekmilo.",
    "Kaj okazis, ke dek pli falis per la glavo, ĉiu kun sia dekmilo; jes, falis mia tuta popolo, krom tiuj dudek kvar, kiuj estis kun mi, kaj ankaŭ kelkaj, kiuj eskapis en la sudajn landojn, kaj kelkaj, kiuj apartiĝis al la lamanidoj; kaj ilia karno kaj ostoj kaj sango kuŝis sur la supraĵo de la tero, por forpolviĝi sur la tero, kaj diseriĝi, kaj reveni al la tero, sia patrino.",
    "Kaj mia animo ŝiriĝis de angoro pro la mortigitoj de mia popolo, kaj mi ekkriis:",
    "Ho vi beluloj, kiel eblis, ke vi foriris de la vojoj de la Sinjoro. Ho vi beluloj, kiel eblis, ke vi malakceptis tiun Jesuon, kiu staris kun malfermitaj brakoj por ricevi vin?",
    "Jen, se vi ne estus tion farinta, vi ne estus falinta. Sed jen, vi estas falinta, kaj mi funebras vian perdiĝon.",
    "Ho vi belaj filoj kaj filinoj, vi patroj kaj patrinoj, vi edzoj kaj edzinoj, vi gebeluloj, kiel eblis, ke vi falis?",
    "Sed je, vi foriris, kaj mia veado ne povas revenigi vin.",
    "Kaj la tago baldaŭ venos, kiam via mortema surmetos senmortecon, kaj ĉi tiuj korpoj, kiuj nun forpolviĝas en putriĝeco, devos baldaŭ fariĝi senputraj korpoj; kaj tiam vi devos stari antaŭ la tribunala seĝo de Kristo por esti juĝataj laŭ viaj faroj; kaj, se vi estas virtaj, tiam vi estos benitaj kun viaj patroj, kiuj iris antaŭ vi.",
    "Ho, ke vi estus pentintaj antaŭ ol ĉi tiu granda pereo venis al vi. Sed jen, vi foriris, kaj la Patro, jes, la Eterna Patro de la ĉielo, konas vian staton; kaj li agos kontraŭ vi laŭ sia justeco kaj kompatemo.",
  ],
  footNotes: ["385 p.K."],
} as const satisfies Chapter;
