export const chapter7 = {
  chapterTitle: "Ĉapitro 7",
  summary: "",
  verses: [
    "La filoj de IsaĤar estis:Tola, Pua, Jaŝub, kaj Ŝimron-kvar.",
    "La idoj de Tola:Uzi, Refaja, Jeriel, JaĤmaj, Jibsam, kaj Ŝemuel, ĉefoj de patrodomoj de Tola, kuraĝaj militistoj en siaj generacioj; ilia nombro en la tempo de David estis dudek du mil sescent.",
    "La idoj de Uzi:JizraĤja; la idoj de JizraĤja:MiĤael, Obadja, Joel, kaj Jiŝija-kune kvin patrodomoj.",
    "Kun ili, laŭ iliaj generacioj, laŭ iliaj patrodomoj, estis da militistoj armitaj por milito tridek ses mil; ĉar ili havis multe da edzinoj kaj infanoj.",
    "Da iliaj fratoj, en ĉiuj familioj de IsaĤar, estis okdek sep mil batalkapabluloj, ĉiuj enskribitaj en la genealogiajn listojn.",
    "Ĉe Benjamen:Bela, BeĤer, kaj Jediael-tri.",
    "La idoj de Bela:Ecbon, Uzi, Uziel, Jerimot, kaj Iri-kvin patrodomoj, militkapablaj. En la genealogiaj listoj ili prezentis la nombron de dudek du mil tridek kvar.",
    "La idoj de BeĤer:Zemira, Joaŝ, Eliezer, Eljoenaj, Omri, Jeremot, Abija, Anatot, kaj Alemet; ĉiuj ili estis la filoj de BeĤer.",
    "En la listoj, laŭ ilia genealogio, laŭ iliaj patrodomoj, estis dudek mil ducent batalkapabluloj.",
    "La idoj de Jediael:Bilhan; la idoj de Bilhan:Jeuŝ, Benjamen, Ehud, Kenaana, Zetan, Tarŝiŝ, kaj AĤiŝaĤar.",
    "Ĉiuj ili estis la idoj de Jediael, laŭ patrodomoj, batalkapabluloj, dek sep mil ducent armitaj por milito.",
    "Ŝupim kaj ĥupim, idoj de Ir; ĥuŝim, idoj de AĤer.",
    "La filoj de Naftali:JaĤciel, Guni, Jecer, kaj Ŝalum, filoj de Bilha.",
    "La filoj de Manase:Asriel, kiun naskis lia kromvirino, Sirianino; ŝi naskis ankaŭ MaĤiron, la patron de Gilead.",
    "MaĤir prenis edzinon el la domanaro de ĥupim kaj Ŝupim; la nomo de lia fratino estis MaaĤa. La nomo de la dua estis CelofĤad. CelofĤad havis nur filinojn.",
    "Kaj MaaĤa, la edzino de MaĤir, naskis filon kaj donis al li la nomon Pereŝ; la nomo de lia frato estis Ŝereŝ; liaj filoj estis Ulam kaj Rekem.",
    "La filo de Ulam estis Bedan. Tio estas la filoj de Gilead, filo de MaĤir, filo de Manase.",
    "Lia fratino MoleĤet naskis Iŝ-Hodon, Abiezeron, kaj MaĤlan.",
    "La filoj de Ŝemida estis:AĤjan, ŜeĤem, LikĤi, kaj Aniam.",
    "La idoj de Efraim:ŜutelaĤ, kaj lia filo Bered, kaj lia filo TaĤat, kaj lia filo Eleada, kaj lia filo TaĤat,",
    "kaj lia filo Zabad, kaj lia filo ŜutelaĤ, kaj Ezer, kaj Elead. Kaj mortigis ilin la loĝantoj de Gat, la indiĝenoj de la lando, kiam ili iris, por forpreni iliajn brutojn.",
    "Kaj ilia patro Efraim funebris longan tempon, kaj liaj fratoj venis, por konsoli lin.",
    "Kaj li envenis al sia edzino, kaj ŝi gravediĝis kaj naskis filon, kaj donis al li la nomon Beria, ĉar malfeliĉo okazis en lia domo.",
    "Lia filino estis Ŝeera. Ŝi konstruis Bet-ĥoronon, la malsupran kaj la supran, kaj Uzen-Ŝeeran.",
    "Kaj lia filo estis RefaĤ, lia filo estis Reŝef, lia filo estis TelaĤ, lia filo estis TaĤan,",
    "lia filo estis Ladan, lia filo estis Amihud, lia filo estis Eliŝama,",
    "lia filo estis Nun, lia filo estis Josuo.",
    "Ilia posedaĵo kaj loĝloko estis Bet-El kaj ĝiaj filinurboj, oriente Naaran, okcidente Gezer kun ĝiaj filinurboj, kaj ŜeĤem kun ĝiaj filinurboj, ĝis Aza kun ĝiaj filinurboj;",
    "ĉe la flanko de la Manaseidoj:Bet-Ŝean kun ĝiaj filinurboj, TaanaĤ kun ĝiaj filinurboj, Megido kun ĝiaj filinurboj, Dor kun ĝiaj filinurboj. En tiuj lokoj loĝis la idoj de Jozef, filo de Izrael.",
    "La filoj de Aŝer:Jimna, Jiŝva, Jiŝvi, Beria; ilia fratino estis SeraĤ.",
    "La filoj de Beria:ĥeber, kaj Malkiel, kiu estis la patro de Birzait.",
    "ĥeber naskigis Jafleton, Ŝomeron, ĥotamon, kaj Ŝuan, ilian fratinon.",
    "La filoj de Jaflet:PasaĤ, Bimhal, kaj Aŝvat. Tio estas la filoj de Jaflet.",
    "La filoj de Ŝemer:AĤi, Rohaga, JeĤuba, kaj Aram.",
    "La filoj de lia frato Helem:CofaĤ, Jimna, Ŝeleŝ, kaj Amal.",
    "La filoj de CofaĤ:SuaĤ, ĥarnefer, Ŝual, Beri, Jimra,",
    "Becer, Hod, Ŝama, Ŝilŝa, Jitran, kaj Beera.",
    "La filoj de Jeter:Jefune, Pispa, kaj Ara.",
    "La filoj de Ula:AraĤ, ĥaniel, kaj Ricja.",
    "Ĉiuj ĉi tiuj estis idoj de Aŝer, ĉefoj de patrodomoj, elektitaj, kuraĝaj militistoj, ĉefaj estroj. Ili estis enskribitaj en la genealogia listo, en la militistaro, por milito; ilia nombro estis dudek ses mil viroj.",
  ],
} as const satisfies Chapter;
