export const chapter7 = {
  chapterTitle: "Ĉapitro 7",
  verses: [
    "Kaj nun mi, Moroni, skribis kelkajn el la vortoj de mia patro Mormon, kiujn li diris pri fido, espero kaj karitato; ĉar ĉi-maniere li parolis al la popolo, kiam li instruis al ili en la sinagogo, kiun ili konstruis kiel adorejon.",
    "Kaj nun mi Mormon, parolas al vi, miaj amataj fratoj; kaj per la graco de Dio la Patro kaj nia Sinjoro Jesuo Kristo kaj lia sankta volo, pro la dono de lia voko al mi, mi estas permesita paroli al vi nuntempe.",
    "Pro tio mi volas paroli al vi, kiuj estas anoj de la Eklezio, kiuj estas pacemaj disĉiploj de Kristo, kaj kiuj akiris sufiĉan esperon, per kiu vi povos veni en la ripozon de la Sinjoro, de nun ĝis vi ripozos ĉe li en la ĉielo.",
    "Kaj nun, miaj fratoj, mi juĝas tion pri vi pro via pacema irado inter la homidoj.",
    "Ĉar mi memoras la Vorton de Dio, kiu diras, ke per iliaj faroj vi konos ilin; ĉar se iliaj faroj estas bonaj, ankaŭ ili estas bonaj.",
    "Ĉar jen, Dio jam diris, ke homo malbona ne povas fari tion, kio estas bona; ĉar se li oferdonas donacon, aŭ preĝas al Dio, ne farinte tion kun vera intenco, per tio li neniom profitos.",
    "Ĉar jen, tio ne estos kalkulita al li kiel virto.",
    "Ĉar jen, se homo malbona donas donacon, li tion faras domaĝante; pro kio tio estas kalkulita al li same kvazaŭ li estus konservinta la donacon; pro tio li estas kalkulita kiel malbona antaŭ Dio.",
    "Kaj simile tio estas ankaŭ kalkulata kiel malbono al homo se li preĝas sen vera korintenco; jes, kaj per tio li neniom profitos, ĉar Dio ne akceptas tiajn homojn.",
    "Pro tio faranto de malbono ne povas fari tion, kio estas bona; kaj li ankaŭ ne donos bonan oferdonon.",
    "Ĉar jen, maldolĉa fonto ne povas doni dolĉan akvon; kaj dolĉa fonto ne povas doni maldolĉan akvon; pro tio homo, kiu estas servanto de la Diablo, ne povas sekvi Kriston; kaj se li sekvas Kriston, li ne povas estis servanto de la Diablo.",
    "Tial ĉio, kio estas bona, venas de Dio; kaj tio, kio estas malbona, venas de la Diablo; ĉar la Diablo estas malamiko de Dio, kaj bataladas kontraŭ li, kaj invitas kaj logas al pekado kaj farado de tio kio estas malbona.",
    "Sed jen, tio, kio estas de Dio, invitas kaj logas al farado de bono; tial ĉio, kio invitas kaj logas fari bonon kaj ami Dion kaj servi lin, estas inspirita de Dio.",
    "Pro tio, atentu, miaj amataj fratoj, ke vi ne juĝu tion, kio estas malbona, esti de Dio, aŭ tion, kio estas bona kaj de Dio, esti de la Diablo.",
    "Ĉar jen, miaj fratoj, al vi estas donite juĝi, por ke vi povu distingi bonon de malbono; kaj la juĝmaniero por scii kun perfekta scio estas tiel klara kiel estas la taglumo kompare al la malluma nokto.",
    "Ĉar jen, la Spirito de Kristo estas donita al ĉiu homo, por ke li povu distingi bonon de malbono; por tio mi montras al vi la manieron juĝi; ĉar ĉio, kio logas fari bonon kaj persvadi kredi je Kristo, estas dissendata per la potenco kaj dono de Kristo; por ke vi sciu kun perfekta scio, ke tio estas de Dio.",
    "Sed vi povos scii kun perfekta scio, ke ĉio, kio persvadas homojn fari malbonon kaj ne kredi je Kristo kaj fornei lin kaj ne servi Dion, estas de la Diablo; ĉar laŭ ĉi tiu maniero la Diablo laboras, ĉar li persvadas neniun fari bonon, ne, eĉ ne unu; kaj liaj anĝeloj ankaŭ ne; kaj ankaŭ ne tiuj, kiuj submetas sin al li.",
    "Kaj nun, miaj fratoj, pro tio, ke vi konas la lumon, per kiu vi povos juĝi, kiu lumo estas la lumo de Kristo, atentu, ke vi ne malprave juĝu; ĉar per tiu sama juĝo, per kiu vi juĝas, ankaŭ vi estos juĝata.",
    "Pro tio, mi petegas de vi, fratoj, ke vi serĉu diligente en la lumo de Kristo, por ke vi distingu bonon de malbono; kaj se vi ekprenos ĉion bonan, kaj ne kondamnos ĝin, vi certe estos infano de Kristo.",
    "Kaj nun, miaj fratoj, kiel eblas, ke vi povos ekpreni ĉion bonan?",
    "Kaj nun mi venas al tiu fido, pri kiu mi diris, ke mi parolos; kaj mi diros al vi la manieron laŭ kiu vi povos ekpreni ĉion bonan.",
    "Ĉar jen, Dio, sciante ĉion, estante de eterne ĝis eterne, jen li sendis anĝelojn por spirite helpi la homidojn, klarigante pri la veno de Kristo, kaj ke en Kristo venos ĉio bona.",
    "Kaj Dio ankaŭ deklaris al profetoj, per sia propra buŝo, ke Kristo venos.",
    "Kaj jen, diversmaniere li elmontris al la homidoj tion, kio estas bona; kaj ĉio bona venas de Kristo; alie la homoj estus defalintaj, kaj nenio bona povus veni al ili.",
    "Pro tio, per la spirita helpo de anĝeloj, kaj per ĉiu vorto, kiu eliris el la buŝo de Dio, homoj ekmontirs fidon al Kristo; kaj tiel per fido ili ekprenis ĉion bonan; kaj tiel estis ĝis la veno de Kristo.",
    "Kaj post kiam li venis, homoj estis ankaŭ savitaj per fido al lia nomo; kaj per fido ili fariĝis la filoj de Dio. Kaj tiel certe kiel Kristo vivas, li diris ĉi tiujn vortojn al niaj patroj, dirante; Kio ajn, kio estas bona, kion vi petas de la Patro en mia nomo, en fido kredante ke vi ricevos ĝin, jen tio estos farata al vi.",
    "Tial, miaj amataj fratoj, ĉu mirakloj ĉesis, ĉar Kristo supreniris en la ĉielon kaj eksidis dekstre de Dio por pretendi de la Patro siajn rajtojn de korfavoro, kiun li havas super la homidoj?",
    "Ĉar li plenumis la celojn de la Leĝo, kaj li propetis pro ĉiuj, kiuj havas fidon al li; kaj tiuj, kiuj havas fidon al li, alfiksiĝos al ĉio bona; pro tio li estas Advokato por la homidoj; kaj li loĝas poreterne en la ĉielo.",
    "Kaj ĉar li faris tion, miaj amataj fratoj, ĉu mirakloj ĉesis? Jen mi diras al vi, Ne; kaj ankaŭ anĝeloj ne ĉesis spirite helpi la homidojn.",
    "Ĉar jen, ili estas submetitaj al li, por servi laŭ la vorto de lia ordono, montrante sin al tiuj, kiu havas fortan fidon kaj firman menson en ĉia pieco.",
    "Kaj la ofico de ilia servado estas alvoki homojn al pento, kaj plenumi kaj fari la prilaboron de la interligoj de la Patro, kiujn li faris kun la homidoj, por prepari la vojon inter la homidoj, per deklarado de la vorto de Kristo al la elektitaj vazoj de la Sinjoro, por ke ili atestu pri li.",
    "Kaj tiel farante, Dio la Sinjoro preparas la vojon por ke la ceteraj homoj havu fidon al Kristo, por ke la Sankta Spirito havu lokon en iliaj koroj, per sia povo; kaj laŭ ĉi tiu maniero la Patro plenumas la interligojn, kiujn li faris kun la homidoj.",
    "Kaj Kristo diris: Se vi havos fidon al mi, vi havos povon fari ĉion, kio estas oportuna por mi.",
    "Kaj li diris: Pentu, ĉiuj vi finoj de la tero, kaj venu al mi, kaj baptiĝu en mia nomo, kaj havu fidon al mi, por ke vi estu savitaj.",
    "Kaj nun, miaj amataj fratoj, se ĉi tio, kion mi diris al vi, estas efektive vera, kaj Dio montros al vi, kun forto kaj granda gloro en la lasta tago, ke ĝi estas vera, kaj se ĝi estas vera, ĉu la tempo de mirakloj ĉesis?",
    "Aŭ ĉu anĝeloj ĉesis aperi al la homidoj? Aŭ ĉu li retenis de ili la povon de la Sankta Spirito? Aŭ ĉu li tion faros dum la tempo daŭros, aŭ la tero restos, aŭ unu homo sur ĝis supraĵo estos savota?",
    "Jen mi diras al vi, Ne; ĉar per fido oni faras miraklojn; kaj per fido anĝeloj aperas kaj spirite servas al homoj; tial se tio ĉesis, ve al la homidoj, ĉar tio okazis pro nekredado, kaj ĉio estas vana.",
    "Ĉar neniu homo povas esti savata, laŭ la vortoj de Kristo, krom tiuj, kiuj havos fidon en lia nomo; sekve, se ĉi tio ĉesis, tiam ankaŭ fido ĉesis; kaj terura estas la stato de la homaro, ĉar ili estas kvazaŭ neniu redempto estus farita.",
    "Sed jen, miaj amataj fratoj, mi atendas pli bonajn aferojn de vi, ĉar mi juĝas, ke vi havas fidon al Kristo pro via humileco; ĉar se vi ne havas fidon al li, vi ne meritas esti kalkulitaj inter la popolo de lia eklezio.",
    "Kaj plie, miaj amataj fratoj, mi volas paroli al vi pri espero. Kiel vi povos akiri fidon, se vi ne havas esperon?",
    "Kaj kia estas tio, kion vi esperas? Jen mi diras al vi, ke vi havos esperon esti levata al vivo eterna per la elaĉeto de Kristo kaj la potenco de lia releviĝo, kaj ĉi tion vi havos pro via fido al li laŭ la promeso.",
    "Pro tio, se homo havas fidon, li nepre devas havi esperon; ĉar sen fido ne povas esti la espero.",
    "Kaj krome, jen mi diras al vi, ke li ne povos havi fidon kaj esperon se li ne estos milda kaj korhumila.",
    "Se ne, liaj fido kaj espero estas vanaj, ĉar akcepteblaj antaŭ Dio estas nur tiuj, kiu estas mildaj kaj korhumilaj; kaj se homo estas milda kaj korhumila kaj konfesas per la potenco de la Sankta Spirito, ke Jesuo estas la Kristo, li nepre devas havi karitaton; ĉar se li ne havas karitaton, li estas nenio; pro tio li nepre devas havi karitaton.",
    "Kaj karitato estas pacienca, kaj bonkora, kaj ne envias, kaj ne ŝveligas sin, ne celas por si mem, ne estas facile provokata, pripensas nenian malbonon, kaj ne ĝojas pri malvirteco, sed ĝojas pri la vero, toleras ĉion, kredas ĉion, esperas ĉion, eltenas ĉion.",
    "Pro tio, miaj amataj fratoj, se vi ne havas karitaton, vi estas nenio, ĉar karitato neniam pereas. Pro tio, alfiksiĝu al karitato, kiu estas la plej granda el ĉio, ĉar ĉio devo neniiĝi -",
    "Sed karitato estas la pura amo de Kristo, kaj ĝi eltenas por ĉiam; kaj estos bone al tiu, kiu montriĝos posedata de ĝi en la lasta tago.",
    "Pro tio, miaj amataj fratoj, preĝu al la Patro kun la tuta energio de koro, por ke vi pleniĝu de ĉi tiu amo, kiun li donis al ĉiuj, kiuj estas veraj disĉiploj de lia Filo, Jesuo Kristo; por ke vi fariĝu la filoj de Dio; por ke ni estu similaj al li, kiam li aperos, ĉar ni vidos lin tia, kia li estas; por ke ni havu ĉi tiun esperon; por ke ni estu purigitaj same kiel li estas pura. Amen.",
  ],
  footNotes: ["400-421 p.K."],
} as const satisfies Chapter;
