export const chapter26 = {
  chapterTitle: "Ĉaptiro 26",
  summary: "",
  verses: [
    "Kaj post la punfrapado la Eternulo ekparolis al Moseo, kaj al Eleazar, filo de la pastro Aaron, dirante:",
    "Kalkulu la tutan komunumon de la Izraelidoj en la aĝo de dudek jaroj kaj pli, laŭ iliaj patrodomoj, ĉiujn militkapablajn en Izrael.",
    "Kaj ekparolis al ili Moseo kaj la pastro Eleazar sur la stepoj de Moab apud la JeriĤa Jordan, dirante:",
    "Kalkulu la popolon en la aĝo de dudek jaroj kaj pli, kiel la Eternulo ordonis al Moseo kaj al la Izraelidoj, kiuj eliris el la lando Egipta.",
    "Ruben, la unuenaskito de Izrael. La filoj de Ruben:de ĥanoĤ, la familio de la ĥanoĤidoj; de Palu, la familio de la Paluidoj;",
    "de ĥecron, la familio de la ĥecronidoj; de Karmi, la familio de la Karmiidoj.",
    "Tio estas la familioj de la Rubenidoj; kaj ilia nombro estas kvardek tri mil sepcent tridek.",
    "Kaj la filoj de Palu:Eliab.",
    "Kaj la filoj de Eliab:Nemuel kaj Datan kaj Abiram; tio estas tiuj Datan kaj Abiram, eminentuloj de la komunumo, kiuj ribelis kontraŭ Moseo kaj Aaron en la anaro de KoraĤ, kiam ili ribelis kontraŭ la Eternulo",
    "kaj la tero malfermis sian buŝon kaj englutis ilin kaj KoraĤon ĉe la morto de la anaro, kiam la fajro ekstermis la ducent kvindek homojn, kaj ili fariĝis averto.",
    "Sed la filoj de KoraĤ ne mortis.",
    "La filoj de Simeon laŭ iliaj familioj:de Nemuel, la familio de la Nemuelidoj; de Jamin, la familio de la Jaminidoj; de JaĤin, la familio de la JaĤinidoj;",
    "de ZeraĤ, la familio de la ZeraĤidoj; de Ŝaul, la familio de la Ŝaulidoj.",
    "Tio estas la familioj de la Simeonidoj, dudek du mil ducent.",
    "La filoj de Gad laŭ iliaj familioj:de Cefon, la familio de la Cefonidoj; de ĥagi, la familio de la ĥagiidoj; de Ŝuni, la familio de la Ŝuniidoj;",
    "de Ozni, la familio de la Ozniidoj; de Eri, la familio de la Eriidoj;",
    "de Arod, la familio de la Arodidoj; de Areli, la familio de la Areliidoj.",
    "Tio estas la familioj de la Gadidoj, laŭ ilia nombro kvardek mil kvincent.",
    "La filoj de Jehuda:Er kaj Onan; sed Er kaj Onan mortis en la lando Kanaana.",
    "Kaj la filoj de Jehuda laŭ iliaj familioj estis:de Ŝela, la familio de la Ŝelaidoj; de Perec, la familio de la Perecidoj; de ZeraĤ, la familio de la ZeraĤidoj.",
    "Kaj la filoj de Perec estis:de ĥecron, la familio de la ĥecronidoj; de ĥamul, la familio de la ĥamulidoj.",
    "Tio estas la familioj de Jehuda, laŭ ilia nombro sepdek ses mil kvincent.",
    "La filoj de IsaĤar laŭ iliaj familioj:de Tola, la familio de la Tolaidoj; de Puva, la familio de la Puvaidoj;",
    "de Jaŝub, la familio de la Jaŝubidoj; de Ŝimron, la familio de la Ŝimronidoj.",
    "Tio estas la familioj de IsaĤar, laŭ ilia nombro sesdek kvar mil tricent.",
    "La filoj de Zebulun laŭ iliaj familioj:de Sered, la familio de la Seredidoj; de Elon, la familio de la Elonidoj; de JaĤleel, la familio de la JaĤleelidoj.",
    "Tio estas la familioj de la Zebulunidoj, laŭ ilia nombro sesdek mil kvincent.",
    "La filoj de Jozef laŭ iliaj familioj:Manase kaj Efraim.",
    "La filoj de Manase:de MaĤir, la familio de la MaĤiridoj; kaj de MaĤir naskiĝis Gilead; de Gilead, la familio de la Gileadidoj.",
    "Jen estas la filoj de Gilead:de Iezer, la familio de la Iezeridoj; de ĥelek, la familio de la ĥelekidoj;",
    "kaj de Asriel, la familio de la Asrielidoj; kaj de ŜeĤem, la familio de la ŜeĤemidoj;",
    "kaj de Ŝemida, la familio de la Ŝemidaidoj; kaj de ĥefer, la familio de la ĥeferidoj.",
    "Kaj CelofĤad, filo de ĥefer, ne havis filojn, sed nur filinojn; kaj la nomoj de la filinoj de CelofĤad estis:MaĤla kaj Noa kaj ĥogla kaj Milka kaj Tirca.",
    "Tio estas la familioj de Manase, laŭ ilia nombro kvindek du mil sepcent.",
    "Jen estas la filoj de Efraim laŭ iliaj familioj:de ŜutelaĤ, la familio de la ŜutelaĤidoj; de BeĤer, la familio de la BeĤeridoj; de TaĤan, la familio de la TaĤanidoj.",
    "Kaj jen estas la filoj de ŜutelaĤ:de Eran, la familio de la Eranidoj.",
    "Tio estas la familioj de la filoj de Efraim, laŭ ilia nombro tridek du mil kvincent. Tio estas la filoj de Jozef laŭ iliaj familioj.",
    "La filoj de Benjamen laŭ iliaj familioj:de Bela, la familio de la Belaidoj; de Aŝbel, la familio de la Aŝbelidoj; de AĤiram, la familio de la AĤiramidoj;",
    "de Ŝefufam, la familio de la Ŝefufamidoj; de ĥufam la familio de la ĥufamidoj.",
    "Kaj la filoj de Bela estis:Ard kaj Naaman; de Ard, la familio de la Ardidoj; de Naaman, la familio de la Naamanidoj.",
    "Tio estas la filoj de Benjamen laŭ iliaj familioj, kaj ilia nombro estis kvardek kvin mil sescent.",
    "Jen estas la filoj de Dan laŭ iliaj familioj:de ŜuĤam, la familio de la ŜuĤamidoj. Tio estas la familioj de Dan laŭ iliaj familioj.",
    "Ĉiuj familioj de la ŜuĤamidoj prezentis la nombron de sesdek kvar mil kvarcent.",
    "La filoj de Aŝer laŭ iliaj familioj:de Jimna, la familio de la Jimnaidoj; de Jiŝvi, la familio de la Jiŝviidoj; de Beria, la familio de la Beriaidoj.",
    "De la filoj de Beria:de ĥeber, la familio de la ĥeberidoj; de Malkiel, la familio de la Malkielidoj.",
    "Kaj la nomo de la filino de Aŝer estis SeraĤ.",
    "Tio estas la familioj de la filoj de Aŝer, laŭ ilia nombro kvindek tri mil kvarcent.",
    "La filoj de Naftali laŭ iliaj familioj:de JaĤceel, la familio de la JaĤceelidoj; de Guni, la familio de la Guniidoj;",
    "de Jecer, la familio de la Jeceridoj; de Ŝilem la familio de la Ŝilemidoj.",
    "Tio estas la familioj de Naftali laŭ iliaj familioj, kaj ilia nombro estis kvardek kvin mil kvarcent.",
    "Tia estis la kalkulita nombro de la Izraelidoj:sescent unu mil sepcent tridek.",
    "Kaj la Eternulo ekparolis al Moseo, dirante:",
    "Al tiuj estu dividita la tero kiel posedaĵo laŭ la nombro de la nomoj.",
    "Al la plinombra donu pli grandan posedaĵon, kaj al la malplinombra donu malpli grandan posedaĵon; al ĉiu laŭ lia nombro estu donita lia posedaĵo.",
    "Sed per loto oni dividu la teron; laŭ la nomo de siaj patraj triboj ili ricevu posedaĵon.",
    "Per la loto oni dividu al ĉiu lian posedaĵon, kiel al la plinombraj, tiel al la malplinombraj.",
    "Kaj jen estas la kalkulitoj de Levi laŭ iliaj familioj:de Gerŝon, la familio de la Gerŝonidoj; de Kehat, la familio de la Kehatidoj; de Merari, la familio de la Merariidoj.",
    "Jen estas la familioj de Levi:la familio de la Libniidoj, la familio de la ĥebronidoj, la familio de la MaĤliidoj, la familio de la Muŝiidoj, la familio de la KoraĤidoj. Kaj de Kehat naskiĝis Amram.",
    "Kaj la nomo de la edzino de Amram estis JoĤebed, filino de Levi, kiu estis naskita al Levi en Egiptujo; kaj ŝi naskis al Amram Aaronon kaj Moseon kaj ilian fratinon Mirjam.",
    "Kaj al Aaron naskiĝis Nadab kaj Abihu kaj Eleazar kaj Itamar.",
    "Sed Nadab kaj Abihu mortis, kiam ili alportis fremdan fajron antaŭ la Eternulon.",
    "Kaj la nombro de iliaj kalkulitoj estis dudek tri mil, ĉiuj virseksuloj en la aĝo de pli ol unu monato; ĉar ili ne estis kalkulitaj kune kun la Izraelidoj, ĉar al ili ne estis donita posedaĵo inter la Izraelidoj.",
    "Tio estas la nombro, kiun kalkulis Moseo kaj la pastro Eleazar, kiuj kalkulis la Izraelidojn sur la stepoj de Moab ĉe la JeriĤa Jordan.",
    "Kaj inter ili estis neniu el tiuj, kiujn kalkulis Moseo kaj la pastro Aaron, kiam ili kalkulis la Izraelidojn en la dezerto Sinaj.",
    "Ĉar la Eternulo diris pri ili:Ili mortos en la dezerto. Kaj restis el ili neniu, krom Kaleb, filo de Jefune, kaj Josuo, filo de Nun.",
  ],
} as const satisfies Chapter;
