export const chapter6 = {
  chapterTitle: "Ĉaptiro 6",
  summary: "",
  verses: [
    "La filoj de Levi:Gerŝon, Kehat, kaj Merari.",
    "La filoj de Kehat:Amram, Jichar, ĥebron, kaj Uziel.",
    "La infanoj de Amram:Aaron, Moseo, kaj Mirjam; kaj la filoj de Aaron:Nadab, Abihu, Eleazar, kaj Itamar.",
    "Eleazar naskigis PineĤason, PineĤas naskigis Abiŝuan,",
    "Abiŝua naskigis Bukin, Buki naskigis Uzin,",
    "Uzi naskigis ZeraĤjan, ZeraĤja naskigis Merajoton,",
    "Merajot naskigis Amarjan, Amarja naskigis AĤitubon,",
    "AĤitub naskigis Cadokon, Cadok naskigis AĤimaacon,",
    "AĤimaac naskigis Azarjan, Azarja naskigis JoĤananon,",
    "JoĤanan naskigis Azarjan (li estis tiu, kiu estis pastro en la domo, kiun Salomono konstruis en Jerusalem),",
    "Azarja naskigis Amarjan, Amarja naskigis AĤitubon,",
    "AĤitub naskigis Cadokon, Cadok naskigis Ŝalumon,",
    "Ŝalum naskigis ĥilkijan, ĥilkija naskigis Azarjan,",
    "Azarja naskigis Serajan, Seraja naskigis Jehocadakon.",
    "Jehocadak iris en kaptitecon, kiam la Eternulo elpatrujigis la Judojn kaj la Jerusalemanojn per Nebukadnecar.",
    "La filoj de Levi:Gerŝon, Kehat, kaj Merari.",
    "Jen estas la nomoj de la filoj de Gerŝon:Libni kaj Ŝimei.",
    "La filoj de Kehat:Amram, Jichar, ĥebron, kaj Uziel.",
    "La filoj de Merari:MaĤli kaj Muŝi. Kaj jen estas la familioj de Levi laŭ iliaj patrodomoj:",
    "la idoj de Gerŝon:Libni; lia filo:JaĤat; lia filo:Zima;",
    "lia filo:JoaĤ; lia filo:Ido; lia filo:ZeraĤ; lia filo:Jeatraj.",
    "La idoj de Kehat:lia filo:Aminadab; lia filo:KoraĤ; lia filo:Asir;",
    "lia filo:Elkana; lia filo:Ebjasaf; lia filo:Asir;",
    "lia filo:TaĤat; lia filo:Uriel; lia filo:Uzija; lia filo:Ŝaul.",
    "La filoj de Elkana:Amasaj kaj AĤimot.",
    "Elkana:la idoj de Elkana:lia filo:Cofaj; lia filo:NaĤat;",
    "lia filo:Eliab; lia filo:JeroĤam; lia filo:Elkana.",
    "La filoj de Samuel:la unuenaskito Vaŝni, kaj Abija.",
    "La idoj de Merari:MaĤli; lia filo:Libni; lia filo:Ŝimei; lia filo:Uza;",
    "lia filo:Ŝimea; lia filo:ĥagija; lia filo:Asaja.",
    "Jen estas tiuj, kiujn David starigis por kantado en la domo de la Eternulo de post la tempo, kiam la sankta kesto trovis tie ripozejon;",
    "ili servadis antaŭ la tabernaklo de kunveno per kantado, ĝis Salomono konstruis la domon de la Eternulo en Jerusalem; kaj ili stariĝadis al sia servado laŭ sia regularo;",
    "jen estas tiuj, kiuj stariĝadis, kaj iliaj filoj:el la Kehatidoj estis la kantisto Heman, filo de Joel, filo de Samuel,",
    "filo de Elkana, filo de JeroĤam, filo de Eliel, filo de ToaĤ,",
    "filo de Cuf, filo de Elkana, filo de MaĤat, filo de Amasaj,",
    "filo de Elkana, filo de Joel, filo de Azarja, filo de Cefanja,",
    "filo de TaĤat, filo de Asir, filo de Ebjasaf, filo de KoraĤ,",
    "filo de Jichar, filo de Kehat, filo de Levi, filo de Izrael.",
    "Kaj lia frato Asaf, kiu staradis dekstre de li, Asaf, filo de BereĤja, filo de Ŝimea,",
    "filo de MiĤael, filo de Baaseja, filo de Malkija,",
    "filo de Etni, filo de ZeraĤ, filo de Adaja,",
    "filo de Etan, filo de Zima, filo de Ŝimei,",
    "filo de JaĤat, filo de Gerŝon, filo de Levi.",
    "La idoj de Merari, iliaj fratoj, staradis maldekstre:Etan, filo de Kiŝi, filo de Abdi, filo de MaluĤ,",
    "filo de ĥaŝabja, filo de Amacja, filo de ĥilkija,",
    "filo de Amci, filo de Bani, filo de Ŝemer,",
    "filo de MaĤli, filo de Muŝi, filo de Merari, filo de Levi.",
    "Kaj iliaj fratoj, la Levidoj, estis destinitaj por ĉiuj servoj en la tabernaklo de la domo de Dio.",
    "Aaron kaj liaj filoj incensadis sur la altaro de bruloferoj kaj sur la altaro de incensado; ili estis destinitaj por ĉiuj servoj en la plejsanktejo, kaj por pekliberigi Izraelon, konforme al ĉio, kion ordonis Moseo, servanto de Dio.",
    "Kaj jen estas la idoj de Aaron:lia filo:Eleazar; lia filo:PineĤas; lia filo:Abiŝua;",
    "lia filo:Buki; lia filo:Uzi; lia filo:ZeraĤja;",
    "lia filo:Merajot; lia filo:Amarja; lia filo:AĤitub;",
    "lia filo:Cadok; lia filo:AĤimaac.",
    "Kaj jen estas iliaj loĝlokoj, laŭ iliaj vilaĝoj en iliaj limoj:al la idoj de Aaron, al la familioj de la Kehatidoj, ĉar al ili destinis la loto,",
    "oni donis ĥebronon, en la lando de Jehuda, kaj ĝiajn antaŭurbojn ĉirkaŭ ĝi;",
    "sed la kampon de tiu urbo kaj ĝiajn vilaĝojn oni donis al Kaleb, filo de Jefune.",
    "Al la idoj de Aaron oni donis la urbojn de rifuĝo:ĥebronon, Libnan kaj ĝiajn antaŭurbojn, Jatiron, Eŝtemoan kaj ĝiajn antaŭurbojn,",
    "ĥilenon kaj ĝiajn antaŭurbojn, Debiron kaj ĝiajn antaŭurbojn,",
    "Aŝanon kaj ĝiajn antaŭurbojn, Bet-Ŝemeŝon kaj ĝiajn antaŭurbojn;",
    "kaj de la tribo de Benjamen:Geban kaj ĝiajn antaŭurbojn, Alemeton kaj ĝiajn antaŭurbojn, kaj Anatoton kaj ĝiajn antaŭurbojn. La nombro de ĉiuj iliaj urboj en iliaj familioj estis dek tri urboj.",
    "Al la idoj de Kehat, kiuj restis el la familio de la tribo, oni donis de la duontribo de Manase laŭlote dek urbojn.",
    "Al la idoj de Gerŝon laŭ iliaj familioj oni donis de la tribo IsaĤar, de la tribo Aŝer, de la tribo Naftali, kaj de la tribo Manase en Baŝan dek tri urbojn.",
    "Al la idoj de Merari laŭ iliaj familioj oni donis de la tribo Ruben, de la tribo Gad, kaj de la tribo Zebulun laŭlote dek du urbojn.",
    "Kaj la Izraelidoj donis al la Levidoj la urbojn kaj iliajn antaŭurbojn.",
    "Ili donis laŭlote de la tribo de la Jehudaidoj, de la tribo de la Simeonidoj, kaj de la tribo de la Benjamenidoj tiujn urbojn, kiujn ili nomis laŭ la nomoj.",
    "Al kelkaj familioj el la idoj de Kehat oni donis urbojn, apartenontajn al ili, de la tribo Efraim.",
    "Kaj oni donis al ili la urbojn de rifuĝo:ŜeĤemon kaj ĝiajn antaŭurbojn, sur la monto de Efraim, Gezeron kaj ĝiajn antaŭurbojn,",
    "Jokmeamon kaj ĝiajn antaŭurbojn, Bet-ĥoronon kaj ĝiajn antaŭurbojn,",
    "Ajalonon kaj ĝiajn antaŭurbojn, Gat-Rimonon kaj ĝiajn antaŭurbojn;",
    "kaj de la duontribo de Manase:Aneron kaj ĝiajn antaŭurbojn, Bileamon kaj ĝiajn antaŭurbojn. Tio estis por la restintaj familioj de la Kehatidoj.",
    "Al la idoj de Gerŝon oni donis de la familioj de la duontribo de Manase:Golanon en Baŝan kaj ĝiajn antaŭurbojn, kaj Aŝtaroton kaj ĝiajn antaŭurbojn;",
    "de la tribo IsaĤar:Kedeŝon kaj ĝiajn antaŭurbojn, Dabraton kaj ĝiajn antaŭurbojn,",
    "Ramoton kaj ĝiajn antaŭurbojn, kaj Anemon kaj ĝiajn antaŭurbojn;",
    "de la tribo Aŝer:Maŝalon kaj ĝiajn antaŭurbojn, Abdonon kaj ĝiajn antaŭurbojn,",
    "ĥukokon kaj ĝiajn antaŭurbojn, kaj ReĤobon kaj ĝiajn antaŭurbojn;",
    "de la tribo Naftali:Kedeŝon en Galileo kaj ĝiajn antaŭurbojn, ĥamonon kaj ĝiajn antaŭurbojn, kaj Kirjataimon kaj ĝiajn antaŭurbojn.",
    "Al la ceteraj idoj de Merari oni donis de la tribo Zebulun:Rimonon kaj ĝiajn antaŭurbojn, kaj Taboron kaj ĝiajn antaŭurbojn;",
    "kaj transe de Jordan, kontraŭ JeriĤo, oriente de Jordan, oni donis de la tribo Ruben:Beceron en la dezerto kaj ĝiajn antaŭurbojn, Jahacon kaj ĝiajn antaŭurbojn,",
    "Kedemoton kaj ĝiajn antaŭurbojn, kaj Mefaaton kaj ĝiajn antaŭurbojn;",
    "kaj de la tribo Gad:Ramoton en Gilead kaj ĝiajn antaŭurbojn, MaĤanaimon kaj ĝiajn antaŭurbojn,",
    "ĥeŝbonon kaj ĝiajn antaŭurbojn, kaj Jazeron kaj ĝiajn antaŭurbojn.",
  ],
} as const satisfies Chapter;
