export const chapter12 = {
  chapterTitle: "Ĉapitro 12",
  verses: [
    "Kaj okazis, post kiam Jesuo parolis ĉi tiujn vortojn al Nifai, kaj al tiuj, kiuj estis vokitaj, (tiam la nombro de tiuj, kiuj estis vokitaj kaj ricevis potencon kaj aŭtoritaton bapti, estis dek du) ke jen, li etendis sian manon al la homamaso, kaj kriis al ili, dirante; Benataj estas vi, se vi atentos la vortojn de ĉi tiuj dek du, kiujn mi elektis el inter vi por pastrohelpi al vi kaj esti viaj servantoj; kaj al ili mi donis aŭtoritaton, por ke ili povu bapti vin per akvo; kaj, kiam vi estos baptitaj per akvo, jen, mi baptos vin per fajro kaj per la Sankta Spirito; tial benataj estas vi se vi kredos je mi kaj estos baptitaj, post kiam vi vidis min kaj scias, ke mi estas.",
    "Kaj plue, pli feliĉaj estas tiuj, kiuj kredos je viaj vortoj pro tio, ke vi atestos, ke vi vidis min, kaj ke vi scias, ke mi estas. Jes, feliĉaj estas tiuj, kiuj kredos je viaj vortoj kaj venos malsupren en la profundaĵon de humileco kaj estos baptitaj, ĉar ili estos helpataj per fajro kaj per la Sankta Spirito kaj ricevos pardonadon de siaj pekoj.",
    "Jes, feliĉaj estas la malriĉaj en spirito, kiuj venas al mi, ĉar ilia estas la regno de la ĉielo.",
    "Kaj plue, feliĉaj estas ĉiuj plorantoj, ĉar ili konsoliĝos.",
    "Kaj feliĉaj estas la humilaj, ĉar ili heredos la teron.",
    "Kaj feliĉaj estas ĉiuj tiuj, kiuj malsatas kaj soifas justecon, ĉar ili satiĝos per la Sankta Spirito.",
    "Kaj feliĉaj estas la kompatemaj, ĉar ili ricevos kompaton.",
    "Kaj feliĉaj estas ĉiuj kore puraj, ĉar ili vidos Dion.",
    "Kaj feliĉaj estas ĉiuj pacigantoj, ĉar filoj de Dio ili estos nomataj.",
    "Kaj feliĉaj estas ĉiuj, kiuj estas persekutitaj pro mia nomo, ĉar ilia estas la regno de la ĉielo.",
    "Kaj feliĉaj estas vi, kiam oni vin riproĉos kaj persekutos kaj false vin kalumnios pro mi;",
    "Ĉar vi havos grandan ĝojon kaj raviĝon, ĉar via rekompenco estos granda en la ĉielo; ĉar tiel oni persekutis la profetojn, kiuj estis antaŭ vi.",
    "Vere, vere, mi diras al vi, mi donas al vi esti la salo de la tero; sed se la salo sengustiĝos, per kio la tero estos salita? La salo jam taŭgos por nenio, krom por esti elĵetita kaj piedpremita de homoj.",
    "Vere, vere, mi diras al vi, mi donas al vi esti la lumo de ĉi tiu popolo. Urbo starigita sur monto ne povas esti kaŝita.",
    "Jen, ĉu oni bruligas lampon, kaj metas ĝin sub grenmezurilon? Ne, sed sur la lampingon, kaj ĝi lumas sur ĉiujn, kiuj estas en la domo;",
    "Pro tio tiel same via lumo lumu antaŭ ĉi tiu popolo, por ke ili vidu viajn bonajn farojn kaj gloru vian Patron, kiu estas en la ĉielo.",
    "Ne pensu, ke mi venis por detrui la leĝon aŭ la profetojn. Mi venis ne por detrui, sed por plenumi;",
    "Vere mi diras al vi, nek unu joto nek unu streketo forpasis de la leĝo, sed en mi ĉio plenumiĝis.",
    "Kaj jen, mi donis al vi la leĝon kaj la ordonojn de mia Patro, por ke vi kredu je mi, kaj pentu pri viaj pekoj, kaj venu al mi kun rompita koro kaj pentema spirito. Jen, vi havas la ordonojn antaŭ vi, kaj la leĝo plenumiĝis.",
    "Tial venu al mi kaj saviĝu; ĉar vere mi diras al vi, ke, se vi ne observos miajn ordonojn, kiujn mi ĉi momente ordonis al vi, vi neniel eniros en la regnon de la ĉielo.",
    "Vi aŭdis, ke estas dirite de la antikvuloj, kaj estas ankaŭ skribite antaŭ vi, ke vi ne mortigu, kaj kiu mortigas, tiu estos en danĝero de juĝado de Dio;",
    "Sed mi diras al vi, ke kiu koleras kontraŭ sia frato, tiu estos en danĝero de lia juĝado. Kaj kiu diros al sia frato; Raka, tiu estos en danĝero de la sinedrio; kaj kiu diros: Malsaĝulo, tiu estos en danĝero de Gehena de fajro.",
    "Tial, se vi venos al mi, aŭ deziros veni al mi, kaj memoros, ke via frato havas ion kontraŭ vi -",
    "Foriru al via frato, kaj unue paciĝu kun via frato, kaj poste venu al mi kun plena korintenco, kaj mi akceptos vin.",
    "Konsentu rapide kun via kontraŭulo, dum vi estas kun li sur la vojo, por ke li ne prenu vin kaj por ke vi ne estu ĵetita en malliberejon.",
    "Vere, vere, mi diras al vi, ke vi neniel eliros el tie, ĝis vi pagos la lastan seninon. Kaj dum vi estos en malliberejo, ĉu vi povos pagi eĉ unu seninon? Vere, vere, mi diras al vi, ke ne.",
    "Jen, estas skribite de la antikvuloj, ke vi ne adultu;",
    "Sed mi diras al vi, ke ĉiu, kiu rigardas virinon, por deziri ŝin, jam adultis en sia koro.",
    "Jen, mi donas al vi ordonon, ke vi ne permesu, ke io ajn el ĉi tio eniru en vian koron;",
    "Ĉar estas pli bone ke vi abnegacius ĉi tion, kaj levus vian krucon, ol ke vi estus ĵetita en Gehenan.",
    "Estas skribite, ke, kiu forsendos sian edzinon, tiu donu al ŝi eksedzigan leteron.",
    "Vere, vere, mi diras al vi, ke ĉiu, kiu forsendos sian edzinon, krom pro malĉasteco, igos ŝin adulti; kaj kiu edziĝos kun forsenditino, tiu adultos.",
    "Kaj, plue, estas skribite: Ne rompu ĵurojn, sed plenumu viajn ĵurojn antaŭ la Sinjoro;",
    "Sed vere, vere, mi diras al vi: Tute ne ĵuru; nek per la ĉielo, ĉar ĝi estas la trono de Dio;",
    "Nek per la tero, ĉar ĝi estas la benketo de liaj piedoj;",
    "Nek ĵuru per la kapo, ĉar vi ne povas fari eĉ unu haron nigra aŭ blanka;",
    "Sed via parolo estu; Jes, jes; Ne, ne; ĉio ekster tio venas el malbono.",
    "Kaj jen, estas skribite: Okulon pro okulo, kaj denton pro dento;",
    "Sed mi diras al vi: Ne rezistu al malbono; sed al tiu, kiu frapas vian dekstran vangon, turnu ankaŭ la alian;",
    "Kaj se iu deziras procesi kontraŭ vi, por forpreni vian tunikon, lasu lin preni ankaŭ vian mantelon;",
    "Kaj se iu devigas vin iri unu mejlon, iru kun li du.",
    "Donu al tiu, kiu petas de vi; kaj ne deturnu vin de tiu, kiu deziras prunti de vi.",
    "Kaj jen, estas skribite ankaŭ, ke vi amu vian proksimulon, kaj malamu vian malamikon;",
    "Sed jen, mi diras al vi: Amu viajn malamikojn: benu tiujn, kiuj vin malbenas; faru bonon al viaj malamantoj; kaj preĝu por tiuj, kiuj kun insulto vin atakas kaj vin persekutas;",
    "Por ke vi estu filoj de via Patro, kiu estas en la ĉielo; ĉar li levas sian sunon sur la malbonulojn kaj bonulojn.",
    "Tial tio, kio estis antikva kaj sub la leĝo, tute plenumiĝis en mi.",
    "Malnovaĵoj neniiĝis, kaj ĉio fariĝis nova.",
    "Tial mi volas, ke vi estu perfektaj, kiel mi aŭ via Ĉiela Patro estas perfekta.",
  ],
  footNotes: ["34 p.K."],
} as const satisfies Chapter;
