export const chapter18 = {
  chapterTitle: "Ĉapitro 18",
  verses: [
    "Kaj okazis, ke Jesuo ordonis al siaj disĉiploj, ke ili alportu iom da pano kaj vino al li.",
    "Kaj, kiam ili foriris por pano kaj vino, li ordonis al la homamaso, ke ĝi sidiĝu sur la tero.",
    "Kaj, kiam la disĉiploj alvenis kun pano kaj vino, li prenis al la pano kaj dispeĉigis kaj benis ĝin; kaj li disdonis al la disĉiploj kaj ordonis, ke ili manĝu.",
    "Kaj, post kiam ili manĝis kaj pleniĝis, li ordonis, ke ili disdonu al la homamaso.",
    "Kaj, post kiam la homamaso manĝis kaj pleniĝis, li diris al la disĉiploj; Jen unu estos ordinita inter vi, kaj al tiu mi donos aŭtoritaton, ke li dispecigu panon kaj benu ĝin kaj donu ĝin al la homoj de mia eklezio, al ĉiuj, kiuj kredos kaj estos baptitaj en mia nomo.",
    "Kaj ĉi tion vi ĉiam devos observi fari, eĉ kiel mi faris, eĉ kiel mi dispecigis panon kaj benis ĝin kaj disdonis ĝin al vi.",
    "Kaj ĉi tion vi devos fari por memorigo pri mia korpo, kiun mi montris al vi. Kaj tio estos atestaĵo al la Patro, ke vi ĉiam memoras min. Kaj, se vi ĉiam memoros min, vi havos mian Spiriton ĉe vi.",
    "Kaj okazis, kiam li diris ĉi tiujn vortojn, ke li ordonis al siaj disĉiploj, ke ili prenu el la vino de la kaliko kaj trinku el ĝi, kaj ke ili ankaŭ disdonu al la homamaso, por ke ĝi trinku el ĝi.",
    "Kaj okazis, ke ili tion faris, kaj trinkis el ĝi kaj sensoifiĝis; kaj ili disdonis al la homamaso, kaj tiu trinkis, kaj tiu sensoifiĝis.",
    "Kaj, post kiam la disĉiploj faris tion, Jesuo diris al ili: Feliĉaj estas vi pro tio, kion vi faris, ĉar tio plenumas miajn ordonojn, kaj tio atestas al la Patro, ke vi deziras fari tion, kion mi ordonis al vi.",
    "Kaj ĉi tion vi devos ĉiam fari al tiuj, kiuj pentas kaj baptiĝas en mia nomo; kaj vi devos fari ĉi tion por memorigo pri mia sango, kiun mi elverŝis por vi, por ke vi atestu al la Patro, ke vi ĉiam memoras min. Kaj, se vi ĉiam memoros min, vi havos mian Spiriton ĉe vi.",
    "Kaj mi donas al vi ordonon, ke vi faru ĉi tion. Kaj, se vi ĉiam faros ĉi tion, feliĉaj estas vi, ĉar vi konstruiĝas sur mia roko.",
    "Sed ĉiuj inter vi kiuj faros pli aŭ malpli ol ĉi tion, ne konstruiĝas sur mia roko, sed konstruiĝas sur sabla fundamento; kaj, kiam falas pluvo, kaj venas inundoj, kaj blovas ventoj, kaj albatas ilin, ili falos, kaj la pordegoj de Hades estas malfermitaj, pretaj por ricevi ilin.",
    "Do, feliĉaj estas vi, se vi obeos miajn ordonojn, kiujn la Patro ordonis al mi doni al vi.",
    "Vere, vere, mi diras al vi, vi devas ĉiam vigli kaj preĝi, por ke vi ne estu tentataj de la Diablo kaj por ke vi ne estu forkaptataj de li.",
    "Kaj same kiel mi preĝis inter vi, eĉ tiel vi devos preĝi en mia eklezio, inter mia popolo, kiu pentas kaj baptiĝas en mia nomo. Jen mi estas la Lumo; mi donis ekzemplon por vi.",
    "Kaj okazis, post kiam Jesuo diris ĉi tiujn vortojn al siaj disĉiploj, ke li denove turnis sin al la homamaso kaj diris al ĝi:",
    "Jen, vere, vere, mi diras al vi, vi devos ĉiam vigli kaj preĝi, por ke vi ne eniru en tenton; ĉar Satano deziras havi vin, por ke li disĵetu vin per kribrilo kiel tritikajn grajnojn.",
    "Vi do devos ĉiam preĝi al la Patro en mia nomo.",
    "Kaj kion ajn, kio estas justa, kion vi petos de la Patro en mia nomo, kredante ke vi ricevos ĝin, jen ĝi estos donata al vi.",
    "Preĝu en viaj familioj al la Patro, ĉiam en mia nomo, por ke viaj edzinoj kaj viaj infanoj estu benataj.",
    "Kaj jen, vi devos ofte kune kunveni; kaj vi devos ne malpermesi, ke homoj venu al vi, kiam vi kune kunvenos, sed vi devos permesi, ke ili venu al vi, kaj vi devos ne malpermesi ilin;",
    "Sed vi devos preĝi por ili kaj ne forpeli ilin; kaj, se ili eventuale ofte venos al vi, vi devos preĝi por ili al la Patro, en mia nomo.",
    "Do, alte tenu vian lumon, por ke ĝi brilu al la mondo. Jen mi estas la Lumo, kiun vi devos alte teni kion vi vidis min fari. Jen vi vidas, ke mi preĝis al la Patro, kaj vi ĉiuj tion atestis.",
    "Kaj vi vidas, ke mi ordonis, ke neniu el vi foriru, sed mi ordonis, ke vi anstataŭe venu al mi, por ke vi tuŝu kaj vidu; vi devos same fari al la mondo; kaj ĉiu, kiu rompos ĉi tiun ordonon, lasos sin kondukiĝi en tenton.",
    "Kaj tiam okazis, kiam Jesuo parolis ĉi tiujn vortojn, ke li denove turnis sian rigardon al la disĉiploj, kiujn li elektis, kaj diris al ili;",
    "Jen vere, vere, mi diras al vi, mi donos al vi unu plian ordonon, kaj poste mi devos iri al mia Patro, por ke mi plenumu aliajn ordonojn, kiujn li donis al mi.",
    "Kaj nun jen la ordono, kiun mi donas al vi, ke vi ne plenscie permesu, ke iu neinde partoprenu en mia sango kaj karno, kiam vi disdonos ĝin;",
    "Ĉar ĉiu, kiu neinde manĝas mian karnon kaj trinkas mian sangon, manĝas kaj trinkas juĝon al sia animo; tial, se vi scios, ke homo ne indas manĝi el mia karno kaj trinki el mia sango, vi devos malpermesi tion al li.",
    "Tamen, vi devos ne elpeli lin el inter vi, sed vi devos pastrohelpi al li kaj preĝi por li al la Patro, en mia nomo; kaj, se li eventuale pentos kaj estos baptita en mia nomo, tiam vi devos akcepti lin kaj doni al li el mia sango kaj karno.",
    "Sed, se li ne pentos, li ne estos kalkulita inter mia popolo, por ke li ne detruu mian popolon, ĉar jen mi konas miajn ŝafojn, kaj ili estas kalkulitaj.",
    "Tamen, vi devos ne forpeli lin el viaj sinagogoj, aŭ viaj preĝejo, ĉar al tiaj homoj vi devos pastrohelpadi; ĉar vi ne scias, ke ili ne revenos kaj pentos, kaj venos al mi kun plena korfirmeco, kaj mi kuracos ilin; kaj vi estos la helpilo por venigi savon al ili.",
    "Do, observu ĉi tiujn vortojn, kiujn mi ordonis al vi, por ke vi ne venu sub juĝon; ĉar ve al tiu, kiun la Patro kondamnas.",
    "Kaj mi donas al vi ĉi tiujn ordonojn pro la disputadoj, kiuj okazis inter vi. Kaj feliĉaj estas vi, se disputoj ne okazos inter vi.",
    "Kaj nun mi iros al la Patro, ĉar estas necese, ke mi iru al la Patro por vi.",
    "Kaj okazis, kiam Jesuo finis ĉi tiujn parolojn, ke li ektuŝis per sia mano unu post alia al la disĉiploj, kiujn li elektis, ĝis li tuŝis ilin ĉiujn kaj, tuŝante ilin, li parolis al ili.",
    "Kaj la homamaso ne aŭdis la vortojn, kiujn li parolis, sekve ili ne atestis; sed la disĉiploj atestis, ke li donis al ili potencon doni la Sanktan Spiriton. Kaj mi poste montros al vi, ke ĉi tiu atesto estas vera.",
    "Kaj okazis, post kiam Jesuo tuŝis ilin ĉiujn, ke venis nubo kaj superombris la homamason tiel ke ili ne povis vidi Jesuon.",
    "Kaj, dum ili estis superombrataj, li foriris de ili kaj supreniris en la ĉielon. Kaj la disĉiploj vidis kaj atestis, ke li denove supreniris en la ĉielon.",
  ],
  footNotes: ["34 p.K."],
} as const satisfies Chapter;
