export const chapter17 = {
  chapterTitle: "Ĉapitro 17",
  verses: [
    "Jen, tiam okazis, post kiam Jesuo diris ĉi tiujn vortojn, ke li ĉirkaŭrigardis la homamason denove, kaj li diris al ili: Jen, mia tempo estas proksima.",
    "Mi vidas, ke vi estas malfortaj, ke vi ne povas kompreni ĉiujn miajn vortojn, kiujn la Patro ordonis al mi nuntempe diri al vi.",
    "Do, iru al viaj hejmoj, kaj meditu pri tio, kion mi diris, kaj petu de la Patro, en mia nomo, ke vi komprenu, kaj preparu viajn mensojn por la morgaŭo, kiam mi revenos al vi.",
    "Sed nun mi iros al la Patro, kaj ankaŭ montros min al la perditaj triboj de Izrael, ĉar ili ne estas perditaj de la Patro, ĉar li scias, kien li forkondukis ilin.",
    "Kaj okazis, post kiam Jesuo tiel parolis, ke li denove ĵetis siajn rigardojn ĉirkaŭen sur la homamason, kaj vidis, ke ili ploris kaj konstante rigardis lin, kvazaŭ ili volus peti lin resti iomete pli longe ĉe ili.",
    "Kaj li diris al ili; Jen, mia interno pleniĝas de kompato al vi.",
    "Ĉu vi havas malsanulojn inter vi? Venigu ilin ĉi tien. Ĉu vi havas lamulojn, aŭ blindulojn, aŭ kriplulojn, aŭ invalidojn, aŭ leprulojn, aŭ velkintojn, aŭ surdulojn, aŭ homojn, kiuj iel afliktiĝis? Venigu ilin ĉi tien, kaj mi kuracos ilin, ĉar mi havas kompaton al vi; mia interno estas plena de kompatemo.",
    "Ĉar mi vidas, ke vi deziras, ke mi montru al vi, kion mi faris al viaj fratoj en Jerusalemo, ĉar mi vidas, ke sufiĉas via fido, ke mi kuracos vin.",
    "Kaj okazis, post kiam li tiel parolis, ke la tuta homamaso, unuanime, elvenis kun siaj malsanuloj kaj siaj afliktitoj, kaj siaj lamuloj, kaj kun siaj blinduloj, kaj kun siaj mutuloj, kaj kun ĉiuj, kiuj iel afliktiĝis; kaj li kuracis ĉiun el ili laŭvice, kiel ili estis venigitaj al li.",
    "Kaj ili ĉiuj, kaj kuracitoj kaj sanuloj, kliniĝis ĉe liaj piedoj vizaĝaltere, kaj adoris lin; kaj tiom, kiom povis veni spite la homamason, kisis liajn piedojn, tiagrade ke ili lavis liajn piedojn per siaj larmoj.",
    "Kaj okazis, ke li ordonis, ke oni venigu iliajn infanetojn.",
    "Ili do venigis siajn infanetojn kaj metis ilin malsupren sur la teron ĉirkaŭ li, kaj Jesuo staris en la mezo; kaj la homamaso cedis spacon ĝis ili ĉiuj estis venigitaj al li.",
    "Kaj okazis, kiam ili ĉiuj estis venigitaj, kaj Jesuo staris en la mezo, ke li ordonis al la homamaso, ke ili ekgenuu sur la tero.",
    "Kaj okazis, kiam ili genuis sur la tero, ke Jesuo ĝemis en si kaj diris: Patro, mi maltrankviliĝas pro la malvirteco de la popolo de la domo de Izrael.",
    "Kaj, dirinte ĉi tiujn vortojn, ankaŭ li mem ekgenuis sur la tero; kaj jen li preĝis al la Patro, kaj tio, kion li preĝis, ne povas esti skribata, kaj la homamaso, kiu aŭdis lin, atestis.",
    "Kaj ili atestis jene; Neniam la okulo vidis, nek la orelo aŭdis, tiel grandiozajn kaj mirindajn aferojn kiel tiujn, kiujn ni vidis kaj aŭdis Jesuon diri al la Patro;",
    "Kaj neniu lango povas paroli, nek iu homo povas skribi, nek la koroj de homoj povas koncepti tiel grandiozajn kaj mirindajn aferojn kiel tiujn, kiujn ni kaj vidis kaj aŭdis Jesuon paroli; kaj neniu povas koncepti la ĝojon, kiu plenigis niajn animojn, kiam ni aŭdis lin preĝi por ni al la Patro.",
    "Kaj okazis, kiam Jesuo ĉesis preĝi al la Patro, ke li leviĝis; sed tiel granda estis la ĝojo de la homamaso, ke ili estis senfortigitaj.",
    "Kaj okazis, ke Jesuo parolis al ili, kaj diris, ke ili levu sin.",
    "Kaj ili leviĝis de la tero, kaj li diris al ili: Benitaj estas vi pro via fido. Kaj nun jen, mia ĝojo estas plena.",
    "Kaj, dirinte ĉi tiujn vortojn, li ploris, kaj la homamaso atestis tion, kaj li prenis iliajn infanetojn, unuope, kaj benis ilin, kaj preĝis al la Patro por ili.",
    "Kaj, farinte ĉi tion, li denove ploris;",
    "Kaj li parolis al la homamaso, kaj diris al ĝi; Rigardu viajn infanetojn.",
    "Kaj, ekrigardante, ili ĵetis siajn rigardojn sur la ĉielon, kaj ili vidis la ĉielon malfermitan, kaj ili vidis anĝelojn malsupreniranta el la ĉielo kvazaŭ en la mezo de fajro; kaj ili malsuprenvenis kaj ĉirkaŭis tiujn etulojn, kaj ili estis ĉirkaŭataj de fajro; kaj la anĝeloj servis al ili.",
    "Kaj la homamaso vidis kaj aŭdis kaj atestis; kaj ili scias, ke ilia atesto estas vera, ĉar ĉiuj el ili vidis kaj aŭdis, ĉiu por si mem; kaj ili nombris ĉirkaŭ du mil kvincent animojn; kaj ili konsistis el viroj, virinoj, kaj infanoj.",
  ],
  footNotes: ["34 p.K."],
} as const satisfies Chapter;
