export const chapter1 = {
  chapterTitle: "Ĉapitro 1",
  verses: [
    "Tiam okazis, ke la naŭdek unua jaro jam forpasis, kaj sescent jarojn antaŭe Lihai foriris de Jerusalemo; kaj la jaro estis tiu, kiam Lakoneus estis la ĉefjuĝisto kaj la estro super la lando.",
    "Kaj Nifai, la filo de Helaman, jam foriris al la lando Zarahemla, doninte al sia filo Nifai instrukciojn pri la platoj el latuno kaj pri ĉiuj analoj, kiujn oni konservis, kaj pri ĉio, kion oni konsideris sankta de post la foriro de Lihai el Jerusalemo.",
    "Poste li eliris el la lando kaj neniu scias, kien li iris; kaj lia filo Nifai konservis la analojn anstataŭ li, jes, la kronikon de ĉi tiu popolo.",
    "Kaj okazis, ke je la komenco de la naŭdek dua jaro, jen, la antaŭdiroj de la profetoj komencis esti pli plene plenumataj; ĉar pli grandaj signoj kaj pli grandaj mirakloj ekfariĝis inter la popolo.",
    "Sed kelkaj komencis diri, ke la horo jam pasis por la plenumiĝo de la vortoj, kiuj estis diritaj de Samuel la lamanido.",
    "Kaj ili komencis ĝoji pri siaj fratoj, dirante: Jen la horo jam pasis, kaj la vortoj de Samuel ne estas plenumitaj; tial via ĝojo kaj via fido pri ĉi tio estis vanaj.",
    "Kaj okazis, ke ili faris grandan tumultan bruon tra la lando; kaj la popolanoj, kiuj kredis, komencis esti tre malĝojaj, timante ke tio, kio estis parolita, eble ne okazos.",
    "Sed jen, ili konstante atendis tiun tagon kaj tiun nokton kaj tiun tagon, kiuj devus esti kiel unu tago, kvazaŭ estus neniu nokto, por ke ili sciu, ke ilia fidado ne estis vana.",
    "Tiam okazis, ke unu tago estis konsekrita de la nekredantoj, por ke ĉiuj tiuj, kiuj kredis al tiuj tradicioj, estu mortigataj, se ne plenumiĝos la pruvosigno, kiun Samuel la profeto diris.",
    "Tiam okazis, kiam Nifai, la filo de Nifai, vidis ĉi tiun malvirtecon de sia popolo, ke lia koro treege malĝojiĝis.",
    "Kaj okazis, ke li eliris kaj klinis sin malsupren sur la teron, kaj fervore kriis al sia Dio por sia popolo, jes, por tiuj, kiuj estis detruotaj pro sia kredo al la tradicio de siaj prapatroj.",
    "Kaj okazis, ke li fervore kriis la tutan tagon al la Sinjoro; kaj jen, la voĉo de la Sinjoro venis al li, dirante:",
    "Levu vian kapon kaj kuraĝiĝu; ĉar jen, la horo alproksimiĝas, kaj ĉi nokte la provosigno estos donita, kaj morgaŭ mi venos en la mondon, por montri al la homaro, ke mi plenumos ĉion tion, kion mi elparoligis per la buŝo de miaj sanktaj profetoj.",
    "Jen, mi venas al miaj propraj, por plenumi ĉion, kion mi sciigis al la homidoj de post la fondiĝo de la mondo, kaj por fari la volon kaj de la Patro kaj de la Filo de la Patro pro mi, kaj de la Filo pro mia karno. Kaj jen, la horo estas proksima, kaj ĉi nokte la pruvosigno estos donita.",
    "Kaj okazis, ke plenumiĝis la vortoj, kiuj venis al Nifai, konforme al tio, kio estis dirita en ili; ĉar jen, je la subiĝo de la suno ne okazis mallumiĝo; kaj la popolo ekmiregis pro la manko de mallumo, kiam la nokto venis.",
    "Kaj multaj, kiuj antaŭe ne kredis la vortojn de la profetoj, falis al la tero kaj fariĝis kvazaŭ ili estus mortintaj, ĉar ili sciis, ke vaniĝis la granda plano de detruo, kiun ili komplotis por tiuj, kiuj kredis je la vortoj de la profetoj; ĉar jam tie estis la signalo, kiu estis donita.",
    "Kaj ili eksciis, ke la Filo de Dio baldaŭ aperos; jes, efektive, ĉiuj homoj sur la supraĵo de la tuta tero de la okcidento al la oriento, kaj en la landa nordo kaj en la landa sudo, tial treege konsterniĝis, ke ili falis al la tero.",
    "Ĉar ili sciis, ke la profetoj atestis pri ĉi tio dum multaj jaroj, kaj ke jam tie estis la signo, kiu estis donita; kaj ili ektimis pro sia malvirteco kaj sia nekredemo.",
    "Kaj okazis, ke dum tiu tuta nokto ne estis mallume, sed estis tiel lume, kvazaŭ tagmeze. Kaj okazis, ke la suno releviĝis en la mateno laŭ sia natura ordo; kaj ili sciis pro la signo, kiu estis donita, ke tiu estis la tago, en kiu la Sinjoro naskiĝos.",
    "Kaj ĉio ĉiel plenumiĝis jes, konforme al la vortoj de la profetoj.",
    "Kaj okazis ankaŭ, ke nova stelo aperis, konforme al la vorto.",
    "Kaj okazis, ke de post tiam Satano dissendis mensogaĵojn inter la homojn por malmoligi iliajn korojn, intencante, ke ili ne kredu je tiuj pruvosignoj kaj miraĵoj, kiujn ili vidis; sed malgraŭ ĉi tiuj mensogaĵoj kaj trompaĵoj la plimulto de la popolo ja kredis kaj konvertiĝis al la Sinjoro.",
    "Kaj okazis, ke Nifai eliris inter la popolon, kaj ankaŭ multaj aliaj, baptante al pento, en kiu estis granda pardonado de pekoj. Kaj tiel la popolo komencis rehavi pacon en la lando.",
    "Kaj oni ne disputis, krom kelkaj, kiuj komencis prediki, provante pruvi per la Skriboj, ke ne plu necesas observi la Leĝon de Moseo. Tamen pri tio ili eraris, ne komprenante la Skribojn.",
    "Sed okazis, ke ili baldaŭ konvertiĝis kaj konvinkiĝis pri la eraro, en kiu ili estis ĉar oni sciigis al ili, ke la Leĝo ankoraŭ ne estas plenumita, kaj ke ghi devos esti tute plenumita; jes, la Diro venis al ili, ke ĝi devos esti plenumita; jes, ke nek unu joto nek unu streketo forpasos ĝis ĉio plenumiĝos; do en tiu sama jaro ili estis kondukitaj al scio pri sia eraro kaj konfesis sian kulpon.",
    "Kaj tiel la naŭdek dua jaro forpasis, doninte bonan sciigon al la popolo pro la signoj kiuj okazis, konforme al la vortoj de la profetaĵo de ĉiuj el la sanktaj profetoj.",
    "Kaj okazis, ke ankaŭ la naŭdek tria jaro pace forpasis, escepte de la rabistoj de Gadianton, kiuj loĝis sur la montoj kaj infestis la landon; ĉar tiel fortaj estis iliaj fortikaĵoj kaj iliaj sekretaj lokoj, ke la popolo ne povis subigi ilin; ili do faris multajn murdojn kaj grandan buĉadon inter la popolo.",
    "Kaj okazis, ke en la naŭdek kvara jaro ili altgrade plinombriĝis, ĉar multaj skismuloj el la nifaidoj fuĝis al ili, kio kaŭzis multan malĝojon al tiuj nifaidoj, kiuj restis en la lando.",
    "Kaj estis alia kaŭzo de multa malĝojo inter la lamanidoj; ĉar jen, ili havis multajn infanojn, kiuj plenaĝiĝis kaj ekfortiĝis kun la jaroj, tiom ke ili emancipiĝis kaj estis forkondukitaj de kelkaj, kiuj estis Zoramidoj, per iliaj mensogaĵoj kaj iliaj flataj vortoj, por aliĝi al tiuj rabistoj de Gadianton.",
    "Kaj do ankaŭ la lamanidoj afliktiĝis, kaj ilia fido kaj ilia justeco komencis malpliiĝi pro la malvirteco de la kreskanta generacio.",
  ],
  footNotes: ["35 a.K."],
} as const satisfies Chapter;
