export const chapter8 = {
  chapterTitle: "Ĉapitro 8",
  verses: [
    "Kaj tiam okazis, ke laŭ nia kroniko, kaj ni scias, ke nia kroniko estas vera, ĉar jen, virtulo kompilis la kronikon ĉar li vere faris multajn miraklojn en la nomo de Jesuo; kaj neniu homo povis fari miraklon en la nomo de Jesuo krom tiu, kiu estis ĉiel puriĝinta de siaj pekoj -",
    "Kaj okazis, se ĉi tiu viro faris neniun eraron en la kalkulado de nia tempo, ke la tridek tria jaro estis forpasinta;",
    "Kaj la popolo komencis tre fervore atendi la signon, kiu estis donita de la profeto Samuel la lamanido, jes, la tempon, kiam estos mallumo dum la daŭro de tri tagoj super la supraĵo de la tuta lando.",
    "Kaj ekokazis multa dubado kaj disputado inter la popolo malgraŭ tio, ke tiom da signoj estis donitaj.",
    "Kaj okazis en la tridek kvara jaro, en la unua monato, en la kvara tago de la monato, ke leviĝis forta ventego tia, kia neniam antaŭe estis konata en la tuta lando. 6. Kaj okazis ankaŭ granda kaj terura tempesto; kaj okazis terura tondrado, tiom ke ĝi skuis la tutan teron kvazaŭ ĝi estus disdividota.",
    "Kaj okazis treege brila fulmado, tia kia neniam antaŭe estis konata en la tuta lando.",
    "Kaj la urbo de Zarahemla ekbrulis.",
    "Kaj la urbo de Moroni subiĝis en la profundon de la maro, kaj ĝiaj loĝantoj dronis.",
    "Kaj la tero amasiĝis sur la urbon de Moroniha, tiel ke anstataŭ la urbo troviĝis tie granda monto.",
    "Kaj okazis granda kaj terura detruo en la lando suden.",
    "Sed jen, okazis pli granda kaj terura detruo en la lando norden; ĉar jen, la supraĵo de la tuta lando ŝanĝiĝis pro la tempesto kaj la turnoventegoj kaj la tondrado kaj la fulmado, kaj la treega tremado de la tuta tero:",
    "Kaj la ĉefaj vojoj disrompiĝis, kaj la ebenaj vojoj difektiĝis, kaj multaj glataj lokoj fariĝis malglataj.",
    "Kaj multaj grandaj kaj famaj urboj submariĝis, kaj multaj brulis, kaj multaj skuiĝis ĝis iliaj konstruaĵoj falis al la tero, kaj iliaj loĝantoj mortis, kaj la lokoj estis lasitaj dezertaj.",
    "Kaj kelkaj urboj restis; sed la difektoj al ili estis grandegaj, kaj multaj en ili estis mortigitaj.",
    "Kaj kelkaj estis forblovitaj de la turnoventego; kaj kien ili iris neniu homo scias; oni scias nur; ke ili estis forblovitaj.",
    "Kaj tiel la supraĵo de la tuta tero deformiĝis pro la tempestoj kaj la tondrado kaj la fulmado kaj la tremado de la tero.",
    "Kaj jen, la rokoj disŝiriĝis en pecojn; ili disrompiĝis sur la supraĵo de la tuta tero tiagrade, ke ili troviĝis en rompitaj fragmentoj, kaj en vejnoj kaj en fendoj, sur la tuta supraĵo de la tuta lando,",
    "Kaj okazis, ke, kiam la tondrado kaj la fulmado kaj la ventego kaj la tempesto kaj la tremoj de la tero ĉesis ĉar jen, ili daŭris dum preskaŭ tri horoj; kaj kelkaj diris, ke la daŭro estis pli longa; tamen, ĉiuj ĉi grandaj kaj teruraj aferoj estis faritaj en ĉirkaŭ tri horoj kaj poste jen, estis mallumo sur la supraĵo de la tuta lando.",
    "Kaj okazis, ke estis densa mallumo sur la supraĵo de la tuta lando tiagrade, ke la tieaj loĝantoj, kiuj ne estis falintaj, povis senti la vaporon de la mallumo;",
    "Kaj pro la mallumo ne povis esti lumo, nek kandeloj nek torĉoj; kaj oni ne povis ekbruligi fajron per sia bonega kaj treege seka ligno, tiel ke tute ne povis esti ia lumo;",
    "Kaj nenia lumo estis vidata, nek fajro nek brileto, nek la suno nek la luno nek la steloj, ĉar tiel granda estis la nebuloj de mallumo, kiuj estis sur la supraĵo de la tuta lando.",
    "Kaj okazis, ke dum la daŭro de tri tagoj nenia lumo estis vidata; kaj estis granda malĝojo kaj ĝemegado kaj plorado daŭre ĉe la popolo; jes, granda estis la ĝemado de la popolo pro la mallumo kaj la granda ruiniĝo, kiuj trafis ilin.",
    "Kaj en unu loko oni aŭdis ilin vekrii, dirante: Ho, se ni estus pentintaj antaŭ ĉi tiu granda kaj terura tago, niaj fratoj estus indulgitaj, kaj ili ne estus bruligitaj en tiu granda urbo Zarahemla.",
    "Kaj en alia loko oni aŭdis ilin vekrii kaj lamenti, dirante; Ho, se ni estus pentintaj antaŭ ĉi tiu granda kaj terura tago, kaj ne estus mortigintaj kaj ŝtonumintaj la profetojn kaj forpelintaj ilin, niaj patrinoj kaj niaj belaj filinoj kaj niaj infanoj estus indulgitaj, kaj ili ne estus enterigitaj en tiu granda urbo Moroniha. Kaj tiel la ĝemegado de la popolo estis granda kaj terura.",
  ],
  footNotes: ["34 a.K."],
} as const satisfies Chapter;
