export const chapter20 = {
  chapterTitle: "Ĉapitro 20",
  verses: [
    "Kaj okazis, ke li ordonis al la homamaso, kaj ankaŭ al siaj disĉiploj, ke ili ĉesu preĝi. Kaj li ordonis al ili, ke ili ne ĉesu preĝi en siaj koroj.",
    "Kaj li ordonis al ili, ke ili leviĝu kaj ekstaru sur siaj piedoj. Kaj ili leviĝis kaj stariĝis sur siaj piedoj.",
    "Kaj okazis, ke li denove dispecigis panon kaj benis ĝin kaj donis ĝin al la disĉiploj por manĝi.",
    "Kaj, post kiam ili manĝis, li ordonis al ili, ke ili dispecigu panon kaj donu ĝin al la homamaso.",
    "Kaj, post kiam ili donis ĝin al la homamaso, li donis al ili ankaŭ vinon por trinki, kaj ordonis al ili, ke ili disdonu al la homamaso.",
    "Nu, nek pano nek vino estis jam alportita de la disĉiploj aŭ la homamaso;",
    "Sed li vere donis al ili panon por manĝi, kaj ankaŭ vinon por trinki.",
    "Kaj li diris al ili; Tiu, kiu manĝas ĉi tiun panon manĝas el mia korpo en sian animon; kaj tiu, kiu trinkas el ĉi tiu vino, trinkas el mia sango en sian animon; kaj lia animo neniam malsatos aŭ soifos, sed satos.",
    "Nu, post kiam ĉiuj en la homamaso manĝis kaj trinkis, jen, ili pleniĝis de la Spirito; kaj ili kriis per unu voĉo, kaj gloris Jesuon, kiun ili kaj vidis kaj aŭdis.",
    "Kaj okazis, post kiam ili ĉiuj gloris Jesuon, ke li diris al ili; Jen nun mi plenumas la ordonon, kiun la Patro ordonis al mi pri ĉi tiu popolo, kiu estas restaĵo de la domo de Izrael.",
    "Vi memoras, ke mi parolis al vi, kaj diris, ke, kiam la vortoj de Jesaja plenumiĝos jen ili estas skribitaj, vi havas ilin antaŭ vi, do esploru ilin -",
    "Kaj vere, vere, mi diras al vi, ke, kiam ili plenumiĝos, tiam plenumiĝos la interligo, kiun la Patro faris kun sia popolo, ho, domo de Izrael.",
    "Kaj tiam la restaĵoj, kiuj estos disigitaj sur la supraĵo de la tuta tero, estos kolektitaj de la oriento kaj de la okcidento, kaj de la sudo kaj de la nordo; kaj ili estos venigitaj al la Sinjoro, sia Dio, kiu redemptis ilin.",
    "Kaj la Patro ordonis al mi, ke mi donu el vi ĉi tiun landon, por via heredaĵo.",
    "Kaj mi diras al vi, ke, se la nejudaj nacioj ne pentos post la beno, kiun ili ricevos, post kiam ili estos dispelintaj mian popolon -",
    "Tiam vi, kiu estas restaĵo de la domo de Jakob, iros inter ilin; kaj vi estos meze de ili, kiuj estos multaj; kaj vi estos inter ili kiel leono inter la bestoj de la arbaro, kiel leonido meze de ŝafaroj, kiu dispremas paŝante, disŝiras, kaj neniu povas savi.",
    "Leviĝos via mano super viaj kontraŭuloj, kaj ĉiuj viaj malamikaj ekstermiĝos.",
    "Kaj mi kolektos mian popolon, kiel viro kolektas garbojn en sian draŝejon.",
    "Ĉar, mia popolo, kun kiu la Patro faris interligon, jes, vian kornon mi faros fera, viajn hufojn mi faros kupraj. Kaj vi dispremos multe da popoloj; kaj mi konsekros al la Sinjoro ilian akiritaĵon, kaj ilian havaĵon al la Sinjoro de la tuta tero. Kaj jen, mi estas tiu, kiu faros tion.",
    "Kaj okazos, diras la Patro, ke en tiu tago la glavo de mia justeco pendos super ili; kaj, se ili ne pentos, ĝi falos sur ilin, diras la Patro, jes, ja, sur ĉiujn nejudajn naciojn.",
    "Kaj okazos, ke mi starigos mian popolon, ho domo de Izrael.",
    "Kaj jen, ĉi tiun popolon mi starigos en ĉi tiu lando, por plenumi la interligon, kiun mi faris kun via prapatro Jakob; kaj ĝi estos Nova Jerusalemo. Kaj la potencoj de la ĉielo estos meze de ĉi tiu popolo; jes, mi mem estos meze de vi.",
    "Jen, mi estas tiu, pri kiu Moseo parolis, dirante; profeton el viaj fratoj, similan al mi, starigos por vi la Sinjoro, via Dio; lin aŭskultu pri tio kion li al vi parolos. Kaj okazos, ke ĉiu animo, kiu ne aŭskultos tiun profeton, ekstermiĝos el la popolo.",
    "Vere mi diras al vi, jes, kaj ĉiuj profetoj de post Samuel kaj liaj posteuloj, kiuj parolis, tiuj atestis pri mi.",
    "Kaj jen, vi estas la gefiloj de la profetoj; kaj vi estas de la domo de Izrael; kaj vi estas de la interligo, kiun la Patro faris kun viaj prapatroj, dirante al Abraham; Kaj beniĝos per via idaro ĉiuj gentoj de la tero.",
    "La Patro, levinte min unue por vi, kaj sendinte min por beni vin, deturnante ĉiun el vi de liaj malvirtecoj; kaj ĉi tio, ĉar vi estas la filoj de la interligo -",
    "Kaj, post kiam vi estis benitaj, tiam la Patro plenumis la interligon, kiun li faris kun Abraham; dirante: Beniĝos per via idaro ĉiuj gentoj de la tero ĝis la elverŝiĝo de la Sankta Spirito per mi sur la nejudajn nacianojn, donaco al la nacianoj, kiu faros ilin potencaj super ĉiuj, ĝis la dispelo de mia popolo, ho domo de Izrael.",
    "Kaj ili estos vipo al la popolo de ĉi tiu lando. Tamen, post kiam ili ricevos la plenecon de mia evangelio, tiam, se ili malmoligos siajn korojn kontraŭ mi, mi repagos iliajn malvirtecojn sur iliajn kapojn, diras la Patro.",
    "Kaj mi memoros la interligon, kiun mi faris kun mia popolo; kaj mi faris interligon kun ili, ke mi kolektos ilin en tempo konvena al mi, ke mi redonos al ili por ilia heredaĵo la landon de iliaj prapatroj, kiu estas la lando Jerusalema, kiu estas la lando promesita al ili por ĉiam, diras la Patro.",
    "Kaj okazos, ke la tempo venos, kiam estos predikata la plenecon de mia evangelio al ili;",
    "Kaj ili kredos je mi, ke mi estas Jesuo Kristo, la Filo de Dio, kaj preĝos al la Patro en mia nomo.",
    "Tiam eksonos la voĉo de iliaj gardostaranto kaj ili levos la voĉon kaj kune ĝojkrios; ĉar per siaj propraj okuloj ili vidos.",
    "Tiam la Patro rekolektos ilin, kaj donos al ili Jerusalemon por la lando de ilia heredaĵo.",
    "Tiam ili triumfos ĝojkriu kune, ho ruinoj de Jerusalem; ĉar la Patro konsolis sian popolon, liberigis Jerusalemon.",
    "La Patro malkovris sian sanktan brakon antaŭ la okuloj de ĉiuj nacioj; kaj ĉiuj finoj de la tero vidos la helpon de la Patro; kaj la Patro kaj mi estas unu.",
    "Kaj tiam okazos tio, kio estas skribita: Vekiĝu, vekiĝu, vestu vin per via forto, ho Cion; surmetu sur vin la vestojn de via majesto, ho Jerusalem, sankta urbo, ĉar ne plu eniros en vin necirkumcidito kaj malpurulo.",
    "Forskuu de vi la polvon, leviĝu, sidiĝu, ho Jerusalem; disigu la ligilojn de via kolo, ho kaptita filino de Cion.",
    "Ĉar tiele diras la Sinjoro; Senpage vi estis vendita, kaj ne per arĝento vi estos elaĉetita.",
    "Vere, vere, mi diras al vi, ke mia popolo ekkonos mian nomon; jes, ĝi ekscios en tiu tago, ke mi estas tiu sama, kiu parolas.",
    "Kaj tiam ili diros; Kiel ĉarmaj estas sur la montoj la piedoj de anoncanto al ili, kiu proklamas pacon, kiu anoncas al ili bonon, kiu sciigas pri helpo, diras al Cion: Reĝos via Dio;",
    "Kaj tiam eliros krio: Foriru, foriru, eliru el tie, ne tuŝu malpuraĵon; eliru el ĝia mezo: purigu vin, ho portantoj de la vazoj de la Sinjoro.",
    "Tamen ne rapidante vi eliros, kaj ne forkurante vi iros: ĉar iros antaŭ vi la Sinjoro. Kaj gardos vin malantaŭe la Dio de Izrael.",
    "Jen mia servanto havos sukceson; li altigos kaj gloriĝos kaj staros tre alte.",
    "Kiel multaj estis teruritaj, rigardante vin tiele lia aspekto estis malbeligita pli ol ĉe ĉiu alia kaj lia eksteraĵo pli ol ĉe iu ajn homo",
    "Tiel li aspergos multe da popoloj; reĝoj fermos antaŭ li sian buŝon, ĉar ili vidos ion, kio ne estis dirita al ili; kaj ili rimarkis ion, pri kio ili ne aŭdis.",
    "Vere, vere, mi diras al vi, ĉio ĉi certe venos, same kiel la Patro ordonis al mi. Tiam plenumiĝos ĉi tiu interligo, kiun la Patro faris kun sia popolo; kaj tiam mia popolo denove loĝos en Jerusalem, kaj ĝi estos la lando de ilia heredaĵo.",
  ],
  footNotes: ["34 p.K."],
} as const satisfies Chapter;
