export const chapter13 = {
  chapterTitle: "Ĉapitro 13",
  verses: [
    "Vere, vere, mi diras, ke mi volas, ke vi donu almozojn al la malriĉuloj; sed gardu vin, ke vi ne faru vian justaĵon antaŭ homoj, por esti alrigardataj de ili; alie vi ne havas rekompencon ĉe via Patro, kiu estas en la ĉielo.",
    "Tial, kiam vi donos almozon, ne sonigu trumpeton antaŭ vi, kiel faras la hipokrituloj en la sinagogoj kaj sur la stratoj, por havi gloron ĉe homoj. Vere mi diras al vi; Ili jam ricevas sian rekompencon.",
    "Sed kiam vi donas almozon, ne lasu vian maldekstran manon scii, kion faras via dekstra;",
    "Por ke via almozo estu en sekreto; kaj via Patro, kiu vidas en sekreto, vin rekompencos en malsekreto.",
    "Kaj kiam vi preĝas, ne faru kiel la hipokrituloj; ĉar ili amas preĝi, starante en la sinagogoj kaj ĉe la anguloj de la stratoj, por montri sin al homoj. Vere mi diras al vi; Ili jam ricevas sian rekompencon.",
    "Sed vi, kiam vi preĝas, eniru en vian ĉambreton kaj, ŝlosinte vian pordon, preĝu al via Patro, kiu estas en sekreto; kaj via Patro, kiu vidas en sekreto, vin rekompencos en malsekreto.",
    "Kaj dum via preĝado ne vante ripetadu, kiel la nejudaj nacianoj, ĉar ili supozas, ke ili estos aŭskultitaj pro sia multvorteco.",
    "Ne estu similaj al ili, ĉar via Patro scias, kion vi bezonas, antaŭ ol vi petas de li.",
    "Vi do preĝu jene; Patro nia, kiu estas en la ĉielo, via nomo estu sanktigita.",
    "Plenumiĝu via volo, kiel en la ĉielo, tiel ankaŭ sur la tero.",
    "Kaj pardonu al ni niajn ŝuldojn, kiel ankaŭ ni pardonas al niaj ŝuldantoj.",
    "Kaj ne konduku nin en tenton, sed liberigu nin de la malbono.",
    "Ĉar via estas la regno kaj la potenco kaj la gloro, por eterne. Amen.",
    "Ĉar se vi pardonas al homoj iliajn kulpojn, via Patro ĉiela ankaŭ pardonos al vi",
    "Sed se vi ne pardonas al homoj iliajn kulpojn, via Patro ankaŭ ne pardonos viajn kulpojn.",
    "Kaj kiam vi fastas, ne estu kiel la hipokrituloj, kun malĝoja mieno; ĉar ili malbeligas sian vizaĝon, por ke al homoj ili ŝajnu fasti. Vere mi diras al vi; Ili jam ricevas sian rekompencon.",
    "Sed fastante, vi oleu vian kapon kaj lavu vian vizaĝon;",
    "Por ke vi ne al homoj ŝajnu fasti, sed al via Patro en sekreto; kaj via Patro, kiu vidas en sekreto, vin rekompencos en malsekreto.",
    "Ne provizu al vi trezorojn sur la tero, kie tineo kaj rusto konsumas, kaj kie ŝtelistoj trafosas kaj ŝtelas;",
    "Sed provizu al vi trezorojn en la ĉielo, kie nek tineo nek rusto konsumas, kaj kie ŝtelistoj nek trafosas nek ŝtelas.",
    "Ĉar kie estas via trezoro, tie estos ankaŭ via koro.",
    "La lampo de la korpo estas la okulo; se do via okulo estas sendifekta, via tuta korpo estos luma.",
    "Sed se via okulo estas malbona, via tuta korpo estos malluma. Se do la lumo en vi estas mallumo, kiel densa estos la mallumo!",
    "Neniu povas esti sklavo por du sinjoroj; ĉar aŭ li malamos unu kaj amos la alian, aŭ li aliĝos al unu kaj malestimos la alian. Vi ne povas servi al Dio kaj al Mamono!",
    "Kaj okazis, kiam Jesuo parolis ĉi tiujn vortojn, ke li rigardis al la dek du, kiujn li elektis, kaj diris al ili: Memoru la vortojn, kiujn mi parolis. Ĉar jen, vi estas tiuj, kiujn mi elektis por pastrohelpi al ĉi tiu popolo. Tial mi diras al vi; Ne zorgu pri via vivo, kion vi manĝu, aŭ kion vi trinku; nek pri via korpo, kion vi surmetu. Ĉu la vivo ne estas pli ol nutraĵo, kaj la korpo pli ol vestaĵo?",
    "Rigardu la birdojn de la ĉielo, ke ili ne semas, nek rikoltas, nek kolektas en grenejojn, kaj via Patro ĉiela ilin nutras. Ĉu vi ne multe pli valoras ol ili?",
    "Kiu el vi per zorgado povas aldoni unu ulnon al sia staturo?",
    "Kaj kial vi zorgas pri vestaĵo; Pripensu la liliojn de la kampo, kiel ili kreskas; ili ne laboras, nek ŝpinas;",
    "Kaj tamen mi diras al vi, ke eĉ Salomono en sia tuta gloro ne estis ornamita, kiel unu el ĉi tiuj.",
    "Tial, se Dio tial vestas la kampan herbaĵon, kiu ekzistas hodiaŭ, kaj morgaŭ estos ĵetata en fornon, tiom pli certe li vestos vin, se vi ne estas malgrandfiduloj.",
    "Tial ne zorgu, dirante: Kion ni manĝu? aŭ; Kion ni trinku? aŭ; Kion ni surmetu?",
    "Ĉar via Patro ĉiela scias, ke vi bezonas ĉion tion.",
    "Sed celu unue la regnon de Dio kaj lian justecon, kaj ĉio tio estos aldonita al vi.",
    "Tial ne zorgu pri la morgaŭa tago, ĉar la morgaŭa tago zorgos pri si mem. Sufiĉa por la tago estas ĝia propra malbono.",
  ],
  footNotes: ["34 p.K."],
} as const satisfies Chapter;
