export const chapter24 = {
  chapterTitle: "Ĉapitro 24",
  verses: [
    'Kaj okazis, ke li ordonis al ili, ke ili skribu la vortojn, kiujn la Patro donis al Malachi, kiujn li diros al ili. Kaj okazis, kiam ili estis skribitaj, ke li eksplikis ilin. Kaj jen estas la vortoj, kiujn li parolis al ili, dirante: Tiel parolis la Patro al Malachi - "Jen, mi sendos mian anĝelon, kaj li preparos antaŭ mi la vojon, kaj subite venos en sian templon la Sinjoro, kiun vi serĉas, kaj la anĝelo de la interligo, kiun vi deziras, jen li iras, diras la Sinjoro de la armeoj.',
    "Sed kiu eltenos la tagon de lia veno, kaj kiu povos stari, kiam li aperos. Ĉar li estas kiel la fajro de fandisto, kaj kiel la sapo de la fulistoj.",
    "Kaj li sidiĝos por refandi kaj purigi arĝenton, kaj li purigos la idojn de Levi kaj refandos ilin kiel oron kaj arĝenton, por ke ili alportadu al la Sinjoro la donojn kun pieco.",
    "Tiam al la Sinjoro estos agrablaj la oferoj de Jehuda kaj de Jerusalem, kiel en la tempo antikva kaj kiel en la jaroj antaŭaj.",
    "Kaj mi venos al vi, por juĝi; kaj mi estos rapida atestanto kontraŭ tiuj, kiuj estas maljustaj en la pagado al dungito, maljustaj al vidvino kaj al orfo, kaj kiuj forklinas la fremdulon, kaj min ne timas, diras la Sinjoro de la armeoj.",
    "Ĉar mi, la Sinjoro, ne ŝanĝiĝas; kaj vi, ho filoj de Jakob, ne neniiĝos.",
    "De post la tagoj de viaj patroj vi deturnis vin de miaj leĝoj kaj ne observas ilin. Revenu al mi, kaj tiam mi returnos min al vi, diras la Sinjoro de la armeoj. Sed vi diras: En kio ne venas reveni?",
    "Ĉu povas homo ruzi kontraŭ Dio? Tamen vi ruzas kontraŭ mi. Vi diras: En kio ni ruzas kontraŭ vi? En la dekonaĵo kaj la oferdonoj.",
    "Sub la malbeno vi ruiniĝas, sed kontraŭ mi vi ruzas, la tuta popolo.",
    "Alportu la tutan dekonaĵon en la provizejon, por ke estu manĝaĵo en mia domo; kaj elprovu min per tio, diras la Sinjoro de la armeoj, ĉu mi ne malfermos al vi la aperturon de la ĉielo, kaj ĉu mi ne verŝos sur vin benon abundan.",
    "Tiam mi faros por vi malpermeson al la manĝeganto, ke li ne pereigu al vi la fruktojn de via tero kaj ne senfruktigu al vi la vinberbranĉojn sur la kampoj, diras la Sinjoro de la armeoj.",
    "Kaj ĉiuj nacioj nomos vin feliĉaj, ĉar vi estos lando ravanta, diras la Sinjoro de la armeoj.",
    "Arogantaj estas kontraŭ mi viaj vortoj, diras la Sinjoro. Tamen vi diras: Kion ni parolis kontraŭ vi?",
    "Vi parolas: Vane ni servas al Dio; kian profiton ni havas, se ni plenumas liajn preskribojn kaj se ni iradas senĝoje antaŭ la Sinjoro de la armeoj?",
    "Tial ni diras, ke la malbonuloj estas feliĉaj, kaj la malpiuloj estas bone aranĝitaj; ili incitas Dion, sed restas sendifektaj.",
    "Sed tiuj, kiuj timas la Sinjoron, diras al si reciproke: La Sinjoro atentas kaj aŭdas: kaj memorlibro estas skribita antaŭ li pri tiuj, kiuj timas la Sinjoron kaj respektas lian nomon.",
    "Kaj ili estos miaj, diras la Sinjoro de la armeoj, en la tago, kiam mi aranĝos mian apartan trezoron; kaj mi korfavoros ilin, kiel homo korfavoras sian filon, kiu servas al li.",
    "Kaj vi denove vidos la diferencon inter virtulo kaj malvirtulo, inter tiu, kiu servas al Dio, kaj tiu, kiu ne servas al li.",
  ],
  footNotes: ["34 p.K."],
} as const satisfies Chapter;
