export const chapter26 = {
  chapterTitle: "Ĉapitro 26",
  verses: [
    "Kaj tiam okazis, post kiam Jesuo diris ĉi tion, ke li klarigis ĝin al la popolamaso; kaj li klarigis al ili ĉion, kaj grandan kaj malgrandan.",
    "Kaj li diris; la Patro ordonis, ke mi donu al vi ĉi tiujn skribojn, kiujn vi ne havas ĉe vi; ĉar saĝecon li havas, ke ili estu donataj al estontaj generacioj.",
    "Kaj li klarigadis ĉion, ekde la komenco ĝis la tempo, kiam li venos en sia gloro - jes, ĉion, kio venos sur la tersupraĵon, ĝis la elementoj brulante solviĝos, kaj la tero kunevolviĝos kiel skribrulaĵo, kaj ĝis la ĉielo kaj la tero forpasos.",
    "Kaj ĝis la granda kaj lasta tago, kiam ĉiuj popoloj, kaj ĉiuj gentoj, kaj ĉiuj nacioj kaj lingvanoj staros antaŭ Dio, por esti juĝataj pri siaj agoj, ĉu ili estas bonaj aŭ ĉu ili estas malbonaj -",
    "Se ili estas farintoj de bono, al releviĝo por eterna vivo; kaj, se ili estas farintoj de malbono, al releviĝo por juĝo; paralele, tiu unuflanke kaj ĉi tiu aliflanke, laŭ la korfavoro, kaj la justeco, kaj la sankteco, kiuj estas en Kristo, kiu estis antaŭ ol la mondo komenciĝis.",
    "Kaj nun en ĉi tiu libro ne povas esti skribita eĉ centono de tio, kion Jesuo vere instruis al la popolo;",
    "Sed jen la platoj de Nifai enhavas la plimulton de tio, kion li instruis al la popolo.",
    "Kaj li skribis ĉi tion, kion estas malplimulto de tio, kion li instruis al la popolo; kaj mi skribis ĝin kun la intenco, ke oni raportu ĝin de la nejudaj nacianoj al ĉi tiu popolo, konforme al la vortoj, kiujn Jesuo parolis.",
    "Kaj, kiam ili estos ricevintaj ĝin, ĉar estas konsilinde, ke ili estu la unuaj ricevi ĝin, por ke oni provu ilian fidon kaj, se okazos, ke ili kredos ĉi tion, tiam la pli grandaj aferoj estos montrataj al ili.",
    "Kaj, se okazos, ke ili ne kredos ĉi tion, tiam la pli grandaj aferoj estos rifuzataj al ili, en juĝo al ili.",
    "Jen, mi estis skribonta ĉion, kio estis gravurita sur la platoj de Nifai, sed la Sinjoro tion malpermesis, dirante; Mi provos la fidon de mia popolo.",
    "Tial mi, Mormon, skribas tion, kion la Sinjoro ordonis al mi. Kaj nun mi, Mormon, finas mian paroladon, kaj ekskribas tion, kio estas ordonita al mi.",
    "Tial, mi volas, ke vi vidu, ke la Sinjoro vere instruis la popolon, dum la daŭro de tri tagoj; kaj poste li ofte montris sin al ili; kaj ofte dispecigis panon, kaj benis ĝin, kaj donis ĝin al ili.",
    "Kaj okazis, ke li instruis kaj servis al la infanoj de la popolamaso, pri kiuj estas parolita, kaj li liberigis iliajn langojn, kaj al siaj patroj ili parolis grandajn kaj mirindajn aferojn, je pli grandajn ol li malkaŝis al la popolo; kaj li liberigis iliajn langojn por ke ili povu paroli.",
    "Kaj okazis, post kiam li supreniris en la ĉielon - post kiam la duan fojon li montris sin al ili, kaj iris al la Patro, kuracinte ĉiujn el iliaj malsanuloj kaj lamuloj, kaj malferminte la okulojn de iliaj blinduloj, kaj malŝtopinte la orelojn de la surduloj, kaj farinte ĉiajn kuracojn inter ili, kaj levinte viron el la mortintaro, kaj montrinte sian potencon al ili, kaj supreniris al la Patro -",
    "Jen okazis la morgaŭon, ke la popolamaso kune ariĝis, kaj ili kaj vidis kaj aŭdis ĉi tiujn infanojn; jes, eĉ infanetoj malfermis siajn buŝojn kaj parolis mirindaĵojn; kaj tion, kion ili parolis, estis malpermesite al ĉiuj homoj skribi.",
    "Kaj okazis, ke ekde tiam la disĉiploj, kiujn Jesuo elektis, komencis bapti kaj instrui ĉiujn, kiuj venis al ili; kaj ĉiuj, kiuj estis baptitaj en la nomo de Jesuo, pleniĝis de la Sankta Spirito.",
    "Kaj multaj el ili vidis kaj aŭdis nedireblaĵojn, kiun ne estas permesate al homo skribi.",
    "Kaj ili instruis, kaj servis unu la aliajn; kaj havis ĉion komune inter si, kaj ĉiu juste agis, ĉiu kun la aliaj.",
    "Kaj okazis, ke ili faris ĉion konforme al tio, kion Jesuo ordonis al ili.",
    "Kaj tiuj, kiuj estis baptitaj en la nomo de Jesuo, estis nomitaj la eklezio de Kristo.",
  ],
  footNotes: ["34-35 p.K."],
} as const satisfies Chapter;
