export const chapter28 = {
  chapterTitle: "Ĉapitro 28",
  verses: [
    "Kaj okazis, post kiam Jesuo diris ĉi tiujn vortojn, ke li parolis al siaj disĉiploj, unuope, dirante al ili: Kain peton vi deziras de mi, post kiam mi estos foririnta al la Patro?",
    "Kaj ili ĉiuj parolis, krom tri, dirante: Ni deziras, ke, post kiam nin vivis ĝis la aĝo de homo, nia pastroservado, al kiu vi vokis nin, havu finon, por ke ni rapide venu al vi en via regno.",
    "Kaj li diris al ili: Benitaj estas vi, ĉar vi deziras ĉi tion de mi; tial, post kiam vi havos sepdek du jarojn, vi venos al mi en mia regno; kaj ĉe mi vi trovos ripozon.",
    "Kaj, parolinte al ili, li turnis sin al la tri, kaj diris al ili: Kion vi volas, ke mi faru al vi, kiam mi estos foririnta al la Patro?",
    "Kaj ili malĝojis en siaj koroj, ĉar ili ne kuraĝis paroli al li pri tio, kion ili deziris.",
    "Kaj li diris al ili: Jen, mi konas viajn pensojn, kaj vi deziris tion, kion deziris de mi Johano, mia amata, kiu estis kun mi en mia pastroservado, antaŭ ol mi estis suprenlevita de la judoj.",
    "Tial, pli benitaj estas vi, ĉar vi neniam gustumos la morton; sed vi vivos por vidi ĉiujn farojn de la Patro al la homidoj, eĉ ĝis plenumiĝos ĉio laŭ la volo de la Patro, kiam mi venos en mia gloro kun la potencoj de la ĉielo.",
    "Kaj vi neniam suferos la dolorojn de morto; sed, kiam mi venos en mia gloro, vi ŝanĝiĝos en palpebrumo el morteco al senmorteco; kaj tiam vi estos benitaj en la regno de mia Patro.",
    "Kaj plie, vi ne havos doloron dum vi vivos en la karno, nek malĝojon krom pro la pekoj de la mondo; kaj ĉion ĉi mi faros pro tio, kion vi deziris de mi, ĉar vi deziris, ke vi povu alvenigi la animojn de homoj al mi, dum la mondo daŭros.",
    "Kaj pro tiu kaŭzo vi havos kompletan ĝojon; kaj vi sidiĝos en la regno de mia Patro; jes, via ĝojo estos plena, same kiel la Patro donis al mi kompletan ĝojon; kaj vi estos samaj kiel mi estas, kaj mi estas sama kiel la Patro; kaj la Patro kaj mi estas unu;",
    "Kaj la Sankta Spirito atestas pri la Patro kaj mi; kaj la Patro donas la Sanktan Spiriton al la homidoj, por mi.",
    "Kaj okazis, ke Jesuo, dirinte ĉi tiun vortojn, per sia fingro tuŝis ĉiun el ili krom la tri, kiuj estis restontaj, kaj poste li foriris.",
    "Kaj jen, la ĉielo malfermiĝis, kaj ili estis eklevitaj en la ĉielon kaj vidis kaj aŭdis nedireblaĵojn.",
    "Kaj ne estis permesate al ili paroli; nek estis donita al ili permeso diri tion, kion ili vidis kaj aŭdis;",
    "Kaj ĉu en la korpo, ĉu ekster la korpo, ili ne sciis; ĉar ŝajnis al ili, ke ili aliformiĝis, ke ili ŝanĝiĝis de ĉi tiu korpo el karno al senmorta stato, tiel ke ili povis vidi la Diaĵojn.",
    "Sed okazis, ke ili ankoraŭ pastroservis sur la tero; tamen pro la ordono, kiu estis donita al ili en la ĉielo, ili ne instruis pri tio, kion ili aŭdis kaj vidis tie.",
    "Kaj nun mi ne scias, ĉu ili estas mortemaj, ĉu senmortaj, ekde la tago de ilia aliformiĝo;",
    "Sed ĉi tion mi ja scias, laŭ la atesto, kiu estas donita - ili disiris sur la supraĵo de la lando, kaj pastroservis al la tuta popolo, unuigante al la eklezio ĉiujn, kiuj kredis al ilia predikado, kaj baptante ilin; kaj ĉiuj, kiuj baptiĝis, ricevis la Sanktan Spiriton.",
    "Kaj ili estis ĵetitaj en malliberejojn de tiuj, kiuj ne apartenis al la eklezio. Kaj la malliberejoj ne povis teni ilin, ĉar ili disŝiriĝis en pecojn.",
    "Kaj oni ĵetis ilin malsupre en la teron; sed ili tiom frapis la teron per la vorto de Dio, ke per lia potenco ili liberiĝis el la profundo de la tero; kaj oni do ne povis fosi kavojn sufiĉajn por teni ilin.",
    "Kaj trifoje oni ĵetis ilin en fornon, kaj ili ricevis nenion malbonan.",
    "Kaj dufoje oni ĵetis ilin en kavernon de sovaĝaj bestoj; kaj jen ili ludis kun la bestoj kvazaŭ infano kun suĉanta ŝafido, kaj ili ricevis nenion malbonan.",
    "Kaj okazis, ke ili do eliris inter la tutan popolon de Nifai, kaj predikis la evangelion de Kristo al ĉiuj homoj sur la supraĵo de la lando; kaj ili konvertiĝis al la Sinjoro, kaj unuiĝis al la eklezio de Kristo, kaj tiel la homoj de tiu generacio estis benitaj, konforme al la vorto de Jesuo.",
    "Kaj nun mi, Mormon, dum kelka tempo ĉesas paroli pri ĉi tio.",
    "Jen, mi estis skribonta la nomojn de tiuj, kiuj neniam gustumos morton, sed la Sinjoro malpermesis tion; mi do ne skribas ilin, ĉar ili estas kaŝitaj for de la mondo.",
    "Sed je, mi vidis ilin, kaj ili pastroservis al mi.",
    "Kaj jen ili estos inter la Nacianoj, kaj la Nacianoj ne konos ilin.",
    "Ili estos ankaŭ inter la judoj, kaj la judoj ne konos ilin.",
    "Kaj okazos, kiam la Sinjoro en sia saĝo juĝos tion konvena, ke ili pastroservos al ĉiuj el la disigitaj triboj de Izrael, kaj al ĉiuj nacioj, gentoj, lingvanoj kaj popoloj, kaj venigos el ili al Jesuo multaj animojn, por ke ilia deziro estu plenumita, kaj ankaŭ pro la konvinka povo de Dio, kie estas en ili.",
    "Kaj ili estas kiel la anĝeloj de Dio, kaj, se ili preĝos al la Patro en la nomo de Jesuo, ili povos montri sin al iu ajn homo, se ili opinios tion bona.",
    "Tial, grandiozaj kaj mirindaj faroj estos efektivigitaj de ili, antaŭ la granda kaj venonta tago, kiam ĉiuj homoj tutcerte devos stari antaŭ la tribunala seĝo de Kristo;",
    "Jes, eĉ inter la Nacianoj okazos grandioza kaj mirinda faro efektivigita de ili, antaŭ tiu tago de juĝado.",
    "Kaj, se vi havus ĉiujn Skribojn, kiuj donas raporton pri ĉiuj mirindaj faroj de Kristo, vi scius, laŭ la vortoj de Kristo, ke ĉi tio tutcerte venos.",
    "Kaj ve al tiuj, kiuj ne aŭskultos la vortojn de Jesuo aŭ de tiuj, kiujn li elektis kaj sendis al ili; ĉar tiuj, kiuj ne akceptas la vortojn de Jesuo kaj la vortojn de tiuj, kiujn li sendis, ne akceptas lin; kaj pro tio li ne akceptas ilin en la lasta tago.",
    "Kaj estus pli bone por ili se ili ne estus naskitaj. Ĉar ĉu vi supozas, ke vi povas forigi la justecon de ofendita Dio, kiu estis premita sub la piedoj de homoj, por ke per tio savo venu?",
    "Kaj nun jen, kiam parolis pri tiuj, kiujn la Sinjoro elektis, jes tri, kiuj estis suprenlevitaj en la ĉielon, ke mi ne scias, ĉu ili puriĝis de morteco al senmorteco -",
    "Sed jen, post kiam mi skribis, mi demandis al la Sinjoro, kaj li elmontris al mi, ke nepre okazis ŝanĝo al iliaj korpoj, aŭ, se ne, ili nepre devos gustumi morton;",
    "Tial, por ke ili ne gustumu morton, okazis ŝanĝo al ilia korpoj, por ke ili ne suferu doloron aŭ malĝojon krom pro la pekoj de la mondo.",
    "Nu, ĉi tiu ŝanĝo ne egalis al tiu, kiu okazos en la lasta tago; sed okazis ŝanĝo al ili, tiagrade ke Satano povis havi nenian povon super ili, ke li ne povis tenti ilin; kaj ili sanktiĝis en la karno, tiagrade ke ili estis sanktaj, kaj ke la potencoj de la tero ne povis regi ilin.",
    "Kaj en ĉi tiu stato ili devis resti ĝis la tago de juĝado de Kristo; kaj en tiu tago ili estis ricevonta pli grandan ŝanĝon kaj estis akceptotaj en la regnon de la Patro por neniam plu eliri, sed por eterne loĝi ĉe Dio en la ĉielo.",
  ],
  footNotes: ["34-35 p.K."],
} as const satisfies Chapter;
