export const chapter15 = {
  chapterTitle: "Ĉapitro 15",
  verses: [
    "Kaj tiam okazis, kiam Jesuo finis ĉi tiujn parolojn, ke li ĵetis siajn rigardojn ĉirkaŭen sur la homamason, kaj diris al ili: Jen, vi aŭdis tion, kion mi instruis antaŭ ol mi supreniris al mia Patro; tial ĉiun, kiu memoras ĉi tiujn miajn parolojn, mi levos en la lasta tago.",
    "Kaj okazis, kiam Jesuo diris ĉi tiujn vortojn, ke li vidis, ke kelkaj inter ili miregis, kaj scivolis, kion li volas fari pri la leĝo de Moseo; ĉar ili ne komprenis la parolon, ke malnovaĵoj neniiĝis, kaj ke ĉio fariĝis nova.",
    "Kaj li diris al ili: Ne miru, ke mi diris al vi, ke malnovaĵoj neniiĝis, kaj ke ĉio fariĝis nova.",
    "Jen, mi diras al vi, ke plenumiĝis la leĝo, kiu estis donita al Moseo.",
    "Jen, mi estas tiu, kiu donis la leĝon, kaj mi estas tiu, kiu faris interligon kun mia popolo Izrael; tial, la leĝo en mi plenumiĝis, ĉar mi venis por plenumi la leĝon; tial ĝi havas finon.",
    "Jen, mi ne detruas la profetaĵojn, ĉar el tiuj, kiuj ne plenumiĝis en mi, vere mi diras al vi, ĉiuj plenumiĝis.",
    "Kaj kvankam mi diris al vi, ke malnovaĵoj neniiĝis, mi ne detruas tion, kio estas parolita pri venontaĵoj.",
    "Ĉar jen, la interligo, kiun mi faris kun mia popolo, ne tute plenumiĝis; sed la leĝo, kiu estis donita al Moseo, havas finon en mi.",
    "Jen, mi estas la leĝo kaj la Lumo. Rigardu al mi, kaj persistu ĝis la fino, kaj vi vivos; ĉar al tiu, kiu persistas ĝis la fino, mi donos eternan vivon.",
    "Jen, mi jam donis al vi la ordonojn; do, observu miajn ordonojn. Kaj tio estas la leĝo kaj la profetoj, ĉar ili vere atestis pri mi.",
    "Kaj okazis, kiam Jesuo parolis ĉi tiujn vortojn, ke li diris al tiuj dek du, kiujn li elektis:",
    "Vi estas miaj disĉiploj; kaj vi estas lumo al ĉi tiu popolo, kiu estas restaĵo de la domo de Jozef.",
    "Kaj jen, ĉi tiu estas la lando de via heredaĵo; kaj la Patro donis ĝin al vi.",
    "Kaj neniam la Patro donis al mi ordonon, ke mi diru tion al viaj fratoj en Jerusalemo.",
    "Kaj neniam la Patro donis al mi ordonon, ke mi parolu al ili pri la aliaj triboj de la domo de Izrael, kiujn la Patro kondukis el la lando.",
    "Nur tion la Patro ordonis al mi, ke mi diru al ili;",
    "Ke aliajn ŝafojn mi havas, kiuj ne estas de ĉi tiu gregejo; ilin ankaŭ mi devas alkonduki, kaj ili aŭskultos mian voĉon; kaj estos unu grego, kaj unu paŝtisto.",
    "Nu, pro malmolnukeco kaj nekredemo ili ne komprenis mian vorton; tial mi estis ordonita de la Patro ne paroli plu pri ĉi tio al ili.",
    "Sed, vere, mi diras al vi, ke la Patro ordonis al mi, kaj mi diras al vi, ke vi estis apartigitaj de inter ili pro ilia malvirteco; tial pro sia malvirteco ili ne scias pri vi.",
    "Kaj vere, mi diras al vi plue, ke la Patro apartigis la aliajn tribojn de ili; kaj pro sia malvirteco ili ne scias pri ili.",
    "Kaj vere mi diras al vi, ke vi estas tiuj, pri kiuj mi diris: Aliajn ŝafojn mi havas, kiuj ne estas de ĉi tiu gregejo; ilin ankaŭ mi devas alkonduki, kaj ili aŭskultos mian voĉon; kaj estos unu grego, kaj unu paŝtisto.",
    "Kaj ili ne komprenis min, ĉar ili supozis, ke temas pri la nejudaj nacianoj; ĉar ili ne komprenis, ke la nejudaj nacianoj devus esti konvertitaj per ilia predikado.",
    "Kaj ili ne komprenis min, kiam mi diris, ke ili aŭdos mian voĉon; kaj ili ne komprenis, ke la nejudaj nacianoj neniam aŭdos mian voĉon - ke mi ne montros min al ili krom per la Sankta Spirito.",
    "Sed jen vi kaj aŭdis mian voĉon kaj vidis min: kaj vi estas miaj ŝafoj, kaj vi estas kalkulitaj inter tiuj, kiujn la Patro donis al mi.",
  ],
  footNotes: ["34 p.K."],
} as const satisfies Chapter;
