export const chapter14 = {
  chapterTitle: "Ĉapitro 14",
  verses: [
    "Kaj tiam okazis, kiam Jesuo parolis ĉi tiujn vortojn, ke li turnis sin denove al la homamaso, kaj denove malfermis sian buŝon al ili, dirante; Vere, vere, mi diras al vi, ne juĝu, por ke vi ne estu juĝataj.",
    "Ĉar per kia juĝo vi juĝos, per tia vi estos juĝitaj; kaj per kia mezuro vi mezuros, per tia oni mezuros al vi.",
    "Kaj kial vi rigardas la lignereton en la okulo de via frato, kaj ne pripensas la trabon en via okulo?",
    "Aŭ kiel vi diros al via frato: Lasu min eltiri la lignereton el via okulo; kaj jen la trabo en via propra okulo?",
    "Hipokritulo, eligu unue la trabon el via okulo, kaj tiam vi klare vidos, por eltiri la lignereton el la okulo de via frato.",
    "Ne donu sanktaĵon al la hundoj, nek ĵetu viajn perlojn antaŭ la porkoj; por ke ili ne premu ilin sub la piedoj, nek poste, sin turninte, disŝiru vin.",
    "Petu, kaj estos donite al vi; serĉu, kaj vi trovos; frapu, kaj estos malfermite al vi.",
    "Ĉar ĉiu petanto ricevas, kaj la serĉanto trovas, kaj al la frapanto estos malfermite.",
    "Plue, kiu homo el vi, kies filo de li petos panon, donos al li ŝtonon?",
    "Aŭ se li petos fiŝon, donos al li serpenton?",
    "Se do vi, estante malbonaj, scias doni bonajn donacojn al viaj infanoj, kiom pli certe via Patro, kiu estas en la ĉielo, donos bonaĵojn al tiuj, kiuj petas de li?",
    "Kion ajn do, kion vi deziras, ke la homoj faru al vi, vi ankaŭ faru al ili, ĉar ĉi tio estas la leĝo kaj la profetoj.",
    "Eniru tra la mallarĝa pordo, ĉar larĝa estas la pordego kaj vasta estas la vojo kondukanta al la pereo, kaj multaj tra ĝi eniras;",
    "Ĉar mallarĝa estas la pordo kaj malvastigita estas la vojo kondukanta al la vivo, kaj malmultaj ĝin trovas.",
    "Ĝardu vin kontraŭ la falsaj profetoj, kiuj venas al vi en ŝafaj feloj, sed interne estas rabemaj lupoj.",
    "Per iliaj fruktoj vi konos ilin. Ĉu el dornarbetoj oni kolektas vinberojn, aŭ el kardoj figojn?",
    "Tiel ĉiu bona arbo donas bonajn fruktojn, sed putra arbo donas malbonajn fruktojn.",
    "Bona arbo ne povas doni malbonajn fruktojn, nek putra arbo doni bonajn fruktojn.",
    "Ĉiu arbo, kiu ne donas bonan frukton, estas dehakata kaj ĵetata en fajron.",
    "Tial per iliaj fruktoj vi konos ilin.",
    "Ne ĉiu, kiu diras al mi; Sinjoro, Sinjoro, eniros en la regnon de la ĉielo; sed tiu, kiu plenumas la volon de mia Patro, kiu estas en la ĉielo.",
    "Multaj diros al mi en tiu tago; Sinjoro, Sinjoro, ĉu ni ne profetis en via nomo, kaj en via nomo elpelis demonojn, kaj en via nomo faris multajn potencaĵojn? 23. Kaj tiam mi deklaros al ili; Mi neniam konis vin; foriĝu de mi, vi farantoj de maljusteco.",
    "Tial ĉiu, kiu aŭdas ĉi tiujn miajn parolojn kaj plenumas ilin, estos komparata de mi al saĝa viro, kiu konstruis sian domon sur roko",
    "Kaj falis pluvo, kaj venis inundoj, kaj blovis ventoj, kaj albatis tiun domon, kaj ĝi ne falis, ĉar ĝi estis fondita sur roko.",
    "Kaj ĉiu, kiu aŭdas ĉi tiujn miajn parolojn kaj ne plenumas ilin, estos komparata al viro malsaĝa, kiu konstruis sian domon sur la sablo",
    "Kaj falis pluvo, kaj venis inundoj, kaj blovis ventoj, kaj sin ĵetis sur tiun domon; kaj ĝi falis, kaj granda estis ĝia falo.",
  ],
  footNotes: ["34 p.K."],
} as const satisfies Chapter;
