export const chapter11 = {
  chapterTitle: "Ĉapitro 11",
  summary: "",
  verses: [
    "Kiam ReĤabeam venis en Jerusalemon, li kolektis el la domo de Jehuda kaj de Benjamen cent okdek mil elektitajn militistojn, por militi kontraŭ Izrael, por revenigi la regnon al ReĤabeam.",
    "Sed aperis vorto de la Eternulo al Ŝemaja, homo de Dio, dirante:",
    "Diru al ReĤabeam, filo de Salomono, reĝo de Judujo, kaj al ĉiuj Izraelidoj en la lando de Jehuda kaj de Benjamen jene:",
    "Tiele diras la Eternulo:Ne iru kaj ne militu kontraŭ viaj fratoj; reiru ĉiu al sia domo, ĉar de Mi estas farita ĉi tiu afero. Kaj ili obeis la vortojn de la Eternulo, kaj rifuzis iri kontraŭ Jerobeamon.",
    "ReĤabeam loĝis en Jerusalem, kaj li konstruis fortikaĵojn en la urboj de Judujo.",
    "Li prikonstruis Bet-LeĤemon, Etamon, Tekoan,",
    "Bet-Curon, SoĤon, Adulamon,",
    "Gaton, Mareŝan, Zifon,",
    "Adoraimon, LaĤiŝon, Azekan,",
    "Corean, Ajalonon, kaj ĥebronon, kiuj estis urboj fortikigitaj en la lando de Jehuda kaj de Benjamen.",
    "Li fortigis tiujn fortikaĵojn kaj starigis tie estrojn, aranĝis provizejojn de manĝaĵoj, oleo, kaj vino.",
    "Kaj en ĉiu urbo li kolektis ŝildojn kaj lancojn, kaj tre fortigis ilin. Kaj Jehuda kaj Benjamen restis liaj.",
    "La pastroj kaj Levidoj, kiuj estis en la tuta lando de Izrael, kolektiĝis al li el ĉiuj siaj regionoj;",
    "la Levidoj forlasis siajn antaŭurbojn kaj sian posedaĵon kaj iris en Judujon kaj Jerusalemon, ĉar Jerobeam kaj liaj filoj forpuŝis ilin de la pastrado al la Eternulo.",
    "Li starigis ĉe si pastrojn por la altaĵoj, por la kaproj kaj bovidoj, kiujn li faris.",
    "Post ili el ĉiuj triboj de Izrael tiuj homoj, kiuj havis la inklinon turnadi sin al la Eternulo, Dio de Izrael, venadis en Jerusalemon, por fari oferojn al la Eternulo, Dio de iliaj patroj.",
    "Kaj ili fortigadis la regnon de Judujo, kaj subtenadis ReĤabeamon, filon de Salomono, dum tri jaroj; ĉar ili iradis laŭ la vojo de David kaj Salomono dum tri jaroj.",
    "ReĤabeam prenis al si kiel edzinon MaĤalaton, filinon de Jerimot, filo de David, kaj de AbiĤail, filino de Eliab, filo de Jiŝaj.",
    "Ŝi naskis al li filojn:Jeuŝ, Ŝemarja, kaj Zaham.",
    "Post ŝi li prenis MaaĤan, filinon de Abŝalom; kaj ŝi naskis al li Abijan, Atajon, Zizan, kaj Ŝelomiton.",
    "ReĤabeam amis MaaĤan, filinon de Abŝalom, pli ol ĉiujn siajn edzinojn kaj kromvirinojn; ĉar li havis dek ok edzinojn kaj sesdek kromvirinojn, kaj li naskigis dudek ok filojn kaj sesdek filinojn.",
    "ReĤabeam starigis Abijan, filon de MaaĤa, kiel ĉefon, kiel princon inter liaj fratoj, intencante fari lin reĝo.",
    "Li agadis prudente; li dissendis ĉiujn siajn filojn en ĉiujn regionojn de Jehuda kaj de Benjamen, en ĉiujn fortikigitajn urbojn; li donis al ili grandajn vivrimedojn kaj prenis por ili multe da edzinoj.",
  ],
} as const satisfies Chapter;
