export const chapter11 = {
  chapterTitle: "Ĉaptiro 11",
  summary: "",
  verses: [
    "Sur la tuta tero estis unu lingvo kaj unu parolmaniero.",
    "Kaj kiam ili ekiris de la oriento, ili trovis valon en la lando Ŝinar kaj tie ekloĝis.",
    "Kaj ili diris unu al alia: Venu, ni faru brikojn kaj ni brulpretigu ilin per fajro. Kaj la brikoj fariĝis por ili ŝtonoj, kaj la bitumo fariĝis por ili kalko.",
    "Kaj ili diris: Venu, ni konstruu al ni urbon, kaj turon, kies supro atingos la ĉielon, kaj ni akiru al ni gloron, antaŭ ol ni disiĝos sur la supraĵo de la tuta tero.",
    "Kaj la Eternulo malleviĝis, por vidi la urbon kaj la turon, kiujn konstruis la homidoj.",
    "Kaj la Eternulo diris: Jen estas unu popolo, kaj unu lingvon ili ĉiuj havas; kaj jen, kion ili komencis fari, kaj ili ne estos malhelpataj en ĉio, kion ili decidis fari.",
    "Ni malleviĝu do, kaj Ni konfuzu tie ilian lingvon, por ke unu ne komprenu la parolon de alia.",
    "Kaj la Eternulo disigis ilin de tie sur la supraĵon de la tuta tero, kaj ili ĉesis konstrui la urbon.",
    "Tial oni donis al ĝi la nomon Babel, ĉar tie la Eternulo konfuzis la lingvon de la tuta tero kaj de tie la Eternulo disigis ilin sur la supraĵon de la tuta tero.",
    "Jen estas la generaciaro de Ŝem: Ŝem havis la aĝon de cent jaroj, kaj naskiĝis al li ArpaĤŝad, du jarojn post la diluvo.",
    "Kaj Ŝem vivis post la naskiĝo de ArpaĤŝad kvincent jarojn, kaj naskiĝis al li filoj kaj filinoj.",
    "Kaj ArpaĤŝad vivis tridek kvin jarojn, kaj naskiĝis al li ŜelaĤ.",
    "Kaj ArpaĤŝad vivis post la naskiĝo de ŜelaĤ kvarcent tri jarojn, kaj naskiĝis al li filoj kaj filinoj.",
    "Kaj ŜelaĤ vivis tridek jarojn, kaj naskiĝis al li Eber.",
    "Kaj ŜelaĤ vivis post la naskiĝo de Eber kvarcent tri jarojn, kaj naskiĝis al li filoj kaj filinoj.",
    "Kaj Eber vivis tridek kvar jarojn, kaj naskiĝis al li Peleg.",
    "Kaj Eber vivis post la naskiĝo de Peleg kvarcent tridek jarojn, kaj naskiĝis al li filoj kaj filinoj.",
    "Kaj Peleg vivis tridek jarojn, kaj naskiĝis al li Reu.",
    "Kaj Peleg vivis post la naskiĝo de Reu ducent naŭ jarojn, kaj naskiĝis al li filoj kaj filinoj.",
    "Kaj Reu vivis tridek du jarojn, kaj naskiĝis al li Serug.",
    "Kaj Reu vivis post la naskiĝo de Serug ducent sep jarojn, kaj naskiĝis al li filoj kaj filinoj.",
    "Kaj Serug vivis tridek jarojn, kaj naskiĝis al li NaĤor.",
    "Kaj Serug vivis post la naskiĝo de NaĤor ducent jarojn, kaj naskiĝis al li filoj kaj filinoj.",
    "Kaj NaĤor vivis dudek naŭ jarojn, kaj naskiĝis al li TeraĤ.",
    "Kaj NaĤor vivis post la naskiĝo de TeraĤ cent dek naŭ jarojn, kaj naskiĝis al li filoj kaj filinoj.",
    "Kaj TeraĤ vivis sepdek jarojn, kaj naskiĝis al li Abram, NaĤor, kaj Haran.",
    "Kaj jen estas la generaciaro de TeraĤ: al TeraĤ naskiĝis Abram, NaĤor, kaj Haran; kaj al Haran naskiĝis Lot.",
    "Kaj Haran mortis antaŭ sia patro TeraĤ en sia lando de naskiĝo, en Ur la ĥaldea.",
    "Kaj Abram kaj NaĤor prenis al si edzinojn; la nomo de la edzino de Abram estis Saraj, kaj la nomo de la edzino de NaĤor estis Milka, filino de Haran, kiu estis la patro de Milka kaj la patro de Jiska.",
    "Kaj Saraj estis senfrukta kaj ne havis infanon.",
    "Kaj TeraĤ prenis sian filon Abram kaj sian nepon Lot, filo de Haran, kaj sian bofilinon Saraj, edzino de lia filo Abram; kaj ili eliris kune el Ur la ĥaldea, por iri en la landon Kanaanan; kaj ili venis ĝis ĥaran kaj enloĝiĝis tie.",
    "Kaj TeraĤ atingis la aĝon de ducent kvin jaroj, kaj TeraĤ mortis en ĥaran.",
  ],
} as const satisfies Chapter;
