export const chapter4 = {
  chapterTitle: "Ĉaptiro 4",
  summary: "",
  verses: [
    "La filoj de Jehuda estis:Perec, ĥecron, Karmi, ĥur, kaj Ŝobal.",
    "Reaja, filo de Ŝobal, naskigis JaĤaton; JaĤat naskigis AĤumajon kaj Lahadon; tio estas la familioj de la Coreaidoj.",
    "Kaj jen estas la domanaro de Etam:Jizreel, Jiŝma, Jidbaŝ; la nomo de ilia fratino estis Haclelponi;",
    "kaj Penuel, la fondinto de Gedor, kaj Ezer, la fondinto de ĥuŝa. Tio estas la idoj de ĥur, unuenaskito de Efrata, posedanto de Bet-LeĤem.",
    "AŝĤur, fondinto de Tekoa, havis du edzinojn:ĥela kaj Naara.",
    "Naara naskis al li AĤuzamon, ĥeferon, Temnin, kaj AĤaŝtarin; tio estas la filoj de Naara;",
    "la filoj de ĥela estis:Ceret, CoĤar, kaj Etnan.",
    "Koc naskigis Anubon, Cobeban, kaj la familiojn de AĤarĤel, filo de Harum.",
    "Jabec estis la plej estimata inter siaj fratoj. Lia patrino donis al li la nomon Jabec, ĉar ŝi diris:En malĝojo mi naskis.",
    "Kaj Jabec vokis al Dio de Izrael, dirante:Ho, se Vi min benus kaj vastigus miajn limojn, kaj Via mano estus kun mi kaj forigus la malbonon, por ke mi ne havu aflikton! Kaj Dio plenumis tion, pri kio li petis.",
    "Kelub, frato de ŜuĤa, naskigis MeĤiron; ĉi tiu estis la patro de Eŝton.",
    "Eŝton naskigis Bet-Rafan, PaseaĤon, kaj TeĤinan, fondinton de la urbo NaĤaŝ; tio estas la loĝantoj de ReĤa.",
    "La filoj de Kenaz estis:Otniel kaj Seraja; la filo de Otniel estis ĥatat.",
    "Meonotaj naskigis Ofran, kaj Seraja naskigis Joabon, fondinton de la Valo de Ĉarpentistoj; ĉar ili estis ĉarpentistoj.",
    "La filoj de Kaleb, filo de Jefune:Iru, Ela, kaj Naam; la filo de Ela estis Kenaz.",
    "La filoj de Jehalelel:Zif, Zifa, Tirja, kaj Asarel.",
    "La filoj de Ezra:Jeter, Mered, Efer, kaj Jalon. Ŝi naskis Mirjamon, Ŝamajon, kaj JiŝbaĤon, la patron de Eŝtemoa;",
    "dum lia edzino la Judino naskis Jeredon, fondinton de Gedor, ĥeberon, fondinton de SoĤo, kaj Jekutielon, fondinton de ZanoaĤ. Tiuj estis la filoj de Bitja, filino de Faraono, kiun prenis Mered.",
    "La filoj de la edzino de Hodija, fratino de NaĤam:la patro de Keila, la Garmano, kaj Eŝtemoa, la MaaĤatano.",
    "La filoj de Ŝimon:Amnon, Rina, Ben-ĥanan, kaj Tilon; la filoj de Jiŝei:ZoĤet kaj Ben-ZoĤet.",
    "La filoj de Ŝela, filo de Jehuda:Er, patro de LeĤa, kaj Lada, patro de Mareŝa, kaj la familioj de la tolfaristoj el la domo de Aŝbea;",
    "kaj Jokim, kaj la loĝantoj de Kozeba, kaj Joaŝ, kaj Saraf, kiuj estis sinjoroj en Moab kaj poste revenis en Bet-LeĤemon, laŭ antikvaj rakontoj.",
    "Ili estis potistoj, kaj loĝis inter ĝardenoj kaj brutejoj; ĉe la reĝo ili tie loĝis por liaj laboroj.",
    "La filoj de Simeon:Nemuel, Jamin, Jarib, ZeraĤ, kaj Ŝaul.",
    "La filo de ĉi tiu estis Ŝalum; la filo de ĉi tiu estis Mibsam; la filo de ĉi tiu estis Miŝma.",
    "La filoj de Miŝma:lia filo ĥamuel, lia filo Zakur, lia filo Ŝimei.",
    "Ŝimei havis dek ses filojn kaj ses filinojn; sed liaj fratoj ne havis multe da filoj, kaj ilia tuta parencaro ne tiel multiĝis, kiel la idaro de Jehuda.",
    "Ili loĝis en Beer-Ŝeba, Molada, kaj ĥacar-Ŝual,",
    "en Bilha, Ecem, kaj Tolad,",
    "en Betuel, ĥorma, kaj Ciklag,",
    "en Bet-Markabot, ĥacar-Susim, Bet-Biri, kaj Ŝaaraim. Tio estis iliaj urboj ĝis la reĝado de David.",
    "Iliaj vilaĝoj estis:Etam, Ain, Rimon, ToĤen, kaj Aŝan, kvin urboj;",
    "kaj ĉiuj iliaj vilaĝoj, kiuj estis ĉirkaŭ tiuj urboj, ĝis Baal. Tie estis ilia loĝloko, kaj ili havis apartan genealogian registron.",
    "Kaj Meŝobab, JamleĤ, Joŝa, filo de Amacja,",
    "Joel, Jehu, filo de Joŝibja, filo de Seraja, filo de Asiel,",
    "Eljoenaj, Jaakoba, JeŝoĤaja, Asaja, Adiel, Jesimiel, Benaja,",
    "Ziza, filo de Ŝifi, filo de Alon, filo de Jedaja, filo de Ŝimri, filo de Ŝemaja.",
    "Ĉi tiuj, cititaj laŭ iliaj nomoj, estis princoj en siaj familioj, kaj iliaj patrodomoj forte vastiĝis.",
    "Ili iris ĝis Gedor, ĝis la orienta flanko de la valo, por serĉi paŝtejon por siaj ŝafoj;",
    "kaj ili trovis paŝtejon grasan kaj bonan, kaj teron vastan, trankvilan, kaj kvietan, ĉar el la ĥamidoj estis tiuj, kiuj tie loĝis antaŭe.",
    "Kaj venis tiuj, kiuj ĵus estas cititaj, en la tempo de ĥizkija, reĝo de Judujo, kaj disbatis iliajn tendojn, kaj ankaŭ la Meunojn, kiuj tie troviĝis, kaj ekstermis ilin por ĉiam kaj ekloĝis sur ilia loko, ĉar tie estis paŝtejo por iliaj ŝafoj.",
    "Kaj el ili, el la idoj de Simeon, kvincent homoj iris al la monto Seir; iliaj estroj estis Pelatja, Nearja, Refaja, kaj Uziel, filoj de Jiŝei.",
    "Kaj ili venkobatis la restintajn saviĝintojn de Amalek kaj ekloĝis tie por ĉiam.",
  ],
} as const satisfies Chapter;
