export const chapter16 = {
  chapterTitle: "Ĉapitro 16",
  verses: [
    "Kaj tiam okazis, ke, post kiam mi, Nifai, ĉesis paroli al miaj fratoj, ili diris al mi: Vi deklaris al ni severaĵojn, pli ol kiom ni povas elporti.",
    "Kaj okazis, ke mi diris al ili, ke mi scias, ke mi diris severaĵojn kontraŭ la malbonuloj, konforme al la vero; kaj la virtulojn mi pravigis kaj atestis, ke ili estos altigitaj en la lasta tago; pro tio la kulpuloj opinias, ke la vero estas severa, ĉar ĝi tranĉas ilin al la centro mem.",
    "Kaj nun, miaj fratoj, se vi estus virtaj kaj volus aŭskulti la veron kaj atentus ĝin, por iri ĝustan vojon antaŭ Dio, tiukaze vi ne murmurus pro la vero kaj vi ne dirus: Vi parolas severajn vortojn kontraŭ ni.",
    "Kaj okazis, ke mi, Nifai, admonis miajn fratojn, ke ili diligentege obeu la ordonojn de la Sinjoro.",
    "Kaj okazis, ke ili humiliĝis antaŭ la Sinjoro; tiom ke mi ricevis ĝojon kaj grandajn esperojn pri ili, ke ili iros laŭ la vojo de virteco.",
    "Ĉio ĉi estis dirita kaj farita, dum mia patro loĝis en tendo en la valo, kiun li nomis Lemuel.",
    "Kaj okazis, ke mi, Nifai, prenis unu el la filinoj de Iŝmael kiel edzinon; kaj ankaŭ miaj fratoj prenis el la filinoj de Iŝmael kiel edzinojn; kaj ankaŭ Zoram prenis la plej maljunan filinon de Iŝmael kiel edzinon.",
    "Kaj tiamaniere mia patro plenumis ĉiujn ordonojn de la Sinjoro donitajn al li. Kaj ankaŭ, mi Nifai, estis treege benita de la Sinjoro.",
    "Kaj okazis, ke la voĉo de la Sinjoro parolis al mia patro dumnokte kaj ordonis al li, ke morgaŭ li ekvojaĝu en la dezerton.",
    "Kaj okazis, ke, kiam mia patro leviĝis en la mateno kaj eliris al la tenda pordo, li ekmiregigita vidis sur la tero rondan globon stange faritan; kaj ĝi estis el la plej bona latuno. Kaj en la globo estis du nadloj; kaj unu montris la direkton, kien ni iru en la dezerton.",
    "Kaj okazis, ke ni kolektis ĉiujn aĵojn, kiujn ni portu en la dezerton, kaj la tutan restaĵon de la provizoj, kiujn la Sinjoro donis al ni; kaj ni prenis ĉiajn semojn, kiujn ni povus porti en la dezerton.",
    "Kaj okazis, ke ni prenis niajn tendojn kaj foriris en la dezerton, trans la riveron Laman.",
    "Kaj okazis, ke ni iris dum kvar tagoj laŭ preskaŭ sud sudorienta direkto, kaj ni ree starigis niajn tendojn; kaj ni donis al la loko la nomon Ŝazer.",
    "Kaj okazis, ke ni prenis niajn pafarkojn kaj niajn sagojn kaj eliris en la dezerton por mortigi ĉasaĵon por niaj familioj; kaj mortiginte ĉasaĵon por niaj familioj, ni revenis al niaj familioj en la dezerto, al la loko Ŝazer. Kaj ni denove eliris en la dezerto, sekvante la saman direkton, restante en la plej fekundaj partoj de la dezerto, kiuj estis en la limoj apud la Ruĝa Maro.",
    "Kaj okazis, ke ni iris dum multaj tagoj, survoje mortigante ĉasaĵon per niaj arkoj kaj niaj sagoj kaj niaj ŝtonoj kaj niaj ĵetiloj.",
    "Kaj ni sekvis la direktadon de nia globo, kiu gvidis nin en la pli fekundaj partoj de la dezerto.",
    "Kaj vojaĝinte dum multaj tagoj, ni starigis niajn tendojn por iom da tempo, por ke ni ree ripozu kaj akiru nutraĵon por niaj familioj.",
    "Kaj okazis, ke, elirante por mortigi ĉasaĵon, mi, Nifai, rompis mian pafarkon, kiu estis farita el la plej bona ŝtalo; kaj, post kiam mi rompis mian arkon, miaj fratoj estis ja koleraj kontraŭ mi pro la perdo de mia arko, ĉar ni akiris neniom da ĉasaĵo.",
    "Kaj okazis, ke ni revenis sen ĉasaĵo al niaj familioj, kaj, estante tre lacaj pro sia vojaĝado, ili multe suferis pro la manko de nutraĵo.",
    "Kaj okazis, ke Laman kaj Lemuel kaj la filoj de Iŝmael ekmurmuregis pro sia suferado kaj afliktiĝo en la dezerto; kaj ankaŭ mia patro ekmurmuris kontraŭ la Sinjoro, sia Dio; jes, kaj ili ĉiuj tre malĝojis, eĉ tiom ke ili murmuris kontraŭ la Sinjoro.",
    "Tiam okazis, ke mi, Nifai, estis afliktita kun miaj fratoj pro la perdo de mia arko, kaj ĉar iliaj arkoj perdis sian elastecon, ekfariĝis treege malfacile, jes, tiome ke ni ne povis akiri nutraĵon.",
    "Kaj okazis, ke mi, Nifai, multe parolis al miaj fratoj, ĉar ili ree malmoligis siajn korojn ĝis tia grado, ke ili eĉ plendis kontraŭ la Sinjoro, sia Dio.",
    "Kaj okazis, ke mi, Nifai, el ligno faris arkon kaj el rekta bastono sagon; tiamaniere mi armis min per arko kaj sago, per ĵetilo kaj per ŝtonoj. Kaj mi diris al mia patro: Kien mi iru por trovi ĉasaĵon?",
    "Kaj okazis, ke li demandis al la Sinjoro, ĉar ili humiliĝis pro miaj vortoj; ĉar mi diris multon al ili per la energio de mia animo.",
    "Kaj okazis, ke la voĉo de la Sinjoro venis al mia patro; kaj li estis vere riproĉata pro sia murmurado kontraŭ la Sinjoro, tiom ke li estis malsuprenigita ĝis profunda afliktiĝo.",
    "Kaj okazis, ke la voĉo de la Sinjoro diris al li: Rigardu la globon kaj vidu tion, kio estas skribita.",
    "Kaj okazis, ke kiam mia patro vidis tion, kio estis skribita sur la globo, li timegis kaj tremegis, kaj ankaŭ miaj fratoj kaj la filoj de Iŝmael kaj niaj edzinoj.",
    "Kaj okazis, ke mi, Nifai, vidis, ke la nadloj, kiuj estis en la globo, funkciis laŭ la kredo kaj diligenteco kaj atento, kiujn ni donis al ili.",
    "Kaj skribita sur ili estis nova skribo, kiu estis klare legebla kaj kiu donis al ni komprenon pri la vojoj de la Sinjoro; kaj ĝi estis skribata kaj ŝanĝata de tempo al tempo laŭ la kredo kaj diligenteco, kiujn ni donis al ĝi. Kaj tiamaniere ni vidas, ke per malgrandaj iloj la Sinjoro povas efektivigi grandaĵojn.",
    "Kaj okazis, ke mi, Nifai, eliris al la supro de la monto laŭ la direktoj, kiuj estis donitaj sur la globo.",
    "Kaj okazis, ke mi mortigis sovaĝbestojn, tiom ke mi akiris manĝaĵon por niaj familioj.",
    "Kaj okazis, ke mi revenis al niaj tendoj, portante la bestojn, kiujn mi mortigis; kaj, vidante, ke mi akiris manĝaĵon, kiom multe ili ĝojis! Kaj okazis, ke ili humiliĝis antaŭ la Sinjoro kaj donis dankojn al li.",
    "Kaj okazis, ke ni ree ekvojaĝis, irante preskaŭ la saman direkton kiel en la komenco; kaj, irinte dum multaj tagoj, ni restarigis niajn tendojn por restadi iom da tempo.",
    "Kaj okazis, ke Iŝmael mortis kaj estis enterigita en la loko, kiu estis nomita Nahom.",
    "Kaj okazis, ke la filinoj de Iŝmael treege funebris pro la perdo de sia patro kaj pro siaj afliktiĝoj en la dezerto; kaj ili murmuris kontraŭ mia patro, ĉar li irigis ilin el la lando Jerusalema, dirante: Nia patro estas mortinta; jes, kaj ni vagadis en la dezerto, kaj ni jam suferis multe da afliktiĝo, malsato, soifo kaj laceco; kaj post ĉiuj ĉi suferadoj ni nepre pereos en la dezerto pro malsato.",
    "Kaj tiel ili murmuris kontraŭ mia patro kaj ankaŭ kontraŭ mi; kaj ili deziris reiri al Jerusalemo.",
    "Kaj Laman diris al Lemuel kaj ankaŭ al la filoj de Iŝmael: Jen, ni mortigu nian patron kaj ankaŭ nian fraton Nifai, kiu arogis al si esti nia reganto kaj nia instruanto, kvankam ni estas liaj pli aĝaj fratoj.",
    "Nun li diras, ke la Sinjoro parolis al li kaj ankaŭ, ke anĝeloj servadis al li. Sed jen, ni scias, ke li mensogas al ni; kaj li rakontas al ni ĉi tion, kaj li artifikas multon per siaj ruzaj trukoj por trompi niajn okulojn, pensante, eble, ke li forgvidos nin en iun fremdan dezerton; kaj li jam pensis, ke, forgvidinte nin, li povos fari sin reĝo kaj reganto super ni, por disponi nin laŭ sia deziro kaj plezuro. Kaj tiumaniere mia frato Laman kolerigis iliajn korojn.",
    "Kaj okazis, ke la Sinjoro estis kun ni, jes, nome la voĉo de la Sinjoro venis por paroli multajn vortojn al ili kaj treege admoni ilin; kaj, admonite de la voĉo de la Sinjoro, ili forigis sian koleron kaj pentis pri siaj pekoj, tiel ke la Sinjoro denove benis nin per nutrao kaj ni ne pereis.",
  ],
} as const satisfies Chapter;
