export const chapter4 = {
  chapterTitle: "Ĉapitro 4",
  verses: [
    "Kaj okazis, ke mi parolis al miaj fratoj, dirante: Ni reiru al Jerusalemo kaj ni fidele obeu la ordonojn de la Sinjoro; ĉar, li ja estas pli potenca ol la tuta tero, do kial ne pli potenca ol Laban kaj lia kvindeko, jes, aŭ eĉ liaj dekmiloj?",
    "Ni do iru tien; ni estu fortaj, kiel Moseo; ĉar, efektive, li parolis al la akvoj de la Ruĝa Maro, kaj ili disfendiĝis dekstren kaj maldekstren, kaj niaj prapatroj trairis sur seka tero el kaptiteco, kaj la armeoj de Faraono sekvis kaj dronis en la akvoj de la Ruĝa Maro.",
    "Nu, vi ja scias, ke tio estas vera; kaj vi scias ankaŭ, ke anĝelo parolis al vi; kial vi povas dubi? Ni iru tien; la Sinjoro povas savi nin, eĉ same kiel niajn prapatrojn, kaj detrui Labanon, eĉ same kiel la egiptojn.",
    "Kiam mi finis paroli ĉi tiujn vortojn, ili ankoraŭ estis koleraj kaj ili ankoraŭ murmuradis; tamen ili sekvis min, ĝis ni venis ekster la murojn de Jerusalemo.",
    "Kaj estis nokte; kaj mi igis ilin kaŝi sin ekster la muroj. Kaj, post kiam ili kaŝis sin, mi, Nifai, glitis en la urbon kaj iris al la domo de Laban.",
    "Kaj mi estis gvidata de la Spirito, ne sciante antaŭe tion, kion mi devos fari.",
    "Tamen mi iris kaj, alproksimiĝante al la domo de Laban, mi vidis viron, kiu falis al la tero antaŭ mi, ĉar li estis ebria pro vino.",
    "Kaj, veninte al li, mi konstatis, ke li estas Laban.",
    "Kaj mi vidis lian glavon kaj mi eltiris ĝin el ĝia ingo; kaj ĝia tenilo estis el pura oro kaj ĝia prilaboriteco estis treege delikata, kaj mi vidis, ke ĝia klingo estis el la plej multekosta ŝtalo.",
    "Kaj okazis, ke la Spirito premis min, ke mi mortigu Labanon; sed mi diris en mia koro: Mi neniam verŝis la sangon de homo. Kaj mi hezitis kaj deziris ne devi mortigi lin.",
    "Kaj la Spirito diris al mi denove: Vidu, la Sinjoro transdonis lin en viajn manojn. Jes, kaj mi sciis ankaŭ, ke li celis forpreni mian propran vivon; jes, ke li ne volis aŭskulti la ordonojn de la Sinjoro; kaj ankaŭ, ke li forprenis nian posedaĵon.",
    "Kaj okazis, ke la Spirito ree diris al mi: Mortigu lin, ĉar la Sinjoro transdonis lin en viajn manojn;",
    "Jen la Sinjoro mortigas la malbonulojn por aperigi siajn justajn intencojn. Estas pli bone, ke unu homo pereu ol ke nacio degeneru kaj pereu en nekredemo.",
    "Kaj, aŭdinte ĉi tiujn vortojn, mi, Nifai, ekmemoris la vortojn de la Sinjoro, kiujn li diris al mi en la dezerto, dirante, ke: Se via idaro obeos miajn ordonojn, ĝi prosperos en la lando de promeso.",
    "Jes, kaj mi pensis ankaŭ, ke ĝi ne povos obei la ordonojn de la Sinjoro laŭ la leĝo de Moseo, se ĝi ne posedos la leĝon.",
    "Kaj mi sciis ankaŭ, ke la leĝo estas gravurita sur la platoj el latuno.",
    "Kaj, plie, mi sciis, ke la Sinjoro transdonis Labanon en miajn manojn por ĉi tiu celo por ke mi akiru la analojn laŭ liaj ordonoj.",
    "Pro tio mi obeis la voĉon de la Spirito, kaj mi prenis Labanon je la haroj de la kapo, kaj mi detranĉis lian kapon per lia propra glavo.",
    "Kaj, detranĉinte lian kapon per lia propra glavo, mi prenis la vestojn de Laban kaj metis ilin sur mian korpon; jes, nome ĉiun pecon; kaj mi zonis miajn lumbojn per liaj armiloj.",
    "Kaj, farinte tion, mi ekiris al la trezorejo de Laban. Kaj, irante al la trezorejo de Laban, jen mi vidis la serviston de Laban, kiu havis la ŝlosilojn de la trezorejo. Kaj mi ordonis al li per la voĉo de Laban, ke li iru kun mi en la trezorejon.",
    "Kaj li supozis min esti lia mastro Laban, ĉar li vidis la vestojn kaj ankaŭ la glavon zonitan ĉirkaŭ miaj lumboj.",
    "Kaj li parolis al mi pri la plejaĝuloj de la hebreoj, sciante, ke lia mastro Laban estis ekstere ĉi nokte inter ili.",
    "Kaj mi parolis al li, kvazaŭ mi estus Laban.",
    "Kaj mi diris al li ankaŭ, ke mi portos la gravuraĵojn, kiuj estas sur la platoj el latuno, al miaj pli aĝaj fratoj, kiuj estas ekster la muroj.",
    "Kaj mi ankaŭ ordonis al li, ke li sekvu min.",
    "Kaj li, supozante, ke mi parolis pri la fratoj de la eklezio, kaj ke mi estas vere tiu Laban, kiun mi mortigis, tial li sekvis min.",
    "Kaj li multfoje parolis al mi pri la plejaĝuloj de la hebreoj, dum mi eliris al miaj fratoj, kiuj estis ekster la muroj.",
    "Kaj okazis, ke, kiam Laman vidis min, li treege timis, kaj ankaŭ Lemuel kaj Sam. Kaj ili forkuris de antaŭ mi; ĉar ili supozis ke mi estas Laban, kaj ke li mortigis min kaj celas forpreni ankaŭ iliajn vivojn.",
    "Kaj okazis, ke mi alvokis al ili, kaj ili aŭdis min; kaj pro tio ili ĉesis forkuri de antaŭ mi.",
    "Kaj okazis, ke, kiam la servisto de Laban vidis miajn fratojn, li ektremadis kaj volis tuj fuĝi de antaŭ mi kaj reiri al la urbo Jerusalemo.",
    "Kaj tiam mi, Nifai, estante viro altstatura kaj ankaŭ ricevinte multan forton de la Sinjoro, pro tio mi kaptis la serviston de Laban kaj tenis lin, por ke li ne fuĝu.",
    "Kaj okazis, ke mi parolis kun li, ke, se li aŭskultos miajn vortojn, kiel la Sinjoro vivas kaj kiel mi vivas, se li aŭskultos niajn vortojn, ni lasos lin plu vivi.",
    "Kaj okazis, ke mi parolis kun li, eĉ kun ĵuro, ke ne necesas, ke li timu; ke li estos libera homo kiel ni, se li iros en la dezerton kun ni.",
    "Kaj mi plue parolis al li, dirante: Certe la Sinjoro ja ordonis al ni fari ĉi tion; kaj ĉu ni ne diligente obeos la ordonojn de la Sinjoro? Pro tio, se vi konsentos iri en la dezerton al mia patro, vi havos lokon inter ni.",
    "Kaj okazis, ke Zoram kuraĝiĝis pro la vortoj, kiujn mi diris. Nu, Zoram estis la nomo de la servisto; kaj li promesis, ke li iros en la dezerton al mia patro. Kaj li ankaŭ ĵuris al ni, ke li restos ĉe ni de post tiu tago.",
    "Ni ja deziris, ke li restu ĉe ni pro tio, ke la hebreoj ne eksciu pri nia fuĝo en la dezerton, por ke ili ne sekvu nin kaj detruu nin.",
    "Kaj okazis, ke, kiam Zoram faris uron al ni, niaj timoj pri li ĉesis.",
    "Kaj okazis, ke ni prenis la platojn el latuno kaj la serviston de Laban kaj foriris en la dezerton kaj vojaĝis al la tendo de nia patro.",
  ],
} as const satisfies Chapter;
