export const chapter3 = {
  chapterTitle: "Ĉapitro 3",
  verses: [
    "Kaj okazis, ke mi, Nifai, parolinte kun la Sinjoro, revenis al la tendo de mia patro.",
    "Kaj okazis, ke li parolis al mi, dirante: Jen, mi sonĝis sonĝon, en kiu la Sinjoro ordonis al mi, ke vi kaj viaj fratoj reiru al Jerusalemo.",
    "Ĉar, vidu, Laban havas la analojn de la hebreoj kaj ankaŭ genealogion de viaj prapatroj, kaj ili estas gravuritaj sur platoj el latuno.",
    "Pro tio la Sinjoro ordonis al mi, ke vi kaj viaj fratoj iru al la domo de Laban, por serĉi la analojn kaj alporti ilin ĉi tien en la dezerton.",
    "Kaj nun jen viaj fratoj murmuras, dirante, ke mi postulas de ili malfacilan aferon; sed, sciu, ne mi postulis tion de ili; tio estas ordono de la Sinjoro.",
    "Do iru, mia filo, kaj vi estos favorata de la Sinjoro pro tio, ke vi ne murmuris.",
    "Kaj okazis, ke mi, Nifai, diris al mia patro: Mi iros kaj faros tion, kion la Sinjoro ordonis, ĉar mi scias, ke la Sinjoro donas neniujn ordonojn al la homidoj sen prepari vojon por ili, por ke ili plenumu tion, kion li ordonas al ili.",
    "Kaj okazis, ke, kiam mia patro aŭdis tiujn vortojn, li estis treege kontenta, ĉar li sciis, ke mi estas benita de la Sinjoro.",
    "Kaj mi, Nifai, kaj miaj fratoj faris nian vojaĝon tra la dezerto kun niaj tendoj por iri al la lando Jerusalema.",
    "Kaj okazis, ke, kiam ni alvenis al la lando Jerusalema, mi kaj miaj fratoj interkonsiliĝis unu kun la aliaj.",
    "Kaj ni faris lotadon pri tio, kiu el ni iru al la domo de Laban. Kaj okazis, ke la loto falis por Laman; kaj Laman eniris en la domon de Laban, kaj li parolis al li dum li sidis en lia domo.",
    "Kaj li petis de Laban la analojn gravuritajn sur la platoj el latuno, kiuj surhavas la genealogion de mia patro.",
    "Kaj jen okazis, ke Laban koleriĝis kaj elpelis lin de antaŭ si, kaj li ne volis, ke li havu la analojn. Li do diris al li: Jen vi estas rabisto, kaj mi mortigos vin.",
    "Sed Laman fuĝis de antaŭ li kaj rakontis al ni tion, kion Laban faris. Kaj ni ege ĉagreniĝis, kaj miaj fratoj volis tuj reiri al mia patro en la dezerto.",
    "Sed tiam mi diris al ili, ke: Kiel la Sinjoro vivas, kaj kiel ni vivas, ni ne reiru al nia patro en la dezerto, ĝis ni estos plenumintaj tion, kion la Sinjoro ordonis al ni.",
    "Ni do fidele plenumu la ordonojn de la Sinjoro; tial ni iru al la heredaĵa tero de nia patro heredis, ĉar li ja lasis tie oron kaj arĝenton kaj ĉiajn riĉaĵojn. Kaj ĉion ĉi li faris pro la ordonoj de la Sinjoro.",
    "Ĉar li sciis, ke pro la malboneco de la popolo, Jerusalemo devas esti detruata.",
    "Ĉar ili ja forrifuzis la vortojn de la profetoj. Sekve, se mia patro loĝus en la lando, post kiam li estis ordonita fuĝi el la lando, ankaŭ li pereus. Li do nepre devis fuĝi el la lando.",
    "Kaj, aŭdu, estas saĝo en Dio, ke ni akiru ĉi tiujn analojn, por ke ni konservu por niaj infanoj la lingvon de niaj prapatroj;",
    "Kaj ankaŭ por ke ni konservu por ili la vortojn, kiuj estis parolitaj per la buŝo de ĉiuj el la sanktaj profetoj, kiuj estis donitaj al ili per la Spirito kaj potenco de Dio, depost la komenco de la mondo eĉ ĝis ĉi tiu nuna tempo.",
    "Kaj okazis, ke per ĉi tia lingvaĵo mi persvadis miajn fratojn, por ke ili fidele obeu la ordonojn de Dio.",
    "Kaj okazis, ke ni iris al la tero, kiun ni heredis, kaj ni kolektis nian oron kaj nian arĝenton kaj niajn valoraĵojn.",
    "Kaj kolektinte ĉi tiujn aĵojn, ni reiris al la domo de Laban.",
    "Kaj okazis, ke ni eniris al Laban kaj petis lin, ke li donu al ni la analojn, kiuj estis gravuritaj sur la platoj el latuno, pro kio ni donus al li nian oron kaj nian arĝenton kaj ĉiujn el niaj valoraĵoj.",
    "Kaj okazis, ke, kiam Laban vidis nian posedaĵon kaj konstatis, ke ĝi estas treege ampleksa, li avidegis ĝin tiom, ke li elpelis nin kaj sendis siajn servistojn por mortigi nin, por ke li akiru nian posedaĵon.",
    "Kaj okazis, ke ni fuĝis antaŭ la servistoj de Laban kaj ni devis postlasi nian posedaĵon, kaj ĝi falis en la manojn de Laban.",
    "Kaj okazis, ke ni fuĝis en la dezerton kaj la servistoj de Laban ne kuratingis nin, kaj ni kaŝis nin en kavo de roko.",
    "Kaj okazis, ke Laman koleriĝis kontraŭ mi kaj ankaŭ kontraŭ mia patro; kaj koleriĝis ankaŭ Lemuel, ĉar li aŭskultis la vortojn de Laman. Pro tio Laman kaj Lemuel parolis multajn malafablajn vortojn al ni, siaj pli junaj fratoj, kaj ili batis nin, nome per vergo.",
    "Kaj okazis, ke, dum ili batis nin per vergo, anĝelo de la Sinjoro alvenis kaj staris antaŭ ili, kaj li parolis al ili, dirante: Kial vi batas vian pli junan fraton per vergo? Ĉu vi ne scias, ke la Sinjoro elektis lin esti reganto super vi pro viaj malbonaj faroj? Aŭskultu, vi devas reiri al Jerusalemo, kaj la Sinjoro donos Labanon en viajn manojn.",
    "Kaj, post kiam la anĝelo parolis al ni, li foriris.",
    "Kaj, post kiam la anĝelo foriris, Laman kaj Lemuel rekomencis murmuri, dirante: Kiel eblas, ke la Sinjoro donos Labanon en niajn manojn? Li efektive estas potenculo kaj li komandas kvindekon, jes, li eĉ povas mortigi kvindekon; do kial ne nin?",
  ],
} as const satisfies Chapter;
