export const chapter7 = {
  chapterTitle: "Ĉapitro 7",
  verses: [
    "Kaj nun mi volas, ke vi sciu, ke, post kiam mia patro Lihai ĉesis profetadi pri sia idaro, okazis, ke la Sinjoro parolis al li denove, dirante, ke ne estas oportune, ke li, Lihai, prenu lian familion solan en la dezerton; sed ke liaj filoj prenu filinojn kiel edzinojn, por ke ili naskigu idaron por la Sinjoro en la lando de promeso.",
    "Kaj okazis, ke la Sinjoro ordonis al li, ke mi, Nifai, kaj miaj fratoj, denove reiru al la lando Jerusalema kaj venigu Iŝmaelon kaj lian familion en la dezerton.",
    "Kaj okazis, ke mi, Nifai, kun miaj fratoj, denove iris en la dezerton por iri al Jerusalem.",
    "Kaj okazis, ke ni iris al la domo de Iŝmael, kaj ni akiris plaĉon en la okuloj de Iŝmael, tiom ke ni ja parolis al li la vortojn de la Sinjoro.",
    "Kaj okazis, ke la Sinjoro moligis la koron de Iŝmael kaj ankaŭ de liaj domanoj, tiom ke ili iris kun ni en la dezerton al la tendo de nia patro.",
    "Kaj okazis, ke, dum ni vojaĝis en la dezerto, jen Laman kaj Lemuel, kaj du el la filinoj de Iŝmael, kaj la du filoj de Iŝmael kaj iliaj familioj, ribelis kontraŭ ni; jes, kontraŭ mi, Nifai, kaj Sam, kaj sia patro, Iŝmael, kaj lia edzino, kaj liaj tri aliaj filinoj.",
    "Kaj okazis en tiu ribelo, ke ili deziris reiri al la lando Jerusalema.",
    "Kaj tiam mi, Nifai, ĉagrenita pro la malmoleco de iliaj koroj, mi do parolis al ili, dirante, jes, nome al Laman kaj al Lemuel: Jen vi estas miaj pli aĝaj fratoj, kaj kiel fariĝis, ke vi estas tiel obstinaj en viaj koroj kaj tiel blindaj en viaj mensoj, ke vi havas bezonon, ke mi, via pli juna frato, parolu al vi, jes, kaj starigu ekzemplon por vi?",
    "Kiel fariĝis, ke vi ne aŭskultis la vortojn de la Sinjoro?",
    "Kiel fariĝis, ke vi forgesis, ke vi vidis anĝelon de la Sinjoro?",
    "Jes, kiel fariĝis, ke vi forgesis, kion grandan la Sinjoro faris por ni, savante nin el la manoj de Laban kaj ankaŭ ebligante nian akiron de la analoj?",
    "Jes, kaj kiel fariĝis, ke vi forgesis, ke la Sinjoro povas fari ĉion laŭ lia volo, por la homidoj, se nur ili montru fidon al li? Tial ni estu fidelaj al li.",
    "Kaj, se okazos, ke ni estas fidelaj al li, ni akiros la landon de promeso; kaj vi scios en iu estonta tempo, ke plenumiĝos la Sinjoro parolis pri la detruo de Jerusalemo, devos esti plenumita.",
    "Ĉar, vidu, la Spirito de la Sinjoro baldaŭ ĉesos lukti inter ili; ĉar ili forpuŝis la profetojn kaj ĵetis Jeremion en malliberejon. Kaj ili celis forpreni la vivon de mia patro tiom, ke ili elpelis lin el la lando.",
    "Nun, atentu, mi diras al vi, ke, se vi decidos reiri al Jerusalemo, ankaŭ vi pereos kun ili. Kaj nun, se vi jam elektas, iru al la lando kaj memoru la vortojn, kiujn mi parolas al vi, ke, se vi iros, vi ankaŭ pereos; ĉar tion la Spirito de la Sinjoro devigas min diri.",
    "Kaj okazis, ke, kiam mi, Nifai, diris tiujn ĉi vortojn al miaj fratoj, ili koleriĝis kontraŭ mi. Kaj okazis, ke ili metis siajn manojn sur min, ĉar ili ja estis tre koleraj, kaj ili ligis min per ŝnuroj, ĉar ili intencis forpreni mian vivon, lasonte min en la dezerto por esti manĝata de sovaĝaj bestoj.",
    "Sed okazis, ke mi preĝis al la Sinjoro, dirante: Ho Sinjoro, konforme al mia fido al vi, savu min el la manoj de miaj fratoj; jes, nome donu al mi forton, por ke mi diskrevu ĉi tiujn ŝnurojn, per kiuj mi estas ligita.",
    "Kaj okazis, ke, kiam mi diris ĉi tiujn vortojn, jen la ŝnuroj malligiĝis de miaj manoj kaj piedoj, kaj mi ekstaris antaŭ miajn fratojn, kaj mi denove parolis al ili.",
    "Kaj okazis, ke denove ili estis koleraj kontraŭ mi, kaj celis meti la manojn sur min; sed jen unu el la filinoj de Iŝmael, jes, kaj ankaŭ ŝia patrino kaj unu el la filoj de Iŝmael proparolis kun miaj fratoj tiom, ke ili moligis siajn korojn; kaj ili ĉesis celi forpreni mian vivon.",
    "Kaj okazis, ke ili estis malĝojaj pro sia malboneco tiom, ke ili kliniĝis al mi vizaĝaltere kaj petegis al mi, ke mi pardonu al ili tion, kion ili faris kontraŭ mi.",
    "Kaj okazis, ke mi sincere pardonis al ili ĉion, kion ili faris, kaj mi admonis ilin, ke ili preĝu al la Sinjoro, sia Dio, por pardono. Kaj okazis, ke ili tion faris. Kaj post kiam ili preĝis al la Sinjoro, ni denove ekvojaĝis al la tendo de nia patro.",
    "Kaj okazis, ke ni venis al la tendo de nia patro. Kaj, post kiam mi kaj miaj fratoj kaj la tuta domanaro de Iŝmael venis al la tendo de mia patro, ili ploradis la Sinjoron, sian Dion; kaj ili oferis buĉoferojn kaj bruloferojn al li.",
  ],
} as const satisfies Chapter;
