import "@bedrock-layout/css/lib/reset.min.css";
import "@bedrock-layout/css";
import "open-props/style";
import "./globals.css";

import { CSSProperties } from "react";
import { Inter } from "next/font/google";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        data-bedrock-center
        style={{ "--maxWidth": "60ch" } as CSSProperties}
      >
        {children}
      </body>
    </html>
  );
}
