export const chapter26 = {
  chapterTitle: "Ĉaptiro 26",
  summary: "",
  verses: [
    "La klasoj de la pordegistoj:el la KoraĤidoj:Meŝelemja, filo de Kore, el la filoj de Asaf.",
    "Meŝelemja havis filojn:la unuenaskito estis ZeĤarja, la dua estis Jediael, la tria estis Zebadja, la kvara estis Jatniel;",
    "la kvina estis Elam, la sesa estis JehoĤanan, la sepa estis Eljehoenaj.",
    "Obed-Edom havis filojn:Ŝemaja estis la unuenaskito, Jehozabad la dua, JoaĤ la tria, SaĤar la kvara, Netanel la kvina,",
    "Amiel la sesa, IsaĤar la sepa, Peultaj la oka; ĉar benis lin Dio.",
    "Al lia filo Ŝemaja naskiĝis filoj, kiuj regis en siaj patrodomoj, ĉar ili estis bravaj homoj.",
    "La filoj de Ŝemaja:Otni, Refael, Obed, Elzabad, liaj fratoj, bravaj homoj, Elihu kaj SemaĤja.",
    "Ĉiuj ili estis el la idoj de Obed-Edom; ili kaj iliaj filoj kaj iliaj fratoj estis bravaj homoj, taŭgaj por servado:sesdek du ili estis ĉe Obed- Edom.",
    "Meŝelemja havis filojn kaj fratojn, bravajn homojn dek ok.",
    "ĥosa el la Merariidoj havis filojn:Ŝimri estis la ĉefo (kvankam li ne estis unuenaskito, tamen lia patro faris lin ĉefo),",
    "ĥilkija estis la dua, Tebalja la tria, ZeĤarja la kvara; ĉiuj filoj kaj fratoj de ĥosa estis dek tri.",
    "Al tiuj grupoj da pordegistoj, al la ĉefoj de viroj, estis komisiita la servado en la domo de la Eternulo kune kun iliaj fratoj.",
    "Kaj ili lotis, kiel la malgrandaj, tiel ankaŭ la grandaj, laŭ siaj patrodomoj, por ĉiu pordego aparte.",
    "Kaj la loto pri la oriento falis por Ŝelemja; kaj pri lia filo ZeĤarja, la saĝa konsilanto, oni lotis, kaj lia loto eliris por la nordo;",
    "pri Obed-Edom por la sudo, kaj pri liaj filoj por la provizejo;",
    "pri Ŝupim kaj ĥosa por la okcidento, por la Pordego ŜaleĤet, kie la vojo leviĝas, kie gardo staras apud gardo.",
    "Oriente estis ses Levidoj, norde kvar ĉiutage, sude kvar ĉiutage, kaj ĉe la provizejoj po du.",
    "Ĉe la alirejo okcidente estis:kvar ĉe la vojo, kaj du ĉe la alirejo.",
    "Tio estis la grupoj da pordegistoj el la KoraĤidoj kaj el la Merariidoj.",
    "El la Levidoj, AĤija estis super la trezoroj de la domo de Dio kaj super la trezoroj de la sanktaĵoj.",
    "El la idoj de Ladan, idoj de la Gerŝonido Ladan, ĉefoj de patrodomoj de la Gerŝonido Ladan estis la JeĤielidoj.",
    "La JeĤielidoj:Zetam, kaj Joel, lia frato, estis super la trezoroj de la domo de la Eternulo.",
    "El la Amramidoj, Jicharidoj, ĥebronidoj, kaj Uzielidoj,",
    "Ŝebuel, ido de Gerŝom, filo de Moseo, estis estro super la trezoroj.",
    "Lia frato Eliezer havis filon ReĤabja; lia filo estis Jeŝaja, lia filo estis Joram, lia filo estis ZiĤri, kaj lia filo estis Ŝelomit.",
    "Ĉi tiu Ŝelomit kaj liaj fratoj estis super ĉiuj trezoroj de la sanktaĵoj, kiujn sanktigis la reĝo David, la ĉefoj de patrodomoj, la milestroj, kaj la centestroj, kaj la militestroj.",
    "El la militoj kaj el la militakiraĵoj ili konsekris partojn, por subteni la domon de la Eternulo.",
    "Ankaŭ ĉio, kion sanktigis la antaŭvidisto Samuel, kaj Saul, filo de Kiŝ, kaj Abner, filo de Ner, kaj Joab, filo de Ceruja, ĉio sanktigita estis sub la gardado de Ŝelomit kaj liaj fratoj.",
    "El la Jicharidoj, Kenanja kaj liaj filoj estis por la aferoj eksteraj de Izrael, kiel inspektistoj kaj juĝistoj.",
    "El la ĥebronidoj, ĥaŝabja kaj liaj fratoj, bravaj homoj, mil sepcent, havis oficojn en Izrael transe de Jordan, okcidente, por ĉiuj aferoj koncernantaj la Eternulon kaj por la aferoj de la reĝo.",
    "El la ĥebronidoj, Jerija estis ĉefo de la ĥebronidoj en iliaj generacioj kaj patrodomoj. En la kvardeka jaro de la reĝado de David ili estis esploritaj, kaj oni trovis ĉe ili bravajn homojn en Jazer en Gilead.",
    "Kaj liaj fratoj, bravaj homoj, du mil sepcent, ĉefoj de patrodomoj; al ili la reĝo David donis oficojn ĉe la Rubenidoj, la Gadidoj, kaj la duontribo de Manase, por ĉiuj aferoj de Dio kaj aferoj de la reĝo.",
  ],
} as const satisfies Chapter;
