export const chapter1 = {
  chapterTitle: "Ĉapitro 1",
  summary: "",
  verses: [
    "Estis unu viro el Ramataim-Cofim, de la monto de Efraim; lia nomo estis Elkana, filo de JeroĤam, filo de Elihu, filo de ToĤu, filo de Cuf, Efratano.",
    "Li havis du edzinojn; la nomo de unu estis ĥana, kaj la nomo de la dua estis Penina. Penina havis infanojn, sed ĥana ne havis infanojn.",
    "Tiu viro ĉiujare iradis el sia urbo, por adorkliniĝi kaj fari oferon al la Eternulo Cebaot en Ŝilo; kaj tie ĥofni kaj PineĤas, du filoj de Eli, estis pastroj de la Eternulo.",
    "Unu tagon Elkana faris oferon, kaj li donis al sia edzino Penina kaj al ĉiuj ŝiaj filoj kaj filinoj partojn;",
    "kaj al ĥana li kun malĝojo donis unu parton, ĉar ĥanan li amis, sed la Eternulo ŝlosis ŝian uteron.",
    "Kaj ŝia konkurantino afliktis ŝin kaj tre incitis ŝin kaŭze de tio, ke la Eternulo ŝlosis ŝian uteron.",
    "Tiel estis farate ĉiujare; kiam ŝi iradis al la domo de la Eternulo, la konkurantino tiel incitadis ŝin, ke ŝi ploris kaj ne manĝis.",
    "Kaj ŝia edzo Elkana diris al ŝi:ĥana, kial vi ploras? kaj kial vi ne manĝas? kaj kial tiel afliktiĝas via koro? ĉu mi ne estas por vi pli bona ol dek filoj?",
    "Kaj ĥana leviĝis, manĝinte en Ŝilo kaj trinkinte. Kaj la pastro Eli sidis sur seĝo ĉe la fosto de la templo de la Eternulo.",
    "Kaj ŝi estis tre malĝoja, kaj preĝis al la Eternulo, kaj forte ploris.",
    "Kaj ŝi faris sanktan promeson, kaj diris:Ho Eternulo Cebaot! se Vi rigardos la suferon de Via sklavino kaj rememoros min kaj ne forgesos Vian sklavinon kaj donos al Via sklavino idon virseksan, tiam mi fordonos lin al la Eternulo por la tuta tempo de lia vivo, kaj tondilo ne tuŝos lian kapon.",
    "Dum ŝi longe preĝis antaŭ la Eternulo, Eli atente rigardis ŝian buŝon.",
    "ĥana parolis en sia koro; nur ŝiaj lipoj moviĝadis, sed ŝian voĉon oni ne aŭdis; tial Eli pensis, ke ŝi estas ebria.",
    "Kaj Eli diris al ŝi:Kiel longe vi restos ebria? forigu vian vinon el vi.",
    "Sed ĥana respondis kaj diris:Ne, mia sinjoro, mi estas virino kun malĝoja koro; vinon aŭ ebriigaĵon mi ne trinkis, mi nur elverŝas mian animon antaŭ la Eternulo.",
    "Ne opiniu pri via sklavino, ke ŝi estas virino malmorala; pro mia granda malĝojo kaj sufero mi parolis ĝis nun.",
    "Tiam Eli respondis kaj diris:Iru en paco, kaj la Dio de Izrael plenumos vian peton, kiun vi petis de Li.",
    "Kaj ŝi diris:Via sklavino akiru vian favoron. Kaj la virino iris sian vojon, kaj ŝi manĝis, kaj ŝia vizaĝo ne estis plu malgaja.",
    "Kaj ili leviĝis frue matene kaj adorkliniĝis antaŭ la Eternulo, kaj reiris kaj venis al sia domo en Rama. Kaj Elkana ekkonis sian edzinon ĥana, kaj la Eternulo rememoris ŝin.",
    "Post kelka tempo ĥana gravediĝis kaj naskis filon, kaj ŝi donis al li la nomon Samuel, ĉar:De la Eternulo mi lin elpetis.",
    "La viro Elkana kun sia tuta domanaro iris, por oferi al la Eternulo la ĉiujaran oferon kaj sian promesitaĵon.",
    "Sed ĥana ne iris, sed ŝi diris al sia edzo:Kiam la knabo estos demamigita, tiam mi venigos lin, ke li aperu antaŭ la Eternulo kaj restu tie por ĉiam.",
    "Kaj ŝia edzo Elkana diris al ŝi:Faru tion, kio plaĉas al vi; restu, ĝis vi demamigos lin; nur la Eternulo plenumu Sian promeson. Kaj la virino restis, kaj suĉigis sian infanon, ĝis ŝi demamigis lin.",
    "Kaj post kiam ŝi demamigis lin, ŝi venigis lin kun si kune kun tri bovoj kaj unu efo da faruno kaj felsako da vino, kaj ŝi venigis lin en la domon de la Eternulo en Ŝilo; kaj la knabo estis ankoraŭ juna.",
    "Kaj oni buĉis bovon kaj venigis la knabon al Eli.",
    "Kaj ŝi diris:Ho mia sinjoro! tiel certe, kiel vivas via animo, mia sinjoro, mi estas tiu virino, kiu staris ĉi tie apud vi kaj preĝis al la Eternulo.",
    "Pri ĉi tiu knabo mi preĝis, kaj la Eternulo plenumis al mi mian peton, pri kiu mi petis Lin.",
    "Tial mi fordonas lin al la Eternulo; por la tuta tempo de sia vivo li estu fordonita al la Eternulo. Kaj ili tie adorkliniĝis antaŭ la Eternulo.",
  ],
} as const satisfies Chapter;
