export const chapter3 = {
  chapterTitle: "Ĉaptiro 3",
  summary: "",
  verses: [
    "Jen estas la filoj de David, kiuj naskiĝis al li en ĥebron:la unuenaskito Amnon, de la Jizreelanino AĤinoam; la dua estis Daniel, de la Karmelanino Abigail;",
    "la tria estis Abŝalom, filo de MaaĤa, filino de Talmaj, reĝo de Geŝur; la kvara estis Adonija, filo de ĥagit;",
    "la kvina estis Ŝefatja, de Abital; la sesa estis Jitream, de lia edzino Egla;",
    "ses naskiĝis al li en ĥebron. Li reĝis tie sep jarojn kaj ses monatojn; kaj tridek tri jarojn li reĝis en Jerusalem.",
    "Kaj jen estas tiuj, kiuj naskiĝis al li en Jerusalem:Ŝimea, Ŝobab, Natan, Salomono-ĉi tiuj kvar de Bat-Ŝua, filino de Amiel;",
    "JibĤar, Eliŝama, Elifelet,",
    "Noga, Nefeg, Jafia,",
    "Eliŝama, Eljada, kaj Elifelet-naŭ.",
    "Tio estas ĉiuj filoj de David, krom la filoj de kromvirinoj; kaj ilia fratino estis Tamar.",
    "La filo de Salomono estis ReĤabeam; la filo de ĉi tiu estis Abija; la filo de ĉi tiu:Asa; la filo de ĉi tiu:Jehoŝafat;",
    "la filo de ĉi tiu:Joram; la filo de ĉi tiu:AĤazja; la filo de ĉi tiu:Joaŝ;",
    "la filo de ĉi tiu:Amacja; la filo de ĉi tiu:Azarja; la filo de ĉi tiu:Jotam;",
    "la filo de ĉi tiu:AĤaz; la filo de ĉi tiu:ĥizkija; la filo de ĉi tiu:Manase;",
    "la filo de ĉi tiu:Amon; la filo de ĉi tiu:Joŝija.",
    "La filoj de Joŝija estis:la unuenaskito JoĤanan, la dua Jehojakim, la tria Cidkija, la kvara Ŝalum.",
    "La filoj de Jehojakim:lia filo JeĤonja, lia filo Cidkija.",
    "La filoj de JeĤonja:Asir, lia filo Ŝealtiel,",
    "Malkiram, Pedaja, Ŝenacar, Jekamja, ĥoŝama, kaj Nedabja.",
    "La filoj de Pedaja:Zerubabel kaj Ŝimei. La filoj de Zerubabel:Meŝulam, ĥananja; ilia fratino estis Ŝelomit;",
    "ankaŭ ĉi tiuj kvin:ĥaŝuba, Ohel, BereĤja, ĥasadja, kaj Juŝab- ĥesed.",
    "La idoj de ĥananja:Pelatja kaj Jeŝaja; la filoj de Refaja, la filoj de Arnan, la filoj de Obadja, la filoj de ŜeĤanja.",
    "La filo de ŜeĤanja estis Ŝemaja; la filoj de Ŝemaja:ĥatuŝ, Jigal, BariaĤ, Nearja, kaj Ŝafat-ses.",
    "La filoj de Nearja:Eljoenaj, ĥizkija, kaj Azrikam-tri.",
    "La filoj de Eljoenaj:Hodavja, Eljaŝib, Pelaja, Akub, JoĤanan, Delaja, kaj Anani-sep.",
  ],
} as const satisfies Chapter;
