export const chapter1 = {
  chapterTitle: "Ĉapitro 1",
  verses: [
    "Kaj okazis, ke forpasis la tridek-kvara jaro, kaj ankaŭ la tridek-kvina, kaj jen la disĉiploj de Jesuo jam formis eklezion de Kristo en ĉiuj landoj ĉirkaŭe. Kaj ĉiuj, kiuj venis al ili, kaj vere pentis pri siaj pekoj, baptiĝis en la nomo de Jesuo; kaj ili ankaŭ ricevis la Sanktan Spiriton.",
    "Kaj okazis en la tridek-sesa jaro, ke la tuta popolo sur la tuta lando, kaj nifaidoj kaj lamanidoj, konvertiĝis al la Sinjoro, kaj kvereloj kaj disputoj ne okazis inter ili, kaj ĉiuj homoj juste intertraktis reciproke.",
    "Kaj ĉe ili ĉio estis komuna; kaj ili estis nek riĉuloj nek malriĉuloj, nek sklavoj nek nesklavoj, sed ĉiuj liberiĝis, kaj fariĝis partoprenantoj en la ĉiela dono. 4. Kaj okazis, ke forpasis ankaŭ la tridek-sepa jaro, kaj ankoraŭ daŭris paco en la lando.",
    "Kaj la disĉiploj de Jesuo faris grandajn mirindaĵojn, sanigante malsanulojn, levante mortintojn, marŝigante lamulojn, donante vidpovon al blinduloj kaj aŭdpovon al surduloj; kaj ĉiajn miraklojn ili faris inter la homidoj; kaj ili faris miraklojn nur en la nomo de Jesuo.",
    "Kaj tiamaniere forpasis la tridek-oka jaro, kaj ankaŭ la tridek-naŭa, kaj kvardek-unua, kaj la kvardek-dua, jes, eĉ ĝis forpasis kvardek-naŭ jaroj, kaj ankaŭ la kvindek-unua, kaj la kvindek-dua; jes, kaj eĉ ĝis forpasis kvindek naŭ jaroj.",
    "Kaj la Sinjoro treege sukcesigis ilin en la lando; jes, tiom, ke ili rekonstruis urbojn, kie urboj estis bruligitaj.",
    "Jes, eĉ tiun urbegon Zarahemla ili rekonstruigis.",
    "Sed multaj urboj estis enprofundigitaj, kaj akvoj leviĝis super ilia loko; tiuj ĉi urboj ne povis esti renovigitaj.",
    "Kaj, jen, jam okazis, ke la popolo de Nifai fortiĝis, kaj treege rapide plimultiĝis, kaj fariĝis treege bela kaj ravanta popolo.",
    "Kaj ili geedziĝis, kaj estis geedzigitaj, kaj estis benitaj konforme al la multego da promesoj, kiujn la Sinjoro fari al ili.",
    "Kaj ili ne plu observis la ritojn kaj ordonojn de la leĝaro de Moseo; sed ili observis la ordonojn, kiujn ili ricevis de sia Sinjoro kaj sia Dio, daŭre fastante kaj preĝante, kaj ofte kunvenante kaj por preĝi kaj por aŭskulti la Vorton de la Sinjoro.",
    "Kaj neniu kverelo okazis inter la tuta popolo, en la tuta lando; sed potencaj mirakloj fariĝis inter la disĉiploj de Jesuo.",
    "Kaj okazis, ke forpasis la sepdek-unua jaro, kaj ankaŭ la sepdek-dua jaro, jes, kaj entute, ĝis forpasis la sepdek-naŭa jaro; jes, forpasis eĉ cent jaroj, kaj la disĉiploj de Jesuo, kiun li elektis, ĉiuj jam iris al la paradizo de Dio, krom la tri, kiuj devis resti; kaj aliaj disĉiploj ordiniĝis sur ilia loko; kaj ankaŭ multaj el tiu generacio forpasis.",
    "Kaj neniu kverelo okazis en la lando, pro la amo de Dio, kiu loĝis en la koroj de la popolo.",
    "Kaj ne okazis envioj, aŭ malpacoj, aŭ tumultoj, aŭ malĉastado, aŭ mensogado, aŭ murdoj, aŭ ia voluptemo; kaj certe ne povis esti pli feliĉa popolo inter ĉiuj popoloj, kiujn la mano de Dio kreis.",
    "Ne ekzistis rabistoj, aŭ murdistoj, kaj ne estis lamanidoj, aŭ iaj tiaj idoj; sed ĉiuj estis en unu, la infanaro de Kristo, kaj heredontoj de la regno de Dio.",
    "Kaj kiel benitaj ili estis! Ĉar la Sinjoro benis ilin en ĉiuj iliaj faroj; jes, ili ja estis benitaj kaj prosperis ĝis cent dek jaroj forpasis; kaj la unua generacio post Kristo jam forpasis, kaj ne okazis kverelo en la tuta lando.",
    "Kaj okazis, ke mortis Nifai, tiu kiu skribis ĉi tiun lastan kronikon (kaj kiu skribis ĝin sur la platojn de Nifai), kaj lia filo Amos tenis ĝin anstataŭ li; kaj ankaŭ li skribis ĝin sur la platojn de Nifai.",
    "Kaj li tenis ĝin dum okdek kvar jaroj, kaj ankoraŭ estis paco en la lando, kvankam malgranda parto de la popolo defalis de la eklezio kaj prenis la nomon lamanidoj; sekve ree ekestis lamanidoj en la lando.",
    "Kaj okazis, ke ankaŭ Amos mortis (kaj tio okazis cent naŭdek kvar jarojn post la veno de Kristo), kaj lia filo Amos tenis la kronikon anstataŭ li; kaj ankaŭ li skribis ĝin sur la platojn de Nifai; kaj ĝi estis skribita ankaŭ en la libro de Nifai, kiu estas ĉi tiu libro.",
    "Kaj okazis, ke ducent jaroj forpasis; kaj forpasis la dua generacio, ĉiuj krom malgranda nombro.",
    "Kaj nun mi, Mormon, volas, ke vi sciu, ke la popolo plimultiĝis, disvastiĝante sur la supraĵo de la tuta lando, kaj ke ili fariĝis treege riĉaj, pro sia prospereco per Kristo.",
    "Kaj tiam, en tiu ducent-unua jaro, ekestis inter ili tiuj,; kiu fieriĝis, portante multekostajn vestojn kaj ĉiajn fajnajn perlojn kaj la belaĵojn de la mondo.",
    "Kaj ekde tiam ĉe ili iliaj havaĵoj kaj ilia vivrimedoj ne plu estis komunaj.",
    "Kaj ili ekdividiĝis en klasoj; kaj ili komencis konstrui preĝejojn por si mem por havigi al si profiton, kaj ili komencis neadi la veran eklezion de Kristo.",
    "Kaj okazis, kiam ducent dek jaroj forpasis, multaj preĝejoj estis en la lando; jes, estis multaj preĝejoj, kiuj pretendis koni la Kriston, kaj tamen ili neis la pli multajn partojn de lia evangelio, ricevante ĉiajn malpiaĵojn kaj donante tion, kio estis sankta, al tiu, al kiu tio estis malpermesita pro malindeco.",
    "Kaj ĉi tiu eklezio treege plimultiĝis pro malvirteco kaj pro la potenco de Satano, kiu kaptis iliajn korojn.",
    "Kaj plie, estis alia eklezio, kiu neis la Kriston; kaj persekutis la veran eklezion de Kristo, pro la humileco de ĝiaj anoj kaj ilia kredo al Kristo; kaj ili malestimis ilin pro la multaj mirakloj, kiuj fariĝis inter ili.",
    "Tial ili uzis aŭtoritaton kaj potencon super la disĉiploj de Jesuo, kiuj restis ĉe ili, kaj ili ĵetis ilin en malliberejojn; sed per la potenco de la Vorto de Dio, kiu estis en ili, la malliberejoj disŝiriĝis en pecojn, kaj ili eliris, faronte grandajn miraklojn inter ili.",
    "Tamen, malgraŭ ĉiuj ĉi mirakloj, la popolo malmoligis siajn korojn, kaj celis mortigi ilin, same kiel la judoj en Jerusalemo celis mortigi Jesuon, laŭ lia Vorto.",
    "Kaj ili ĵetis ilin en fornojn de fajro, kaj ili eliris, ricevinte nenion malbonan.",
    "Kaj ili ankaŭ ĵetis ilin en kavojn de sovaĝaj bestoj, kaj ili ludis kun la sovaĝaj bestoj kvazaŭ infano kun ŝafido; kaj ili eliris el inter ili, ricevinte nenion malbonan.",
    "Tamen, la popolo malmoligis siajn korojn, ĉar multaj pastroj kaj falsaj profetoj persvadis ilin starigi multajn ekleziojn, kaj fari ĉiajn malvirtaĵojn. Kaj ili batis la popolon de Jesuo; sed la popolo de Jesuo ne rebatis. Kaj tiel ili malkreskis en nekredemo kaj malvirteco, ĉiujare, ĝis ducent tridek jaroj forpasis.",
    "Kaj tiam en tiu jaro, jes, en la ducent-tridek-unua jaro, okazis granda skismo inter la popolo.",
    "Kaj okazis, ke tiujare leviĝis popolo nomita la nifaidoj, kaj ili estis veraj kredantoj je Kristo; kaj inter ili estis tiuj, kiun la lamanidoj nomis Jakobidoj, kaj Jozefidoj, kaj Zoramidoj;",
    "Do, la veraj kredantoj je Kristo, kaj la veraj adorantoj al Kristo (inter kiuj estis la tri disĉiploj de Jesuo, kiu devis resti) estis nomitaj nifaidoj, kaj Jakobidoj, kaj Jozefidoj, kaj Zoramidoj;",
    "Kaj okazis, ke tiuj, kiuj, malakceptis la evangelion, estis nomitaj lamanidoj, kaj Lemuelidoj, kaj Iŝlmaaelidoj; kaj ili ne malkreskis en nekredemo, sed ili memvole ribelis kontraŭ la evangelio de Kristo; kaj ili instruis al siaj infanoj, ke ili ne kredu, eĉ kiel iliaj patroj, de la komenco, malkreskis.",
    "Kaj tio estis pro la malvirteco kaj abomenideco de iliaj patroj, same kiel tio estis en la komenco. Kaj oni instruis al ili malami la infanojn de Dio, same kiel oni instruis al la lamanidoj malami la infanojn de Nifai de la komenco.",
    "Kaj okazis, ke forpasis ducent kvardek kvar jaroj, kaj tiaj estis la aferoj de la popolo. Kaj la pli malvirta parto de la popolo fortiĝis, kaj fariĝis treege pli multnombra ol la popolo de Dio estis.",
    "Kaj ili ankoraŭ konstruadis preĝejojn por si mem, kaj ornamis ilin per ĉiaj valoraĵoj. Kaj tiel forpasis ducent kvindek jaroj, kaj ankaŭ ducent sesdek jaroj.",
    "Kaj okazis, ke la malvirta parto de la popolo komencis rekonstrui la sekretajn ĵurojn kaj komplotojn de Gadianton.",
    "Kaj ankaŭ la popolo, kiu estis nomita popolo de Nifai, komencis fieri en siaj koroj, pro sia superabunda riĉeco, kaj ili fariĝis vantaj kiel iliaj fratoj, la lamanidoj.",
    "Kaj ekde tiam la disĉiploj malĝojis pro la pekoj de la mondo.",
    "Kaj okazis, kiam tricent jaroj forpasis, ke la popolo de Nifai kaj la lamanidoj ambaŭ treege malvirtiĝis, unu kiel la alia.",
    "Kaj okazis, ke la rabistoj de Gadianton disiris sur la tutan supraĵon de la lando; kaj neniu estis virta krom la disĉiploj de Jesuo. Kaj oron kaj arĝenton ili abunde amasigis, kaj negocis ĉian komercon.",
    "Kaj okazis, kiam forpasis tricent kvin jaroj (kaj la popolo ankoraŭ restis en malvirteco), ke Amos mortis; kaj lia frato Ammaron tenis la kronikon anstataŭ li.",
    "Kaj okazis, kiam forpasis tricent dudek jaroj, ke Ammaron, premdevigita de la Sankta Spirito, kaŝis la analojn, kiuj estis sanktaj - jes, ĉiujn el la sanktaj analoj, kiuj estis transdonitaj de generacio al generacio, kaj kiuj estis sanktaj - eĉ ĝis la tricent-dudeka jaro post la veno de Kristo.",
    "Kaj li kaŝis ilin por la Sinjoro por ke ili revenu al la restaĵo de la domo de Jakob laŭ la profetaĵoj kaj la promesoj de la Sinjoro. Kaj jen estas la fino de la kroniko de Ammaron.",
  ],
  footNotes: ["36-321 p.K."],
} as const satisfies Chapter;
