export const chapter18 = {
  chapterTitle: "Ĉapitro 18",
  verses: [
    "Kaj okazis, ke Alma, fuĝinte de la servistoj de la reĝo Noa, pentis pri siaj pekoj kaj malvirteco, kaj sekrete rondiris inter la popolo, kaj komencis instrui la vortojn de Abinadai",
    "Jes, pri tio, kio venos, kaj ankaŭ pri la releviĝo de la mortintoj, kaj la elaĉeto de la popolo, kio okazos per la potenco, kaj suferoj, kaj morto de Kristo, kaj lia releviĝo kaj supreniro en la ĉielon.",
    "Kaj al ĉiuj, kiuj volis aŭdi liajn vortojn, li instruis. Kaj li instruis al ili sekrete, por ke la reĝo ne eksciu tion. Kaj multaj kredis liajn vortojn.",
    "Kaj okazis, ke ĉiuj, kiuj kredis lin, iris al loko nomita Mormon, kiu ricevis sian nomon de la reĝo, kaj kiu estis ĉe la limo de la lando, kaj kiu de tempo al tempo en kelkaj sezonoj estis infestata de sovaĝaj bestoj.",
    "En Mormon troviĝis fonto de pura akvo, kaj Alma ofte iris tien, ĉar apud la akvo estis densa arbetaro, kie li kaŝis sin dum la tago for de la serĉoj de la reĝo.",
    "Kaj okazis, ke tiuj, kiuj kredis lin, iris tien por aŭdi liajn vortojn.",
    "Kaj okazis post multaj tagoj, ke bela nombro da homoj kuniĝis en la loko Mormon, por aŭdi la vortojn de Alma. Jes, ĉiuj, kiuj kredis liajn vortojn, kuniĝis por aŭdi lin. Kaj li instruis al ili, kaj predikis al ili pri pentado, kaj liberiĝo, kaj fido je la Sinjoro.",
    "Kaj okazis, ke li diris al ili: Rigardu, jen la akvoj de Mormon (ĉar tiel ili nomiĝis) kaj nun, ĉar vi deziras veni en la ŝafejon de Dio, kaj esti nomataj lia popolo, kaj konsentas porti la ŝarĝojn unu de la aliaj, por ke ili estu malpezaj;",
    "Jes, kaj volas plori kun tiuj, kiuj ploras; jes, kaj konsoli tiujn, kiuj bezonas konsolon, kaj stari kiel atestantoj de Dio ĉiam, kaj pri ĉio, kaj ĉie kie vi estas, eĉ ĝis la morto, por ke vi estu elaĉetitaj de Dio, kaj estu alkalkulitaj al tiuj de la unua releviĝo, por ke vi havu eternan vivon",
    "Mi diras al vi, se tio estas la deziro de viaj koroj, kiun oponon vi havas kontraŭ baptiĝo je la nomo de la Sinjoro, kiel atestanto antaŭ li, ke vi transiris en interligon kun li, ke vi servos lin kaj obeos liajn ordonojn, por ke li pli abunde verŝu sian Spiriton sur vin?",
    "Kaj, kiam la popolanoj aŭdis ĉi tiujn vortojn, ili aplaŭdis per la manoj pro ĝojo, kaj ekkriis: Tio estas la deziro de niaj koroj.",
    "Kaj tiam okazis, ke Alma prenis Helam-on, kiu estis unu el la unuaj, kaj iris kaj stariĝis en la akvo, kaj kriis, dirante: Ho Sinjoro, elverŝu vian Spiriton sur vian serviston, por ke li faru ĉi tiun agon kun sankteco de koro.",
    "Kaj, kiam li diris ĉi tiujn vortojn, la Spirito de la Sinjoro estis sur li, kaj li diris: Helam, mi baptas vin posedante la aŭtoritaton de Dio Plejpotenca, kiel atesto, ke vi transiris en interligon por servi lin ĝis vi estos mortinta laŭ la mortema korpo; kaj la Spirito de la Sinjoro estu elverŝata sur vin; kaj li donu al vi eternan vivon, per la elaĉeto de Kristo, kiun li preparis ekde la fondiĝo de la mondo.",
    "Kaj post kiam Alma diris ĉi tiujn vortojn, Alma kaj Helam ambaŭ subiĝis en la akvo, kaj ili leviĝis kaj elvenis el la akvo, ĝojante, estante plenaj de la Spirito.",
    "Kaj denove, Alma prenis alian homon, kaj la duan fojon eniris en la akvon, kaj baptis lin tiel kiel la unuan krom tio, ke li ne ree subiĝis en la akvo.",
    "Kaj sammaniere li baptis ĉiujn, kiuj iris al la loko Mormon; kaj ili nombris ĉirkaŭ ducent kvar animojn; jes, kaj ili baptiĝis en la akvoj de Mormon, kaj pleniĝis per la graco de Dio.",
    "Kaj ili nomiĝis la eklezio de Dio, aŭ la eklezio de Kristo, ekde tiu tempo. Kaj okazis, ke ĉiu ajn, kiu baptiĝis per la potenco kaj aŭtoritato de Dio, aldoniĝis al lia eklezio.",
    "Kaj okazis, ke Alma, havante aŭtoritaton de Dio, starigis pastrojn; nome, unu pastron por ĉiu kvindeko da ili, li starigis por prediki al ili, kaj por instrui al ili pri tio, kio apartenas al la regno de Dio.",
    "Kaj li ordonis al ili, ke ili instruu nenion krom nur tio, kion li instruis, kaj tio, kio estis parolita de la buŝo de la sanktaj profetoj.",
    "Jes, li ja ordonis al ili, ke ili prediku nenion krom nur pentado kaj fido al la Sinjoro, kiu liberigis sian popolon.",
    "Kaj li ordonis al ili, ke ne estu disputoj unu kun alia, sed ke ili rigardu antaŭen per unuigita okulo, havante unu fidon kaj unu baptiĝon, havante siajn korojn kunligitaj en unueco kaj en amo unu al la aliaj.",
    "Kaj tiel li ordonis ilin prediki. Kaj tiel ili fariĝis la infanoj de Dio.",
    "Kaj li ordonis al ili, ke ili memoru pri la tago sabata, ke ili tenu ĝin sankta, kaj ke ĉiutage ili gloru la Sinjoron, sian Dion.",
    "Kaj li ordonis al ili ankaŭ, ke la pastroj, kiujn li starigis, laboru per siaj propraj manoj por vivteni sin.",
    "Kaj unu tago en ĉiu semajno estis elektita, por ke ili kuniĝu por instrui al la popolo, kaj por adori la Sinjoron, sian Dion, kaj ankaŭ tiel ofte kiel ili povos, por kolektiĝi.",
    "Kaj la pastroj ne dependu de la popolo por siaj vivrimedoj; sed por sia laboro ili ricevos la gracon de Dio, por ke ili fariĝu fortaj en la Spirito, havante la scion de Dio, por ke ili instruu per potenco kaj aŭtoritato el Dio.",
    "Kaj plie Alma ordonis, ke la anoj de la eklezio donu parton de sia havaĵo, ĉiu laŭ tio, kion li havas; se iu havas pli abunde, tiu donu pli abunde; kaj de tiu, kiu havas nur malmulton, oni postulu nur malmulton; kaj al tiu, kiu havas neniom, oni donu iom.",
    "Kaj tiumaniere ili donu parton de sia havaĵo propravole kaj bondezire al Dio, kaj al tiuj pastroj, kiuj estas bezonantoj, jes, kaj al ĉiu bezonanta, senvesta animo.",
    "Kaj ĉi tion li diris al ili, ordonite de Dio; kaj ili iris en virto antaŭ Dio, donante unu al la aliaj kaj materie kaj spirite laŭ iliaj bezonoj kaj iliaj mankoj.",
    "Kaj okazis, ke ĉio ĉi fariĝis en Mormon, jes ĉe la akvoj de Mormon, en la arbetaro, kiu estis apud la akvoj de Mormon; ja, la loko Mormon, la akvoj de Mormon, la arbetaro de Mormon, kiel belaj ili estas al la okuloj de tiuj, kiuj tie venis al la kono de sia Elaĉetanto; jes, kaj kiel feliĉaj ili estas, ĉar ili glorkantos al li por eterne.",
    "Kaj ĉio ĉi fariĝis ĉe la limo de la lando, por ke la reĝo ne eksciu pri tio.",
    "Sed okazis, ke la reĝo, rimarkinte moviĝon en la popolo, sendis siajn servistojn por observi ilin. Pro tio je la tago, en kiu ili kolektiĝis por aŭdi la vorton de la Sinjoro, ili malkaŝiĝis al la reĝo.",
    "Kaj la reĝo tiam diris, ke Alma incitas la popolon ribeli kontraŭ li; li do sendis sian armeon por detrui ilin.",
    "Kaj okazis, ke Alma kaj la popolo de la Sinjoro estis informitaj pri la veno de la armeo de la reĝo; ili do prenis siajn tendojn kaj siajn familiojn kaj foriris en la dezerton.",
    "Kaj ilia nombro estis ĉirkaŭ kvarcent kvindek animoj.",
  ],
} as const satisfies Chapter;
