export const chapter17 = {
  chapterTitle: "Ĉapitro 17",
  summary: "",
  verses: [
    "Kaj tiam okazis, kiam Abinadai finis ĉi tiujn dirojn, ke la reĝo ordonis, ke la pastroj prenu lin kaj mortigu lin.",
    "Sed inter ili estis iu, kies nomo estis Alma kaj kiu estis ankaŭ ido de Nifai. Kaj li estis junulo, kaj li kredis la vortojn, kiujn Abinadai diris, ĉar li sciis pri la malbona faro, pri kiu Abinadai atestis kontraŭ ili; tial li ekpledis al la reĝo, ke li ne koleru kontraŭ Abinadai, sed ke li permesu, ke li foriru en paco.",
    "Sed la reĝo fariĝis pli kolera, kaj elpeligis Alma-on el inter ili, kaj sendis siajn servistojn post li, por ke ili mortigu lin.",
    "Sed li fuĝis de antaŭ ili kaj kaŝis sin, tiel ke ili ne trovis lin. Kaj, kaŝite dum multaj tagoj, li skribis ĉiujn el la vortoj, kiujn Abinadai parolis.",
    "Kaj okazis, ke la reĝo faris, ke liaj gardistoj ĉirkaŭu Abinadai on kaj prenu lin; kaj ili ligis lin kaj ĵetis lin en malliberejon.",
    "Kaj post tri tagoj, konsiliĝinte kun siaj pastroj, li denove venigis lin antaŭ sin.",
    "Kaj li diris al li: Abinadai, ni trovis akuzon kontraŭ vi kaj vi meritas la morton.",
    "Ĉar vi diris, ke Dio mem malsuprenvenos inter la homidojn; kaj nun pro ĉi tiu kialo oni mortigos vin se vi ne reprenos ĉiujn el la vortoj de malbono, kiujn vi diris pri mi kaj mia popolo.",
    "Abinadai tuj diris al li: Mi diris al vi, mi ne reprenos la vortojn, kiujn mi diris al vi pri ĉi tiu popolo, ĉar ili estas veraj; kaj por ke vi sciu pri ilia vereco, mi lasis min fali en viajn manojn.",
    "Jes, kaj mi suferos ĝis la morto, kaj mi ne reprenos miajn vortojn, kaj ili staros kiel atesto kontraŭ vi. Kaj se vi mortigos min, vi verŝos senkulpan sangon, kaj ankaŭ tio staros kiel atesto kontraŭ vi je la lasta tago.",
    "Kaj la reĝo Noah estis liberigonta lin, ĉar li timis lian parolon, ĉar li timis, ke la juĝoj de Dio venos al li.",
    "Sed la pastroj levis siajn voĉojn kontraŭ li, kaj ekakuzis lin, dirante: Li hontigis la reĝon. Pro tio la reĝo kolere incitiĝis kontraŭ li, kaj li transdonis lin por ke oni mortigu lin.",
    "Kaj okazis, ke oni prenis lin kaj ligis lin, kaj skurĝis lian haŭton per brulantaj branĉofaskoj, jes, eĉ ĝis la morto.",
    "Kaj, kiam la flamoj komencis brulvundi lin, li kriis al ili, dirante:",
    "Aŭdu, eĉ kiel vi faris al mi, same okazos, ke via idaro faros, ke multaj suferu eĉ la dolorojn, kiujn mi suferos, eĉ la dolorojn de la morto per fajro; kaj tio okazos pro tio, ke ili kredos je la savo de la Sinjoro, ilia Dio.",
    "Kaj okazos, ke vi estos turmentataj per ĉiaj malsanoj pro viaj malbonaj agoj.",
    "Jes, kaj vi estos ĉie frapataj, kaj vi estos pelataj kaj disigataj tien kaj reen, eĉ kiel sovaĝa brutaro estas pelata de sovaĝaj kaj kruelaj bestoj.",
    "Kaj en tiu tago vi estos ĉasataj, kaj vi estos kaptitaj de la mano de viaj malamikoj, kaj tiam vi suferos, kiel mi suferas, la dolorojn de la morto per fajro.",
    "Tiel Dio plenumas venĝon kontraŭ tiuj, kiuj detruas lian popolon. Ho Dio, Akceptu mian animon.",
    "Kaj tiam, dirinte ĉi tiujn vortojn, Abinadai falis, suferinte morton per fajro; jes, mortigite ĉar li rifuzis fornei la ordonojn de Dio; sigelinte la veron de siaj vortoj per sia morto.",
  ],
} as const satisfies Chapter;
