export const chapter1 = {
  chapterTitle: "Ĉaptiro 1",
  summary: "",
  verses: [
    "Adam, Set, Enoŝ,",
    "Kenan, Mahalalel, Jared,",
    "ĥanoĤ, MetuŝelaĤ, LemeĤ,",
    "Noa, Ŝem, ĥam, kaj Jafet.",
    "La filoj de Jafet:Gomer, Magog, Madaj, Javan, Tubal, MeŝeĤ, kaj Tiras.",
    "La filoj de Gomer:Aŝkenaz, Rifat, kaj Togarma.",
    "La filoj de Javan:Eliŝa, Tarŝiŝ, Kitim, kaj Dodanim.",
    "La filoj de ĥam:Kuŝ, Micraim, Put, kaj Kanaan.",
    "La filoj de Kuŝ:Seba, ĥavila, Sabta, Raama, kaj SabteĤa. La filoj de Raama:Ŝeba kaj Dedan.",
    "Kuŝ naskigis ankaŭ Nimrodon; ĉi tiu komencis esti potenculo sur la tero.",
    "Micraim naskigis la Ludidojn, la Anamidojn, la Lehabidojn, la NaftuĤidojn,",
    "la Patrusidojn, la KasluĤidojn (de kiuj devenis la Filiŝtoj), kaj la Kaftoridojn.",
    "De Kanaan naskiĝis Cidon, lia unuenaskito, kaj ĥet,",
    "la Jebusidoj, la Amoridoj, la Girgaŝidoj,",
    "la ĥividoj, la Arkidoj, la Sinidoj,",
    "la Arvadidoj, la Cemaridoj, la ĥamatidoj.",
    "La filoj de Ŝem:Elam, Aŝur, ArpaĤŝad, Lud, Aram, Uc, ĥul, Geter, kaj MeŝeĤ.",
    "De ArpaĤŝad naskiĝis ŜelaĤ, de ŜelaĤ naskiĝis Eber.",
    "Al Eber naskiĝis du filoj:la nomo de unu estis Peleg, ĉar en lia tempo estis dividita la tero; la nomo de lia frato estis Joktan.",
    "De Joktan naskiĝis Almodad, Ŝelef, ĥacarmavet, JeraĤ,",
    "Hadoram, Uzal, Dikla,",
    "Ebal, Abimael, Ŝeba,",
    "Ofir, ĥavila, kaj Jobab. Ĉiuj ĉi tiuj estis la filoj de Joktan.",
    "Ŝem, ArpaĤŝad, ŜelaĤ,",
    "Eber, Peleg, Reu,",
    "Serug, NaĤor, TeraĤ,",
    "Abram (tio estas Abraham).",
    "La filoj de Abraham:Isaak kaj Iŝmael.",
    "Jen estas ilia genealogio:de Iŝmael, la unuenaskito Nebajot, poste Kedar, Adbeel, Mibsam,",
    "Miŝma, Duma, Masa, ĥadad, Tema,",
    "Jetur, Nafiŝ, kaj Kedma. Tio estas la filoj de Iŝmael.",
    "La filoj de Ketura, kromvirino de Abraham, kiujn ŝi naskis:Zimran, Jokŝan, Medan, Midjan, Jiŝbak, kaj ŜuaĤ. Kaj la filoj de Jokŝan estis Ŝeba kaj Dedan.",
    "La filoj de Midjan:Efa, Efer, ĥanoĤ, Abida, kaj Eldaa. Ĉiuj ĉi tiuj estis la filoj de Ketura.",
    "Abraham naskigis Isaakon. La filoj de Isaak:Esav kaj Izrael.",
    "La filoj de Esav:Elifaz, Reuel, Jeuŝ, Jalam, kaj KoraĤ.",
    "La filoj de Elifaz:Teman, Omar, Cefi, Gatam, Kenaz, Timna, kaj Amalek.",
    "La filoj de Reuel:NaĤat, ZeraĤ, Ŝama, kaj Miza.",
    "La filoj de Seir:Lotan, Ŝobal, Cibeon, Ana, Diŝon, Ecer, kaj Diŝan.",
    "La filoj de Lotan:ĥori kaj Homam; la fratino de Lotan estis Timna.",
    "La filoj de Ŝobal:Aljan, ManaĤat, Ebal, Ŝefi, kaj Onam. La filoj de Cibeon:Aja kaj Ana.",
    "La filoj de Ana:Diŝon. La filoj de Diŝon:ĥamran, Eŝban, Jitran, kaj Keran.",
    "La filoj de Ecer:Bilhan, Zaavan, kaj Jaakan. La filoj de Diŝan:Uc kaj Aran.",
    "Jen estas la reĝoj, kiuj reĝis en la lando de Edom, antaŭ ol aperis reĝo ĉe la Izraelidoj:Bela, filo de Beor; la nomo de lia urbo estis Dinhaba.",
    "Kaj Bela mortis, kaj anstataŭ li ekreĝis Jobab, filo de ZeraĤ, el Bocra.",
    "Kaj Joab mortis, kaj anstataŭ li ekreĝis ĥuŝam, el la lando de la Temanidoj.",
    "Kaj ĥuŝam mortis, kaj anstataŭ li ekreĝis Hadad, filo de Bedad, kiu venkobatis la Midjanidojn sur la kampo de Moab; la nomo de lia urbo estis Avit.",
    "Kaj Hadad mortis, kaj anstataŭ li ekreĝis Samla el Masreka.",
    "Kaj Samla mortis, kaj anstataŭ li ekreĝis Ŝaul el ReĤobot ĉe la Rivero.",
    "Kaj Ŝaul mortis, kaj anstataŭ li ekreĝis Baal-ĥanan, filo de AĤbor.",
    "Kaj Baal-ĥanan mortis, kaj anstataŭ li ekreĝis Hadad; la nomo de lia urbo estis Pai; la nomo de lia edzino estis Mehetabel, filino de Matred, filino de Me-Zahab.",
    "Kaj Hadad mortis. Tiam la ĉefoj de Edom estis:ĉefo Timna, ĉefo Alva, ĉefo Jetet,",
    "ĉefo Oholibama, ĉefo Ela, ĉefo Pinon,",
    "ĉefo Kenaz, ĉefo Teman, ĉefo Mibcar,",
    "ĉefo Magdiel, ĉefo Iram. Tio estas la ĉefoj de Edom.",
  ],
} as const satisfies Chapter;
