export const chapter12 = {
  chapterTitle: "Ĉapitro 12",
  summary: "",
  verses: [
    "Kaj jen estas la reĝoj de la lando, kiujn venkobatis la Izraelidoj, kaj kies landon ili ekposedis transe de Jordan oriente, de la torento Arnon ĝis la monto ĥermon, kaj la tutan stepon en la oriento:",
    "SiĤon, reĝo de la Amoridoj, kiu loĝis en ĥeŝbon, kaj regis de Aroer, kiu troviĝas sur la bordo de la torento Arnon, la mezon de la valo, kaj duonon de Gilead, ĝis la torento Jabok, limo de la Amonidoj;",
    "kaj la stepon ĝis la maro Kinerot, oriente, kaj ĝis la maro de la stepo, la Sala Maro, oriente en la direkto al Bet-Jeŝimot, kaj sude la bazon de la deklivo de Pisga;",
    "kaj la regiono de Og, reĝo de Baŝan, restinto el la Rafaidoj, kiu loĝis en Aŝtarot kaj Edrei,",
    "kaj regis la monton ĥermon kaj SalĤan kaj la tutan Baŝanon ĝis la limo de la Geŝuridoj kaj MaaĤatidoj, kaj duonon de Gilead ĝis la limo de SiĤon, reĝo de ĥeŝbon.",
    "Moseo, servanto de la Eternulo, kaj la Izraelidoj venkobatis ilin; kaj Moseo, servanto de la Eternulo, donis la landon kiel posedaĵon al la Rubenidoj kaj al la Gadidoj kaj al la duontribo de Manase.",
    "Kaj jen estas la reĝoj de la lando, kiujn venkobatis Josuo kaj la Izraelidoj transe de Jordan, okcidente, de Baal-Gad en la valo de Lebanon, ĝis la monto ĥalak, kiu leviĝas en la direkto al Seir; kaj Josuo donis ĝin al la triboj de Izrael kiel posedaĵon laŭ iliaj partoj;",
    "sur la monto kaj sur la malaltaĵo kaj en la stepo kaj sur la deklivoj kaj en la dezerto kaj sude, la ĥetidoj, la Amoridoj, kaj la Kanaanidoj, la Perizidoj, la ĥividoj, kaj la Jebusidoj:",
    "la reĝo de JeriĤo, unu; la reĝo de Aj, kiu estas flanke de Bet-El, unu;",
    "la reĝo de Jerusalem, unu; la reĝo de ĥebron, unu;",
    "la reĝo de Jarmut, unu; la reĝo de LaĤiŝ, unu;",
    "la reĝo de Eglon, unu; la reĝo de Gezer, unu;",
    "la reĝo de Debir, unu; la reĝo de Geder, unu;",
    "la reĝo de ĥorma, unu; la reĝo de Arad, unu;",
    "la reĝo de Libna, unu; la reĝo de Adulam, unu;",
    "la reĝo de Makeda, unu; la reĝo de Bet-El, unu;",
    "la reĝo de TapuaĤ, unu; la reĝo de ĥefer, unu;",
    "la reĝo de Afek, unu; la reĝo de Laŝaron, unu;",
    "la reĝo de Madon, unu; la reĝo de ĥacor, unu;",
    "la reĝo de Ŝimron-Meron, unu; la reĝo de AĤŝaf, unu;",
    "la reĝo de TaanaĤ, unu; la reĝo de Megido, unu;",
    "la reĝo de Kedeŝ, unu; la reĝo de Jokneam ĉe Karmel, unu;",
    "la reĝo de Dor en Nafot-Dor, unu; la reĝo de la popoloj en Gilgal, unu;",
    "la reĝo de Tirca, unu. La nombro de ĉiuj reĝoj estis tridek unu.",
  ],
} as const satisfies Chapter;
