export const chapter11 = {
  chapterTitle: "Ĉapitro 11",
  verses: [
    "Nu, laŭ la leĝo de Mozaja ĉiu viro, kiu estis juĝisto de la Leĝo, aŭ tiuj, kiuj estis nomitaj esti juĝistoj, ricevu salajron laŭ la tempo dum kiu ili laboris por juĝi tiujn, kiuj prezentiĝis antaŭ ili por esti juĝataj.",
    "Se homo ŝuldis al alia, kaj ne volis pagi tion, kion li ŝuldis, oni denuncis lin al la juĝisto; kaj la juĝisto uzis sian aŭtoritaton kaj sendis oficistojn por ke la homo estu alkondukata antaŭ lin; kaj li juĝis la homon laŭ la leĝo kaj la atestoj, kiujn oni faris kontraŭ li, kaj sekve la homo estis devigata pagi tion, kion li ŝuldis, aŭ esti senposedigita, aŭ esti elpelita el la popolo kiel ŝtelinto kaj rabinto.",
    "Kaj la juĝisto ricevis kiel sian salajron laŭ sia labortempo po unu senino da oro por unu tago, aŭ po unu senumo da arĝento, kiu egalas al unu senino da oro; kaj tio konformis al la leĝo, kiu estis donita.",
    "Jen sekvas la nomoj de la diversaj oraj moneroj, kaj arĝentaj moneroj, laŭ ilia valoro. Kaj la nomoj estis donitaj de la nifaidoj, ĉar ili ne kalkulis laŭ la maniero de la Judoj, kiuj estis ĉe Jerusalemo; kaj ili ankaŭ ne mezuris laŭ la maniero de la Judoj; sed ili ŝanĝis sian kalkulmetodon kaj siajn mezurojn laŭ la opinioj kaj la cirkonstancoj de la popolo, en ĉiu generacio, ĝis la regado de la juĝistoj, kiujn la reĝo Mozaja estigis.",
    "La kalkulado estis jena senino da oro, seono da oro, ŝumo da oro kaj limnaho de oro.",
    "Senumo da arĝento, amnoro da arĝento, ezromo da arĝento, kaj ontio da arĝento.",
    "Unu senumo da arĝento egalis unu seninon da oro, kaj por mezuro de hordeo kaj por mezuro de ĉiu speco de greno.",
    "La sumo de seono de oro estis duoblo de la valoro de senino.",
    "Kaj unu ŝumo da oro havis duoblon de la valoro de unu seono.",
    "Kaj unu limnaho da oro havis la valoron de ili ĉiuj.",
    "Kaj unu amnoro da arĝento estis tiel granda kiel du senumoj.",
    "Kaj unu ezromo da arĝento estis tiel granda kiel kvar senumoj.",
    "Kaj unu ontio estis tiel granda kiel ili ĉiuj.",
    "Jen nun la valoro de la malpli grandaj moneroj de ilia kalkulmaniero",
    "Unu ŝiblono estas duono de unu senumo; duonmezuro da hordeo do valoras unu ŝiblonon.",
    "Kaj unu ŝiblumo estas duono de ŝiblono.",
    "Kaj unu leaho estas duono de ŝiblumo.",
    "Tio estas ilia valoro laŭ ilia kalkulo.",
    "Unu antiono da oro egalas tri ŝiblonojn.",
    "Nur kun la celo akiri profiton, ĉar ili ricevis sian salajron laŭ sia labortempo, ili incitis la popolon al malpaco kaj ĉiaj tumultoj kaj malvirteco, por ke ili havu pli da laboro, por ke ili akiru monon laŭ la procesoj, kiuj prezentiĝis antaŭ ili; pro tio ili incitis la popolon kontraŭ Alma kaj Amulek.",
    "Kaj ĉi tiu Zeezrom komencis demandi al Amulek, dirante; Ĉu vi respondos al mi kelkajn demandojn, kiujn mi demandos al vi? Ĉar Zeezrom estis homo sperte lerta pri la intencoj de la diablo, ke li detruu tion, kio estas bona; tial li diris al Amulek; Ĉu vi respondos al la demandoj, kiujn mi metos al vi?",
    "Kaj Amulek diris al li; Jes, se tio estos laŭ la Spirito de la Sinjoro, kiu estas en mi; ĉar mi diros nenion, kiu kontraŭas al la spirito de la Sinjoro. Kaj Zeezrom diris al li; Jen ses ontioj da arĝento, kaj ĉiujn el ili mi donos al vi se vi neos la ekziston de Suprema Estaĵo.",
    "Tiam Amulek diris: Ho vi infano de la infero, kial vi tentas min? Ĉu vi ne scias, ke la justuloj ne cedas al tiaj tentoj?",
    "Ĉu vi kredas, ke ne ekzistas Dio? Mi diras el vi. Ne, vi scias, ke ekzistas Dio, sed vi amas tiun monaĉon pli ol lin.",
    "Kaj nun vi mensogis antaŭ Dio al mi. Vi diris al mi Jen ĉi tiujn ses ontiojn, kiuj havas grandan valoron, mi donos al vi kiam en via koro vi deziris deteni ilin de mi; kaj via sola deziro estis, ke mi neu la veran kaj vivantan Dion, por ke vi havu okazon detrui min. Kaj nun aŭdu, por ĉi tiu granda malbono vi havos vian rekompencon.",
    "Kaj Zeezrom diris al li: Ĉu vi diras, ke ekzistas vera kaj vivanta Dio?",
    "Kaj Amulek diris: Jes, ekzistas vera kaj vivanta Dio.",
    "Tiam Zeezrom diris: Ĉu ekzistas pli ol unu Dio?",
    "Kaj li respondis, Ne.",
    "Tiam Zeezrom plue diris al li; Kiel vi scias tion?",
    "Kaj li diris: Anĝelo sciigis tion al mi.",
    "Kaj Zeezrom plue diris: Kiu estas tiu, kiu venos? Ĉu tiu estas la Filo de Dio?",
    "Kaj li diris al li, Jes.",
    "Kaj Zeezrom plue diris: Ĉu li savos sian popolon en iliaj pekoj? Kaj Amulek respondis kaj diris al li: Mi diras al vi, ke ne, ĉar estas ne eble, ke li forneu sian vorton.",
    "Tiam Zeezrom diris al la popolo: Atentu, ke vi memoru ĉi tion; ĉar li diris, ke ekzistas nur unu Dio; tamen li diris, ke la Filo de Dio venos, sed li ne savos sian popolon kvazaŭ li havus aŭtoritaton ordoni al Dio.",
    "Tiam Amulek plue diris al li: Aŭdu, vi mensogis, ĉar vi diris, ke mi parolis kvazaŭ mi havus aŭtoritaton ordoni al Dio, ĉar mi diris, ke li ne savos sian popolon en iliaj pekoj.",
    "Kaj mi ree diras al vi, ke li ne povos savi ilin en iliaj pekoj; ĉar mi ne povas fornei lian vorton, kaj li diris, ke neniu malpurulo havos heredon en la regno de la ĉielo; tial, kiel vi povos esti savitaj se vi ne havos heredon en la regno de la ĉielo? Tial, vi ne povos esti savitaj en viaj pekoj.",
    "Tiam Zeezrom plue diris al li; Ĉu la Filo de Dio estas la Eterna Patro mem",
    "Kaj Amulek diris al li; Jes, li estas la Eterna Patro mem de la ĉielo kaj la tero, kaj de ĉio, kio estas en ili; li estas la komenco kaj la fino, la unua kaj la lasta;",
    "Kaj li venos en la mondon por elaĉeti sian popolon; kaj li prenos sur sin la pekojn de tiuj, kiuj kredas je lia nomo; kaj tiuj havos eternan vivon, kaj savo venos al neniu alia.",
    "Tial la malvirtuloj restos kvazaŭ estus okazinta neniu elaĉeto, krom malligo de la ligiloj de la morto; ĉar ja alproksimiĝas la tago, kiam ĉiuj leviĝos el la mortintoj kaj staros antaŭ Dio, kaj estos juĝataj laŭ siaj faroj.",
    "Nun, ekzistas morto, kiu estas nomita portempa morto; kaj la morto de Kristo malplektos la ligilojn de ĉi tiu portempa morto, por ke ĉiuj estu levitaj el ĉi tiu portempa morto.",
    "La spirito kaj la korpo estos rekunigitaj en sia perfekta formo; kaj membroj kaj artikoj estos redonitaj al sia ĝusta korpo, eĉ kiel ni nuntempe estas; kaj ni kondukiĝos por stari antaŭ Dio, sciante kiel ni nun scias, kaj ni havos klaran memoron pri nia tuta kulpeco.",
    "Tiam ĉi tiu restarigo okazos al ĉiuj, kaj maljunaj kaj junaj, kaj sklavaj kaj liberaj, kaj viraj kaj virinaj, kaj malvirtaj kaj justaj; kaj eĉ ne unu sola el la haroj de iliaj kapoj estos perdita; sed al ĉio estos redonita ĝia perfekta formo, kiel ĝi estas nun, eĉ en la korpo, kaj ĉiuj estos venigitaj kaj vokitaj antaŭ la tribunalon de Kristo la Filo, kaj Dio la Patro, kaj la Sankta Spirito, kiuj estas unu Eterna Dio, por esti juĝataj laŭ siaj faritaĵoj, ĉu ili estas bonaj aŭ ĉu ili estas malbonaj.",
    "Nun, mi ja parolis al vi pri la morto de la mortema korpo, kaj ankaŭ pri la releviĝo de la mortinta korpo. Mi diras al vi, ke ĉi tiu mortema korpo leviĝos al senmorta korpo, tio estas el la morto, eĉ el la unua morto, al la vivo, tiel ke ili ne povos ree morti; iliaj spiritoj unuiĝos kun iliaj korpoj, neniam dividote; tiel la tuto fariĝos spiriteca kaj senmorta, por ke ili ne plu forputru.",
    "Tiam, kiam Amulek finis tiujn vortojn, la popolo denove ekmiris, kaj ankaŭ Zeezrom ektremis. Kaj tiel finiĝis la vortoj de Amulek; jen ĉio, kion mi skribis.",
  ],
} as const satisfies Chapter;
