export const chapter32 = {
  chapterTitle: "Ĉapitro 32",
  verses: [
    "Kaj okazis, ke ili eliris, kaj komencis prediki la vorton de Dio al la popolo, enirante iliajn sinagogojn kaj iliajn domojn; jes, kaj ili predikis la vorton eĉ en iliaj stratoj.",
    "Kaj okazis, ke post granda penado inter ili, ili ekhavis sukceson inter la malriĉa klaso de la popolo; ĉar tiuj estis elpelitaj el la sinagogoj pro la krudeco de siaj vestoj -",
    "Pro tio oni ne permesis al ili eniri siajn sinagogojn por adori Dion, rigardante ilin kiel malpuraj, ĉar ili estis malriĉaj; jes, iliaj fratoj rigardis ilin kiel skorion; ĉar ili estis malriĉaj koncerne la aĵojn de la mondo; kaj ili estis malriĉaj ankaŭ en koro.",
    "Tiam, dum Alma instruis kaj parolis al la popolo sur la monteto Onidah venis al li granda homamaso, kiu konsistis el tiuj, pri kiuj ni ĵus parolis, kiuj estis malriĉaj en koro, pro sia malhavo de la aĵoj de la mondo.",
    "Kaj ili venis al Alma; kaj tiu, kiu estis unua inter ili, diris al li; Aŭdu, kion ĉi tiuj fratoj miaj faru, ĉar ili estas malestimataj de ĉiuj homoj pro sia malriĉeco, jes, precipe de niaj pastroj; ĉar tiuj elpelis nin el niaj sinagogoj, kiujn ni per laborego konstruis per niaj propraj manoj; kaj ili elpelis nin pro nia grandega malriĉeco; kaj ni havas neniun lokon, kie ni povus adori nian Dion; kaj do, kion ni faru?",
    "Kaj, kiam Alma aŭdis tion, li turniĝis kaj turnis sian vizaĝon al li, kaj li rigardis kun granda ĝojo; ĉar li vidis, ke ilia suferado vere humiligis ilin kaj ke ili estis pretaj aŭdi la vorton.",
    "Li do ne parolis plu al la alia homamaso; sed li etendis sian manon, kaj kriis al tiuj, kiujn li vidis kaj kiuj estis vere pentemaj, kaj diris al ili; 8. Ni vidas, ke vi estas humilaj en la koro; kaj se jes, benataj estas vi.",
    "Aŭdu, via frato diris, Kion ni faru? ĉar ni estas elpelitaj el niaj sinagogoj, tiel ke ni ne povas adori nian Dion.",
    "Aŭdu, mi diras al vi, ĉu vi supozas, ke nur en viaj sinagogoj vi povas adori Dion?",
    "Kaj plue, mi volas demandi, ĉu vi supozas, ke nur unu fojon en semajno vi devas adori Dion?",
    "Mi diras al vi, estas bone, ke vi estas elpelitaj el viaj sinagogoj, por ke vi estu humilaj, kaj lernu saĝecon, ĉar necesas, ke vi lernu saĝecon; ĉar pro tio, ke vi estas elpelitaj kaj malestimataj de viaj fratoj pro via grandega malriĉeco, vi kondukiĝis al humileco de koro; ĉar vi pro neceseco humiliĝis.",
    "Kaj nun, ĉar vi estas devigitaj esti humilaj, benataj estas vi; ĉar iufoje homo, se li estas devigita esti humila, deziras penti; kaj nun ĉiu, kiu pentas, certe trovos mizerikordon; kaj tiu, kiu trovas mizerikordon kaj persistas ĝis la fino, estos savita.",
    "Kaj nun, kiel mi diris al vi, ĉar vi estis devigitaj esti humilaj, vi estis benataj, ĉu vi ne supozas, ke pli benataj estas tiuj, kiuj vere humiligas sin pro la vorto?",
    "Jes, tiu, kiu vere humiligas sin, kaj pentas pri siaj pekoj, kaj persistas ĝis la fino, estos benita jes, multe pli benita ol tiuj, kiuj estas devigitaj esti humilaj per sia grandega malriĉeco.",
    "Tial, benataj estas tiuj, kiuj humiligas sin sen devigo humiliĝi; aŭ, alivorte, benata estas tiu, kiu kredas je la vorto de Dio, kaj estas baptita sen obstineco de koro, jes, sen ekkono de la vorto, aŭ eĉ devigo koni ĝin, antaŭ ol kredi.",
    "Jes, troviĝas multaj, kiuj diras; Se vi montros al ni signon el la ĉielo, tiam ni certe scios; tiam ni kredos.",
    "Nun mi demandas, ĉu tio estas fido? Aŭdu, mi diras al vi, Ne; ĉar, se homo scias ion, li ne bezonas kredi, ĉar li scias.",
    "Kaj kiom pli malbenita estas tiu, kiu konas la deziron de Dio kaj ne faras ĝin, ol tiu, kiu nur kredas, aŭ nur havas motivon kredi, kaj falas en leĝorompon?",
    "Nun pri ĉi tio vi devas juĝi. Aŭskultu, mi diras al vi, ke ĝi estas unuflanke sama kiel ĝi estas aliflanke; kaj okazos al ĉiu homo laŭ sia faritaĵo.",
    "Kaj nun, kiel mi diris pri la fido fido ne estas havi perfektan scion pri io; sekve, se vi havas fidon, vi esperas ion, kio ne estas vidata, sed kio estas vera.",
    "Kaj nun, aŭdu, mi diras al vi, kaj mi volas, ke vi memoru, ke Dio havas mizerikordon por ĉiuj, kiuj kredas je lia nomo; tial li deziras, unualoke, ke vi kredu, jes, ja je lia vorto.",
    "Kaj li donas sian vorton per anĝeloj al viroj, jes, ne nur al viroj sed ankaŭ al virinoj. Kaj tio ne estas ĉio; infanetoj multfoje ricevas vortojn, kiuj konfuzas la saĝulojn kaj la klerulojn.",
    "Kaj nun, miaj amataj fratoj, pro tio, ke vi deziris ekscii de mi, kion fari, ĉar vi estas afliktitaj kaj elpelitaj nu, mi ne deziras, ke vi supozu, ke mi intencas juĝi vin nur laŭ tio, kio estas vera.",
    "Ĉar mi ne volas diri, ke vi ĉiuj estas devigitaj humiligi vin; ĉar mi vere kredas, ke inter vi troviĝas kelkaj, kiuj humiligus sin en ĉiu ajn cirkonstanco.",
    "Nu, kiel mi diris pri la fido ke ĝi ne estas perfekta scio same estas pri miaj vortoj. Vi ne povas je la komenco scii pri ilia certeco, ĝis perfektiĝo, ne pli ol la fido estas perfekta scio.",
    "Sed, aŭdu, se vi vekiĝos kaj vekos viajn spiritajn kapablojn, nome al eksperimento pri miaj vortoj, kaj ekzercos eron da fido, jes, se vi ne povos pli ol deziri kredi, lasu tiun deziron agi en vi ĝis vi iel kredos, ke vi povas doni lokon al parto de miaj vortoj.",
    "Nun, ni komparos la vorton al semo. Nu, se vi donos lokon por ke semo plantiĝu en via koro, jen, se ĝi estas vera semo, aŭ bona semo, se vi ne forpuŝos ĝin per via nekredemo, rezistante la Spiriton de la Sinjoro, ĝi ja ekŝvelos en viaj brustoj; kaj, kiam vi sentos ĉi tiujn ŝvelomoviĝojn, vi ekdiros en vi mem ĝi nepre devas esti bona semo, aŭ la vorto estas bona, ĉar ĝi komencas pligrandigi mian animon; jes, ĝi komencas lumigi mian komprenadon, jes, ĝi komencas doni ardan plezuron al mi.",
    "Nun aŭdu, ĉu tio ne pligrandigus vian fidon? Mi diras al vi, Jes; tamen ĝi ne alkreskis ĝis perfekta scio.",
    "Sed aŭdu, kiam la semo ŝvelas, kaj burĝonas, kaj ekkreskas, tiam vi nepre devas diri, ke la semo estas bona; ĉar ĝi ja ŝvelas, kaj burĝonas, kaj ekkreskas.",
    "Kaj nun, aŭdu, ĉu vi estas certa, ke tiu estas bona semo? Ni diras al vi, Jes; ĉar ĉiu semo produktas laŭ sia propra formo.",
    "Tial, se semo kreskas, ĝi estas bona, sed, se ĝi ne kreskas, ĝi ne estas bona, tial oni forĵetas ĝin.",
    "Kaj nun, ja, ĉar vi faris la eksperimenton, kaj plantis la semon, kaj tiu ŝvelas kaj burĝonas, kaj ekkreskas, vi nepre scias, ke la semo estas bona.",
    "Kaj nun, aŭdu, ĉu via scio estas perfekta? Jes, via scio estas perfekta en tio, kaj via fido dormas; kaj tio okazis, ĉar vi scias, ke la Vorto ŝveligis viajn animojn, kaj vi scias ankaŭ, ke ĝi burĝonis, ke via komprenado komencas klariĝi, kaj ke via menso komencas plietendiĝi.",
    "Ho do, ĉu tio ne estas reala? Mi diras al vi, Jes, ĉar ĝi estas luma; kaj ĉio ajn, kio estas luma, estas bona, ĉar ĝi estas distingebla, kaj vi sekve devas scii, ke ĝi estas bona; kaj nun, aŭskultu, post gustumado de ĉi tiu lumo, ĉu via scio estas perfekta?",
    "Mi ja diras al vi, Ne; kaj vi devas ne flankenmeti vian fidon, ĉar vi ekzercis vian fidon nur por planti la semon, por ke vi faru la eksperimenton por scii, ĉu la semo estas bona.",
    "Kaj tiam, kiam la arbo komencos kreski, vi diros; Ni nutru ĝin kun granda zorgo, por ke ĝi ekradiku, ke ĝi plenkresku, kaj donu fruktojn al ni. Kaj nun aŭskultu, se vi nutros ĝin kun multa zorgo, ĝi ekradikos, kaj plenkreskos, kaj donos fruktojn.",
    "Sed, se vi neglektos la arbon, kaj ne pensos pri ĝia kreskigo, ĝi ja ne ricevos radikon; kaj, kiam la varmego de la suno venos kaj brulsekigos ĝin, ĉar ĝi ne havos radikon, ĝi forvelkos, kaj vi elŝiros ĝin kaj elĵetos ĝin.",
    "Ja, tio ne okazos, ĉar la semo ne estis bona, aŭ ĉar ĝiaj fruktoj ne estus dezirindaj; sed tio okazos, ĉar via grundo estas malfekunda, kaj vi ne volas nutri la arbon; tial vi ne povos ricevi fruktojn de ĝi.",
    "Kaj tiele, se vi ne nutros la vorton, rigardante antaŭen per fidanta okulo al ĝiaj fruktoj, vi neniam povos preni de la fruktoj de la arbo de vivo.",
    "Sed, se vi nutros la vorton, jes, nutros la arbon, per via fido kun granda diligenteco kaj kun pacienco, rigardante antaŭen al ĝiaj fruktoj, kiam ĝi komencos kreski, ĝi enradikiĝos; kaj ĝi ja estos arbo leviĝanta al eterna vivo.",
    "Kaj pro via diligenteco kaj via fido kaj via pacienco dum la nutrado de la vorto, por ke ĝi enradikiĝu en vi, iam vi prenos ĝiajn fruktojn, kiuj estas plej valoraj, kiuj estas pli dolĉaj ol ĉio, kio estas dolĉa, kaj kiuj estas pli blankaj ol ĉio, kio estas blanka, jes, kaj pli puraj ol ĉio, kio estas pura; kaj vi regalos vin de tiuj fruktoj ĝis vi plene satiĝos, kaj nek malsatos nek soifos.",
    "Tiam, miaj fratoj, vi rikoltos la rekompencojn de via fido, kaj viaj fervoro kaj pacienco kaj toleremeco dum la atendo ĝis la arbo donis fruktojn al vi.",
  ],
} as const satisfies Chapter;
