export const chapter42 = {
  chapterTitle: "Ĉapitro 42",
  verses: [
    "Kaj nun, mia filo, mi vidas, ke maltrankviligas vian menson io pli, kion vi ne povas kompreni kio koncernas la justecon de Dio en la punado de la pekinto; ĉar vi emas supozi, ke estas maljuste, ke la pekinto estas transdonita al stato de mizero.",
    "Nun aŭskultu, mia filo, mi klarigos ĉi tion al vi. Post kiam Dio la Sinjoro eligis niajn unuajn geprapatrojn el la Edena Ĝardeno, por ke ili prilaboradu la teron, el kiu ili estis prenitaj jes, li elpelis la viron, kaj li lokis oriente antaŭ la Edena Ĝardeno kerubon kaj flaman glavon, kiu ĉiudirekten turniĝis, por gardi la arbon de vivo -",
    "Ni vidas, ke la viro fariĝis kiel Dio, sciante bonon kaj malbonon; kaj por ke li ne etendu sian manon, kaj prenu ankaŭ de la arbo de vivo, kaj manĝu kaj vivu eterne, Dio la Sinjoro metis kerubon kaj la flaman glavon, por ke li ne partoprenu de la fruktoj -",
    "Kaj ni sekve vidas, ke tempo estis donita al la homo por penti, jes, provtempo, tempo por penti kaj servi Dion.",
    "Ĉar ja, se Adam estus tuj etendinta sian manon kaj preninta de la arbo de vivo, li vivus eterne, laŭ la vorto de Dio, havante neniom da tempospaco por pentado; jes, kaj ankaŭ la vorto de Dio estus nuligita, kaj la grandioza plano de savado estus vanigita.",
    "Sed, aŭdu, estis destinite, ke la homoj mortu tial, kiel ili estis fortranĉitaj de la arbo de vivo, ili estu fortranĉitaj de sur la tero - kaj la homoj perdiĝis por eterne, jes, ili fariĝis falinta homaro.",
    "Kaj nun, vi vidas per ĉi tio, ke niaj unuaj geprapatroj estis fortranĉitaj kaj portempe kaj spirite de antaŭ la Sinjoro; kaj ni do vidas, ke ili fariĝis liberaj sekvi sian propran volon.",
    "Nu, aŭdu, ne estis bone, ke la homo estu reakirita el ĉi tiu portempa morto, ĉar tio detruus la grandan planon de feliĉeco.",
    "Pro tio, ĉar la animo povas neniam morti, kaj la falo venigis al la tuta homaro spiritan morton kiel ankaŭ portempan morton, tio estas, ili estis fortranĉitaj de antaŭ la Sinjoro, estis oportune, ke la homaro estu reakirita el ĉi tiu spirita morto.",
    "Pro tio, ĉar ili fariĝis voluptamaj, ĝuamaj, kaj diablecaj en naturo, ĉi tiu prova stato fariĝis stato, en kiu ili povis prepari sin; ĝi fariĝis prepara stato.",
    "Kaj nun memoru, mia filo, se la plano de reaĉeto ne ekzistus, (kaj mi flankenmetas ĝin), tuj post ilia morto iliaj animoj estus mizeraj, estante fortranĉitaj de antaŭ la Sinjoro.",
    "Kaj estis nenia rimedo reakiri homojn el ĉi tiu falinta stato, kiun la homo venigis al si pro sia malobeado;",
    "Tial laŭ la justeco, la plano de reaĉeto ne povus plenumiĝi sen kondiĉo, ke la homoj pentu en ĉi tiu prova stato, jes, ĉi tiu prepara stato; ĉar sen ĉi tiu kondiĉo la mizerikordo ne povus efektiviĝi sen detruo de la efiko de la justeco. Nu, la efiko de la justeco ne povus esti detruata; se jes, Dio ĉesus esti Dio.",
    "Kaj tiel ni vidas, ke la tuta homaro falis, kaj ke ili estis en la tenego de la justeco; jes, la justeco de Dio, kiu transdonis ilin esti fortranĉitaj de antaŭ li por ĉiam.",
    "Kaj la plano de la mizerikordo ne povus plenumiĝi se pentopago ne estus farita; tial Dio mem akiris pardonon por la pekoj de la mondo, por plenumi la planon de la mizerikordo, por plenumi la postulojn de la justeco, por ke Dio estu perfekta, justa Dio, kaj ankaŭ mizerikorda Dio.",
    "Pento ja ne povis veni al homoj sen puno, kiu estis ankaŭ eterna kiel la vivo de la animo devus esti, alfiksita male al la plano de feliĉeco, kiu estis ankaŭ eterna kiel la vivo de la animo.",
    "Nu, kiel homo povus penti se li ne pekis? Kiel li povus peki se ne estis leĝo? Kiel povus esti leĝo se ne estis puno?",
    "Do, puno estis fiksita, kaj justa leĝo estis donita, kiu venigis kulposcion en la konsciencon de la homo.",
    "Nu, se neniu leĝo estus donita ke, se viro murdis, li mortu - ĉu li timus, ke li mortos se li murdus?",
    "Kaj ankaŭ, se estus donita nenia leĝo kontraŭ la peko, homoj ne timus peki.",
    "Kaj se ne estus donita leĝo, se homoj pekus, kion povus fari la justeco, aŭ la mizerikordo, ĉar ili havus nenian pretendon pri la kreitulo?",
    "Sed leĝo estas donita, kaj puno estas alfiksita, kaj pento estas permesata; kiun penton la mizerikordo pretendas; alie, la justeco pretendas la kreiton kaj plenumas la leĝon, kaj la leĝo trudas la punon; se tio ne okazus, la efikoj de la justeco estus detruataj, kaj Dio ĉesus esti Dio.",
    "Sed Dio ne ĉesas esti Dio, kaj la mizerikordo pretendas la pentantojn, kaj la mizerikordo venas pro la pentopago; kaj la pentopago okazigas la releviĝon de la mortintoj; kaj la releviĝo de la mortintoj revenigas homojn antaŭ Dion; kaj tiamaniere ili estas restarigataj antaŭ li, por esti juĝataj laŭ siaj faritaĵoj, laŭ la leĝo kaj la justeco.",
    "Ĉar, aŭdu, la justeco ekzercus ĉiujn el siaj postuloj, kaj ankaŭ la mizerikordo pretendas ĉion, kio apartenas al ĝi; kaj sekve, neniu krom la veraj pentantoj saviĝas.",
    "Kio, ĉu vi supozas, ke la mizerikordo povas prirabi la justecon? Mi diras al vi, Ne; ne unu joton. Se jes, Dio ĉesus esti Dio.",
    "Kaj tiamaniere Dio efektivigas siajn grandiozajn kaj eternajn celojn, kiuj estas preparitaj de post la fondiĝo de la mondo. Kaj tiamaniere okazas la savo kaj la elaĉeto de homoj, kaj ankaŭ ilia pereo kaj mizero.",
    "Tial ho mia filo, kiu ajn venos, rajtos veni kaj libere partopreni de la akvoj de vivo; kaj kiu ajn ne venos, tiu sama ne estos devigata veni: sed je la lasta tago laŭ siaj faritaĵoj ĝi estos restatigita al li.",
    "Se li deziris fari malbonon, kaj ne pentis dum siaj vivotagoj, aŭdu, malbono estos farata al li, laŭ la restatigo de Dio.",
    "Kaj nun, mia filo, mi deziras, ke vi ne plu lasu ĉi tion maltrankviligi vin, kaj nur viaj pekoj ĝenu vin, per tia ĝeno, kiu venigos vin al pento.",
    "Ho mia filo, mi deziras, ke vi ne plu forneu la justecon de Dio. Ne provu senkulpigi vin pri eĉ la malplej granda punkto, forneante la justecon de Dio; sed vi lasu la justecon de Dio, kaj lian mizerikordon, kaj lian toleremecon plene regi en via koro; kaj lasu ĝin meti vin en la polvon en humiliĝo.",
    "Kaj nun, ho mia filo, vi estas vokita de Dio prediki la vorton al ĉi tiu popolo. Kaj nun, mia filo, iru vian vojon, deklaru la vorton kun veremo kaj prudento, por ke vi venigu animojn al pento, por ke la grandioza plano de la mizerikordo asertu rajton super ili. Kaj Dio donu al vi tute laŭ miaj vortoj. Amen.",
  ],
} as const satisfies Chapter;
