export const chapter39 = {
  chapterTitle: "Ĉapitro 39",
  chapterSubtitle: "La ordonoj de Alma al sia filo Korianton",
  verses: [
    "Kaj nun, mia filo, mi havas iom pli por diri al vi ol tion, kion mi diris al via frato; ĉar, aŭdu, ĉu vi ne rimarkis la konstantecon de via frato, lian fidelecon, kaj lian fervoron obeadi la ordonojn de Dio? Aŭskultu, ĉu li ne montris bonan ekzemplon por vi?",
    "Ĉar vi ne donis tiom da atento al miaj vortoj kiel via frato, inter la popolo de la Zoramidoj. Nun, tio estas, kion mi havas kontraŭ vi; vi daŭrigis fanfaronadon pri via forto kaj via saĝo.",
    "Kaj tio ne estas ĉio, mia filo. Vi faris tion, kio forte malplaĉis al mi; ĉar vi forlasis la pastradon, kaj transiris en la landon Siron, ĉe la limoj de la lamanidoj, post la publikulino Izabela.",
    "Jes, ŝi forŝtelis la korojn de multaj; sed tio estis nenia pledo por vi, mia filo. Via devo estis okupi vin pri la pastrado, kiu estis konfidita al vi.",
    "Ĉu vi ne scias, mia filo, ke tio estas abomenaĵo antaŭ la Sinjoro; jes, plej abomeninda inter ĉiuj pekoj krom la verŝo de senkulpa sango aŭ forneo de la Sankta Spirito?",
    "Ĉar, aŭskultu, se vi forneas la Sanktan Spiriton, kiam ĝi iam havis lokon en vi, kaj vi scias, ke vi forneas ĝin, aŭdu, tio estas peko, kiu estas nepardonebla; jes, kaj, se iu murdas kontraŭ la lumo kaj scio de Dio, ne estas facile por tiu akiri pardonon; jes, mi diras al vi, mia filo, ke ne estas facile por li akiri pardonon.",
    "Kaj nun, mia filo, je Dio mi dezirus, ke vi ne estu kulpinta pri tiel granda krimo. Mi ne volus insisti pri viaj krimoj, por erpi vian animon, se tio ne estus bona al vi.",
    "Sed, aŭdu, vi ne povos kaŝi viajn krimojn de Dio; kaj, se vi ne pentos, ili restos kiel atesto kontraŭ vi je la lasta tago.",
    "Nun, mia filo, mi volas, ke vi pentu kaj forlasu viajn pekojn, kaj ne plu iru post la amorindaĵoj de viaj okuloj, sed krucumu vin pri ĉio ĉi; ĉar, se vi ne faros tion, vi povos neniel heredi la regnon de Dio. Ho, memoradu, kaj okupu vin pri tio, kaj krucumu vin pri ĉio ĉi.",
    "Kaj mi ordonas al vi, ke vi decidu konsiliĝi kun viaj pli aĝaj fratoj en viaj entreprenoj; ĉar, aŭdu, vi estas en via juneco, kaj vi bezonas esti vartata de viaj fratoj. Kaj atentu ilian konsiladon.",
    "Ne permesu, ke vi estu forlogata de iu vana aŭ malsaĝa afero; ne permesu, ke la diablo fortentu vian koron denove al tiuj fiaj publikulinoj. Komprenu, ho mia filo, la grandan malbonagon, kiun vi faris al la Zoramidoj; ĉar, vidinte vian konduton, ili ne kredis miajn vortojn.",
    "Kaj nun la Spirito de la Sinjoro diras al mi; Ordonu al viaj infanoj, ke ili faru bonon, por ke ili ne forgvidu la korojn de multaj homoj al pereo; tial mi ordonas al vi, mia filo, je la timo de Dio, ke vi detenu vin de viaj fiagoj;",
    "Ke vi turnu vin al la Sinjoro kun via tuta menso, povo kaj potenco al malvirta; agoj kaj via tuta forto; ke vi ne forgvidu la korojn neniuj aliaj por agi malvirte; sed anstataŭe reiru al ili, kaj konfesu viajn kulpojn kaj tiun fiagon, kiun vi faris.",
    "Ne serĉu riĉaĵojn aŭ la vantaĵojn de ĉi tiu mondo; ĉar, aŭdu, vi ne povos porti ilin kun vi.",
    "Kaj nun, mia filo, mi volas iom paroli al vi pri la veno de Kristo. Aŭdu, mi diras al vi, ke li certe venos por forporti la pekojn de la mondo; jes, li venos por deklari bonan sciigon pri savo al sia popolo.",
    "Kaj nun, mia filo, tia estis la pastrado, al kiu vi estis vokita, por deklari ĉi tiun bonan sciigon al ĉi tiu popolo, por prepari iliajn mensojn; aŭ, pli ĝuste, por ke savo venu al ili, por ke ili preparu la mensojn de siaj infanoj por aŭdi la vorton je la momento de lia veno.",
    "Kaj nun mi iom trankviligos vian menson pri ĉi tiu temo. Vi ja diras, kial ĉi tio estu jam sciata tiel longan tempon antaŭe. Aŭdu, mi diras al vi, ĉu animo nuntempe ne estas tiel valora al Dio kiel animo estos je la momento de lia veno?",
    "Ĉu ne egale necesas, ke la plano de elaĉeto estu sciigata ankaŭ al ĉi tiu popolo same kiel al iliaj infanoj?",
    "Ĉu ne estas tiel facile por la Sinjoro sendi sian anĝelon nuntempe por deklari ĉi tiun bonan sciigon al ni kiel al niaj infanoj, eĉ kiel je la momento de lia veno?",
  ],
} as const satisfies Chapter;
