export const chapter11 = {
  chapterTitle: "Ĉapitro 11",
  summary: "",
  verses: [
    "Kaj kunvenis ĉiuj Izraelidoj al David en ĥebronon, kaj diris:Jen ni estas via osto kaj via karno.",
    "Ankaŭ hieraŭ kaj antaŭhieraŭ, kiam Saul estis ankoraŭ reĝo, vi elkondukadis kaj enkondukadis Izraelon; kaj la Eternulo, via Dio, diris al vi:Vi paŝtos Mian popolon Izrael, kaj vi estos estro de Mia popolo Izrael.",
    "Kaj ĉiuj plejaĝuloj de Izrael venis al la reĝo en ĥebronon, kaj David faris kun ili interligon en ĥebron antaŭ la Eternulo; kaj ili sanktoleis Davidon reĝo super Izrael, konforme al la vorto de la Eternulo per Samuel.",
    "Kaj David kaj ĉiuj Izraelidoj iris en Jerusalemon (tio estas, en Jebuson). Tie la Jebusidoj estis la loĝantoj de la lando.",
    "Kaj la loĝantoj de Jebus diris al David:Vi ne eniros ĉi tien. Sed David venkoprenis la fortikaĵon Cion, tio estas, la urbon de David.",
    "Kaj David diris:Kiu la unua venkobatos la Jebusidojn, tiu estos ĉefo kaj estro. Kaj la unua supreniris Joab, filo de Ceruja, kaj li fariĝis ĉefo.",
    "Kaj David ekloĝis en tiu fortikaĵo; pro tio oni donis al ĝi la nomon:Urbo de David.",
    "Kaj li ĉirkaŭkonstruis la urbon ĉiuflanke, de Milo en la tuta ĉirkaŭo; kaj Joab restarigis la ceterajn partojn de la urbo.",
    "Kaj David fariĝadis ĉiam pli kaj pli granda, kaj la Eternulo Cebaot estis kun li.",
    "Jen estas la ĉefaj herooj, kiuj estis ĉe David, kaj kiuj tenis sin forte kun li dum lia reĝado, kune kun la tuta Izrael, por reĝigi lin super Izrael konforme al la vorto de la Eternulo.",
    "Jen estas la nombro de la herooj, kiuj estis ĉe David:Jaŝobeam, filo de ĥaĤmoni, estro de la tridek; li levis sian lancon kontraŭ tricent kaj mortigis ilin per unu fojo.",
    "Post li estis Eleazar, filo de Dodo, la AĤoĤido; li estis el la tri herooj.",
    "Li estis kun David en Pas-Damim, kie la Filiŝtoj kolektiĝis por batalo; tie estis kampoparto plena de hordeo; kaj la popolo forkuris antaŭ la Filiŝtoj.",
    "Sed tiuj stariĝis meze de la kampoparto, kaj savis ĝin kaj venkobatis la Filiŝtojn; kaj la Eternulo helpis per granda helpo.",
    "Kaj tri el la tridek ĉefoj iris sur la rokon al David, en la kavernon Adulam, dum la tendaro de la Filiŝtoj staris en la valo Refaim.",
    "David tiam estis en la fortikaĵo, kaj la garnizono de la Filiŝtoj estis tiam en Bet-LeĤem.",
    "Kaj David esprimis deziron kaj diris:Kiu trinkigus al mi akvon el la puto Bet-LeĤema, kiu estas apud la pordego?",
    "Tiam tiuj tri trarompe penetris en la tendaron de la Filiŝtoj, ĉerpis akvon el la puto Bet-LeĤema, kiu estis apud la pordego, prenis kaj alportis al David. Sed David ne volis trinki ĝin; li elverŝis ĝin al la Eternulo,",
    "kaj diris:Gardu min mia Dio, ke mi ne faru tion:ĉu mi trinku la sangon de tiuj viroj, kiuj riskis sian vivon? ĉar kun risko por sia vivo ili alportis ĝin. Kaj li ne volis trinki ĝin. Tion faris la tri herooj.",
    "Abiŝaj, frato de Joab, estis estro de tiuj tri; li mortigis per sia lanco tricent homojn, kaj li havis gloran nomon inter la tri.",
    "El la tri li estis honorata de du kaj estis ilia estro, sed en la trion li ne eniris.",
    "Benaja, filo de Jehojada, filo de homo kuraĝa, granda pro siaj faroj, el Kabceel:li mortigis la du fortulojn de Moab; li ankaŭ malsupreniris, kaj mortigis leonon en kavo en neĝa tago.",
    "Li ankaŭ mortigis Egipton, viron, kiu havis la alton de kvin ulnoj; en la mano de la Egipto estis lanco kiel rultrabo de teksisto; li aliris al li kun bastono, elŝiris la lancon el la mano de la Egipto, kaj mortigis lin per lia propra lanco.",
    "Tion faris Benaja, filo de Jehojada. Kaj li havis gloran nomon inter la tri herooj.",
    "Inter la tridek li estis plej honorata, sed en la trion li ne eniris. Kaj David faris lin lia korpogardistestro.",
    "La ĉefaj militistoj estis:Asahel, frato de Joab, ElĤanan, filo de Dodo, el Bet-LeĤem,",
    "Ŝamot, la Harorano, ĥelec, la Pelonano,",
    "Ira, filo de Ikeŝ, la Tekoaano, Abiezer, la Anatotano,",
    "SibĤaj, la ĥuŝaido, Ilaj, la AĤoĤido,",
    "Maharaj, la Netofaano, ĥeled, filo de Baana, la Netofaano,",
    "Itaj, filo de Ribaj, el Gibea de la Benjamenidoj, Benaja, la Piratonano,",
    "ĥuraj, el NaĤale-Gaaŝ, Abiel, la Arbatano,",
    "Azmavet, la BaĤurimano, EljaĤba, la Ŝaalbonano;",
    "el la filoj de Haŝem, la Gizonano:Jonatan, filo de Ŝage, la Hararano,",
    "AĤiam, filo de SaĤar, la Hararano, Elifal, filo de Ur,",
    "ĥefer, la MeĤeratano, AĤija, la Pelonano,",
    "ĥecro, la Karmelano, Naaraj, filo de Ezbaj,",
    "Joel, frato de Natan, MibĤar, filo de Hagri,",
    "Celek, la Amonido, NaĤaraj, la Beerotano, armilportisto de Joab, filo de Ceruja,",
    "Ira, la Jetrido, Gareb, la Jetrido,",
    "Urija, la ĥetido, Zabad, filo de AĤlaj,",
    "Adina, filo de Ŝiza, la Rubenido, ĉefo de Rubenidoj, kaj kun li estis tridek,",
    "ĥanan, filo de MaaĤa, Joŝafat, la Mitnido,",
    "Uzija, la Aŝterotano, Ŝama kaj Jeiel, filoj de ĥotam, la Aroerano,",
    "Jediael, filo de Ŝimri, kaj lia frato JoĤa, la Ticano,",
    "Eliel, la MaĤavido, Jeribaj kaj Joŝavja, filoj de Elnaam, Jitma, la Moabido,",
    "Eliel, Obed, kaj Jaasiel el Mecobaja.",
  ],
} as const satisfies Chapter;
