export const chapter10 = {
  chapterTitle: "Ĉaptiro 10",
  summary: "",
  verses: [
    "Okazis poste, ke mortis la reĝo de la Amonidoj, kaj lia filo ĥanun fariĝis reĝos anstataŭ li.",
    "Tiam David diris:Mi estos favorkora al ĥanun, filo de NaĤaŝ, konforme al tio, kiel lia patro agis favorkore koncerne min. Kaj David sendis, por konsoli lin per siaj servantoj pri lia patro. Kaj la servantoj de David venis en la landon de la Amonidoj.",
    "Sed la eminentuloj de la Amonidoj diris al sia sinjoro ĥanun:Ĉu efektive David deziras honori vian patron antaŭ vi, ke li sendis al vi konsolantojn? ĉu ne por pristudi la urbon, esplorrigardi kaj ruinigi ĝin, David sendis al vi siajn servantojn?",
    "Tiam ĥanun prenis la servantojn de David, kaj forrazis al ili duonon de la barbo, kaj detranĉis iliajn vestojn ĝis duono, ĝis la lumboj, kaj foririgis ilin.",
    "Kiam oni tion raportis al David, li sendis al ili renkonte, ĉar tiuj homoj tre hontis. Kaj la reĝo diris:Restu en JeriĤo, ĝis rekreskos viaj barboj, kaj tiam revenu.",
    "Kiam la Amonidoj vidis, ke ili indignigis Davidon, tiam la Amonidoj sendis kaj dungis Sirianojn el Bet-ReĤob kaj Sirianojn el Coba, dudek mil piedirantojn, kaj de la reĝo de MaaĤa mil homojn kaj de Tob dek du mil homojn.",
    "Kiam David aŭdis pri tio, li sendis Joabon kaj la tutan armeon da kuraĝuloj.",
    "Kaj eliris la Amonidoj kaj batalaranĝiĝis ĉe la enirejo de la pordego; kaj la Sirianoj el Coba kaj el ReĤob kaj la viroj de Tob kaj de MaaĤa estis aparte, sur la kampo.",
    "Kiam Joab vidis, ke li havos kontraŭ si batalon antaŭe kaj malantaŭe, li faris elekton el ĉiuj plejbravuloj en Izrael kaj batalaranĝis ilin kontraŭ la Sirianoj;",
    "kaj la ceteran parton de la popolo li komisiis al sia frato Abiŝaj, kaj batalaranĝis ilin kontraŭ la Amonidoj.",
    "Kaj li diris:Se la Sirianoj superfortos min, tiam vi donos al mi helpon; sed se la Amonidoj superfortos vin, tiam mi iros, por helpi vin.",
    "Estu kuraĝa, kaj ni tenu nin forte por nia popolo kaj por la urboj de nia Dio; kaj la Eternulo faru tion, kio plaĉos al Li.",
    "Kaj Joab, kun la popolo, kiu estis kun li, komencis la batalon kontraŭ la Sirianoj; kaj ĉi tiuj forkuris antaŭ li.",
    "Kiam la Amonidoj vidis, ke la Sirianoj forkuris, ili ankaŭ forkuris antaŭ Abiŝaj, kaj foriris en la urbon. Tiam Joab returnis sin de la Amonidoj, kaj venis Jerusalemon.",
    "Kiam la Sirianoj vidis, ke ili estas venkobatitaj de la Izraelidoj, ili kolektiĝis en unu loko.",
    "Kaj Hadadezer sendis, kaj elirigis la Sirianojn transriverajn; kaj ili venis en ĥelamon; kaj ŜobaĤ, militestro de Hadadezer, ilin kondukis.",
    "Kiam tio estis raportita al David, li kolektis ĉiujn Izraelidojn, kaj transiris Jordanon kaj venis en ĥelamon. Kaj la Sirianoj aranĝis sin kontraŭ David kaj ekbatalis kontraŭ li.",
    "Kaj la Sirianoj forkuris antaŭ Izrael, kaj David mortigis el la Sirianoj sepcent ĉaristojn kaj kvardek mil rajdantojn; ankaŭ ŜobaĤon, la militestron, li frapis, kaj tiu mortis tie.",
    "Kiam ĉiuj reĝoj, kiuj servis Hadadezeron, vidis, ke ili estas venkobatitaj de la Izraelidoj, ili faris pacon kun la Izraelidoj kaj submetiĝis al ili. Kaj la Sirianoj timis helpi plu al la Amonidoj.",
  ],
} as const satisfies Chapter;
