export const chapter2 = {
  chapterTitle: "Ĉapitro 2",
  summary: "",
  verses: [
    "Post tiu afero, kiam kvietiĝis la kolero de la reĝo AĤaŝveroŝ, li rememoris pri Vaŝti, kaj pri tio, kion ŝi faris kaj kio estis dekretita pri ŝi.",
    "Kaj diris la junuloj de la reĝo, kiuj servadis al li:Oni serĉu por la reĝo belajn junajn virgulinojn;",
    "kaj la reĝo starigu en ĉiuj landoj de sia regno oficistojn, kiuj kolektus ĉiujn belajn junajn virgulinojn en la kastelurbon Ŝuŝan, en la virinejon, sub la inspektadon de Hegaj, la reĝa eŭnuko, gardisto de la virinoj, kaj oni donu al ili iliajn beligaĵojn;",
    "kaj la junulino, kiu plaĉos al la okuloj de la reĝo, fariĝos reĝino anstataŭ Vaŝti. Kaj la afero plaĉis al la reĝo, kaj li tiel faris.",
    "En la kastelurbo Ŝuŝan estis Judo, kies nomo estis MordeĤaj, filo de Jair, filo de Ŝimei, filo de Kiŝ, Benjamenido;",
    "kiu estis transloĝigita el Jerusalem kune kun la transloĝigitoj, kiuj estis forkondukitaj kun JeĤonja, reĝo de Judujo, kaj kiujn transloĝigis Nebukadnecar, reĝo de Babel.",
    "Li estis prizorganto de Hadasa, kiu ankaŭ estis nomata Ester, filino de lia onklo, ĉar ŝi ne havis patron nek patrinon. La junulino estis belstatura kaj belvizaĝa. Kiam mortis ŝiaj gepatroj, MordeĤaj prenis ŝin al si kiel filinon.",
    "Kiam estis aŭdigita la ordono de la reĝo kaj lia leĝo, kaj kiam oni kolektis multe da knabinoj en la kastelurbon Ŝuŝan sub la inspekton de Hegaj, tiam ankaŭ Ester estis prenita en la reĝan domon sub la inspekton de Hegaj, la gardisto de la virinoj.",
    "La knabino plaĉis al li kaj akiris lian favoron, kaj li rapide donis al ŝi ŝiajn beligaĵojn kaj ŝian destinitaĵon, kaj sep knabinojn elektitajn el la domo de la reĝo; kaj li transloĝigis ŝin kun ŝiaj knabinoj en la plej bonan parton de la virinejo.",
    "Ester ne diris pri sia popolo nek pri sia patrujo, ĉar MordeĤaj ordonis al ŝi, ke ŝi ne diru.",
    "Ĉiutage MordeĤaj iradis antaŭ la korto de la virinejo, por sciiĝi pri la farto de Ester, kaj pri tio, kio okazas al ŝi.",
    "Kiam por ĉiu knabino venis la vico iri al la reĝo AĤaŝveroŝ, post kiam dum dek du monatoj estis farata al ŝi la beligado destinita por la virinoj (ĉar tiel longe daŭris la tempo de ilia beligado:ses monatoj per mirha oleo, kaj ses monatoj per aromaĵoj kaj per aliaj ŝmiraĵoj),",
    "tiam la knabino eniris al la reĝo. Ĉion, kion ŝi diris, oni donis al ŝi, por ke ŝi iru kun tio el la virinejo en la reĝan domon.",
    "Vespere ŝi eniris, kaj matene ŝi revenis en la virinejon duan, sub la inspekton de Ŝaaŝgaz, reĝa eŭnuko, gardisto de la kromvirinoj; ŝi jam ne plu iris al la reĝo, krom en la okazo, se la reĝo ŝin deziris kaj se ŝi estis vokita laŭnome.",
    "Kiam por Ester, filino de AbiĤail, onklo de MordeĤaj, kiu prenis ŝin al si kiel filinon, venis la vico iri al la reĝo, ŝi nenion petis, krom nur tio, kion diris Hegaj, la reĝa eŭnuko, gardisto de la virinoj. Kaj Ester akiris la favoron de ĉiuj, kiuj ŝin vidis.",
    "Ester estis prenita al la reĝo AĤaŝveroŝ en lian reĝan domon en la deka monato, tio estas en la monato Tebet, en la sepa jaro de lia reĝado.",
    "Kaj la reĝo ekamis Esteron pli ol ĉiujn edzinojn, kaj ŝi akiris ĉe li simpation kaj favoron pli ol ĉiuj virgulinoj; kaj li metis reĝan kronon sur ŝian kapon kaj faris ŝin reĝino anstataŭ Vaŝti.",
    "Kaj la reĝo faris grandan festenon por ĉiuj siaj princoj kaj servantoj, festenon je la honoro de Ester; kaj li donis ripozon al la landoj kaj disdonis reĝajn donacojn.",
    "Kaj kiam oni la duan fojon kolektis junulinojn, MordeĤaj sidis ĉe la pordego de la reĝo.",
    "Ester ankoraŭ ne diris pri sia patrujo kaj pri sia popolo, kiel ordonis al ŝi MordeĤaj; kaj la dirojn de MordeĤaj Ester plenumadis tiel same, kiel tiam, kiam ŝi estis sub lia prizorgado.",
    "En tiu tempo, kiam MordeĤaj sidadis ĉe la pordego de la reĝo, ekkoleris Bigtan kaj Tereŝ, du korteganoj de la reĝo el la sojlogardistoj,  kaj ili intencis meti manon sur la reĝon AĤaŝveroŝ.",
    "Pri tio eksciis MordeĤaj, kaj li diris al la reĝino Ester, kaj Ester diris tion al la reĝo en la nomo de MordeĤaj.",
    "La afero estis esplorita kaj trovita vera, kaj oni pendigis ambaŭ sur arbo. Kaj tio estis enskribita en la kronikon ĉe la reĝo.",
  ],
} as const satisfies Chapter;
