export const chapter8 = {
  chapterTitle: "Ĉapitro 8",
  summary: "",
  verses: [
    "De Benjamen naskiĝis:Bela, lia unuenaskito, Aŝbel, la dua, AĤraĤ, la tria;",
    "NoĤa estis la kvara, kaj Rafa estis la kvina.",
    "La filoj de Bela estis:Adar, Gera, Abihud,",
    "Abiŝua, Naaman, AĤoaĤ,",
    "Gera, Ŝefufan, kaj ĥuram.",
    "Jen estas la filoj de Ehud, kiuj estis ĉefoj de patrodomoj, kiuj loĝis en Geba kaj elmigris en ManaĤaton:",
    "Naaman, AĤija, Gera; ĉi tiu elmigrigis ilin, kaj li naskigis Uzan kaj AĤiĤudon.",
    "ŜaĤaraim naskigis sur la kampoj de Moab, post kiam li forigis de si siajn edzinojn ĥuŝim kaj Baara.",
    "Li naskigis de sia edzino ĥodeŝ:Jobabon, Cibjan, Meŝan, Malkamon,",
    "Jeucon, ŜoĤjan, kaj Mirman. Tio estis liaj filoj, ĉefoj de patrodomoj.",
    "De ĥuŝim li naskigis Abitubon kaj Elpaalon.",
    "La filoj de Elpaal:Eber, Miŝeam, kaj Ŝemer; ĉi tiu konstruis Onon kaj Lodon kaj ĝiajn filinurbojn;",
    "kaj Beria, kaj Ŝema. Ili estis la ĉefoj de patrodomoj de la loĝantoj de Ajalon; ili elpelis la loĝantojn de Gat.",
    "AĤjo, Ŝaŝak, Jeremot,",
    "Zebadja, Arad, Eder,",
    "MiĤael, Jiŝpa, kaj JoĤa estis la filoj de Beria.",
    "Zebadja, Meŝulam, ĥizki, ĥeber,",
    "Jiŝmeraj, Jizlia, kaj Jobab estis la filoj de Elpaal.",
    "Jakim, ZiĤri, Zabdi,",
    "Elienaj, Ciltaj, Eliel,",
    "Adaja, Beraja, kaj Ŝimrat estis la filoj de Ŝimei.",
    "Jiŝpan, Eber, Eliel,",
    "Abdon, ZiĤri, ĥanan,",
    "ĥananja, Elam, Antotija,",
    "Jifdeja, kaj Penuel estis la filoj de Ŝaŝak.",
    "Ŝamŝeraj, ŜeĤarja, Atalja,",
    "Jaareŝja, Elija, kaj ZiĤri estis la filoj de JeroĤam.",
    "Tio estis la ĉefoj de patrodomoj, ĉefoj laŭ siaj generacioj; ili loĝis en Jerusalem.",
    "En Gibeon loĝis:la fondinto de Gibeon-la nomo de lia edzino estis MaaĤa-",
    "kaj lia unuenaskita filo Abdon, Cur, Kiŝ, Baal, Nadab,",
    "Gedor, AĤjo, kaj ZeĤer.",
    "Miklot naskigis Ŝiman. Ankaŭ ili apud siaj fratoj enloĝiĝis en Jerusalem kun siaj fratoj.",
    "Ner naskigis Kiŝon, Kiŝ naskigis Saulon, Saul naskigis Jonatanon, Malki-Ŝuan, Abinadabon, kaj Eŝbaalon.",
    "La filo de Jonatan estis Merib-Baal, kaj Merib-Baal naskigis MiĤan.",
    "La filoj de MiĤa estis Piton, MeleĤ, Taarea, kaj AĤaz.",
    "AĤaz naskigis Jehoadan; Jehoada naskigis Alemeton, Azmaveton, kaj Zimrin; Zimri naskigis Mocan.",
    "Moca naskigis Binean; lia filo estis Rafa, lia filo estis Eleasa, lia filo estis Acel.",
    "Acel havis ses filojn; jen estas iliaj nomoj:Azrikam, BoĤru, Iŝmael, Ŝearja, Obadja, kaj ĥanan. Ĉiuj ĉi tiuj estis la filoj de Acel.",
    "La filoj de lia frato Eŝek:lia unuenaskito estis Ulam, la dua estis Jeuŝ, kaj la tria estis Elifelet.",
    "La filoj de Ulam estis kuraĝaj militistoj, pafarkistoj, kaj ili havis multe da filoj kaj nepoj:cent kvindek. Ĉiuj ĉi tiuj estis el la Benjamenidoj.",
  ],
} as const satisfies Chapter;
