export const chapter4 = {
  chapterTitle: "Ĉapitro 4",
  summary: "",
  verses: [
    "Kiam la malamikoj de Jehuda kaj Benjamen aŭdis, ke la revenintoj el la kaptiteco konstruas templon al la Eternulo, Dio de Izrael,",
    "tiam ili venis al Zerubabel kaj al la ĉefoj de la patrodomoj, kaj diris al ili:Ni ankaŭ deziras konstrui kun vi, ĉar simile al vi ni ankaŭ serĉas vian Dion, kaj al Li ni alportas oferojn de post la tempo de Esar-ĥadon, reĝo de Asirio, kiu venigis nin ĉi tien.",
    "Sed Zerubabel kaj Jeŝua kaj la aliaj ĉefoj de patrodomoj de Izrael diris al ili:Ne estas bone, ke vi kune kun ni konstruu domon por nia Dio; ni solaj konstruos por la Eternulo, Dio de Izrael, kiel ordonis al ni la reĝo Ciro, reĝo de Persujo.",
    "Tiam la popolo de la lando komencis malfortigadi la manojn de la Juda popolo kaj malhelpadi al ĝi en la konstruado.",
    "Kaj ili dungadis kontraŭ ili konsilistojn, por detrui ilian entreprenon, dum la tuta tempo de Ciro, reĝo de Persujo, ĝis la reĝado de Dario, reĝo de Persujo.",
    "Kaj en la tempo de la reĝado de AĤaŝveroŝ, en la komenco de lia reĝado, ili skribis akuzon kontraŭ la loĝantoj de Judujo kaj de Jerusalem.",
    "En la tempo de ArtaĤŝaŝt skribis Biŝlam, Mitredat, Tabeel, kaj la aliaj iliaj kunuloj al ArtaĤŝaŝt, reĝo de Persujo:la letero estis skribita Sirie kaj klarigita Sirie.",
    "ReĤum, konsilisto, kaj Ŝimŝaj, skribisto, skribis unu leteron kontraŭ Jerusalem al ArtaĤŝaŝt, la reĝo, en la sekvanta maniero:",
    "Ni, ReĤum, konsilisto, kaj Ŝimŝaj, skribisto, kaj iliaj aliaj kunuloj, Dinaanoj, AfarsatĤanoj, Tarpelanoj, Afarsanoj, Arkevanoj, Babelanoj,  Ŝuŝananoj, Dehaanoj, Elamanoj,",
    "kaj la aliaj popoloj, kiujn transloĝigis Asnapar, la granda kaj glora, kaj enloĝigis en Samario kaj en la aliaj urboj transriveraj, kaj tiel plu.",
    "Jen estas la teksto de la letero, kiun ili sendis al li:Al la reĝo ArtaĤŝaŝt viaj sklavoj, la transriveranoj, kaj tiel plu.",
    "Estu sciate al la reĝo, ke la Judoj, kiuj foriris de vi kaj venis al ni en Jerusalemon, rekonstruas nun tiun ribeleman kaj malbonan urbon kaj faras muregojn kaj starigas jam la fundamentojn.",
    "Nun estu sciate al la reĝo, ke se tiu urbo estos konstruita kaj la muregoj estos finitaj, tiam ili ne donos tributon nek impostojn nek jarpagon, kaj la reĝa kaso havos malprofiton.",
    "Ĉar ni manĝas salon el la reĝa palaco, kaj ni ne volas vidi ion, kio malhonoras la reĝon, tial ni sendas kaj sciigas al la reĝo,",
    "ke oni serĉu en la kronikoj de viaj patroj, kaj vi trovos en la kronikoj kaj konvinkiĝos, ke tiu urbo estas urbo ribelema kaj malutila por la reĝoj kaj landoj, kaj ke ribeloj estis farataj en ĝi de la plej malproksimaj tempoj, kio estas la kaŭzo, pro kiu tiu urbo estis detruita.",
    "Ni sciigas al la reĝo, ke se tiu urbo estos rekonstruita kaj ĝiaj muregoj estos finitaj, tiam vi poste havos nenian parton en la regiono transrivera.",
    "La reĝo sendis respondon:Al ReĤum, konsilisto, Ŝimŝaj, skribisto, kaj al la aliaj iliaj kunuloj, kiuj loĝas en Samario kaj en la aliaj transriveraj lokoj, pacon kaj saluton.",
    "La letero, kiun vi sendis al ni, estas klare legita antaŭ mi;",
    "kaj mi donis ordonon, ke oni serĉu; kaj oni trovis, ke tiu urbo de malproksima tempo ribeladis kontraŭ la reĝoj, kaj tumultoj kaj defaloj estis farataj en ĝi;",
    "ke potencaj reĝoj estis en Jerusalem kaj posedis la tutan transriveran regionon, kaj tributo, impostoj, kaj jarpagoj estis donataj al ili.",
    "Tial agu laŭ ĉi tiu ordono:malhelpu tiujn homojn en ilia laborado, ke la urbo ne estu rekonstruata, ĝis estos donita ordono de mi.",
    "Kaj estu singardaj, ke vi ne estu malatentaj en tio, por ke ne naskiĝu granda malprofito por la reĝo.",
    "Kiam ĉi tiu letero de la reĝo ArtaĤŝaŝt estis tralegita antaŭ ReĤum, la skribisto Ŝimŝaj, kaj iliaj kunuloj, ili tuj iris en Jerusalemon al la Judoj kaj haltigis ilian laboradon per forta mano.",
    "Tiam ĉesiĝis la laborado ĉe la domo de Dio en Jerusalem; kaj tiu stato daŭris ĝis la dua jaro de reĝado de Dario, reĝo de Persujo.",
  ],
} as const satisfies Chapter;
