export const chapter3 = {
  chapterTitle: "Ĉaptiro 3",
  summary: "",
  verses: [
    "Kaj leviĝis la ĉefpastro Eljaŝib, kaj liaj fratoj, la pastroj, kaj konstruis la Pordegon de Ŝafoj; ili sanktigis ĝin kaj starigis ĝiajn pordojn, ili sanktigis ĝis la turo Mea, ĝis la turo ĥananel.",
    "Apud li konstruis la loĝantoj de JeriĤo, apud ili konstruis Zakur, filo de Imri.",
    "La Pordegon de Fiŝoj konstruis la loĝantoj de Senaa; ili tegis ĝin, kaj starigis ĝiajn pordojn, serurojn, kaj riglilojn.",
    "Apud ili konstruis Meremot, filo de Urija, filo de Hakoc; apud ili konstruis Meŝulam, filo de BereĤja, filo de Meŝezabel; apud ili konstruis Cadok, filo de Baana.",
    "Apud ili konstruis la Tekoaanoj; tamen iliaj eminentuloj ne metis sian kolon sub laboradon por sia sinjoro.",
    "La Malnovan Pordegon konstruis Jojada, filo de PaseaĤ, kaj Meŝulam, filo de Besodja; ili tegis ĝin, kaj starigis ĝiajn pordojn, ĝiajn serurojn, kaj ĝiajn riglilojn.",
    "Apud ili konstruis Melatja, la Gibeonano, kaj Jadon, la Meronotano, la loĝantoj de Gibeon kaj de Micpa, ĝis la seĝo de la transrivera regionestro.",
    "Apud li konstruis Uziel, filo de ĥarhaja, fandisto; apud li konstruis ĥananja, filo de ŝmiraĵisto. Kaj ili restarigis Jerusalemon ĝis la Larĝa Murego.",
    "Apud ili konstruis Refaja, filo de ĥur, estro de duondistrikto de Jerusalem.",
    "Apud ili kaj kontraŭ sia domo konstruis Jedaja, filo de ĥarumaf; apud li konstruis ĥatuŝ, filo de ĥaŝabneja.",
    "Alian parton konstruis Malkija, filo de ĥarim, kaj ĥaŝub, filo de PaĤat-Moab; ankaŭ la Turon de la Fornoj.",
    "Apude konstruis Ŝalum, filo de HaloĤeŝ, estro de duondistrikto de Jerusalem, li kaj liaj filinoj.",
    "La Pordegon de la Valo konstruis ĥanun kaj la loĝantoj de ZanoaĤ; ili konstruis ĝin, kaj starigis ĝiajn pordojn, ĝiajn serurojn, kaj ĝiajn riglilojn, kaj mil ulnojn de la murego ĝis la Pordego de Sterko.",
    "La Pordegon de Sterko konstruis Malkija, filo de ReĤab, estro de la distrikto de Bet-Kerem; li konstruis ĝin, kaj starigis ĝiajn pordojn, serurojn, kaj riglilojn.",
    "La Pordegon de la Fonto konstruis Ŝalun, filo de Kol-ĥoze, estro de la distrikto de Micpa; li konstruis ĝin kaj tegis ĝin, kaj starigis ĝiajn pordojn, serurojn, kaj riglilojn; ankaŭ la muregon ĉe la lageto ŜelaĤ de la reĝa ĝardeno kaj ĝis la ŝtupoj, kiuj iras malsupren de la urbo de David.",
    "Post li konstruis NeĤemja, filo de Azbuk, estro de duondistrikto de Bet-Cur, ĝis la loko kontraŭ la tomboj de David kaj ĝis la farita lageto kaj ĝis la Domo de Herooj.",
    "Post li konstruis la Levidoj:ReĤum, filo de Bani; apude konstruis ĥaŝabja, estro de duondistrikto de Keila, por sia distrikto.",
    "Post li konstruis iliaj fratoj, Bavaj, filo de ĥenadad, estro de duondistrikto de Keila.",
    "Apud li konstruis Ezer, filo de Jeŝua, estro de Micpa, duan parton, ĉe la angulo, kontraŭ la loko, kie oni supreniras al la armilejo.",
    "Post li vigle konstruis BaruĤ, filo de Zakaj, alian parton, de la angulo ĝis la pordo de la domo de Eljaŝib, la ĉefpastro.",
    "Post li konstruis Meremot, filo de Urija, filo de Hakoc, alian parton, de la pordo de la domo de Eljaŝib ĝis la fino de la domo de Eljaŝib.",
    "Post li konstruis la pastroj, kiuj loĝis en la ĉirkaŭaĵo.",
    "Post ili konstruis Benjamen kaj ĥaŝub, kontraŭ sia domo; post ili konstruis Azarja, filo de Maaseja, filo de Ananja, apud sia domo.",
    "Post li konstruis Binuj, filo de ĥenadad, alian parton, de la domo de Azarja ĝis la angulo kaj la rando.",
    "Palal, filo de Uzaj, de kontraŭ la angulo kaj la turo, kiu elstaras el la supra reĝa domo, apud la korto de malliberejo. Post li Pedaja, filo de Paroŝ",
    "(La Netinoj loĝis en Ofel.) ĝis kontraŭ la Pordego de la Akvo oriente, kaj ĝis la elstaranta turo.",
    "Poste konstruis la Tekoaanoj, alian parton, de kontraŭ la granda elstaranta turo ĝis la muro de Ofel.",
    "De post la Pordego de la Ĉevaloj konstruis la pastroj, ĉiu kontraŭ sia domo.",
    "Poste konstruis Cadok, filo de Imer, kontraŭ sia domo; post li konstruis Ŝemaja, filo de ŜeĤanja, gardisto de la Orienta Pordego.",
    "Post li konstruis ĥananja, filo de Ŝelemja, kaj ĥanun, sesa filo de Calaf, alian parton. Post li konstruis Meŝulam, filo de BereĤja, kontraŭ sia ĉambro.",
    "Post li konstruis Malkija, filo de fandisto, ĝis la domo de la Netinoj kaj de la butikistoj, kontraŭ la Pordego de Depono kaj ĝis la tegmenta ĉambro de la angulo.",
    "Inter la tegmenta ĉambro de la angulo kaj la Pordego de Ŝafoj konstruis la fandistoj kaj la butikistoj.",
  ],
} as const satisfies Chapter;
