export const chapter2 = {
  chapterTitle: "Ĉaptiro 2",
  summary: "",
  verses: [
    "Jen estas la filoj de Izrael:Ruben, Simeon, Levi, Jehuda, IsaĤar, Zebulun,",
    "Dan, Jozef, Benjamen, Naftali, Gad, kaj Aŝer.",
    "La filoj de Jehuda:Er, Onan, kaj Ŝela, tri naskiĝis al li de Bat-Ŝua, la Kanaanidino. Er, la unuenaskito de Jehuda, estis malbona antaŭ la Eternulo, kaj Li mortigis lin.",
    "Kaj lia bofilino Tamar naskis al li Perecon kaj ZeraĤon. La nombro de ĉiuj filoj de Jehuda estis kvin.",
    "La filoj de Perec:ĥecron kaj ĥamul.",
    "La filoj de ZeraĤ:Zimri, Etan, Heman, Kalkol, kaj Dara; da ili ĉiuj estis kvin.",
    "La filoj de Karmi:AĤan, kiu malĝojigis Izraelon, pekinte kontraŭ anatemaĵo.",
    "La filoj de Etan:Azarja.",
    "La filoj de ĥecron, kiuj naskiĝis al li:JeraĤmeel, Ram, kaj Kelubaj.",
    "Ram naskigis Aminadabon; Aminadab naskigis NaĤŝonon, princon de la idoj de Jehuda;",
    "NaĤŝon naskigis Salman; Salma naskigis Boazon;",
    "Boaz naskigis Obedon; Obed naskigis Jiŝajon;",
    "Jiŝaj naskigis sian unuenaskiton Eliab, la dua estis Abinadab, la tria estis Ŝimea,",
    "la kvara estis Netanel, la kvina estis Radaj,",
    "la sesa estis Ocem, la sepa estis David.",
    "Iliaj fratinoj estis:Ceruja kaj Abigail. La filoj de Ceruja estis:Abiŝaj, Joab, kaj Asahel-tri.",
    "Abigail naskis Amasan; la patro de Amasa estis Jeter, Iŝmaelido.",
    "Kaleb, filo de ĥecron, naskigis de sia edzino Azuba kaj de Jeriot; jen estas ŝiaj filoj:Jeŝer, Ŝobab, kaj Ardon.",
    "Kiam mortis Azuba, Kaleb prenis al si Efratan, kaj ŝi naskis al li ĥuron.",
    "ĥur naskigis Urin; kaj Uri naskigis Becalelon.",
    "Poste ĥecron envenis al la filino de MaĤir, patro de Gilead; li prenis ŝin, kiam li havis la aĝon de sesdek jaroj, kaj ŝi naskis al li Segubon.",
    "Segub naskigis Jairon, kaj li havis dudek tri urbojn en la lando Gilead.",
    "Sed la Geŝuranoj kaj Sirianoj forprenis de ili la Vilaĝojn de Jair, Kenaton kaj ĝiajn dependaĵojn, sesdek urbetojn. Ĉiuj ĉi tiuj estis la filoj de MaĤir, patro de Gilead.",
    "Post la morto de ĥecron en Kaleb-Efrata la edzino de ĥecron, Abija, naskis al li AŝĤuron, la fondinton de Tekoa.",
    "La filoj de JeraĤmeel, unuenaskito de ĥecron, estis:la unuenaskito Ram, poste Buna, Oren, Ocem, kaj AĤija.",
    "JeraĤmeel havis ankaŭ alian edzinon, ŝia nomo estis Atara; ŝi estis la patrino de Onam.",
    "La filoj de Ram, la unuenaskito de JeraĤmeel, estis:Maac, Jamin, kaj Eker.",
    "La filoj de Onam estis:Ŝamaj kaj Jada. La filoj de Ŝamaj estis:Nadab kaj Abiŝur.",
    "La nomo de la edzino de Abiŝur estis AbiĤail; ŝi naskis al li AĤbanon kaj Molidon.",
    "La filoj de Nadab estis:Seled kaj Apaim. Seled mortis sen infanoj.",
    "La filo de Apaim estis Jiŝei. La filo de Jiŝei estis Ŝeŝan. La filo de Ŝeŝan estis AĤlaj.",
    "La filoj de Jada, frato de Ŝamaj, estis:Jeter kaj Jonatan. Jeter mortis sen infanoj.",
    "La filoj de Jonatan estis:Pelet kaj Zaza. Tio estis la idoj de JeraĤmeel.",
    "Ŝeŝan ne havis filojn, sed nur filinojn. Ŝeŝan havis sklavon Egipton, kies nomo estis JarĤa;",
    "kaj Ŝeŝan donis sian filinon kiel edzinon al sia sklavo JarĤa, kaj ŝi naskis al li Atajon.",
    "Ataj naskigis Natanon; kaj Natan naskigis Zabadon.",
    "Zabad naskigis Eflalon; kaj Eflal naskigis Obedon.",
    "Obed naskigis Jehun, kaj Jehu naskigis Azarjan.",
    "Azarja naskigis ĥelecon; kaj ĥelec naskigis Eleasan.",
    "Eleasa naskigis Sismajon; kaj Sismaj naskigis Ŝalumon.",
    "Ŝalum naskigis Jekamjan; kaj Jekamja naskigis Eliŝaman.",
    "La filoj de Kaleb, frato de JeraĤmeel:lia unuenaskito Meŝa, kiu estis la fondinto de Zif; kaj la filoj de Mareŝa, fondinto de ĥebron.",
    "La filoj de ĥebron:KoraĤ, TapuaĤ, Rekem, kaj Ŝema.",
    "Ŝema naskigis RaĤamon, fondinton de Jorkeam; kaj Rekem naskigis Ŝamajon.",
    "La filo de Ŝamaj estis Maon; kaj Maon estis la fondinto de Bet-Cur.",
    "Kaj Efa, kromvirino de Kaleb, naskis ĥaranon, Mocan, kaj Gazezon; kaj ĥaran naskigis Gazezon.",
    "La filoj de Jedaj estis:Regem, Jotam, Geŝan, Pelet, Efa, kaj Ŝaaf.",
    "MaaĤa, kromvirino de Kaleb, naskis Ŝeberon kaj TirĤanan.",
    "Ŝi naskis ankaŭ Ŝaafon, la fondinton de Madmana, Ŝevan, la fondinton de MaĤbena kaj la fondinton de Gibea. La filino de Kaleb estis AĤsa.",
    "Tio estis la idoj de Kaleb:la filo de ĥur, unuenaskito de Efrata:Ŝobal, fondinto de Kirjat-Jearim,",
    "Salma, fondinto de Bet-LeĤem, ĥaref, fondinto de Bet-Gader.",
    "Ŝobal, fondinto de Kirjat-Jearim, havis la filojn:Haroe, duono de la MenuĤot.",
    "La familioj de Kirjat-Jearim estis:la Jetridoj, la Putidoj, la Ŝumatidoj, la Miŝraidoj. De ĉi tiuj devenis la Coreaidoj kaj la Eŝtaolidoj.",
    "La idoj de Salma:la Bet-LeĤemanoj, la Netofaanoj, la Atrotanoj de la domo de Joab, la duono de la ManaĤatanoj, la Coreanoj;",
    "kaj la familioj de la skribistoj, kiuj loĝis en Jabec, la Tiratidoj, Ŝimeatidoj, kaj SuĤatidoj; tio estis la Kenidoj, kiuj devenis de ĥamat, la fondinto de Bet-ReĤab.",
  ],
} as const satisfies Chapter;
