export const chapter5 = {
  chapterTitle: "Ĉaptiro 5",
  summary: "",
  verses: [
    "Jen estas la libro de naskoj de Adam. Kiam Dio kreis la homon, Li faris lin laŭ la bildo de Dio;",
    "kiel viron kaj virinon Li kreis ilin, kaj Li benis ilin kaj donis al ili la nomon Homo en la tago de ilia naskiĝo.",
    "Kaj Adam vivis cent tridek jarojn, kaj al li naskiĝis filo laŭ lia bildo kaj simileco, kaj li donis al li la nomon Set.",
    "Kaj Adam vivis, post kiam naskiĝis al li Set, okcent jarojn, kaj naskiĝis al li filoj kaj filinoj.",
    "Kaj la tuta vivo, kiun travivis Adam, estis naŭcent tridek jaroj, kaj li mortis.",
    "Kaj Set vivis cent kvin jarojn, kaj naskiĝis al li Enoŝ.",
    "Kaj Set vivis, post kiam naskiĝis al li Enoŝ, okcent sep jarojn, kaj naskiĝis al li filoj kaj filinoj.",
    "Kaj la tuta vivo de Set estis naŭcent dek du jaroj, kaj li mortis.",
    "Kaj Enoŝ vivis naŭdek jarojn, kaj naskiĝis al li Kenan.",
    "Kaj Enoŝ vivis, post kiam naskiĝis al li Kenan, okcent dek kvin jarojn, kaj naskiĝis al li filoj kaj filinoj.",
    "Kaj la tuta vivo de Enoŝ estis naŭcent kvin jaroj, kaj li mortis.",
    "Kaj Kenan vivis sepdek jarojn, kaj naskiĝis al li Mahalalel.",
    "Kaj Kenan vivis, post kiam naskiĝis al li Mahalalel, okcent kvardek jarojn, kaj naskiĝis al li filoj kaj filinoj.",
    "Kaj la tuta vivo de Kenan estis naŭcent dek jaroj, kaj li mortis.",
    "Kaj Mahalalel vivis sesdek kvin jarojn, kaj naskiĝis al li Jared.",
    "Kaj Mahalalel vivis, post kiam naskiĝis al li Jared, okcent tridek jarojn, kaj naskiĝis al li filoj kaj filinoj.",
    "Kaj la tuta vivo de Mahalalel estis okcent naŭdek kvin jaroj, kaj li mortis.",
    "Kaj Jared vivis cent sesdek du jarojn, kaj naskiĝis al li ĥanoĤ.",
    "Kaj Jared vivis, post kiam naskiĝis al li ĥanoĤ, okcent jarojn, kaj naskiĝis al li filoj kaj filinoj.",
    "Kaj la tuta vivo de Jared estis naŭcent sesdek du jaroj, kaj li mortis.",
    "Kaj ĥanoĤ vivis sesdek kvin jarojn, kaj naskiĝis al li MetuŝelaĤ.",
    "Kaj ĥanoĤ iradis kun Dio, post kiam naskiĝis al li MetuŝelaĤ, tricent jarojn, kaj naskiĝis al li filoj kaj filinoj.",
    "Kaj la tuta vivo de ĥanoĤ estis tricent sesdek kvin jaroj.",
    "Kaj ĥanoĤ iradis kun Dio; kaj li malaperis, ĉar Dio lin prenis.",
    "Kaj MetuŝelaĤ vivis cent okdek sep jarojn, kaj naskiĝis al li LemeĤ.",
    "Kaj MetuŝelaĤ vivis, post kiam naskiĝis al li LemeĤ, sepcent okdek du jarojn, kaj naskiĝis al li filoj kaj filinoj.",
    "Kaj la tuta vivo de MetuŝelaĤ estis naŭcent sesdek naŭ jaroj, kaj li mortis.",
    "Kaj LemeĤ vivis cent okdek du jarojn, kaj naskiĝis al li filo.",
    "Kaj li donis al li la nomon Noa, dirante: Ĉi tiu konsolos nin en niaj faroj kaj en la laboroj de niaj manoj sur la tero, kiun la Eternulo malbenis.",
    "Kaj LemeĤ vivis, post kiam naskiĝis al li Noa, kvincent naŭdek kvin jarojn, kaj naskiĝis al li filoj kaj filinoj.",
    "Kaj la tuta vivo de LemeĤ estis sepcent sepdek sep jaroj, kaj li mortis.",
    "Kaj Noa havis la aĝon de kvincent jaroj, kaj al Noa naskiĝis Ŝem, ĥam, kaj Jafet.",
  ],
} as const satisfies Chapter;
