export const chapter6 = {
  chapterTitle: "Ĉapitro 6",
  chapterSubtitle:
    "Kiel rivelitaj al Jozefo Smith la Profeto en decembro 1830--Daŭrigo.",
  verses: [
    "KAJ Adam aŭskultis al la vo o de Dio, kaj vokis al siaj filoj, ke ili pentu.",
    "Kaj denove Adam ekkonis sian edzinon, kaj ŝi naskis filon, kaj li donis al li la nomon Set. Kaj Adam gloris la nomon deDio; ar li diris: Dio metis al mi alian semonanstataŭ Habel, kiun mortigis Kain.",
    "Kaj Dio rivelis sin al Set, kaj li ne ribelis, sed alportis akceptindan donacoferon, simile al lia frato Habel. Kaj al li ankaŭ naski is filo, kaj li donis al li la nomon Enoŝ.",
    "Kaj tiam i tiuj homoj komencis alvokadi la nomon de la Eternulo, kaj la Eternulo benis ilin;",
    "Kaj oni ekkonservis memorlibron, en kiu oni skribis, per la lingvo de Adam, ar oni donis in al iuj, kiuj vokis al Dio, por skribi per spirito de inspirigo;",
    "Kaj ili instruis al siaj infanoj legi kaj skribi, havante lingvon, kiu estis pura kaj nekoruptita.",
    "Nun i tiu sama Pastreco, kiu estis en la komenco, estos ankaŭ en la fino de la mondo.",
    "Adam diris i tiun profetaĵon, emociate de la Sankta Spirito, kaj oni daŭrigis genealogian registron pri la infanoj de Dio. Kaj tiu estis la libro de naskoj de Adam, kiu diris: Kiam Dio kreis la homon, li faris lin laŭ la bildo de Dio;",
    "Laŭ la bildo de sia propra korpo, kiel viron kaj virinon li kreis ilin, kaj benis ilin, kaj donis al ili la nomon Homo en la tago de ilia naski o, kiam ili fari is vivaj animoj en la lando sur la piedbenketo de Dio.",
    "Kaj Adam vivis cent tridek jarojn, kaj al li naski is filo laŭ lia bildo kaj simileco, kaj li donis al li la nomon Set.",
    "Kaj Adam vivis, post kiam naski is al li Set, okcent jarojn, kaj naski is al li multaj filoj kaj filinoj;",
    "Kaj la tuta vivo, kiun travivis Adam, estis naŭcent tridek jaroj, kaj li mortis.",
    "Set vivis cent kvin jarojn, kaj naski is al li Enoŝ, kaj li profetadis sian tutan vivon, kaj instruis la vojojn de Dio al sia filo Enoŝ; pro tio ankaŭ Enoŝ profetis.",
    "Kaj Set vivis, post kiam naski is al li Enoŝ, okcent sep jarojn, kaj naski is al li multaj filoj kaj filinoj.",
    "Kaj la homidoj estis multnombraj sur la tuta lando. Kaj en tiuj tagoj Satano regis kun multa forto super la homoj, kaj furiozis en iliaj koroj; kaj el tio venis militoj kaj verŝo de sango; kaj la mano de viro estis kontraŭ lia propra frato, mortigante, pro sekretaj faroj, ser ante potencon.",
    "La tuta vivo de Set estis naŭcent dek du jaroj, kaj li mortis.",
    "Kaj Enoŝ vivis naŭdek jarojn, kaj naski is al li Kenan. Kaj Enoŝ kaj la cetera popolo de Dio venis el la lando, kiu estis nomita Öulon, kaj lo is en lando de la promeso, al kiu li donis la nomon de sia filo, kiun li nomis Kenan.",
    "Kaj Enoŝ vivis, post kiam naski is al li Kenan, okcent dek kvin jarojn, kaj naski is al li multaj filoj kaj filinoj.",
    "Kaj Kenan vivis sepdek jarojn, kaj naski is al li Mahalalel. Kaj Kenan vivis, post kiam naski is al li Mahalalel, okcent kvardek jarojn, kaj naski is al li filoj kaj filinoj. Kaj la tuta vivo de Kenan estis naŭdek dek jaroj, kaj li mortis.",
    "Kaj Mahalalel vivis sesdek kvin jarojn, kaj naski is al li Jared. Kaj Mahalalel vivis, post kiam naski is al li Jared, okcent tridek jarojn, kaj naski is al li filoj kaj filinoj. Kaj la tuta vivo de Mahalalel estis okcent naŭdek kvin jaroj, kaj li mortis.",
    "Kaj Jared vivis cent sesdek du jarojn, kaj naski is al li ano¡, okcent jarojn, kaj naski is al li filoj kaj filinoj. Kaj Jared instruis ano¡on pri iuj vojoj de Dio.",
    "Kaj i tio estas la genealogio de la filoj de Adam, kiu estis la filo de Dio, kun kiu Dio mem interparolis.",
    "Kaj ili estis predikantoj de justeco, kaj parolis kaj profetis, kaj vokis al iuj homoj ie, ke ili pentu; kaj la kredo estis instruata al la homidoj.",
    "Kaj okazis, ke la tuta vivo de Jared estis naŭcent sesdek du jaroj, kaj li mortis.",
    "Kaj ano¡ vivis sesdek kvin jarojn, kaj naski is al li Metuŝela¡.",
    "Kaj okazis, ke ano¡ voja is en la lando, inter la popolo; kaj, dum li voja is, la Spirito de Dio mallevi is el la ielo, kaj restis sur li.",
    "Kaj li aŭdis vo on el la elo, kiu diris: ano¡ mia filo, profetu al i tiu popolo, kaj diru al ili: Pentu, ar jenon diras la Eternulo: Mi estas kolera kontraŭ i tiu popolo, kaj mia arda kolero ekbrulis kontraŭ ili; ar iliaj koroj malmoli is, kaj iliaj oreloj aŭdas malklare, kaj iliaj okuloj ne povas vidi malproksimen;",
    "Kaj dum i tiuj multaj generacioj, ĉe de la tago, kiam mi kreis ilin, ili devoji is, kaj malkonfesis min, kaj ser is siajn konsilojn en la mallumo; kaj en siaj abomenaĵoj ili elpensis la murdon, kaj ne obeis la ordonojn, kiujn mi donis al ilia patro, Adam.",
    "sekve, ili rompis siajn ĵurojn, kaj, per siaj blasfemoj, ili venigis al si la morton; kaj inferon mi preparis por ili, se ili ne pentos;",
    "Kaj tio estas dekreto, kiun mi dissendis en la komenco de la mondo, el mia propra buŝo, jam de ia kreo, kaj per la buŝoj de miaj servantoj, viaj patroj, mi dekretis in, ĉe kiel i estos dissendata en la mondo, is iaj finoj.",
    "Kaj, aŭdinte tiujn vortojn, ano¡ sin sternis al la tero, antaŭ la Eternulo, kaj parolis antaŭ la Eternulo, dirante: Kial okazis, ke mi trovis pla on en viaj okuloj, kvankam mi estas nur junulo, kaj iuj homoj malamas min; ar mi havas nelertan buŝon; kial mi estas via servanto?",
    "Kaj la Eternulo diris al ano¡: Eliru kaj faru, kiel mi ordonis al vi, kaj neniu homo trapikos vin. Malfermu vian buŝon, kaj i estos plenigita, kaj mi donos al vi parolpovon, ar iu karno estas en miaj manoj, kaj mi faros tion, kio ŝajnos al mi bona.",
    "Diru al i tiu popolo: Elektu hodiaŭ servi la Eternulon, kiu kreis vin.",
    "Jen mia Spirito estas sur vi, pro kio mi pravigos iujn viajn vortojn; kaj la montoj forkuros antaŭ vi, kaj la riveroj deturni os de siaj fluejoj; kaj vi restos e mi, kaj mi e vi; do iradu kun mi.",
    "Kaj la Eternulo parolis al ano¡, kaj diris al li: Ömiru per koto viajn okulojn, kaj lavu ilin, kaj vi vidos. Kaj li tion faris.",
    "Kaj li vidis la spiritojn, kiujn Dio kreis; kaj li vidis ankaŭ aĵojn, kiuj ne estis videblaj al la natura okulo; kaj de tiam oni diris tra la lando: La Eternulo estigis antaŭvidiston por sia popolo.",
    "Kaj okazis, ke ano¡ eliris tra la lando, inter la popolo, starante sur la montetoj kaj altaj lokoj, kaj kriadis per laŭta vo o, atestante kontraŭ iaj faroj; kaj iuj homoj ofendi is pro li.",
    "Kaj ili alvenis por aŭdi lin, sur la altajn lokojn, dirante al la tendgardistoj: Atendu i tie kaj prizorgu la tendojn dum ni iros tien por vidi la antaŭvidiston, ar li profetas, kaj okazas stranga afero en la lando; sova a viro venis inter nin.",
    "Kaj okazis, kiam ili aŭdis lin, ke neniu metis la manon sur lin; ar timo venis al iuj, kiuj aŭdis lin; ar li iradis kun Dio.",
    "Kaj venis al li viro, kies nomo estis Mahija¡, kaj diris al li: Diru al ni klare, kiu vi estas, kaj de kie vi venis?",
    "Kaj li diris al ili: Mi venis el la lando de Kenan, la lando de miaj patroj, lando de justeco is hodiaŭ. Kaj mia patro instruis min pri iuj vojoj de Dio.",
    "Kaj okazis, dum mi voja is de la lando de Kenan, laŭlonge de la maro orienten, mi vidis vizion; kaj jen la ielon mi vidis, kaj la Eternulo parolis kun mi, kaj donis al mi ordonon; pro kio, por obei la ordonon, mi eldiras i tiujn vortojn.",
    "Kaj ano¡ daŭrigis sian paroladon, dirante: La Eternulo, kiu parolis kun mi, tiu sama estas la Dio de la ielo, kaj la estas mia Dio, kaj via Dio, kaj vi estas miaj fratoj, kaj kial vi konsilas vin mem, kaj malkonfesas la Dion de la ielo?",
    "La ielon li kreis; la tero estas lia piedbenketo; kaj ia fundamento estas lia. Jen li metis in; li venigis multe da homoj sur in.",
    "Kaj la morto venis al niaj patroj; tamen ni konas ilin, kaj ne povas malkonfesi tion, kaj e la unuan el iuj ni konas e Adamon.",
    "Ĉar memorlibron ni skribis inter ni, laŭ la modelo donita per la fingro de Dio; kaj ĉi estas donita en nia propra lingvo.",
    "Kaj, dum ano¡ eldiris la vortojn de Dio, la popolo tremis, kaj ne povis stari antaŭ li.",
    "Kaj li diris al ili: Pro tio, ke Adam falis, ni estas; kaj per lia falo venis la morto; kaj ni fari is partoprenantoj de mizero kaj malfeliĉo.",
    "Jen Satano venis inter la homidojn, kaj tromplogis ilin adori lin; kaj la homoj fari is karnaj, laŭsentaj, kaj demonaj, kaj estas forbaritaj de antaŭ Dio.",
    "Sed Dio sciigis al niaj patroj, ke iuj homoj devas penti.",
    "Kaj li vokis al nia patro Adam per sia propra vo o, dirante: Mi estas Dio; mi kreis la mondon, kaj la homojn antaŭ ol ili estis en karno.",
    "Kaj li ankaŭ diris al li: Se vi turnos vin al mi, kaj aŭskultos mian vo on, kaj kredos, kaj pentos pri iuj viaj le orompoj, kaj bapti os, e en akvo, en la nomo de mia Solenaskita Filo, kiu estas plena de graco kaj vero, kiu estas Jesuo Kristo, la sola nomo kiu estos donita sub la ielo, per kiu savo venos al la homidoj, vi ricevos la donacon de la Sankta Spirito, petante ion en lia nomo, kaj ion, kion vi petos, vi ricevos.",
    "Kaj nia patro Adam parolis al la Eternulo, kaj diris: Kial homoj devas penti kaj bapti i en akvo? Kaj la Eternulo diris al Adam: Jen mi pardonis al vi vian le orompon en la Edena ardeno.",
    "De tio disvasti is la diraĵo inter la popolo: Ke la Filo de Dio akiris pardonon por la origina kulpo, kaj sekve pri la pekoj de la gepatroj ne respondecas la kapoj de la infanoj, ĉar ili estas puraj de la kreo de la mondo.",
    "Kaj la Eternulo parolis al Adam, dirante: Kvankam viaj infanoj estas konceptitaj en peko, tamen, kiam ili komencas plia i i, la peko koncipi as en iliaj koroj, kaj ili gustumas la amarecon por ke ili sciu ŝati la bonon.",
    "Kaj al ili estas donata scii bonon de malbono; pro kio ili havas decidpovon por si mem, kaj mi donis al vi plian le on kaj plian ordonon.",
    "Pro tio instruu al viaj infanoj, ke iuj homoj, ie, devos penti, aŭ ili neniel povos heredi la regnon de Dio, ar nenio malpura povos lo i tie, aŭ lo i antaŭ li; ar, en la lingvo de Adam, Homo de Sankteco estas lia nomo, kaj la nomo de lia Solenaskito estas la Filo de Homo, e Jesuo Kristo, justa Ju anto, kiu venos, kiam la tempo estos matura.",
    "Tial mi donas al vi ordonon, instrui ĉi tiujn aferojn malkaŝe al viaj infanoj, dirante:",
    "Ke pro rompo de le o venas la falo, kiu falo venigas la morton, kaj pro tio, ke vi naski is en la mondon per akvo, kaj per la Spirito, kaj esti purigita per sango, e la sango de mia Solenaskito, por ke vi estu sanktigita el ia peko, kaj uu la vortojn de eterna vivo en ĉi tia mondo, kaj eterna vivo en la mondo venonta, e senmorta gloro;",
    "ar per la akvo vi obeas la ordonon; per la Spirito vi estas pravigita, kaj per la sango vi estas sanktigita;",
    "Tial estas donitaj resti inter vi: la kroniko de la ielo; la Konsolanto; la pacaj aferoj de la senmorta gloro; la vero de io; tiu, kiu vivigas ion, kiu donas vivon al io; tiu, kiu scias ion, kaj havas iun potencon laŭ sa o, kompato, vero, justeco, kaj ju povo.",
    "Kaj nun, jen, mi diras al vi: Tio estas la plano de savi o por iuj homoj, per la sango de mia Solenaskito, kiu venos, kiam la tempo estos matura.",
    "Kaj jen, io havas sian bildon, kaj io estas kreita kaj farita por atesti pri mi, kaj tio, kio estas portempa, kaj tio, kio estas spirita; tio, kio estas supre en la ielo, kaj tio, kio estas sur la tero, kaj tio, kio estas en la tero, kaj tio, kio estas sub la tero, kaj supre kaj sube: io atestas pri mi.",
    "Kaj okazis, kiam la Eternulo parolis kun Adam, nia patro, ke Adam kriis al la Eternulo, kaj li estis forkaptita de la Spirito de la Eternulo, kaj portita malsupren en la akvon, kaj sternita sub la akvo, kaj elprenita el la akvo.",
    "Kaj tiamaniere li estis baptita, kaj la Spirito de Dio mallevi is sur lin, kaj tiel li estis naskita de la Spirito, kaj fari is vivigita en la interna homo.",
    "Kaj li aŭdis vo on el la ielo, kiu diris: Vi estas baptita per fajro, kaj de la Sankta Spirito. Jen la kroniko de la Patro, kaj la Filo, de nun kaj por eterne;",
    "Kaj vi estas laŭ la maniero de tiu, kiu estis sen komenco de tagoj aŭ fino de jaroj, de tuta eterneco is tuta eterneco.",
    "Jen, vi estas unu en mi, filo de Dio; kaj tiel iuj povas fari i miaj filoj. Amen.",
  ],
} as const satisfies Chapter;
