export const chapter4 = {
  chapterTitle: "Ĉapitro 4",
  chapterSubtitle:
    "Kiel rivelitaj al Jozefo Smith la Profeto en decembro 1830--Daŭrigo.",
  verses: [
    "Kaj mi, la Eternulo, parolis al Moseo, dirante: Tiu Satano, al kiu vi ordonis en la nomo de mia Solenaskito, estas tiu, kiu estis de la komenco, kaj li venis antaŭ min, dirante: Jen ĉi tie mi; sendu min; mi estos via folo, kaj mi savos la tutan homaron, tiel ke ne unu animo estos perdita, kaj mi certe faros tion; pro tio donu al mi vian gloron.",
    "Sed, jen, mia Filo, la Amata, kiu estis mia Amato kaj Elektito de la komenco, diris al mi: Patro, plenumiĝu via volo, kaj la gloro estu via por eterne.",
    "Sekve, pro tio, ke Satano ribelis kontraŭ mi, kaj volis detrui la libervolan agpovon de la homo, kiun mi, la Eternulo, donis al li, kaj ankaŭ ke mi donu al li mian propran potencon; per la potenco de mia Solenaskito mi faligis lin;",
    "Kaj li fariĝis Satano, jes, eĉ la diablo, la patro de ĉiuj mensogoj, por trompi kaj blindigi la homojn, kaj por konduki ilin por plenumi sian volon kiel kaptitojn, eĉ ĉiujn el tiuj, kiuj ne volis aŭskulti mian voĉon.",
    "Kaj la serpento estis pli ruza, ol ĉiuj kampaj bestoj, kiujn kreis mi, la Eternulo.",
    "Kaj Satano incitis la koron de la serpento, (ĉar li forlogis multajn post si), kaj li volis ankaŭ tromplogi Evan, ĉar li ne konis la intencon de Dio, kaj sekve li provis detrui la mondon.",
    "Kaj li diris al la virino: Ĉu Dio diris, ke vi ne manĝu de ĉiuj arboj de la ĝardeno? (Kaj li parolis per la buŝo de la serpento.)",
    "Kaj la virino diris al la serpento: La fruktojn de la arboj de la gardeno ni povas manĝi;",
    "Sed pri la Fruktoj de la arbo, kiu estas en la mezo de la ĝardeno, Dio diris: Ne manĝu ion de ili kaj ne tuŝu ilin, por ke vi ne mortu.",
    "Kaj la serpento diris al la virino: Ne, vi ne mortos;",
    "Sed Dio scias, ke en la tago, en kiu vi manĝos ion de ili, malfermiĝos viaj okuloj kaj vi estos kiel Dio, vi scios bonon kaj malbonon.",
    "Kaj la virino vidis, ke la arbo estas bona por manĝi kaj ĝi fariĝis ĉarma por la okuloj, kaj la arbo estas dezirinda por saĝigi ŝin; kaj ŝi prenis de ĝiaj fruktoj, kaj ŝi manĝis, kaj ŝi donis kune ankaŭ al sia edzo, kaj li manĝis.",
    "Kaj malfermiĝis la okuloj de ili ambaŭ, kaj ili sciiĝis, ke ili estis nudaj. Kaj ili kunkudris foliojn de figarbo kaj faris al si zonaĵojn.",
    "Kaj ili aŭdis la voĉon de Dio la Eternulo, marŝante en la ĝardeno dum la malvarmeto de la tago; kaj Adam kaj lia edzino foriris por kaŝiĝi de Dio la Eternulo inter la arboj de la gardeno.",
    "Kaj mi, la Eternulo, vokis Adamon, kaj diris al li: Kien vi iras?",
    "Kaj tiu diris: Vian voĉon mi aŭdis en la ĝardeno, kaj mi ektimis, ĉar mi vidis, ke mi estis nuda, kaj mi kaŝis min.",
    "Kaj mi, la Eternulo, diris al Adam: Kiu diris al vi, ke vi estas nuda? Ĉu vi ne manĝis de la arbo, pri kiu mi ordonis al vi, ke vi ne manĝu de ĝi; ke, manĝinte, vi certe mortos?",
    "Kaj la viro diris: La virino, kiun vi donis al mi, kaj ordonis, ke ŝi restu kun mi, ŝi donis al mi de la frukto de la arbo, kaj mi manĝis.",
    "Kaj mi, la Eternulo, diris al la virino: Kial vi tion faris? Kaj la virino diris: La serpento tromplogis min, kaj mi manĝis.",
    "Kaj mi, la Eternulo, diris al la serpento: Ĉar vi tion faris, tial vi estos malbenita inter ĉiuj brutoj kaj inter ĉiuj bestoj de la kampo; sur via ventro vi irados kaj teron vi manĝados dum via tuta vivo;",
    "Kaj mi metos malamikecon inter vi kaj la virino kaj inter via idaro kaj ŝia idaro; ĝi frapados vian kapon, kaj vi pikados ĝian kalkanon.",
    "Al la virino mi, la Eternulo, diris: Mi multigos viajn suferojn dum via gravedeco. En doloro vi naskados infanojn; kaj al via viro vi vin tiros, kaj li regos super vi.",
    "Kaj al Adam mi, la Eternulo, diris: Ĉar vi obeis la voĉon de via edzino, kaj vi manĝis de la frukto de la arbo, pri kiu mi ordonis al vi, dirante, ke vi ne manĝu de ĝi, tial malbenita estos la tero pro vi; kun suferoj vi manĝados de ĝi dum via tuta vivo.",
    "Kaj dornojn kaj pikaĵojn ĝi kreskigos por vi, kaj vi manĝados herbojn de kampo.",
    "Per la ŝvito de via vizaĝo vi manĝados panon, ĝis vi revenos en la teron-- ĉar vi nepre mortos--ĉar el ĝi vi estis prenita: ĉar vi estis polvo kaj refariĝos polvo.",
    "Kaj Adam donis al sia edzino la nomon Eva, ĉar ŝi estis patrino de ĉiuj vivantoj; ĉar tiel mi, la Eternulo, nomis la unuan el ĉiuj virinoj, kiuj estas multaj.",
    "Kaj mi, la Eternulo, faris por Adam kaj ankaŭ por lia edzino vestojn el felo, kaj mi vestis ilin.",
    "Kaj mi, la Eternulo, diris al mia Solenaskito: Jen la homo fariĝis kiel unu el ni, sciante bonon kaj malbonon; nun eble li etendos sian manon kaj prenos ankaŭ de la arbo de vivo, kaj manĝos kaj vivos eterne.",
    "Pro tio mi, la Eternulo, eligos lin el la Edena ĝardeno, por ke li prilaboradu la teron, el kiu li estis prenita.",
    "Ĉar, kiel mi, la Eternulo, vivas, eĉ tiel miaj vortoj ne revenos al mi vane, ĉar, elirante el mia buŝo, ili devas plenumiĝi.",
    "Mi do elpelis la homon, kaj mi lokis oriente antaŭ la Edena ĝardeno kerubon kaj turniĝantan flaman glavon, por gardi la vojon al la arbo de vivo.",
    "(Kaj tiaj estas la vortoj, kiujn mi parolis al mia servanto Moseo, kaj ili estas veraj eĉ kiel mi deziras; kaj mi diris ilin al vi. Zorgu, ke vi montru ilin al neniu ĝis mi ordonos vin, krom al tiuj, kiuj kredas. Amen.)",
  ],
} as const satisfies Chapter;
