export const chapter1 = {
  chapterTitle: "Ĉapitro 1",
  chapterSubtitle: "Kiel rivelitaj al Jozefo Smith la Profeto en junio 1830.",
  verses: [
    "La vortoj de Dio, kiujn li parolis al Moseo en tempo, kiam Moseo estis forlevita al treege alta monto,",
    "Kaj li vidis Dion, vizaĝon kontraŭ vizaĝo, kaj li parolis kun li, kaj la gloro de Dio estis sur Moseo; pro tio Moseo povis elteni lian ĉeeston.",
    "Kaj Dio parolis al Moseo, dirante: Jen, mi estas la Eternulo, la Plejpotenca, kaj Senfina estas mia nomo; ĉar mi estas sen komenco de tagoj aŭ fino de jaroj; kaj ĉu tio ne estas senfina?",
    "Kaj, jen, vi estas mia filo; sekve rigardu, kaj mi montros al vi la farojn de miaj manoj; sed ne ĉiujn, ĉar miaj faroj estas senfinaj, kaj ankaŭ miaj vortoj, ĉar ili neniam ĉesas.",
    "Pro tio, neniu homo povas vidi ĉiujn el miaj faroj se li ne vidas mian tutan gloron; kaj neniu homo povas vidi mian tutan gloron, kaj poste resti en la karno sur la tero.",
    "Kaj mi havas laboron por vi, Moseo, mia filo; kaj vi estas laŭ la bildo de mia Solenaskito; kaj mia Solenaskito estas kaj estos la Savonto, ĉar li estas plena de graco kaj vero; sed ne ekzistas alia dio krom mi, kaj ĉiuj ĵoj ĉeestas ĉe mi, ĉar mi konas ĉiujn el ili.",
    "Kaj nun, jen unu afero, kiun mi montru al vi, Moseo, mia filo; ĉar vi estas en la mondo, kaj nun mi montru ĝin al vi.",
    "Kaj okazis, ke Moseo rigardis, kaj vidis la mondon, sur kiu li estis kreita; kaj Moseo rigardis la mondon kaj ĝiajn limojn, kaj ĉiujn homidojn kiuj estas, kaj estis, kreitaj; pri tio li ege miris kaj meditis.",
    "Kaj Dio foriris de antaŭ Moseo, tiel ke lia gloro ne estis sur Moseo, kaj Moseo estis lasita sola. Kaj, estante lasita sola, li falis al la tero.",
    "Kaj okazis, ke multaj horoj pasis antaŭ ol Moseo denove ricevis sian naturan forton kiel viro; kaj li diris al si: Nun, pro tiu kialo mi scias, ke la homo estas nenio, kiun fakton mi neniam supozis.",
    "Sed nun miaj propraj okuloj vidis Dion; sed ne miaj okuloj naturaj, sed miaj okuloj spiritaj, ĉar miaj okuloj naturaj ne povus vidi; ĉar mi sekiĝus kaj mortus antaŭ li; sed lia gloro estis sur mi; kaj mi vidis lian vizaĝon, ĉar mi estis aliformita antaŭ li.",
    "Kaj okazis post kiam Moseo diris ĉi tiujn vortojn, ke jen Satano venis por tenti lin, dirante: Moseo, filo de homo, adoru min.",
    "Kaj okazis, ke Moseo rigardis Satanon kaj diris: Kiu estas vi? Ĉar jen mi estas filo de Dio, laŭ la bildo de lia Solenaskito; kaj kie estas via gloro, ke mi adoru vin?",
    "Ĉar, komprenu, mi ne povus rigardi Dion se lia gloro ne estus veninta sur min kaj mi ne estus fortigita antaŭ li. Sed mi povas rigardi vin kiel naturan homon. Ĉu tio ne estas vera?",
    "Benata estu la nomo de mia Dio, ĉar lia Spirito ne tute foriris de mi, aŭ kie alie estas via gloro, ĉar por mi ĝi estas mallumo? Kaj mi povas juĝi inter vi kaj Dio; ĉar Dio diris al mi: Adoru Dion, ĉar nur lin vi servu.",
    "Foriru de ĉi tie, Satano; ne tromplogu min; ĉar Dio diris al mi: Vi estas laŭ la bildo de mia Solenaskito.",
    "Kaj li ankaŭ donis al mi ordonojn, kiam li vokis al mi el la flamanta arbetaĵo, dirante: Voku al Dio en la nomo de mia Solenaskito, kaj adoru min.",
    "Kaj denove Moseo diris: mi ne ĉeso voki al Dio, mi havas aliajn aferojn por demandi al li: ĉar lia gloro estis sur mi, pro tio mi povas juĝi inter li kaj vi. Foriru de ĉi tie, Satano.",
    "Kaj, kiam Moseo diris tiujn vortojn, Satano ekkriis per laŭta voĉo, kaj ŝire resonis sur la tero, kaj ordonis, dirante: mi estas la Solenaskito, adoru min.",
    "Kaj okazis, ke Moseo ektimegis; kaj, ektimante, li vidis la amarecon de la infero. Tamen, vokinte la nomon de Dio, li ricevis forton, kaj li ordonis, dirante: Foriru de mi, Satano, ĉar mi adoros nur ĉi tiun unikan Dion, kiu estas la Dio de la gloro.",
    "Kaj nun Satano ektremis, kaj la tero skuiĝis; kaj Moseo ricevis forton, kaj vokis al Dio, dirante: En la nomo de la Solenaskito, foriru de ĉi tie, Satano.",
    "Kaj okazis, ke Satano ekkriis per laŭta voĉo, kun plorado, kaj veado, kaj grincado de dentoj; kaj li foriris de tie, eĉ de antaŭ Moseo, tiel ke li jam ne vidis lin.",
    "Kaj nun pri ĉi tiu afero Moseo atestis; sed pro la malboneco la atesto ne troviĝas inter la homidoj.",
    "Kaj okazis, kiam Satano foriris de antaŭ Moseo, ke Moseo levis siajn okulojn al la ĉielo, plenigite per la Sankta Spirito, kiu atestas pri la Patro kaj la Filo;",
    "Kaj vokante la nomon de Dio, li revidis lian gloron, ĉar ĝi estis sur li; kaj li aŭdis voĉon, kiu diris: Benita estas vi, Moseo, ĉar mi, la Plejpotenca, elektis vin, kaj vi estos farita pli forta ol multaj akvoj; ĉar ili obeos vian ordonon kvazaŭ vi estus Dio.",
    "Kaj, jen, mi estas kun vi, eĉ ĝis la fino de viaj tagoj; ĉar vi liberigos el la sklaveco mian popolon, eĉ Izraelon, mian elektiton.",
    "Kaj okazis, dum la voĉo ankoraŭ parolis, ke Moseo etis sian rigardon kaj vidis la teron, jes, eĉ la tutan teron; kaj ne estis ereto de ĝi, kiun li ne vidis, distingante ĝin per la Spirito de Dio.",
    "Kaj li vidis ankaŭ ĝiajn loĝantojn, kaj ne estis animo, kiun li ne vidis; kaj li distingis ilin per la Spirito de Dio; kaj ilia nombro estis granda, eĉ nenombrebla kiel la sablo sur la bordo de la maro.",
    "Kaj li vidis multajn landojn; kaj ĉiu lando estis nomita tero, kaj havis loĝantojn sur sia suprĵo.",
    "Kaj okazis, ke Moseo vokis al Dio, dirante: Diru al mi, mi petas vin, kial ĉi tiuj ĵoj estas tiaj, kaj per kio vi faris ilin?",
    "Kaj jen, la gloro de la Eternulo estis sur Moseo, tiel ke Moseo staris antaŭ Dio, kaj parolis kun li vizaĝon kontraŭ vizaĝo. Kaj la Eternulo diris al Moseo: Por mia propra intenco mi faris ĉi tiujn ĵojn. Jen estas la saĝo kaj ĝi restas en mi.",
    "Kaj mi kreis ilin per la vorto de mia potenco, kiu estas mia Solenaskito, kiu estas plena de graco kaj vero.",
    "Kaj nenombreblajn mondojn mi kreis; kaj mi kreis ilin ankaŭ por mia propra intenco; kaj mi kreis ilin per la Filo, kiu estas mia Solenaskito.",
    "Kaj la unuan homon el ĉiuj homoj mi nomis Adam, kio estas multaj.",
    "Sed nur raporton pri ĉi tiu tero, kaj ĝiaj loĝantoj, mi donas al vi. Ĉar, sciu, ke multaj mondoj forpasis pro la vorto de mia potenco. Kaj multaj ankoraŭ restas, kaj ili estas nenombreblaj por homo; sed ĉiuj ĵoj estas nombreblaj por mi, ĉar ili estas miaj kaj mi konas ilin.",
    "Kaj okazis, ke Moseo parolis al la Eternulo, dirante: Korfavoru vian servanton, ho Dio, kaj rakontu al mi pri ĉi tiu tero, kaj ĝiaj loĝantoj, kaj ankaŭ la ĉieloj, kaj poste via servanto estos kontenta.",
    "Kaj la Eternulo parolis al Moseo, dirante: La ĉieloj, ili estas multaj, kaj ili estas nenombreblaj por la homo; sed ili estas nombreblaj por mi, ĉar ili estas miaj.",
    "Kaj, kiam unu tero forpasos, kaj ĝia ĉielo, alvenos alia; kaj miaj verkoj ne havas finon, kaj ankaŭ ne miaj vortoj.",
    "Ĉar jen, ĉi tio estas mia laboro kaj mia gloro--efektivigi la senmortecon kaj eternan vivon de la homo.",
    "Kaj nun, Moseo, mia filo, mi parolos al vi pri ĉi tiu tero sur kiu vi staras; kaj vi skribu tion, kion mi parolos.",
    "Kaj iun tagon, kiam la homidoj taksos miajn vortojn kiel nulon kaj elprenos multajn el ili el la libro, kiun vi skribos, jen mi estigos alian similan al vi; kaj ili estos haveblaj denove inter la homidoj--inter ĉiuj, kiuj kredos.",
    "(Ĉi tiuj vortoj estis parolitaj al Moseo sur la Monto, kies nomo ne estas konata de la homidoj. Kaj nun ili estas parolataj al vi. Ne montru ilin al iu krom al tiuj, kiuj kredas. Eĉ tiel. Amen.)",
  ],
} as const satisfies Chapter;
