export const chapter3 = {
  chapterTitle: "Ĉapitro 3",
  chapterSubtitle: "Kiel rivelitaj al Jozefo Smith la Profeto en decembro 1830--Daŭrigo.",
  verses: [
    "Kaj estis finitaj la ĉielo kaj la tero kaj ĉiuj iliaj apartenaĵoj.",
    "Kaj en la sepa tago mi, Dio, finis mian laboron, kaj ĉion, kion mi faris; kaj mi ripozis en la sepa tago de la tuta laboro, kaj ĉio, kion mi faris, estis finita, kaj mi, Dio, vidis, ke ĝi estas bona;",
    "Kaj mi, Dio, benis la sepan tagon, kaj sanktigis ĝin; ĉar en ĝi mi ripozis de mia tuta laboro, kiun mi, Dio, faris kreante.",
    "Kaj nun, jen mi diras al vi, ke tia estas la naskiĝo de la ĉielo kaj la tero, kiam ili estis kreitaj, en la tago kiam mi, la Eternulo, faris la ĉielon kaj la teron;",
    "Kaj nenia kampa arbetaĵo ankoraŭ estis sur la tero, kaj nenia kampa herbo ankoraŭ kreskis. Ĉar mi, la Eternulo, spirite kreis ĉion, pri kio mi parolis, antaŭ ol ĝi estis fizike sur la tero. Ĉar mi, la Eternulo, ne pluvigis sur la teron. Kaj mi, la Eternulo, jam kreis ĉiujn homidojn; kaj ankoraŭ ne homon, por prilabori la teron; ĉar en la ĉielo mi kreis ilin; kaj ankoraŭ ne estis karno sur la tero, nek en la akvo, nek en la aero;",
    "Sed mi, la Eternulo, parolis, kaj nebulo levigadis de la tero kaj donadis malsekecon al la tuta supraĵo de la tero,",
    "Kaj mi, la Eternulo, kreis la homon el polvo de la tero, kaj enblovis en lian nazon spiron de vivo, kaj la homo fariĝis viva animo, la unua karno sur la tero, ankaŭ la unua homo; tamen, ĉio estis antaŭe kreita; sed ĝi estis spirite kreita kaj farita laŭ mia vorto.",
    "Kaj mi, la Eternulo, plantis ĝardenon en Eden en la Oriento, kaj mi metis tien la homon, kiun mi kreis.",
    "Kaj el la tero mi, la Eternulo, fizike elkreskigis ĉiun arbon ĉarman por la vido de la homo; kaj la homo povis vidi ĝin. Kaj ankaŭ ĝi fariĝis viva animo. Ĉar ĝi estis spirito, kiam mi kreis ĝin; ĉar ĝi restas en la sfero en kiu mi, Dio, kreis ĝin, jes, eĉ ĉion, kion mi preparis por la homa uzo; kaj la homo vidis, ke ĝi estas bona por la manĝo. Kaj mi, la Eternulo, plantis ankaŭ la arbon de vivo en la mezo de la ĝardeno, kaj ankaŭ la arbon de sciado pri bono kaj malbono.",
    "Kaj mi, la Eternulo, elirigis riveron el Eden, por akvoprovizi la ĝardenon; kaj de tie ĝi dividiĝis kaj fariĝis kvar ĉefbrakoj.",
    "Kaj mi, la Eternulo, donis al la unua la nomon Piŝon, kaj ĝi ĉirkaŭas la tutan landon avila, kie mi, la Eternulo, kreis multe da oro;",
    "Kaj la oro de tiu lando estis bona, kaj tie troviĝis bedelio kaj la ŝtono onikso.",
    "Kaj la dua rivero estis nomita Gi¡on; ĝi estas tiu, kiu ĉirkaŭas la tutan landon Etiopujo.",
    "Kaj la nomo de la tria rivero estis idekel; ĝi estas tiu, kiu fluas al la oriento de Asirio. Kaj la kvara rivero estis Eŭfrato.",
    "Kaj mi, la Eternulo, prenis la homon kaj enloĝigis lin en la ĝardeno Edena, por ke li prilaboradu ĝin kaj gardu ĝin.",
    "Kaj mi, la Eternulo, ordonis al la homo, dirante: De ĉiu arbo de la ĝardeno vi manĝu.",
    "Sed de la arbo de sciado pri bono kaj malbono vi ne manĝu, tamen vi mem elektu, ĉar al vi estas donite; sed memoru, ke mi malpermesas tion, ĉar en la tago, en kiu vi manĝos de ĝi, vi mortos.",
    "Kaj mi, la Eternulo, diris al mia Solenaskito, ke ne estas bona, ke la homo estu sola; sekve mi kreos al li helpanton similan al li.",
    "Kaj mi, la Eternulo, kreis el la tero ĉiujn bestojn de la kampo kaj ĉiujn birdojn de la ĉielo; kaj ordonis, ke ili venu al Adam, por vidi, kiel li nomos ilin; kaj ankaŭ ili estis vivaj animoj; ĉar mi, Dio, enblovis en ilin spiron de vivo, kaj ordonis, ke, kiel Adam nomis ĉiun vivan estaĵon, tiel restu ĝia nomo.",
    "Kaj Adam donis nomojn al ĉiuj brutoj kaj al la birdoj de la ĉielo kaj al ĉiuj bestoj de la kampo; sed por Adam ne troviĝis helpanto simila al li.",
    "Kaj mi, la Eternulo, faligis profundan dormon sur Adamon; Kaj li endormiĝis, kaj mi prenis unu el liaj ripoj kaj fermis la lokon per karno;",
    "Kaj mi, la Eternulo, konstruis el la ripo, kiun mi prenis de la homo, virinon, kaj mi venigis ŝin al la homo.",
    "Kaj Adam diris: Jen nun mi scias, ke ŝi estas osto el miaj ostoj kaj karno el mia karno; ŝi estu nomata Virino, ĉar el Viro ŝi estas prenita.",
    "Tial viro forlasos sian patron kaj sian patrinon, kaj aliĝos al sia edzino, kaj ili estos unu karno.",
    "Kaj ili ambaŭ estis nudaj, la homo kaj lia edzino, kaj ili ne hontis.",
  ],
} as const satisfies Chapter;
