export const chapter2 = {
  chapterTitle: "Ĉapitro 2",
  chapterSubtitle:
    "Kiel rivelitaj al Jozefo Smith la Profeto en decembro 1830.",
  verses: [
    "Kaj Okazis, ke la Eternulo parolis al Moseo, dirante: Jen, mi rivelas al vi pri ĉi tiu ĉielo, kaj ĉi tiu tero; skribu la vortojn, kiujn mi parolas. Mi estas la Komenco kaj la Fino, la Eternulo Plejpotenca; per mia Solenaskito mi kreis ĉi tiujn aĵojn; jes, en la komenco mi kreis la ĉielon, kaj la teron sur kiu vi staras.",
    "Kaj la tero estis senforma kaj dezerta; kaj mi venigis mallumon super la abismon; kaj mia Spirito ŝvebis super la akvo; ĉar mi estas Dio.",
    "Kaj mi, Dio, diris: Estu lumo; kaj fariĝis lumo.",
    "Kaj mi, Dio, vidis la lumon; kaj ke la lumo estas bona.",
    "Kaj mi, dio, nomis la lumon Tago; kaj la mallumon mi nomis Nokto; kaj tion mi faris per la vorto de mia potenco, kaj tio estis farata dum mi parolis; kaj estis vespero, kaj estis mateno, unu tago.",
    "Kaj mi, Dio, plue diris: Estu firmaĵo inter la akvo, kaj fariĝis tiel, eĉ dum mi parolis; kaj mi diris: i apartigu akvon de akvo; kaj tio fariĝis;",
    "Kaj mi, Dio, kreis la firmaĵon kaj apartigis la akvon, jes, la grandan akvon sub la firmaĵo de la akvo, kiu estas super la firmaĵo, kaj fariĝis tiel, eĉ dum mi parolis.",
    "Kaj mi, Dio, nomis la firmaĵon ielo; kaj estis vespero, kaj estis mateno, la dua tago.",
    "Kaj mi, Dio, diris: Kolektiĝu la akvo de sub la ĉielo en unu lokon, kaj fariĝis tiel; kaj mi, Dio, diris: Estu sekaĵo; kaj fariĝis tiel.",
    "Kaj mi, Dio, nomis la sekaĵon Tero; kaj la kolektiĝojn de la akvo mi nomis la Maro; kaj mi, Dio, vidis, ke ĉio, kion mi faris, estas bona.",
    "Kaj mi, Dio, diris: Kreskigu la tero verdaĵon, herbon, kiu naskas semon, fruktarbon, kiu donas laŭ sia speco frukton, kaj arbon, kiu donas frukton, kies semo estas en ĝi mem sur la tero, kaj fariĝis tiel dum mi parolis.",
    "Kaj la tero elkreskigis verdaĵon, herbon, kiu naskas semon laŭ sia speco, kaj arbon, kiu donas frukton, kies semo estas en ĝi mem laŭ sia speco; kaj mi, Dio, vidis, ke ĉio, kion mi faris, estas bona;",
    "Kaj estis vespero, kaj estis mateno, la tria tago.",
    "Kaj mi, Dio, diris: Estu lumaĵoj en laĉielofirmaĵo,porapartigilatagondela nokto, kaj ili prezentu signojn, tempojn, tagojn, kaj jarojn;",
    "Kaj ili estu lumaĵoj en la ĉielo firmaĵo, por lumi super la tero; kaj fariĝis tiel.",
    "Kaj mi, Dio, faris la du grandajn lumaĵojn;lapligrandanlumaĵon,porregila tagon, kaj la malpli grandan lumaĵon, por regi la nokton, kaj la pli granda lumaĵo estis la suno, kaj la malpli granda lumaĵo estis la suno, kaj la malpli granda lumaĵo estis la luno; kaj ankaŭ fariĝis la steloj eĉ laŭ mia vorto.",
    "Kaj mi, Dio, starigis ilin sur la ĉiela firmaĵo, por ke ili lumu sur la teron,",
    "Kaj la sunon, por regi la tagon, kaj la lumon, por regi la nokton, kaj por fari diferencon inter la lumo kaj la mallumo; kaj mi, Dio, vidis, ke ĉio, kion mi faris, estas bona;",
    "Kaj estis vespero, kaj estis mateno, la kvara tago.",
    "Kaj mi, Dio, diris: La akvo aperigu moviĝantaĵojn, vivajn estaĵojn, kaj birdoj ekflugu super la tero, sub la ĉiela firmaĵo.",
    "Kaj mi, Dio, kreis la grandajn balenojn, kaj ĉiujn vivajn estaĵ ojn moviĝantajn kiujn aperigis la akvo, laŭ ilia speco, kaj ĉiujn flugilhavajn birdojn, laŭ ilia speco; kaj mi, Dio, vidis, ke ĉio, kion mi kreis, estas bona.",
    "Kaj mi, Dio, ilin benis, dirante: Fruktu kaj multiĝu, kaj plenigu la akvon en la maroj, kaj la birdoj multiĝu sur la tero;",
    "Kaj estis vespero, kaj estis mateno, la kvina tago.",
    "Kaj mi, Dio, diris: La tero aperigu vivajn estaĵojn, laŭ ilia speco, brutojn kaj rampaĵojn kaj surterajn bestojn, laŭ ilia speco; kaj fariĝis tiel.",
    "Kaj mi, Dio, kreis la bestojn de la tero, laŭ ilia speco, kaj la brutojn, laŭ ilia speco, kaj ĉiujn rampaĵojn de la tero, laŭ ilia speco; kaj mi, Dio, vidis, ke ĉiuj tiuj estas bonaj.",
    "Kaj mi, Dio, diris al mia Solenaskito, kiu estis kun mi de la komenco: Ni kreu homon laŭ nia bildo, similan al ni; kaj fariĝis tiel. Kaj mi, Dio, diris: Ili regu super la fiŝoj de la maro kaj super la birdoj de la ĉielo kaj super la brutoj, kaj super la tuta tero, kaj super ĉiuj rampaĵoj, kiuj rampas sur la tero. Kaj mi, Dio, kreis la homon laŭ mia bildo, laŭ la bildo de mia Solenaskito mi kreis lin; en formo de viro kaj virino mi kreis ilin.",
    "Kaj mi, Dio, benis ilin, kaj diris al ili: Fruktu kaj multiĝu, kaj plenigu la teron kaj submetu ĝin al vi, kaj regu super la fiŝoj de la maro, kaj super la birdoj de la ĉielo, kaj super ĉiuj bestoj, kiuj moviĝas sur la tero.",
    "Kaj mi, Dio, diris al la homo: Jen mi donis al vi ĉiujn herbojn, kiuj semas semon, kiuj troviĝas sur tuta tero, kaj ĉiujn arbojn, kiuj havas en si arban frukton, kiu semas semon; tio estu por vi manĝaĵo.",
    "Kaj al ĉiuj bestoj de la tero kaj al ĉiuj birdoj de la ĉielo kaj al ĉiuj rampaĵoj sur la tero, al kiuj mi donis vivon, estu donita la tuta pura herbaĵo kiel manĝaĵo; kaj fariĝis tiel, eĉ kiel mi diris.",
    "Kaj mi, Dio, rigardis ĉion, kion mi kreis, kaj vidis, ke ĉio, kion mi kreis, estas tre bona; kaj estis vespero, kaj estis mateno, la sesa tago.",
  ],
} as const satisfies Chapter;
