export const chapter5 = {
  chapterTitle: "Ĉapitro 5",
  chapterSubtitle: "Kiel rivelitaj al Jozefo Smith la Profeto en decembro 1830--Daŭrigo.",
  verses: [
    "Kaj okazis, post kiam mi, la Eternulo, elpelis ilin, ke Adam komencis prilaboradi la teron, kaj regi super iuj bestoj de la kampo, kaj man adi sian panon sub la ŝvito de sia frunto, kiel mi, la Eternulo, ordonis al li. Kaj ankaŭ Eva, lia edzino, laboradis kun li",
    "Kaj Adam ekkonis sian edzinon, kaj ŝi naskis al li filojn kaj filinojn, kaj ili komencis multi i kaj plenigi la teron.",
    "Kaj ekde tiu tempo la filoj kaj filinoj de Adam komencis disiri duope tra la lando, kaj prilaboradi la teron, kaj paŝti ŝafarojn, kaj ankaŭ al ili naski is filoj kaj filinoj",
    "Kaj Adam kaj Eva, lia edzino, vokis je la nomo de al Eternulo, kaj de la vojo al la Edena ardeno ili aŭdis la vo on de la Eternulo parolantan al ili, sed ili ne vidis lin; ar ili estis elbaritaj de antaŭ li.",
    "Kaj li donis al ili ordonojn, ke ili adoru la Eternulon kaj oferu la unuenaskitojn de siaj ŝafoj kiel donacoferon al la Eternulo. Kaj Adam obeis la ordonojn de la Eternulo.",
    "Kaj post multaj tagoj an elo de la Eternulo aperis al Adam, dirante: Kial vi alportas oferojn al la Eternulo? Kaj Adam diris al li: Mi ne scias, krom ke la Eternulo ordonis min.",
    "Kaj la an elo parolis, dirante: Tio i estas bildo de la ofero de la Solenaskito de la Patro, kiu estas plena de graco kaj vero.",
    "Pro tio, vi devos fari ion, kion vi faras, en la nomo de la Filo, kaj vi devos penti kaj voki al Dio en la nomo de la Filo por eterne.",
    "Kaj en tiu tago la Sankta Spirito, kiu portas ateston de la Patro kaj Filo, falis sur Adamon, dirante: Mi estas la Solenaskito de la Patro de la komenco, de nun kaj por eterne, por ke, kvankam vi falis, vi tamen povos esti savita, kaj la tuta homaro, e iuj, kiuj deziras.",
    "Kaj en tiu tago Adam benis Dion kaj inspira is, kaj komencis profeti pri iuj familioj de la tero, dirante: La nomo de la Eternulo estu benata, ar pro mia le orompo miaj okuloj estas malfermitaj, kaj en i tiu vivo mi havos ojon, kaj denove mi fidos Dion en la karno.",
    "Kaj Eva, lia edzino, aŭdis ion i kaj ek ojis, dirante: Se ni ne estus rompintaj la le on, ni neniam havus idaron, kaj neniam scius bonon kaj malbonon, kaj la ojon de nia savi o, kaj la eternan vivon, kiun Dio donas al iuj obeantoj.",
    "Kaj Adam kaj Eva benis la nomon de Dio, kaj ili konigis ion al siaj filoj kaj siaj filinoj.",
    "Kaj Satano venis inter ilin, dirante: Ankaŭ mi estas filo de Dio; kaj li ordonis al ili, dirante: Ne kredu tion; kaj ili ne kredis in, kaj ili amis Satanon pli ol Dion. Kaj la homoj ekde tiu tempo fari is karnaj, laŭsentaj kaj demonaj.",
    "Kaj la Eternulo vokis al la homoj ie per la Sankta Spirito kaj ordonis al ili, ke ili pentu;",
    "Kaj iuj, kiuj kredas al la Filo kaj pentas pri siaj pekoj, estos savitaj; kaj iuj, kiuj ne kredas kaj ne pentas, estos kondamnitaj; kaj la vortoj eliris el la buŝo de Dio kiel firma dekreto; sekve ili devas esti plenumitaj.",
    "Kaj Adam kaj Eva, lia edzino, ne esis voki al Dio. Kaj Adam ekkonis Evan, sian edzinon, kaj ŝi gravedi is kaj naskis Kainon, kaj diris: Ni akiris homon de la Eternulo; pro tio li eble ne malakceptos liajn vortojn. Sed jen Kian ne saŭskultis, dirante: Kiu estas la Eternulo, ke mi devu koni lin?",
    "Kaj ŝi denove gravedi is kaj naskis lian fraton Habel. Kaj Habel aŭskultis la vo on de la Eternulo. Kaj Habel fari is ŝafpaŝtisto, sed Kain fari is terlaboristo.",
    "Kaj Kian amis Satanon pli ol Dion. Kaj Satano ordonis al li, dirante: Faru donacoferon al la Eternulo",
    "Kaj post ia tempo fari is, ke Kian alportis el la fruktoj de la tero donacoferon al la Eternulo.",
    "Kaj ankaŭ Habel elportis el la unuenaskitoj de siaj ŝafoj kaj el ilia graso. Kaj la Eternulo atentis Habelon kaj lian donacoferon.",
    "Sed Kainon kaj lian donacoferon li ne atentis. Satano sciis tion, kaj tio pla is al li. Kaj Kian tre ekkoleris, kaj lia viza o klini is.",
    "Kaj la Eternulo diris al Kain: Kial vi koleras? kaj kial klini is via viza o?",
    "Ja, se vi agos bone, vi estos forta. Sed, se vi agos malbone, la peko kuŝos e la pordo, kaj Satano deziras havi vin; kaj, se vi ne aŭskultos miajn ordonojn, mi transdonos vin, kaj okazos al vi laŭ lia deziro. Kaj vi regos super li;",
    "Ĉar ekde nun vi estos la patro de liaj mensogoj; vi estos nomita Perdi o; ar vi estis ankaŭ antaŭ la mondo.",
    "Kaj oni diros en la venonta tempo: Ke tiuj abomenaĵoj venis de Kain; ar li malakceptis la pli superan konsilon, kiu venis de Dio; kaj i tio estas malbeno, kiun mi metos sur vin, se vi ne pentos.",
    "Kaj Kain ekkoleris, kaj jam ne aŭskultis al la vo o de la Eternulo, nek al Habel, lia frato, kiu iris en sankteco antaŭ la Eternulo.",
    "Kaj Adam kaj lia edzino aflikti is antaŭ la Eternulo, pro Kain kaj liaj fratoj.",
    "Kaj okazis, ke Kain prenis al si unu el la filinoj de siaj fratoj kiel edzinon, kaj ili amis Satanon pli ol Dion.",
    "Kaj Satano diris al Kain: ĵuru al mi per via gor o, kaj se vi malkaŝos vi mortos: kaj ĵurigu viajn fratojn per iliaj kapoj, kaj per la vivanta Dio, ke ili ne malkaŝos; ar, se ili malkaŝos, ili certe mortos: kaj tiel por ke via patro ne sciu; kaj hodiaŭ mi donos vian fraton Habel en viajn manojn.",
    "Kaj Satano ĵuris al Kain, ke li faros laŭ liaj ordonoj. Kaj io i estis sekrete farita.",
    "Kaj Kain diris: Certe mi estas Mahan, mastro de i tiu granda sekreto, ke mi povas murdi kaj profiti. Pro tio Kain estis nomita Mastro Mahan, kaj li fieris pri sia malboneco.",
    "Kaj Kain iris sur la kampon, kaj Kain parolis kun sia frato Habel. Kaj, kiam ili estis sur la kampo, Kain levi is kontraŭ sian fraton Habel kaj mortigis lin.",
    "Kaj Kain sin gloris pri tio, kion li faris, dirante: Mi estas libera; la ŝafaroj de mia frato certe venos en miajn manojn.",
    "Kaj la Eternulo diris al Kain: Kie estas via frato Habel? Kaj tiu diris: Mi ne scias. u mi estas gardisto de mia frato?",
    "Kaj la Eternulo diris: Kion vi faris? La vo o de la sango de via frato krias al mi de la tero.",
    "Kaj nun vi estos malbenita de sur la tero, kiu malfermis sian buŝon, por preni la sangon de via frato el via mano.",
    "Kiam vi prilaboros la teron, i ne plu donos al vi sian forton. Vaganto kaj forkuranto vi estos sur la tero.",
    "Kaj Kian diris al la Eternulo: Satano tentis min pro la ŝafaroj de mia frato. Kaj mi ankaŭ koleri is; ar lian donacoferon vi akceptis, sed ne mian; pli granda estas mia puno, ol kion mi povos elporti.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ĉar ekde la tagoj de Kain ekzistis sekreta komploto, kaj iliaj faroj estis en la mallumo, kaj iu el ili konis sian fraton.",
    "Pro tio la Eternulo malbenis Leme¡on, kaj lian domon, kaj iujn, kiuj havis interligon kun Satano; ar ili ne obeis la ordonojn de Dio, kaj tio malpla is al Dio, kaj li esis konsili ilin, kaj iliaj faroj estis abomenaĵoj kaj komencis disvasti i inter la homidoj.",
    "Kaj tio estis inter la homidoj, kaj inter la homidinoj oni ne parolis pri tiuj faroj, ar Leme¡ diris la sekreton al siaj edzinoj, kaj ili ribelis kontraŭ li, kaj disigis la scion, sen kompato;",
    "Pro tio oni malestimis Lame¡on kaj elektis lin, kaj li ne venis inter la homidojn por ke li ne mortu.",
    "Kaj tiamaniere la faroj de la mallumo komencis superforti inter iuj homidoj.",
    "Kaj Dio malbenis la teron per terura malbeno, kaj koleris kontraŭ la malbonuloj, kontraŭ iuj homidoj, kiujn li kreis.",
    "Ĉar ili ne volis aŭskulti lian vo on, nek kredi al lia Solenaskita Filo, kiu laŭ lia deklaro alvenos, kiam la tempo estos plej favora, kiu estis pretigita antaŭ la kreo de la mondo.",
    "Kaj tial la Evangelio komencis esti predikata, de la komenco, estante proklamata de sanktaj an eloj dissenditaj de antaŭ Dio, kaj per lia propra vo o, kaj per la graco de la Sankta Spirito.",
    "Kaj tiel io estis konfirmita al Adam, per sankta le o, kaj la Evangelio estis predikata, kaj dekreto estis dissendita, ke tio estu en la mondo, is ia fino; kaj tiel estis. Amen.",
  ],
} as const satisfies Chapter;
