export const chapter19 = {
  chapterTitle: "Ĉaptiro 19",
  summary: "",
  verses: [
    "Kaj la dua loto eliris por Simeon, por la tribo de la Simeonidoj, laŭ iliaj familioj. Kaj ilia posedaĵo estis meze de la posedaĵo de la Jehudaidoj.",
    "Apartenis al ili en ilia posedaĵo:Beer-Ŝeba (kun Ŝeba) kaj Molada",
    "kaj ĥacar-Ŝual kaj Bala kaj Ecem",
    "kaj Eltolad kaj Betul kaj ĥorma",
    "kaj Ciklag kaj Bet-Markabot kaj ĥacar-Susa",
    "kaj Bet-Lebaot kaj ŜaruĤen:dek tri urboj kaj iliaj vilaĝoj.",
    "Ain, Rimon kaj Eter kaj Aŝan:kvar urboj kaj iliaj vilaĝoj.",
    "Kaj ĉiuj vilaĝoj, kiuj estas ĉirkaŭ tiuj urboj, ĝis Baalat-Beer, Ramat sude. Tio estas la posedaĵo de la tribo de la Simeonidoj, laŭ iliaj familioj.",
    "El la landpeco de la Jehudaidoj estis la posedaĵo de la Simeonidoj; ĉar la parto de la Jehudaidoj estis tro granda por ili, tial la Simeonidoj ricevis posedaĵon meze de ilia posedaĵo.",
    "Kaj la tria loto eliris por la Zebulunidoj, laŭ iliaj familioj; kaj la limo de ilia posedaĵo estis ĝis Sarid.",
    "Kaj ilia limo iras ĝis la maro kaj Marala, kaj kuntuŝiĝas kun Dabeŝet, kaj kuntuŝiĝas kun la torento, kiu estas antaŭ Jokneam.",
    "Kaj ĝi iras returne de Sarid orienten, al la flanko de sunleviĝo, ĝis la limo de Kislot-Tabor; kaj ĝi iras al Dabrat, kaj leviĝas al Jafia.",
    "Kaj de tie ĝi iras orienten, al la flanko de sunleviĝo, tra Gat- ĥefer kaj Et-Kacin, kaj eliras al Rimon-Metoar kaj Nea.",
    "Kaj la limo turniĝas de nordo al ĥanaton, kaj finiĝas en la valo JiftaĤ-El.",
    "Kaj Katat, kaj Nahalal kaj Ŝimron kaj Jidala kaj Bet-LeĤem:dek du urboj kaj iliaj vilaĝoj.",
    "Tio estas la posedaĵo de la Zebulunidoj, laŭ iliaj familioj, tiuj urboj kaj iliaj vilaĝoj.",
    "Por IsaĤar eliris la kvara loto, por la IsaĤaridoj, laŭ iliaj familioj.",
    "Kaj ilia limo estis:Jizreel kaj Kesulot kaj Ŝunem",
    "kaj ĥafaraim kaj Ŝion kaj AnaĤarat",
    "kaj Rabit kaj Kiŝjon kaj Abec",
    "kaj Remet kaj En-Ganim kaj En-ĥada kaj Bet-Pacec.",
    "Kaj la limo kuntuŝiĝas al Tabor kaj ŜaĤacima kaj Bet-Ŝemeŝ; kaj ilia limo finiĝas ĉe Jordan:dek ses urboj kaj iliaj vilaĝoj.",
    "Tio estas la posedaĵo de la tribo de la IsaĤaridoj, laŭ iliaj familioj, la urboj kaj iliaj vilaĝoj.",
    "Kaj la kvina loto eliris por la tribo de la Aŝeridoj, laŭ iliaj familioj.",
    "Kaj ilia limo estis:ĥelkat kaj ĥali kaj Beten kaj AĤŝaf",
    "kaj AlameleĤ kaj Amad kaj Miŝal. Kaj ĝi kuntuŝiĝas al Karmel okcidente, kaj al ŜiĤor-Libnat.",
    "Kaj ĝi returniĝas oriente al Bet-Dagon, kaj kuntuŝiĝas al Zebulun kaj al la valo JiftaĤ-El norde, al Bet-Emek kaj Neiel, kaj eliras al Kabul maldekstre.",
    "Kaj Ebron kaj ReĤob kaj ĥamon kaj Kana ĝis Granda Cidon.",
    "Kaj la limo returniĝas al Rama kaj al la fortikigita urbo Tiro; kaj la limo returniĝas al ĥosa, kaj finiĝas ĉe la maro, de ĥebel ĝis AĤzib;",
    "kaj Uma kaj Afek kaj ReĤob:dudek du urboj kaj iliaj vilaĝoj.",
    "Tio estas la posedaĵo de la tribo de la Aŝeridoj, laŭ iliaj familioj, tiuj urboj kaj iliaj vilaĝoj.",
    "Por la Naftaliidoj eliris la sesa loto, por la Naftaliidoj, laŭ iliaj familioj.",
    "Kaj ilia limo estis de ĥelef, de la kverkaro ĉe Caananim, Adami- Nekeb, kaj Jabneel, ĝis Lakum; kaj ĝi finiĝas ĉe Jordan.",
    "Kaj la limo turniĝas okcidenten al Aznot-Tabor, kaj eliras de tie al ĥukok, kaj kuntuŝiĝas al Zebulun sude, kaj al Aŝer ĝi kuntuŝiĝas okcidente, kaj al Jehuda ĉe Jordan oriente.",
    "Kaj fortikigitaj urboj:Cidim, Cer kaj ĥamat, Rakat kaj Kineret",
    "kaj Adama kaj Rama kaj ĥacor",
    "kaj Kedeŝ kaj Edrei kaj En-ĥacor",
    "kaj Jiron kaj Migdal-El, ĥorem kaj Bet-Anat kaj Bet-Ŝemeŝ:dek naŭ urboj kaj iliaj vilaĝoj.",
    "Tio estas la posedaĵo de la tribo de la Naftaliidoj, laŭ iliaj familioj, la urboj kaj iliaj vilaĝoj.",
    "Por la tribo de la Danidoj, laŭ iliaj familioj, eliris la sepa loto.",
    "Kaj la limo de ilia posedaĵo estis:Corea kaj Eŝtaol kaj Ir-Ŝemeŝ",
    "kaj Ŝaalabin kaj Ajalon kaj Jitla",
    "kaj Elon kaj Timna kaj Ekron",
    "kaj Elteke kaj Gibeton kaj Baalat",
    "kaj Jehud kaj Bene-Berak kaj Gat-Rimon",
    "kaj Me-Jarkon kaj Rakon, kun la limo apud Jafo.",
    "Kaj tie finiĝas la limo de la Danidoj. Kaj la Danidoj iris kaj militis kontraŭ Leŝem, kaj prenis ĝin kaj batis ĝin per glavo, kaj ekposedis ĝin kaj enloĝiĝis en ĝi, kaj donis al Leŝem la nomon Dan, laŭ la nomo de Dan, ilia patro.",
    "Tio estas la posedaĵo de la tribo de la Danidoj, laŭ iliaj familioj, tiuj urboj kaj iliaj vilaĝoj.",
    "Kaj ili finis la dividadon de la lando laŭ ĝiaj limoj; kaj la Izraelidoj donis al Josuo, filo de Nun, heredan posedaĵon inter si.",
    "Laŭ la ordono de la Eternulo ili donis al li la urbon, kiun li petis, Timnat-SeraĤ sur la monto de Efraim; kaj li konstruis la urbon kaj loĝis en ĝi.",
    "Tio estas la posedaĵoj, kiujn la pastro Eleazar, kaj Josuo, filo de Nun, kaj la familiestroj disdividis al la triboj de la Izraelidoj laŭ loto, en Ŝilo, antaŭ la Eternulo, antaŭ la pordo de la tabernaklo de kunveno.  Kaj ili finis la dividadon de la lando.",
  ],
} as const satisfies Chapter;
